import {mediaSlot,staticMediaStory} from './media-static.mjs';
import {preparation,purposes} from './batch-a-engine.mjs';
export const batchSteps=['scope','parties','authority','tasks'];
export const batchScene=id=>['SCN-SCOPE','SCN-ENTITY'].includes(id);
export const labels={coordinate_information:['Coordinate information','协调资料'],make_declarations:['Make declarations','作出声明'],execute_agreement:['Execute agreement','签署协议'],issue_trade_instruction:['Issue trade instruction','发出交易指令'],evidence_required:['Evidence required','需要证据'],not_established:['Not established','尚未建立'],not_assessed:['Not assessed','尚未评估'],clarification_required:['Clarification required','需要澄清'],draft:['Draft','草稿'],working_scope_recorded:['Working scope recorded','工作范围已记录'],unresolved:['Unresolved','未解决'],resolved_for_scope:['Resolved for scope','范围内主体已明确'],under_review:['Under review','复核中'],not_started:['Not started','尚未开始'],in_review:['In review','复核中'],requirements:['Requirements draft','要求草稿'],source:['Source preparation','来源准备'],conflicts:['Conflicts preparation','冲突检查准备'],pre_screen:['Preliminary screening preparation','初步筛查准备'],legal:['Legal preparation','法务准备'],credit:['Credit preparation','信贷准备'],client_request:['Client request','客户请求'],agreement_execution:['Agreement execution','协议签署'],publication:['Publication','发布'],ready_for_preparation:['Ready for preparation','可开展准备'],awaiting_input:['Awaiting input','等待输入'],scope_draft_saved:['Scope draft saved','已保存范围草稿'],counterparty_scope_clarified:['Counterparty scope clarified','已澄清交易主体'],working_scope_recorded:['Working scope recorded','工作范围已记录'],source_result_received:['Synthetic source received','已收到合成来源'],entity_context_reviewed:['Entity context reviewed','已复核主体背景'],evidence_use_assessed:['Purpose assessment recorded','已记录用途评估'],authority_gap_opened:['Authority gap opened','已建立权限缺口任务'],review_task_opened:['Review task opened','已建立复核任务'],clarification_draft_created:['Clarification draft created','已建立澄清草稿'],downstream_preparation_enabled:['Preparation gates evaluated','已评估准备工作门槛'],relationship_request_received:['Relationship request received','已收到关系请求']};
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function batchUI({data,n,L,button,fields={},rationale='',dirty=false}){
 const sc=data.scopes[0],live=!!data.demoConfig.batchA,B=(en,zh)=>L(en,zh),label=v=>labels[v]?L(...labels[v]):escape(v),none=B('Not provided','尚未提供');
 const can=a=>live&&n.trigger==='new-relationship'&&data.demoConfig.batchA.permissions[n.role]?.includes(a);
 const action=(a,en,zh)=>button(B(en,zh),'batch-action',a,'',can(a)?'':'disabled');
 const dl=rows=>`<dl class="batch-fields">${rows.map(([k,v])=>`<div><dt>${k}</dt><dd>${v??none}</dd></div>`).join('')}</dl>`;
 const note=`<p class="notice batch-blocker">${B('Not ready · booking and product eligibility unresolved. Person T’s authority must be assessed per purpose; see the latest records. BO/CDD, Legal, Credit and final bank permissions remain separate.','尚未就绪 · Booking 与产品资格未确定。Person T 对 Entity A 的具体权限须按用途查看最新记录。受益所有权 / CDD、法务、信贷与银行最终权限保持独立。')}</p>`;
 const help=`<span class="batch-help-wrap"><button type="button" class="batch-help" popovertarget="authority-help" aria-label="${B('Authority definition','权限定义')}" aria-expanded="false">i</button><span id="authority-help" popover="auto" role="note">${B('Employment at Entity B is not authority to act for Entity A. Assess each principal and purpose separately. Employee demo permission does not grant customer authority.','任职于 Entity B 不等于获准代表 Entity A。须按被代表主体与用途分别评估。员工演示操作权限不赋予客户代表权限。')} <button popovertarget="authority-help" popovertargetaction="hide" aria-label="${B('Close definition','关闭说明')}">×</button></span></span>`;
 const authority=()=>`<h3>Person T ${help}</h3><p>${B('Employer: Entity B · Singapore / Claimed principal: Entity A · Australia','任职组织：Entity B · 新加坡 / 声称代表主体：Entity A · 澳大利亚')}</p><div class="table-scroll"><table class="compare-table authority-table"><thead><tr><th>${B('Purpose','用途')}</th><th>${B('Principal','被代表主体')}</th><th>${B('Status','状态')}</th></tr></thead><tbody>${purposes.map(p=>{const a=data.authorities.find(x=>x.action_type===p);return `<tr><td>${label(p)}</td><td>Entity A</td><td>${label(a?.status||'not_assessed')}</td></tr>`;}).join('')}</tbody></table></div><p>${B('EV-A03 supports employment at B; it does not itself establish the Entity A coordination scope.','EV-A03 支持在 B 任职的声明，但其本身不建立为 Entity A 协调资料的权限范围。')}</p><p class="live-evidence-status">EV-A05 · ${data.evidence.some(e=>e.alias==='EV-A05'&&e.receipt_status==='received')?B('Received in live session · receipt is not purpose sufficiency','实际会话已收到 · 收到不等于用途充分'):B('Not received in live session','实际会话尚未收到')}</p>${note}`;
 const inputs=()=>`<label class="field">${B('Rationale / request reason','评估理由 / 请求原因')}<textarea id="rationale">${escape(rationale)}</textarea></label>`;
 const gates=()=>`<section class="batch-gates"><h3>${B('Next work · per-task prerequisites','后续工作 · 各任务前置条件')}</h3>${preparation(data).map(g=>`<article data-gate="${g.id}"><div><strong>${label(g.id)}</strong><span class="badge">${label(g.status)}</span></div><p>${n.locale==='zh-CN'?({requirements:'已记录范围、明确产品及演示规则集；booking 相关适用性仍未知。',source:'主体可查询且具合成来源访问依据。',conflicts:'主体及业务请求可区分，并且没有适用暂停；仅准备。',pre_screen:'主体版本与预编制查询范围；不代表完整群体筛查。',legal:'协议适用性未知，不执行协议。',credit:'信贷适用性未知，不推断额度。',client_request:'收件人、披露与发送权限未知；只保存草稿。',agreement_execution:'尚未建立具体签署权限。',publication:'条件、booking 与最终银行权限未闭合。'})[g.id]:escape(g.basis)}${g.hold?' · '+B('Hold active / unresolved','暂停生效 / 未确认'):''}</p><small>${g.dependency} · ${B('Scope','范围')} v${g.scope_revision}</small></article>`).join('')}</section>`;
 const parties=()=>`<div class="batch-parties">${data.entities.map(e=>`<article class="record"><span class="eyebrow">${escape(e.display_alias||e.legal_name)}</span><h3>${escape(e.legal_name)}</h3>${dl([[B('Incorporation','注册地'),e.incorporation_jurisdiction],[B('Relationship','关系'),e.incorporation_jurisdiction==='SG'?B('Reported parent · not counterparty / guarantor','声称的母公司 · 非交易主体 / 担保人'):B('Only proposed trading entity','唯一拟准入交易主体')],[B('Identity resolution','主体界定'),label(e.identity_resolution_status)],[B('Verification','核验'),label(e.verification_status)],[B('Beneficial ownership','受益所有权'),B('Unknown','未知')],[B('LEI / registration number','LEI / 注册编号'),none]])}</article>`).join('')}</div><article class="record"><h3>Person T</h3><p>${B('Employed by Entity B; claims to coordinate information for Entity A. Consult the separate current purpose assessments.','任职于 Entity B，声称为 Entity A 协调资料。具体权限请查看独立的当前用途评估。')}</p></article>`;
 const taskList=()=>{const tasks=data.workItems.filter(x=>x.work_type);return `<h3>${B('Tasks','任务')}</h3>${tasks.length?tasks.map(t=>`<article class="record"><strong>${label(t.work_type==='authority_gap'?'coordinate_information':'awaiting_input')}</strong>${dl([[B('Principal / purpose','被代表主体 / 用途'),'Entity A / '+label(t.purpose_code)],[B('Owner','责任人'),B('Unassigned · role to be confirmed','未分派 · 待确认角色')],[B('Status','状态'),label(t.status)],[B('Waiting for','等待'),B('Entity A purpose-specific authority basis','针对 Entity A 具体用途的权限依据')],[B('Due date','截止日期'),none]])}<small class="trace-meta">${escape(t.id)}</small></article>`).join(''):`<p>${B('No Batch A task created yet.','尚未建立本组任务。')}</p>`}<h3>${B('Request drafts','请求草稿')}</h3>${(data.informationRequests||[]).map(r=>`<article class="record"><strong>${B('Draft · not sent','草稿 · 未发送')}</strong><p>${escape(r.reason)}</p><small class="trace-meta">${escape(r.id)}</small></article>`).join('')}${gates()}`;};
 const panel=()=>!live?`<div class="notice">${B('This tab contains a preserved earlier session. Archive it before opening the approved Batch A baseline.','本标签页保留着之前的会话。请先归档，再打开已批准的 Batch A 基线。')}</div>${button(B('Archive session & start Batch A','归档会话并开始 Batch A'),'batch-start')}`:n.step==='scope'?`${dl([[B('Case / request','案件 / 请求'),'<span class="trace-meta">'+escape(data.case.id)+' / EV-A01</span>'],[B('Counterparty','交易主体'),sc.counterparty_entity_id?'Entity A':B('Unresolved — RM clarification required','尚未明确 — 需客户经理澄清')],[B('Product requested','申请产品'),'FX forward'],[B('Product eligibility','产品资格'),B('Not assessed','尚未评估')],[B('Booking entity / jurisdiction','Booking 主体 / 地区'),none],[B('DD level','尽调等级'),B('Not assessed','尚未评估')],[B('Scope status / revision','范围状态 / 版本'),label(sc.scope_status)+' / v'+sc.revision]])}<label class="field">${B('Group display name','集团展示名称')}<input id="batch-group" data-batch-field="group_display_name" value="${escape(fields.group_display_name??sc.group_display_name)}"></label><label class="field">${B('Business purpose','业务用途')}<textarea id="batch-purpose" data-batch-field="business_purpose">${escape(fields.business_purpose??sc.business_purpose)}</textarea></label><p class="small">${dirty?B('Unsaved changes','有未保存变更'):B('Saved session values','已保存的会话值')} · ${B('Source','来源')}: EV-A01 / SRC-013</p>${note}<div class="work-actions">${action('save_scope_draft','Save draft','保存草稿')}${action('clarify_counterparty','Record RM clarification: Entity A','记录客户经理澄清：Entity A')}${action('record_working_scope','Record working scope','记录工作范围')}${button(B('Parties','主体'),'step','parties')}</div>`:n.step==='parties'?`${parties()}<p>${B('EV-A04 registry source','EV-A04 登记来源')}: ${data.evidence.find(x=>x.alias==='EV-A04')?.receipt_status==='received'?B('Received · synthetic','已收到 · 合成'):B('Awaiting source result','等待来源结果')}</p>${inputs()}<div class="work-actions">${action('receive_registry','Receive synthetic registry result','接收合成登记来源结果')}${action('review_entity','Record entity review','记录主体复核')}${button(B('Authority','代表权限'),'step','authority')}</div>`:n.step==='authority'?`${authority()}${inputs()}<div class="work-actions">${button(B('Save draft','保存草稿'),'save')}${action('assess_authority','Assess EV-A03 for this purpose','评估 EV-A03 对此用途的支持')}${action('open_authority_gap','Open gap task','建立缺口任务')}${action('refer_authority','Refer for review','转交复核')}${action('request_clarification','Draft clarification request','起草澄清请求')}${button(B('Tasks','任务'),'step','tasks')}</div>`:taskList();
 const figure=kind=>`<figure class="batch-diagram"><img src="./diagrams/batch-a/${kind}.${n.locale}${n.mode==='print'?'.print':''}.svg" alt="${B(kind==='DG-ENTITY-A'?'Entity B reported parent of A; Person T employed by B and claims coordination for A. Authority remains unestablished.':kind==='DG-SCOPE-A'?'Group display name is distinct from Entity A. Recorded working scope retains unknown booking and eligibility.':'Preparation requires task-specific inputs and no applicable hold. Signing and publication wait.',kind==='DG-ENTITY-A'?'Entity B 为 A 的声称母公司；Person T 任职于 B 并声称为 A 协调资料，具体权限未建立。':kind==='DG-SCOPE-A'?'集团展示名称与 Entity A 不同；记录工作范围后 booking 与资格仍未知。':'准备工作须满足各任务输入且没有适用暂停；签署及发布仍等待。')}"><figcaption>Archify 2.17 · SRC-013 · ${B('Synthetic static relationship model','合成静态关系模型')}</figcaption></figure>`;
 const beats=n.scenario==='SCN-SCOPE'?[
 ['A-01','SNAP-A0','Request received','收到业务请求','Group A is the display name. EV-A01–03 are available; booking and authority unknown.','Group A 是展示名称。仅有 EV-A01–03；booking 与权限未知。'],
 ['A-02','SNAP-A0','Group ≠ legal entity','集团 ≠ 法人','Entity A and Entity B must not merge because their group name looks similar.','不能因集团名称相似而合并 Entity A 与 Entity B。'],
 ['A-03','SNAP-A1','RM clarifies Entity A','客户经理澄清 Entity A','Authored RM clarification identifies A as the proposed counterparty, B as related only.','预编制的客户经理澄清将 A 指定为拟交易主体，B 仅为关联主体。'],
 ['A-04','SNAP-A2','Record the working scope','记录工作范围','FX forward requested; booking, eligibility and DD remain open. Human action required.','申请 FX forward；booking、资格及尽调等级仍未确定。须人工操作。']
 ]:[
 ['B-01','SNAP-A2','Separate the records','分开对象记录','Entity A, Entity B and Person T retain separate identities and roles.','Entity A、Entity B 与 Person T 保留独立身份及角色。'],
 ['B-02','SNAP-A2','Review the entity source','复核主体来源','EV-A04 appears only following its synthetic arrival event. BO/CDD is still unknown.','EV-A04 仅在合成来源到达事件后出现；受益所有权 / CDD 仍未知。'],
 ['B-03','SNAP-A3','Locate the authority gap','定位具体权限缺口','EV-A03 supports employment at B, not the Entity A coordination purpose.','EV-A03 支持在 B 任职，但不支持为 Entity A 协调资料的具体用途。'],
 ['B-04','SNAP-A3','Open targeted work','建立定向工作','Principal A; coordinate information; evidence required; owner Unassigned; request remains draft.','被代表主体 A；协调资料；需要证据；责任人未分派；请求仍为草稿。'],
 ['B-05','SNAP-A3','Prepare where permitted','按门槛开展准备','Specific preparation may continue. Signing, trading authority and case clearance remain unresolved.','特定准备工作可继续。签署、交易权限及整体准入仍未解决。']];
 const benchmarks=()=>`<details class="batch-benchmarks"><summary>${B('Design references · not bank policy','设计参考 · 非银行政策')}</summary>
<p>B01 · <a href="https://www.austrac.gov.au/industry-and-business/obligations-and-guidance/your-amlctf-program/customer-due-diligence/initial-customer-due-diligence/overview-initial-customer-due-diligence" target="_blank" rel="noopener">AUSTRAC · Initial CDD</a> · INDUSTRY-BENCHMARK</p><p>${B('Adopt distinct customer, representative authority and beneficial-owner records. Adapt evidence purposes. Avoid treating this prototype as a bank-approved CDD policy.','采用客户、代表权限及受益所有权的独立记录；适配证据用途；不将原型视为银行已批准的 CDD 政策。')}</p>
<p>B02 · <a href="https://www.gleif.org/en/lei-data/access-and-use-lei-data/level-2-data-who-owns-whom" target="_blank" rel="noopener">GLEIF · Level 2</a> · INDUSTRY-BENCHMARK</p><p>${B('Adopt sourced relationship records. Level 2 describes accounting-consolidating parents; avoid equating a parent record with natural-person beneficial ownership, complete KYC or vLEI authority.','采用带来源的关系记录。Level 2 描述会计合并母公司；不等同自然人受益所有权、完整 KYC 或 vLEI 权限。')}</p>
<p>B03 · <a href="https://www.eurocontrol.int/publication/eurocontrol-specification-airport-collaborative-decision-making-cdm" target="_blank" rel="noopener">EUROCONTROL · A-CDM</a> · CROSS-INDUSTRY-PATTERN</p><p>${B('Adapt milestone-triggered downstream updates to versioned work dependencies. Avoid importing aviation safety rules, time estimates or SLAs into bank controls.','借鉴里程碑触发下游更新，用于有版本的工作依赖；不移植航空安全规则、时间估计或 SLA 到银行控制。')}</p><small>${B('Primary pages checked 2026-09-07. Design-transfer hypotheses; bank applicability unconfirmed.','一手网页核对日期：2026-09-07。属于设计迁移假设，银行适用性未确认。')}</small></details>`;
 const scene=()=>{const i=Math.min(n.batchBeats?.[n.scenario]?.beat||0,beats.length-1),beat=beats[i],old=n.originScopeRevision;return `<section class="batch-context"><span class="eyebrow">S1 / ${n.scenario} · ${B('Scope','范围')} v${sc.revision}</span>${old&&old!==sc.revision?`<p class="notice">${B('Scope changed during work','工作期间范围已变更')}: v${old} → v${sc.revision}. ${B('Same case and source scene restored; latest session retained.','已恢复同一案件及来源场景，保留最新会话。')}</p>`:''}${mediaSlot(n.scenario,n.locale)}${benchmarks()}${figure(n.scenario==='SCN-SCOPE'?'DG-SCOPE-A':'DG-ENTITY-A')}<details class="batch-focus" open><summary>${B('Live session · latest saved business records','实际会话 · 最新已保存业务记录')}</summary>${n.scenario==='SCN-SCOPE'?dl([[B('Actual session scope','实际会话范围'),label(sc.scope_status)+' / v'+sc.revision],[B('Proposed counterparty','拟交易主体'),sc.counterparty_entity_id?'Entity A':B('Awaiting clarification','等待澄清')],[B('Requested product','申请产品'),'FX forward'],[B('Booking / eligibility','Booking / 资格'),B('Unknown / not assessed','未知 / 尚未评估')]]):authority()}</details><details><summary>${B('What can continue / what waits','哪些可继续 / 哪些需等待')}</summary>${gates()}${figure('DG-ENABLE-A')}</details><div class="batch-next"><strong>${B('Journey connection','旅程衔接')}</strong><p>${n.scenario==='SCN-SCOPE'?B('Scope outputs feed entity / authority review, then a requirements draft.','范围输出进入主体 / 代表权限复核，继而供要求草稿使用。'):B('Entity and authority outputs feed SCN-REQUIREMENTS. Unresolved authority stays attached; downstream work is not completed by continuing.','主体与权限输出进入 SCN-REQUIREMENTS。未解决权限随上下文保留；继续主线不会完成下游工作。')}</p>${button(B('Open next linked scene','打开下一关联场景'),'scene',n.scenario==='SCN-SCOPE'?'SCN-ENTITY':'SCN-REQUIREMENTS')}</div></section>`;};
 const print=()=>`<section class="print-scene batch-print"><h2>${B('Scope, parties and authority','范围、主体与权限')}</h2><p class="trace-meta">D2 Batch A</p><p>DEMO-CTT-001 · SRC-013 Final v1.0 · SRC-014 Media Brief v1.0 · ${B('Scope','范围')} v${sc.revision} · ${B('Synthetic / reported / source reviewed / unknown are distinct','合成 / 声称 / 来源复核 / 未知为不同状态')}</p>${dl([[B('Request','请求'),'EV-A01 / FX forward / USD procurement'],[B('Group display','集团展示'),'Group A'],[B('Counterparty','交易主体'),sc.counterparty_entity_id?'Entity A':B('Unresolved','尚未明确')],[B('Booking / eligibility / DD','Booking / 资格 / 尽调等级'),B('Not provided / not assessed','尚未提供 / 尚未评估')],[B('Scope','范围'),label(sc.scope_status)]])}${parties()}${authority()}${taskList()}${['DG-SCOPE-A','DG-ENTITY-A','DG-ENABLE-A'].map(figure).join('')}${staticMediaStory('SCN-SCOPE',n.locale)}${staticMediaStory('SCN-ENTITY',n.locale)}</section>`;
 return {panel,scene,print,gates,label};
}
let helpController;
export function bindBatchHelp(){
 helpController?.abort();helpController=new AbortController();
 const root=document.querySelector('#scenario-dialog[open]')||document.querySelector('#app');
 const trigger=root?.querySelector('.batch-help'),popover=root?.querySelector('#authority-help');if(!trigger||!popover)return;
 let suppressed=false;const show=()=>{if(!suppressed&&!popover.matches(':popover-open')){popover.showPopover();trigger.setAttribute('aria-expanded','true');}};
 trigger.addEventListener('mouseenter',()=>{suppressed=false;show();});trigger.addEventListener('focus',e=>{if(popover.contains(e.relatedTarget))return;suppressed=false;show();});
 popover.addEventListener('toggle',()=>trigger.setAttribute('aria-expanded',String(popover.matches(':popover-open'))));
 document.addEventListener('keydown',function dismiss(e){if(e.key==='Escape'&&popover.matches(':popover-open')){suppressed=true;popover.hidePopover();e.preventDefault();e.stopImmediatePropagation();}}, {capture:true,signal:helpController.signal});
}
