import {chromium} from '/Users/christinaliu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';
const dir='prototype/qa/operating-model/print/',out='output/pdf/operating-model/';fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(out,{recursive:true});const results=[];
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try{for(const locale of ['zh-CN','en-AU','en-US'])for(const kind of ['scenario','skill']){const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page.setDefaultTimeout(10000);
 try{await page.goto(`http://127.0.0.1:8765/prototype/?studio=operating-model&scene=SCN-MATCH&locale=${locale}`);await page.waitForSelector('.om-page');const before=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('ctt-round-a-v1')));await page.locator(`[data-action="om-print"][data-value="${kind}"]`).click();const print=page.locator(`[data-print-scope="operating-model-${kind}"]`);await print.waitFor();const text=await print.innerText();
 if(kind==='scenario')for(const key of ['D4A-MATCH-01-01','D4A-MATCH-07-02','OM-F3','OM-F4','OM-F6'])assert.ok(text.includes(key),key+' remains in complete print');else assert.match(text,/SK-06/);if(locale!=='zh-CN')assert.doesNotMatch(text,/\p{Script=Han}/u);assert.equal(await print.locator('pre').count(),0);assert.match(text,/To-be|目标设计/);assert.match(text,/Synthetic|合成/);
 await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>[...document.images].every(i=>i.complete));const pdf=out+kind+'.'+locale+'.pdf';await page.pdf({path:pdf,format:'A4',landscape:true,preferCSSPageSize:true,printBackground:true});assert.deepEqual((await page.evaluate(()=>JSON.parse(sessionStorage.getItem('ctt-round-a-v1')))).data,before.data);await page.emulateMedia({media:'screen'});const exit=page.locator('[data-action="om-exit-print"]');if(await exit.isVisible())await exit.click();assert.equal((await page.evaluate(()=>JSON.parse(sessionStorage.getItem('ctt-round-a-v1')))).navigation.operating.action,before.navigation.operating.action);assert.ok(await page.locator('.om-page').isVisible());results.push({ids:['OM-23','OM-25'],name:kind+'.'+locale,status:'passed',pdf,visualStatus:'pending'});
 }catch(e){results.push({ids:['OM-23','OM-25'],name:kind+'.'+locale,status:'failed',error:e.message,stack:e.stack});await page.screenshot({path:dir+kind+'.'+locale+'.failure.png'}).catch(()=>{});}finally{await page.close();fs.writeFileSync(dir+'print.results.json',JSON.stringify({at:new Date().toISOString(),results},null,2));}}
 const page=await browser.newPage({viewport:{width:1440,height:1000},javaScriptEnabled:false});try{await page.goto('http://127.0.0.1:8765/07_output/operating-model-customer-en/');const text=await page.locator('body').innerText();assert.doesNotMatch(text,/\p{Script=Han}|IC-PHKL|PPT-S\d|D3-ISS|N = 8/u);assert.match(text,/Human Collaboration/);await page.pdf({path:out+'customer.en-AU.pdf',format:'A4',landscape:true,preferCSSPageSize:true,printBackground:true});results.push({ids:['OM-23','OM-25'],name:'customer.en-AU',status:'passed',pdf:out+'customer.en-AU.pdf',visualStatus:'pending'});}catch(e){results.push({ids:['OM-23','OM-25'],name:'customer.en-AU',status:'failed',error:e.message});}finally{await page.close();fs.writeFileSync(dir+'print.results.json',JSON.stringify({at:new Date().toISOString(),results},null,2));}
}finally{await browser.close();}console.log({checks:results.length,passed:results.filter(x=>x.status==='passed').length,failed:results.filter(x=>x.status==='failed')});if(results.some(x=>x.status==='failed'))process.exitCode=1;
