import {chromium} from '/Users/christinaliu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {initialNavigation} from '../../navigation.mjs';
import {screeningAction,screeningProjection} from '../../screening-engine.mjs';
const dir='prototype/qa/batch-c/',base='http://127.0.0.1:8765/prototype/';
const snapshots=JSON.parse(readFileSync('04_operating_model/batch-c/screening-snapshots.json')).snapshots;
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const results=[],errors=[];
const act=(s,type,extra={})=>screeningAction(s,{type,role:'ROLE-KYCOPS',expectedRevision:s.case.revision,expectedScopeRevision:s.scopes[0].revision,expectedInputRevisions:screeningProjection(s,{role:'ROLE-KYCOPS'}).inputRevisions,key:'edge:'+type+':'+s.case.revision,rationale:'Explicit local regression fixture',at:'2026-09-07T12:00:00Z',...extra});
const run=(outcome,unknown=false)=>{let s=structuredClone(snapshots['C-entry']);if(unknown)s.demoConfig.batchC.dataset={ref:null,version_status:'unknown',as_of:null};s=act(act(s,'prepare_preliminary'),'request_preliminary');return act(s,'receive_result',{runId:s.screeningRuns.at(-1).id,outcome});};
async function check(ids,name,data,options,fn){const {navigation,...browserOptions}=options||{};const ctx=await browser.newContext({viewport:{width:1440,height:1000},...browserOptions});const page=await ctx.newPage();page.setDefaultTimeout(6000);page.on('pageerror',e=>errors.push(name+': '+e.message));
 const n={...initialNavigation(),page:'product',step:'population',scenario:'SCN-POPULATION',stage:'S3',...options?.navigation};
 const session={data,navigation:n,versions:[],drafts:{},archives:[],collabCtx:{audience:'ops',tab:'requirements',userId:null,sessionId:null,itemId:null}};
 await page.addInitScript(s=>sessionStorage.setItem('ctt-round-a-v1',JSON.stringify(s)),session);
 try{await fn(page,data);results.push({ids:ids.map(n=>'RT-C'+String(n).padStart(2,'0')),name,status:'passed',steps:'Isolated explicit synthetic fixture through actual HTML; no alteration of user session',case_before:{revision:data.case.revision},case_after:await page.evaluate(()=>({revision:JSON.parse(sessionStorage.getItem('ctt-round-a-v1')).data.case.revision})),screenshot:name+'.png'});await page.screenshot({path:dir+name+'.png'});}catch(e){results.push({ids:ids.map(n=>'RT-C'+String(n).padStart(2,'0')),name,status:'failed',error:e.message});await page.screenshot({path:dir+name+'.failed.png'}).catch(()=>{});}finally{await ctx.close();}}
for(const outcome of ['zero','failed','partial','pending'])await check([2,5,6,20,45],'outcome.'+outcome,run(outcome,true),{},async(page,data)=>{
 await page.goto(base);await page.waitForSelector('[data-c-panel="population"]');const text=await page.locator('.c-workspace').innerText();assert.match(text,/Incomplete/);assert.match(text,/Unknown/);assert.ok(!text.includes('latest dataset'));assert.equal((await page.evaluate(()=>JSON.parse(sessionStorage.getItem('ctt-round-a-v1')))).data.case.revision,data.case.revision);
 const status=outcome==='zero'?'Completed':outcome==='failed'?'Failed':outcome==='partial'?'Partial':'Pending';assert.match(text,new RegExp(status));
});
const held=structuredClone(snapshots['C-referred']);held.demoConfig.batchC.holds.push({id:'QA-UNKNOWN-HOLD',status:'unknown',action_scope:['resume_branch'],object_scope_refs:[held.case.id]});
await check([24,46],'resume.held',held,{navigation:{step:'screening-evidence',scenario:'SCN-MATCH'}},async(page,data)=>{
 await page.goto(base);await page.waitForSelector('[data-c-panel="screening-evidence"]');assert.equal(await page.locator('[data-value="resume_branch"]').isDisabled(),true);assert.match(await page.locator('.c-workspace').innerText(),/HOLD_REQUIRES_REVIEW/);await page.locator('[data-action="c-back-review"]').click();assert.equal((await page.evaluate(()=>JSON.parse(sessionStorage.getItem('ctt-round-a-v1')))).data.case.revision,data.case.revision);assert.ok(await page.locator('#screening-rationale').isVisible());
});
await check([13,14],'role.unconfigured',snapshots['C-result'],{navigation:{role:'ROLE-CASEMGR',step:'screening',scenario:'SCN-MATCH'}},async(page)=>{
 await page.goto(base);await page.waitForSelector('#main');assert.equal(await page.locator('[data-action="c-action"]:enabled').count(),0);assert.doesNotMatch(await page.locator('#main').innerHTML(),/SYN-PROVIDER|1970|comparison_basis/);
});
await check([33,56,62],'fallback.reduced-mobile',snapshots['C-referred'],{viewport:{width:390,height:844},reducedMotion:'reduce',navigation:{page:'studio',step:'screening',scenario:'SCN-MATCH',modal:true}},async(page,data)=>{
 await page.route('**/diagrams/batch-c/*.svg',r=>r.abort());await page.goto(base);await page.waitForSelector('#scenario-dialog[open]');assert.equal(await page.locator('[data-semantic-node]').count(),12);assert.equal(await page.locator('#scenario-dialog video').count(),0);assert.match(await page.locator('#scenario-dialog').innerText(),/unknown|Unknown/);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal((await page.evaluate(()=>JSON.parse(sessionStorage.getItem('ctt-round-a-v1')))).data.case.revision,data.case.revision);
});
await check([49,57,58,59],'reference.public-url',snapshots['C-result'],{navigation:{page:'studio',scenario:'SCN-MATCH',modal:true}},async(page)=>{
 const requests=[];let resolveRequest;const externalRequest=new Promise(resolve=>{resolveRequest=resolve;});await page.context().route('**/*',route=>{if(!route.request().url().startsWith('https:'))return route.continue();const request={url:route.request().url(),headers:route.request().headers()};requests.push(request);resolveRequest(request);return route.abort();});await page.goto(base);await page.waitForSelector('#scenario-dialog[open]');await page.locator('[data-c-ref="M03"]').click();const a=page.locator('#scenario-dialog a[href^="https://"]').first();const href=await a.getAttribute('href');assert.doesNotMatch(href,/DEMO-CTT|Person|token|case_id/);assert.equal(await a.getAttribute('referrerpolicy'),'no-referrer');const popupPromise=page.context().waitForEvent('page');await a.click();const popup=await popupPromise;const request=await Promise.race([externalRequest,new Promise((_,reject)=>setTimeout(()=>reject(Error('No intercepted public-link request')),6000))]);assert.equal(request.url,new URL(href).href);assert.equal(request.headers.referer,undefined);await popup.close();assert.doesNotMatch(await page.locator('#scenario-dialog').innerHTML(),/\.pptx|\/Users\/|Planning-transcript/);
});
await check([28,30,50,64],'journey.drag-and-history',snapshots['C-referred'],{navigation:{page:'studio',scenario:'SCN-MATCH',modal:false,mode:'explore',comparison:'current',stage:'S3',camera:{anchor:'SCN-MATCH',offset:40}}},async(page,data)=>{
 await page.goto(base);const box=page.locator('.journey-scroll');await box.scrollIntoViewIfNeeded();const rect=await box.boundingBox();await page.mouse.move(rect.x+rect.width-100,rect.y+100);await page.mouse.down();await page.mouse.move(rect.x+rect.width-320,rect.y+100,{steps:10});await page.mouse.up();const card=page.locator('.scene-card[data-value="SCN-MATCH"]');await card.scrollIntoViewIfNeeded();const left=await box.evaluate(e=>e.scrollLeft);await card.click();await page.locator('[data-c-node="M04"]').click();const anchored=await box.evaluate(e=>e.scrollLeft);const diagram=page.locator('.c-diagram');if(await diagram.isVisible()){const d=await diagram.boundingBox();await page.mouse.move(d.x+d.width/2,d.y+30);await page.mouse.down();await page.mouse.move(d.x+d.width/2-80,d.y+30,{steps:5});await page.mouse.up();assert.equal(await box.evaluate(e=>e.scrollLeft),anchored);}
 await page.locator('[data-action="close"]').click();assert.ok(Math.abs(await box.evaluate(e=>e.scrollLeft)-left)<4);await card.click();await page.locator('#scenario-dialog [data-action="product"][data-value="screening"]').click();await page.goBack();await page.waitForSelector('#scenario-dialog[open]');const s=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('ctt-round-a-v1')));assert.equal(s.navigation.comparison,'current');assert.equal(s.navigation.scenario,'SCN-MATCH');assert.equal(s.data.case.revision,data.case.revision);
});
for(const role of ['ROLE-KYCOPS','ROLE-RM','ROLE-CLIENT'])await check([13,36],'clearance.'+role,snapshots['C-referred'],{navigation:{step:'clearance',scenario:'SCN-READINESS',role}},async(page,data)=>{
 await page.goto(base);await page.waitForSelector('#main');const text=await page.locator('#main').innerText();assert.match(text,/Not ready|not ready/);assert.doesNotMatch(text,/undefined|NaN/);assert.doesNotMatch(await page.locator('#main').innerHTML(),/SYN-PROVIDER|comparison_basis|1970/);const actual=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('ctt-round-a-v1')).data);assert.deepEqual(actual.clearanceConditions,data.clearanceConditions);
});
for(const step of ['scope','authority'])await check([67],'preserved-a.'+step,snapshots['C-referred'],{navigation:{step,scenario:step==='scope'?'SCN-SCOPE':'SCN-ENTITY'}},async(page,data)=>{
 await page.goto(base);await page.waitForSelector('#main');assert.equal(await page.locator('.c-workspace').count(),0);assert.doesNotMatch(await page.locator('#main').innerText(),/undefined|NaN/);assert.equal((await page.evaluate(()=>JSON.parse(sessionStorage.getItem('ctt-round-a-v1')))).data.case.revision,data.case.revision);
});
writeFileSync(dir+'browser-edge-results.json',JSON.stringify({at:new Date().toISOString(),browser:browser.version(),command:'node prototype/qa/batch-c/edge-browser.mjs',results,errors},null,2)+'\n');await browser.close();console.log({passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed'),errors});if(results.some(r=>r.status==='failed')||errors.length)process.exitCode=1;
