import {chromium} from '/Users/christinaliu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';import {writeFileSync} from 'node:fs';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const dir=new URL('./',import.meta.url),base='http://127.0.0.1:8765/prototype/media/d2-batch-c/static/',results=[];
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try{for(const scene of ['SCN-POPULATION','SCN-MATCH','SCN-EDD'])for(const locale of ['en-AU','en-US','zh-CN']){
 const context=await browser.newContext({javaScriptEnabled:false,viewport:{width:1440,height:1000}}),page=await context.newPage();
 try{await page.goto(base+scene+'.'+locale+'.html');assert.equal(await page.locator('[data-semantic-node]').count(),24);assert.equal(await page.locator('video,iframe,script').count(),0);assert.equal(await page.locator('button').count(),0);assert.ok(await page.locator('.reference-card').count()>0);assert.equal(await page.locator('a[target="_blank"]:not([rel="noopener noreferrer"])').count(),0);for(const img of await page.locator('img').all())assert.ok(await img.evaluate(e=>e.complete&&e.naturalWidth>0));if(locale==='en-AU')await page.screenshot({path:fileURLToPath(new URL(scene+'.static.png',dir))});results.push({scene,locale,status:'passed',assertions:['24 Current/Target nodes','no script/player/business control','visible source footnotes','canonical SVG loaded']});}catch(e){results.push({scene,locale,status:'failed',error:e.message});}finally{await context.close();}
 }
 const context=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}}),page=await context.newPage();await page.route('**/*.svg',r=>r.abort());await page.goto(base+'SCN-MATCH.en-AU.html');assert.equal(await page.locator('[data-semantic-node]').count(),24);assert.match(await page.locator('body').innerText(),/Refer or stay unresolved|Refer \/ maintain unresolved/);await page.screenshot({path:fileURLToPath(new URL('match.no-image.mobile.png',dir)),fullPage:true});results.push({scene:'SCN-MATCH',locale:'en-AU',status:'passed',assertions:['SVG blocked and JavaScript disabled: full decision content remains']});await context.close();
}finally{await browser.close();writeFileSync(new URL('static-results.json',dir),JSON.stringify({results,scope:'static fallback only; not interactive mainline proof'},null,2)+'\n');}
console.log({checks:results.length,failed:results.filter(r=>r.status==='failed')});if(results.some(r=>r.status==='failed'))process.exitCode=1;
