import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
const read=f=>fs.readFileSync(f,'utf8'),hash=f=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const put=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');};
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
for(const d of ['environment','contracts','ui-baseline','reports','traces','accessibility','ux-audit-assets','screenshots/baselines','screenshots/actual','screenshots/diffs','screenshots/annotated'])fs.mkdirSync('audit/'+d,{recursive:true});
const source='00_sources/d5/Clear_to_Trade_D5_Product_Experience_Bindings_v0.2.json',j=JSON.parse(read(source));
const sourceFiles=[source,'00_sources/d5/Clear_to_Trade_D5_Product_Experience_Review_v0.2.md','00_sources/d4/Clear_to_Trade_D4_Action_Assessments_v0.1.json','/Users/christinaliu/Downloads/CLEAR_TO_TRADE_PRODUCT_EXPERIENCE_QUALITY_GATE.md'];
const files=walk('prototype').filter(f=>/\.(mjs|css|html)$/.test(f)&&!f.includes('/qa/'));
put('audit/environment/pre-audit-hashes.json',{at:new Date().toISOString(),sources:Object.fromEntries(sourceFiles.map(f=>[f,hash(f)])),product:Object.fromEntries(files.map(f=>[f,hash(f)]))});
fs.copyFileSync(sourceFiles.at(-1),'audit/environment/CLEAR_TO_TRADE_PRODUCT_EXPERIENCE_QUALITY_GATE.md');
put('audit/environment/git-status-before.txt',execFileSync('git',['status','--short'],{encoding:'utf8'}));
const dep=JSON.parse(read('audit/tooling/package-lock.json'));
put('audit/environment/ENVIRONMENT_DISCOVERY.md',`# Environment discovery\n\nDate: ${new Date().toISOString()}\n\nRepository: ${process.cwd()}\n\nBranch: ${execFileSync('git',['branch','--show-current'],{encoding:'utf8'}).trim()}\nHEAD: ${execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim()}\n\nNode ${process.version}; ${execFileSync('npm',['--version'],{encoding:'utf8'}).trim()} npm. Existing native HTML/CSS/ES modules; no root package manifest changed. Dirty checkout preserved and hashed. No remote publishing.\n\n## Audit tooling\n\n- Playwright Test ${dep.packages['node_modules/@playwright/test'].version}; axe integration ${dep.packages['node_modules/@axe-core/playwright'].version}; axe ${dep.packages['node_modules/axe-core'].version}. Isolated audit/tooling dependency lock. npm reports zero vulnerabilities at installation; not a security certification.\n- Existing Google Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome; localhost-only browser runs previously authorised by Christina.\n- ux-audit was absent. Installer download failed local Python TLS certificate-chain validation; normal-TLS Git transport succeeded. Installed /Users/christinaliu/.codex/skills/ux-audit. Not auto-discovered/executed this session; available on a subsequent turn. Current heuristic review uses installed Product Design Audit, explicitly distinguished.\n- No Figma tooling, paid services, real bank integrations, model calls or global Python installs.\n- Source hashes and pre-audit product hashes: pre-audit-hashes.json. Bank policy/authority unknown; document approval is not application test evidence.\n`);
const runtime={
 'SCN-SCOPE':['scope','Existing A scope action guards'], 'SCN-ENTITY':['entity','Existing A entity/authority guards'],
 'SCN-REQUIREMENTS':['requirements','Round A bounded requirements'], 'SCN-SOURCE':['evidence','Round A source/evidence'],
 'SCN-GAP':['collaboration','B scoped request save / review / dispatch / submit_response'],
 'SCN-VALIDATE':['screening-evidence','B release/link and C assess_identity_insufficient'],
 'SCN-POPULATION':['population','C prepare_preliminary / request_preliminary / receive_result'],
 'SCN-MATCH':['screening','C save_review_draft / request_identity / refer / record_unresolved; exclusion disabled'],
 'SCN-EDD':['edd','C conditional EDD fixture; not hero closure'],
 'SCN-CONFLICTS':['conflicts','D bounded specialist work'], 'SCN-CREDIT':['credit','D bounded specialist work'], 'SCN-LEGAL':['legal','D bounded specialist work'],
 'SCN-QA':['authored scenario only','No complete D5 QA remediation/signoff runtime'],
 'SCN-READINESS':['readiness','Readiness projection only; missing full approved closure manifest'],
 'SCN-PUBLISH':['authored scenario only','No final authorisation/publication runtime']};
const priority=['SCN-MATCH','SCN-READINESS','SCN-PUBLISH','SCN-GAP','SCN-QA'];
const contracts=j.scenario_bindings.map(s=>{const p=j.progress_scene_bindings.find(p=>p.scenario_id===s.scenario_id),actions=j.action_presentations.filter(a=>a.scenario_ref===s.scenario_id),surface=j.surfaces.find(x=>x.surface_id===s.primary_surface_ref);return {...s,contract_depth:priority.includes(s.scenario_id)?'full_priority':'thin_mapping',source_status:'approved demo design, not bank policy or runtime proof',source_file:source,journey_moment:p.display_topics_zh,product_surface:surface,runtime:{entry:runtime[s.scenario_id][0],scope:runtime[s.scenario_id][1]},next_owner:p.owner_and_handoff_zh,local_consequence_boundary:p.boundary_zh,actions:actions.map(a=>({id:a.action_ref,parent:a.parent_change_ref,persona:a.source_primary_executor,intent:a.source_label_zh,reads:a.source_reads,outputs:a.source_outputs,required_information:a.source_preconditions,formal_gate:a.source_formal_gate,forbidden_effects:a.source_forbidden_effects,oracle:a.source_test_oracle,source_refs:[...a.current_ppt_source_refs,...a.target_ppt_source_refs],ui_button_automatic:false})),test_binding:s.scenario_id==='SCN-MATCH'?'audit/tests/journey.mjs P1–P8 / CHK-01–04':s.scenario_id==='SCN-GAP'?'audit/tests/journey.mjs P3–P5':s.scenario_id==='SCN-READINESS'?'audit/tests/surfaces.mjs Not Ready + engine safety tests':priority.includes(s.scenario_id)?'NOT_RUN complete runtime absent; source mapping and readonly scene audit only':'thin mapping; existing engine suites where implemented'};});
put('audit/contracts/D5_SCENARIO_PRODUCT_CONTRACTS.json',{source,source_sha256:hash(source),counts:j.source_counts,contracts,context_contract:j.context_contract,closure_manifest:j.inherited_closure_manifest,unresolved_source_issues:j.unresolved_source_issues});
let md='# D5 Scenario → Product contracts\n\nAuthoritative design mapping, not proof of implementation. Stable D4/D3/PX/SCN identifiers preserved; demo roles are not verified bank authority. Full reads/outputs/preconditions/forbidden effects and exact inherited source refs are in the companion JSON (229 actions, 94 parents, 15 scenes).\n\n';
for(const c of contracts){md+=`## ${c.scenario_id} · ${c.contract_depth}\n\n${c.role_views.join(' / ')} → ${c.workflow_ref} → ${c.primary_surface_ref} ${c.product_surface.title_en}\n\nIntent / moment: ${c.journey_moment.join(' → ')}\n\nCurrent runtime: ${c.runtime.entry}; ${c.runtime.scope}.\n\nConsequence boundary: ${c.local_consequence_boundary}\n\nTest: ${c.test_binding}\n\n`;if(c.contract_depth==='full_priority')for(const a of c.actions)md+=`- ${a.id}: ${a.intent}. Reads: ${a.reads.join(', ')}. Outputs: ${a.outputs.join(', ')}. Forbidden: ${a.forbidden_effects.join('; ')}. Oracle: ${a.oracle}\n`;md+='\n';}
put('audit/contracts/D5_SCENARIO_PRODUCT_CONTRACTS.md',md);
const css=files.filter(f=>f.endsWith('.css')),tokens=[];for(const f of css)for(const m of read(f).matchAll(/(--[\w-]+)\s*:\s*([^;}]+)/g))tokens.push({file:f,token:m[1],value:m[2]});
put('audit/ui-baseline/tokens.json',tokens);
put('audit/ui-baseline/UI_TOKEN_INVENTORY.md',`# Current UI baseline\n\nInspected BEFORE fresh screenshots. Source of truth: current prototype/glass.css, readability/navigation styles and product-experience/product-experience.css, not older design prose. All source files hashed.\n\n| Layer | Existing implementation |\n|---|---|\n| Colour | ink #17191c; muted #5b6067; blue #086bb5; deep blue #004d86; paper #efede9; translucent white panel |\n| Typography | Helvetica Neue / Helvetica / Arial / PingFang SC / Microsoft YaHei; operational 14px, metadata 12px, mobile inputs 16px; display headings light |\n| Spacing | Operational grid gap 32px; panel padding 28px; details 12px; 6-step strip gap 4px |\n| Radius | Glass panel 30px, card 22px, capsule control 999px; D5 step cards 6px, layout editor 8px |\n| Border / surface | Muted grey-blue hairlines, soft white glass; backdrop blur + simulated gradient bevel/highlight, NOT physical optical refraction |\n| Icons | Existing ui-icon / status icon mapping; labels remain sharp |\n| States | Focus-visible blue outline; disabled grey; glass pressed/release; reduced motion disables transforms/transitions |\n| Layout | Evidence/action 1.9:1; six steps desktop, three <=900px, two <=650px; task grid stacks <=650px |\n| Breakpoints | Glass 1200,1101,700; D5 1200,900,650; audit also checks tablet/mobile |\n\nExact declarations: tokens.json. No palette/radius/font redesign authorised by this audit.\n`);
put('audit/ui-baseline/COMPONENT_USAGE_MATRIX.md',`# Component usage\n\n| Component | Current surfaces | Audit focus |\n|---|---|---|\n| Topbar / Current–Target / locale | Studio, Product | Stable position, selected state, contrast |\n| Journey scroll / stage rail | Current and Target | Drag alternative, semantic location, modal return |\n| Native Scenario / dirty dialog | Studio ↔ Product | Accessible name, keyboard trap, return focus |\n| CORE-CONTEXT / PROGRESS | PX-09 | Identity, owner, next actor, factual times; cannot remove |\n| Comparison table / evidence | PX-09 / PX-07 | Relevant source, unknown, received vs sufficient |\n| CORE-ACTION | PX-09 | Role guards, exact consequence, notices, one primary action |\n| Scoped request cards / input | PX-04 / PX-06 | Recipient permission, client projection, receipt vs sufficiency |\n| Cases / History | D5 Product | Current ACL, empty vs missing, readonly snapshot |\n| Customise / optional modules | D5 Product | Keyboard reorder, no business mutation, fixed core |\n| Print sheet / static graph | Studio, Product | Complete content, role filtering, fallback |\n\nQA/PUBLISH full workspaces not implemented. Existing scene descriptions are not substitute interactive workflows.\n`);
console.log({contracts:contracts.length,actions:contracts.reduce((n,c)=>n+c.actions.length,0),product_files:files.length,css:css.length});
