import fs from 'node:fs';
const steps=[
 ['01','进入同一个案件','REVIEW','../screenshots/baselines/04-CHK01.png','案件、Person T 与范围版本清晰；当前问题和下一动作已作受控修正。首屏密度仍待调整。'],
 ['02','比较资料与未知项','PASS — bounded','../screenshots/actual/compare-detail.png','姓名相似、出生年份冲突与其他未知属性分开；截图只能证明呈现，实际写入边界见浏览器与单元证据。'],
 ['03','查看原查询与来源','PASS — bounded','../screenshots/actual/source-detail.png','原查询、主体快照、来源快照可展开。编号保留追溯，但不应成为主要信息。'],
 ['04','只请求当前缺口','REVIEW','../screenshots/actual/journey/identity.request.en-AU.png','实际请求链保留原有 authority / ownership 项，不扩张客户访问。演示控制区占比偏大。'],
 ['05','客户完成限定任务','REVIEW','../screenshots/actual/journey/identity.client.en-AU.png','客户只能看到自己的资料任务；内部 provider 信息未出现在实际 DOM。首屏仍像演示控制台。'],
 ['06','收到不等于充分','PASS — bounded','../screenshots/baselines/05-CHK02.png','收到资料后还需接收放行、关联及用途评估。导航到内部视图不会替用户完成评估。'],
 ['07','按用途评估与恢复','PASS — bounded','../screenshots/actual/visual/06-CHK03.png','本例身份资料不足以支持排除；保留用途与版本，不改变签约权限或全案条件。结论限于当前演示角色配置；修改权限后的指引边界见 UX-010。'],
 ['08','人工问题与局部结果','REVIEW','../screenshots/actual/visual/08-decision-pack.png','只呈现配置允许的有界动作；资料评估先进入显式选项，不由导航按钮代写 Unknown。未决或转交不是全案批准。需要真实复核人员验证用语与判断可理解性。'],
 ['09','回看全案 Readiness','REVIEW','../screenshots/baselines/10-readiness.png','当前案保持尚未就绪；未知条件、其他条线与发布边界不因局部结果变绿。'],
 ['10','返回原场景','PASS — bounded','../screenshots/baselines/09-case-return.png','Current 来源与最新中文偏好保留；单独浏览器检查验证横向 760px 返回 760px、业务数据不变。']
];
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>D5 体验审查 · Person T</title><style>body{margin:0;background:#efede9;color:#17191c;font:16px/1.65 'Helvetica Neue',Arial,'PingFang SC',sans-serif}main{max-width:1180px;margin:auto;padding:40px 24px}h1{font-size:36px;font-weight:400}h2{font-size:24px}small,.meta{color:#5b6067;font-size:13px}nav{display:flex;gap:18px;flex-wrap:wrap}a{color:#004d86}section{border-top:1px solid #bbc4cc;margin-top:36px;padding-top:20px}img{width:100%;height:auto;border:1px solid #c7cdd2;border-radius:8px}figure{margin:18px 0}figcaption{padding:12px 16px;background:#fff;border-left:3px solid #086bb5}.status{font-size:13px;padding:4px 8px;border:1px solid #9ba9b4;border-radius:20px}strong{font-weight:600}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}@media(max-width:800px){.pair{display:block}}@media print{main{padding:0}section{break-before:page}nav{display:none}}</style><main><small>CLEAR TO TRADE · LOCAL DESIGN REVIEW</small><h1>先让人知道下一步，再让界面更从容。</h1><p>这轮以 Person T 的真实本地操作链审查 D5：从疑似命中、限定补证、用途评估，到人工未决结果和回看全案。不是银行确认，也不是用户研究。</p><nav><a href="../reports/UX_EXECUTIVE_SUMMARY.md">审查结论</a><a href="../reports/UX_FINDINGS.md">问题与修复清单</a><a href="../reports/ACCESSIBILITY_REPORT.md">可访问性</a><a href="../reports/UI_VISUAL_REGRESSION_REPORT.md">视觉验证范围</a></nav><section><h2>本轮标注：保留方向，修正三个断点</h2><p>状态不变的“下一步”文案、跨到其他演示数据的 Readiness 入口、以及未显示的键盘焦点，属于本轮受控修复。首屏密度、客户页演示工具和技术文案属于下一轮待确认项。</p><div class="pair"><figure><img src="../screenshots/actual/surfaces/responsive-1366-en-AU.png" alt="1366像素笔记本视图"><figcaption><strong>信息层级：</strong>顶部多层导航和步骤条挤压实际任务空间。建议下一轮压缩为当前步骤摘要，不删业务依据。</figcaption></figure><figure><img src="../screenshots/actual/journey/identity.client.en-AU.png" alt="客户限定任务首屏"><figcaption><strong>角色体验：</strong>客户任务应成为主角；主持人工具应后退到单独可控层。权限隔离通过不等于客户体验已经成熟。</figcaption></figure></div></section>${steps.map(([n,title,status,img,note])=>`<section id="step-${n}"><small>JOURNEY STEP ${n}</small><h2>${title} <span class="status">${status}</span></h2><figure><img src="${img}" alt="${title}的本轮真实截图"><figcaption>${note}</figcaption></figure></section>`).join('')}<section><h2>无法从截图判定的内容</h2><p>真实用户是否能快速理解、银行权限是否正确、生产系统安全性、辅助技术实际可用性及完整归档结果。交互行为只引用实际测试结果；截图不替代行为证据。</p><p class="meta">截图为当前审查回合采集。修复前后与基线状态见报告；候选基线并不代表 Christina 已批准视觉。完整页长截图中的 sticky 定位可能是捕获伪影，不作为产品缺陷依据。</p></section></main></html>`;
fs.writeFileSync('audit/ux-audit-assets/journey-review.html',html);
fs.writeFileSync('audit/screenshots/annotated/README.md','# Annotated review\n\nAnnotations are HTML captions beside unmodified screenshots in ../../ux-audit-assets/journey-review.html. No generative redraw or fabricated product screenshot. Initial versus final capture references are distinguished in the visual report.\n');
fs.writeFileSync('audit/reports/HEURISTIC_JOURNEY_REVIEW.md','# Ordered heuristic review\n\nMethod: installed Product Design Audit framework, not the newly installed ux-audit skill. Fresh screenshots were opened and inspected as an ordered journey. Interactive claims come only from separately cited executable checks.\n\n'+steps.map(([n,title,status,img,note])=>`## ${n} ${title} — ${status}\n\n${note}\n\nEvidence: ${img}\n`).join('\n')+'\n## Positives\n\nClear identity comparison; bounded unresolved result; visible non-readiness; constrained contributor task; consistent black/blue/white environment.\n\n## Not assessable\n\nReal-user comprehension/time, bank policy correctness, production RBAC, actual email/screening integration, assistive-tech experience and meaningful historical-outcome usability. Native zoom/400% reflow not completed.\n');
