import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
const read=f=>fs.readFileSync(f,'utf8'),json=f=>JSON.parse(read(f)),put=(f,s)=>fs.writeFileSync('audit/reports/'+f,typeof s==='string'?s:JSON.stringify(s,null,2));
const units=json('audit/reports/unit-results.json'),surfaces=json('audit/reports/surfaces-results.json'),journey=json('audit/screenshots/actual/journey-final/browser-results.json');
const checks=[...surfaces.results,...journey.results,...json('audit/reports/time-print-results.json').results,...json('audit/reports/context-extra-results.json').results];
const host=fs.readdirSync('audit/screenshots/actual/host').filter(f=>f.endsWith('.results.json')).flatMap(f=>json('audit/screenshots/actual/host/'+f).results);checks.push(...host);
const scans=fs.readdirSync('audit/accessibility').filter(f=>f.endsWith('.json')).map(f=>({file:f,...json('audit/accessibility/'+f)}));
const violations=scans.flatMap(s=>s.violations.map(v=>({file:s.file,id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))),serious=violations.filter(v=>['serious','critical'].includes(v.impact));
const fixes=fs.existsSync('audit/reports/fix-review-verdict.json')?json('audit/reports/fix-review-verdict.json'):{guidance:'open',readiness:'open',keyboard:'open',review:'pending'};
const ready=fixes.guidance==='fixed'&&fixes.readiness==='fixed'&&fixes.keyboard==='fixed'&&!serious.length&&!checks.some(c=>c.status==='failed');
const gates=[['G0','PASS','15 scenario contracts / 229 action mappings; full priority contracts. QA/PUBLISH runtime is explicitly absent.'],['G1',fixes.guidance==='fixed'?'REVIEW':'FAIL','Role/state-specific guidance retested if fixed; real-user comprehension timing not tested.'],['G2',fixes.readiness==='fixed'?'REVIEW':'FAIL','Actual C/B hero executed; QA remediation and publication success runtime NOT_RUN.'],['G3',checks.filter(c=>c.name?.includes('horizontal')).some(c=>c.status==='failed')?'FAIL':'REVIEW','Executed same-case navigation, locale, history and module-isolation subset PASS; mandatory full CTX-06 Lab Shadow NOT_RUN.'],['G4','PASS','Bounded engine/browser safety oracles; production RBAC, bank policy and live systems not validated.'],['G5','REVIEW','Time semantics and clock no-write pass; default time/next-owner visibility and long progress layout need user review.'],['G6','REVIEW','Tokens retained; first-viewport density and workshop chrome remain S2.'],['G7',surfaces.results.filter(c=>c.name.startsWith('responsive')).some(c=>c.status==='failed')?'FAIL':'PASS','12 width/language combinations; CSS text scaling only, not full native zoom coverage.'],['G8',serious.length?'FAIL':'REVIEW',`${scans.length} axe scans; ${serious.length} serious/critical violation groups; heading outline moderate issues remain.`],['G9','REVIEW','15 provisional screenshot states; repeated-capture checks are not Christina visual approval. Archived/completed outcome fixtures absent.'],['G10','REVIEW','Fresh ordered screenshot heuristic review; installed ux-audit not executed this session; Product Design Audit method used.']];
const findings=[
 ['UX-001','S1','G1/G2','KYC Ops / Reviewer','SCN-MATCH','PX-09','Summary and action emphasis do not follow receipt, purpose assessment or recorded result.','screenshots/actual/journey/review.pack.en-AU.text.txt','Current-state guidance with one permitted next step.','Avoid unnecessary repeated collection and repeated local decisions.','Use existing projection and guarded actions, no new business writes.','M',fixes.guidance,'controlled-fix-report.md','Quality Gate P1/P5/P6; D5 §18.2/20.2'],
 ['UX-002','S1','G2/G3','KYC Ops','SCN-READINESS','PX-12 entry','Current C case Readiness route leads to Batch D fixture-load preview.','reports/surfaces-initial.json; screenshots/actual/surfaces/readiness-not-ready.failure.png','Readonly readiness of the same case without loading another fixture.','Breaks the end-to-end current-case story.','Reuse current safe projection; keep D fixture entry separate.','M',fixes.readiness,'surfaces-results.json; controlled-fix-report.md','Quality Gate P7/P8 and CTX-01'],
 ['UX-003','S2','G6/G7','KYC Ops','SCN-MATCH','PX-09','Core evidence and action column begins around y=660 at 1366×768 before the guidance fix; too little of the task fits the first screen.','screenshots/actual/surfaces/responsive-1366-en-AU.png','Current task and a meaningful amount of evidence immediately visible.','Excess navigation/progress height increases scrolling and weakens hierarchy.','After review, compact upper navigation/progress into a summary; keep full detail expandable.','M','open — review only','No S2 redesign performed','Quality Gate G6/G7'],
 ['UX-004','S2','G8','All tested roles','SCN-MATCH / SCN-GAP','PX-09 / PX-04 / Cases','Missing h1 or skipped heading levels in several rendered surfaces.','accessibility/*.json','Logical heading outline with page heading.','Assistive navigation loses structure, although tested keyboard tasks remain operable.','Correct semantic heading levels independently of visual typography.','S','open — review only','Automated axe; no screen-reader certification','Quality Gate G8'],
 ['UX-005','S2','G6/G10','Client contributor','SCN-GAP','PX-04','Large workshop controls dominate the client first viewport above the actual request.','screenshots/actual/journey/identity.client.en-AU.png','Client task before facilitator controls in the presentation hierarchy.','Makes the limited client contribution look like an internal demo console.','Fold facilitator tools into a clearly separate controlled disclosure after review.','M','open — review only','No client chrome redesign','D5 client scope / Quality Gate G6'],
 ['UX-006','S2','G6/G10','Chinese-speaking facilitator / reviewer','SCN-MATCH','Studio / PX-09','Some source/internal labels remain mixed-language or prominent (source-comparison, finding, review, EV-ID-C01 and long evidence IDs).','screenshots/actual/journey/population.return.zh-CN.png; identity.assessed.en-AU.png','Human-readable bilingual wording first, source IDs secondary.','Still feels partly written for builders; weakens the requested human-friendly journey.','Translate human-facing prose and keep exact identifiers in muted metadata/disclosures, without renumbering.','M','open — review only','No bulk copy rewrite','User instruction to de-emphasise IDs; Quality Gate G6'],
 ['UX-007','S2','G2/G9','QA / Clearance reviewer','SCN-QA / SCN-PUBLISH','PX-11 / PX-12','Full QA remediation, final authorisation/publication and three ended/cleared historical outcomes are not implemented or lack approved fixtures.','contracts/D5_SCENARIO_PRODUCT_CONTRACTS.json; cases-archived screenshot','Explicit scope limit; no fictional success state.','Prevents representing this bounded pilot as the full workshop product.','Approve downstream fixtures and scope in a later batch; keep NOT_RUN now.','L','scope limitation — not expanded','NOT_RUN full downstream outcomes','D5 §16.1/22.4; Quality Gate G2/G9'],
 ['UX-008','S2','G5','KYC Ops','SCN-MATCH','PX-09 progress','Timing detail is honest but mostly collapsed; six equally large step cards and repeated metadata add density.','screenshots/actual/progress-detail.png','Compact current owner/wait/expected summary with accessible details.','Users must open another layer to understand waiting and timing.','Review compact current-step summary in the next visual pass; retain unknowns and factual clock separation.','M','open — review only','Time semantics tests pass; user comprehension NOT_ASSESSABLE','D5 §18.2; Quality Gate G5'],
 ['UX-009','S1','G8','Keyboard user','SCN-MATCH','PX-09','Actual focused summary matches :focus-visible but outline computes to none because --accent is undefined.','reports/focus-diagnostic.json; context-extra-initial.json','Visible keyboard focus using the existing palette.','Keyboard users cannot reliably see their location, which axe alone did not detect.','Replace invalid colour-token reference with the existing blue token; no new colour values.','S',fixes.keyboard||'open','context-extra-results.json; controlled-fix-report.md','Quality Gate G8 manual focus requirement']
].map(([id,severity,gate,persona,scenario,surface,finding,evidence,expected,why,recommendation,effort,status,retest,oracle])=>({id,severity,gate,persona,scenario,surface,finding,evidence,expected,why,recommendation,effort,status,retest,oracle}));
findings.push({id:'UX-010',severity:'S1 — configuration-specific, outside frozen main demo',gate:'G1/G4',persona:'Reviewer with changed demo permissions',scenario:'SCN-MATCH',surface:'PX-09 hero',finding:'Removing assess_identity from the viewing Reviewer role can make a still-valid KYCOps assessment appear as changed evidence. Native basis resolution itself is permission-sensitive.',evidence:'reports/final-review-verdict.md; prototype/screening-predicates.mjs:225',expected:'Permission denial and actual evidence invalidation must have distinct guidance.',why:'No write bypass occurs, but the next-action explanation can be misleading after permission reconfiguration.',recommendation:'Keep this review limited to the frozen supplied role configuration. In a subsequent bounded fix, distinguish denied basis visibility from changed evidence without weakening guards.',effort:'M',status:'open — unsupported permission-reconfiguration variant',retest:'Default configured roles passed; reviewer reproduced the altered configuration in memory. Not included in passing browser count.',oracle:'Final scoped review; bank permissions remain unconfirmed demo configuration.'});
put('findings.json',findings);put('gates.json',gates.map(([gate,result,basis])=>({gate,result,basis})));
put('UX_FINDINGS.md','# UX / UI findings\n\nSeverity is task/safety impact, not a visual score. Only S0/S1 may be fixed in this round. No S0 reproduced in the tested local fixtures.\n\n'+findings.map(f=>`## ${f.id} · ${f.severity} · ${f.status}\n\n- Gate / persona / scene / surface: ${f.gate} · ${f.persona} · ${f.scenario} · ${f.surface}\n- Finding: ${f.finding}\n- Evidence (relative to audit/): ${f.evidence}\n- Expected: ${f.expected}\n- Why it matters: ${f.why}\n- Recommendation / effort: ${f.recommendation} · ${f.effort}\n- Retest: ${f.retest}\n- Oracle: ${f.oracle}\n`).join('\n'));
put('ACCESSIBILITY_REPORT.md',`# Accessibility — first pass\n\nResult: ${serious.length?'FAIL':'REVIEW'}. ${scans.length} fresh axe scans. ${serious.length} serious/critical violation groups. ${violations.length} total violation groups, with repeated headings counted per page.\n\nNative modal Tab containment (20 advances), Escape and source-focus return are tested in surfaces-results/context-extra-results. Customize keyboard entry, non-drag move buttons and reduced-motion/touch input are covered by host checks. Visible focus outline is checked on source disclosure. 12 viewport/language combinations checked for horizontal page overflow.\n\n## Automated findings\n\n| Surface evidence | Rule | Impact | Nodes |\n|---|---|---|---|\n${violations.map(v=>`| ${v.file} | ${v.id} | ${v.impact} | ${v.nodes.length} |`).join('\n')}\n\n## Limits\n\nNo VoiceOver/NVDA user run, OS high-contrast review, native 200% browser zoom or comprehensive 400% reflow verification. CSS root/body text scaling is a limited probe and fixed-px typography does not fully scale. Axe incomplete items (notably contrast where backgrounds prevent certainty) remain in raw JSON for human review. Disabled controls intentionally are not keyboard actions. This is NOT WCAG certification. S2 heading fixes await Christina review.\n`);
const vectors=[
 ['False Ready','False Green:', 'business logic','Unresolved required branches prevent whole-case clearance.'],
 ['Stale / withdrawn evidence','D5 changed or quarantined intake', 'business logic','Changed/quarantined evidence invalidates old assessment. Withdrawal event not implemented; not separately exercised.'],
 ['Wrong role / authority','D5 RM request bridge cannot', 'permission/privacy','Role-bound bridge exposes no Ops commands to RM or denied client.'],
 ['Missing owner','D5 progress has five anchors', 'open business assumption','Unassigned remains explicit; no invented bank reviewer.'],
 ['Missing applicability','Empty conditions and missing scope', 'business logic','Empty/unknown manifest cannot become Ready.'],
 ['Conflicting evidence','RT-C07/08/09/34:', 'test-data','Authored contradictory year claims remain inconclusive; conflicting uploaded-document workflow NOT_RUN.'],
 ['Stale decision write','RT-C14/15/16/17/66:', 'business logic','Current role, versions, rationale and idempotency gate decisions.'],
 ['History / current collision','D5 history access precedes', 'permission/privacy','Historical projection does not replace current session; no full archived outcome fixture.'],
 ['Language / view writes','D5 progress has five anchors', 'UX/business logic','Actual browser language/future-step/return checks preserve data.'],
 ['Optional module hides core','D5 layout stores only IDs', 'UI/permission','Core cannot be removed or grant derived from preference.'],
 ['Page open writes started','D5 progress has five anchors', 'business logic','Projection read does not create event or start time; browser open state equality.'],
 ['Estimate expires → complete','D5 exact time illustration', 'business logic','Clock jump to 2027 and readonly timing view cannot complete current case (time-print-results).'],
 ['Parallel branch wrongly paused','D review fix: unknown Legal dependency', 'business logic','Affected Legal work can wait without stopping Credit.'],
 ['Local complete closes case','One complete slice records a local decision', 'business logic','Local decision preserves open Legal/Credit/QA/EDD and no publication.'],
 ['Client-safe narrative leak','D5 RM/client projections exclude', 'permission/privacy','Provider details, internal counts and timing illustration excluded before HTML; actual client DOM/print checked.']
];
const attacks=vectors.map(([attack,pattern,classification,oracle],i)=>{const matches=units.tests.filter(t=>t.name.startsWith(pattern));return {id:`ERT-${String(i+1).padStart(2,'0')}`,attack,classification,oracle,result:matches.length&&matches.every(t=>t.status==='passed')?'PASS bounded oracle':'NOT_RUN',tests:matches.map(x=>x.name)};});
put('red-team.json',attacks);put('EXPERIENCE_RED_TEAM_REPORT.md','# Experience Red Team\n\n15 attack vectors mapped to fresh native tests and browser receipts. PASS applies only to each stated local oracle; it is not production security or regulatory validation. Partial/unimplemented variants are named. No new bank facts or test-success data were created.\n\n'+attacks.map(a=>`## ${a.id} ${a.attack}\n\n- Result: ${a.result}; classification: ${a.classification}; reproduced severity: none in this bounded oracle.\n- Expected / scope: ${a.oracle}\n- Evidence: unit-results.json / unit-results.tap; ${a.tests.join('; ')||'No matching test'}\n`).join('\n')+'\nUX-001 and UX-002 are S1 experience defects uncovered by the real journey, separately tracked with controlled retests. Lab Shadow, conflicting uploaded documents and withdrawal-specific commands remain NOT_RUN.\n');
put('UX_TRACEABILITY_MATRIX.md',`# Traceability\n\n| Scenario | Surface / persona | Intent | Test / result | Finding |\n|---|---|---|---|---|\n| SCN-MATCH | PX-09 / Ops, Reviewer | Evidence-grounded bounded human outcome | journey.mjs P1–P8; CHK01–04; unit-results; context/host/time checks | UX-001,003,004,006,008 |\n| SCN-GAP | PX-06→PX-04→PX-07 / Ops, Client | Scoped draft→dispatch→receipt→purpose assessment | actual journey request/client/assessed browser receipts PASS; received/unassessed is native rendered-test coverage | UX-004,005 |\n| SCN-READINESS | PX-12 / Ops | Same-case honest Not Ready | surfaces-results readiness-not-ready: ${surfaces.results.find(x=>x.name==='readiness-not-ready')?.status}; engine False Green PASS | UX-002,007 |\n| SCN-QA | PX-11 / QA | Remediation and independent re-review | Full workflow NOT_RUN; source contract mapped | UX-007 |\n| SCN-PUBLISH | PX-12 / authorised reviewer | Decision ≠ publication ≠ trading | Success runtime NOT_RUN; unavailable action/engine no-publication tested | UX-007 |\n\nOther ten scenes have thin contracts with exact inherited action and PPT source locators in contracts/D5_SCENARIO_PRODUCT_CONTRACTS.json. This is not 15 complete workspaces.\n`);
const summary=`# D5 UX/UI quality gate — review summary\n\n**Overall: ${ready?'READY WITH KNOWN LIMITATIONS — bounded Person T pilot':'NOT READY — open gate / retest remains'}.** Not bank sign-off, formal accessibility conformance or real-user validation. No S0 reproduced in the tested fixtures.\n\n${units.tests.filter(t=>t.status==='passed').length}/${units.tests.length} native tests and ${checks.filter(t=>t.status==='passed').length}/${checks.length} browser probes passed in this audit namespace. Counts are probes, not independent user tasks.\n\n## Gates\n\n| Gate | Result | Qualification |\n|---|---|---|\n${gates.map(g=>`| ${g.join(' | ')} |`).join('\n')}\n\n## Five leading risks\n\n1. Current-state guidance needed an S1 correction; status: ${fixes.guidance}.\n2. Current-case Readiness route needed an S1 continuity correction; status: ${fixes.readiness}.\n3. Dense header / progress leaves little task content on a laptop first screen.\n4. Client-facing request is visually subordinate to facilitator tools; IDs and mixed-language prose remain.\n5. QA/publication/history outcome fixtures and user-tested comprehension remain incomplete.\n\n## Five strengths\n\n1. Same Person T case and scoped request/evidence chain is genuinely operable.\n2. Received, assessed, unresolved and whole-case clearance remain distinct.\n3. RM/client projection and local command guards prevent tested role escalation.\n4. Current/Target, language, drafts, history and layout have executable state-preservation checks.\n5. Black/blue/white warm-glass tokens retained; keyboard focus and no-page-overflow checks pass on tested surfaces.\n\n## Fix order / stop\n\nReview the S1 fixes and their focused diff first. Then approve one compact-header / client-tools / metadata pass (S2), followed by semantic headings. Do not bulk-expand all 15 workspaces. This round stops for Christina review; no push, publish or fixture auto-load.\n\nReal validation still needed: observed Ops/reviewer/client task sessions; exact decision comprehension and recipient confidence; role/policy ownership; real evidence integration; screen-reader and zoom users; complete downstream fixtures. No completion-time or KPI claim.\n`;
put('UX_EXECUTIVE_SUMMARY.md',summary);
const before=json('audit/environment/pre-audit-hashes.json').product;const changed=Object.entries(before).filter(([f,h])=>fs.existsSync(f)&&createHash('sha256').update(fs.readFileSync(f)).digest('hex')!==h).map(([f])=>f);put('change-impact.json',{at:new Date().toISOString(),changed_existing_product_files:changed,engine_changes:changed.filter(f=>/engine\.mjs$/.test(f)),css_changes:changed.filter(f=>f.endsWith('.css')),note:'New files and controlled diff are listed in controlled-fix-report.md. No git mutations or remote publication.'});
console.log({ready,checks:checks.length,passed:checks.filter(x=>x.status==='passed').length,axe_scans:scans.length,serious:serious.length,changed});
// Keep acceptance of the controlled fixes distinct from visual baseline approval.
const visualPath='audit/reports/visual-results.json';
if(fs.existsSync(visualPath)){
 const v=json(visualPath).stats;
 const details=`\n## Final verification qualification\n\nThree S1 corrections: state-specific next-action guidance (${fixes.guidance}), same-case Readiness route (${fixes.readiness}), visible keyboard focus (${fixes.keyboard}). Independent scoped review found all reported fix-round issues addressed.\n\nScreenshot tests: ${v.expected} passed, ${v.unexpected} failed, ${v.skipped} skipped, ${v.flaky} flaky. The retained 08-decision-pack difference is removal of the ambiguous assessment command plus the shorter page's changed scroll framing; see visual report and untouched expected/actual/diff files. This is awaiting Christina review, not an approved replacement baseline. Four additional focused browser checks passed (readiness-guidance-fix1-results.json); they are separate from the ${checks.length} general browser probes.\n`;
 fs.appendFileSync('audit/reports/UX_EXECUTIVE_SUMMARY.md',details);
}
fs.appendFileSync('audit/reports/ACCESSIBILITY_REPORT.md',`\n## Manual focus defect\n\nUX-009 status: ${fixes.keyboard}. Actual keyboard focus initially had outline-style none because the colour token was undefined; after using the existing blue token, the same keyboard check reports solid. See focus-diagnostic.json (before) and context-extra-results.json (after). Zero serious axe findings did not detect or excuse this defect.\n`);
fs.appendFileSync('audit/reports/UX_EXECUTIVE_SUMMARY.md','\n## Explicit remaining configuration boundary\n\nUX-010 is an open S1 outside the frozen main demo: changing Reviewer assessment permissions can produce a misleading changed-input hero even when the assessed evidence itself is unchanged. No write bypass was found. Therefore READY WITH KNOWN LIMITATIONS applies only to the supplied role configuration, not arbitrary permission changes or production roles. Universal permission-independent guidance is not established. See final-review-verdict.md.\n\nThe final screenshot run also retains 06-CHK03 as FAILED against its old candidate (3,013 changed pixels in the corrected assessment-basis sentence), alongside 08-decision-pack. Both require visual approval; neither baseline was replaced.\n');
