import test from 'node:test';
import assert from 'node:assert/strict';
import {renderCollaboration} from '../collaboration-ui.mjs';
const item={id:'item-one',alias:'ITEM-AUTHORITY',purpose_code:'coordinate_information',client_reason:'Provide authority for Entity A',response_status:'open',response_draft:'',revision:1};
test('New pending-review request does not inherit historic notification sent state',()=>{const html=renderCollaboration({projection:{allowed:true,items:[item],request_revision:3,request:{review_status:'pending_review',dispatch_status:'not_requested',delivery_status:'unknown'},notifications:[{request_revision:2,dispatch_status:'sent',delivery_status:'unknown'}]},audience:'ops',tab:'requests'});assert.match(html,/Dispatch: Not dispatched/);assert.doesNotMatch(html,/Dispatch: Dispatched/);});
test('Chinese client uses approved fixture explanation translation, retaining custom source text unchanged',()=>{const known={...item,client_reason:'Please provide a synthetic basis showing who may coordinate onboarding information for Entity A.'};const html=renderCollaboration({projection:{allowed:true,items:[known]},audience:'client',tab:'tasks',locale:'zh-CN'});assert.match(html,/请提供合成依据/);assert.doesNotMatch(html,/Please provide a synthetic basis/);});
test('Client denied view emits no task editor or internal work panels',()=>{const html=renderCollaboration({projection:{allowed:false,reason:'grant_revoked'},audience:'client',tab:'tasks',locale:'en-AU'});assert.match(html,/Access unavailable/);assert.doesNotMatch(html,/collab-text|Screening|bank_authority/);});
test('Client task renders only supplied safe items and escapes response text',()=>{const html=renderCollaboration({projection:{allowed:true,items:[item],submissions:[],entity_label:'Entity A'},audience:'client',tab:'tasks',locale:'en-AU',draftText:'<script>bad()</script>'});assert.match(html,/Your tasks/);assert.match(html,/item-one/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>|ITEM-OWNERSHIP|Internal review/);});
test('Client print has no form actions and includes only safe task receipt',()=>{const html=renderCollaboration({projection:{allowed:true,items:[item],submissions:[{id:'receipt-one',response_text:'Synthetic response',intake_security_status:'received'}],entity_label:'Entity A'},audience:'client',tab:'tasks',locale:'zh-CN',print:true});assert.match(html,/你的任务/);assert.match(html,/receipt-one/);assert.doesNotMatch(html,/<textarea|<button|内部|Screening/);});
