// D5 rerun of D4 contract; historical receipts preserved.
import assert from 'node:assert/strict';import {probe,finish}from './harness.mjs';
const O=s=>s.navigation.operating;
await probe(['OM-01','OM-03','OM-18','OM-26'],'global-entry-and-groups',async h=>{
 assert.equal((await h.state()).navigation.studioPage,'operating-model');assert.equal(await h.page.locator('.topnav button').count(),2);assert.match(await h.page.locator('#main').innerText(),/Authored example|Authored|authored/);assert.equal(await h.page.locator('.om-group').count(),6);assert.equal(await h.page.locator('.om-action-list button').count(),17);assert.equal(await h.page.locator('.om-group details[open]').count(),1);assert.match(await h.page.locator('.om-task-link').innerText(),/Prototype not included/);assert.equal(await h.page.locator('[data-action="om-product"]').count(),0);assert.deepEqual((await h.state()).data,h.before.data);
});
await probe(['OM-04','OM-05','OM-06','OM-07','OM-11','OM-29'],'execution-choices-source-bound',async h=>{
 const before=h.before.data;await h.click('om-view','execution-choice');
 for(const [id,executor,n,f,focus]of [['D4A-MATCH-04-01','Workflow + Semantic Skill',8,7,'skill'],['D4A-MATCH-03-01','candidate',12,6,'agent'],['D4A-MATCH-05-02','Human',11,4,'human']]){
  await h.click('om-action',id);assert.equal(O(await h.state()).action,id);const detail=h.page.locator('#om-selected-work');assert.match(await detail.innerText(),new RegExp(executor.replace('+','\\+')));await detail.locator('.om-assessment summary').click();const text=await detail.innerText();assert.ok(text.includes('N = '+n));assert.ok(text.includes('F = '+f));assert.match(await h.page.locator('.om-diagram img').getAttribute('src'),new RegExp('\\.'+focus+'\\.svg$'));assert.equal(await detail.locator('input,select').count(),0);
 }
 assert.deepEqual((await h.state()).data,before);
});
await probe(['OM-08','OM-09','OM-10'],'skill-samples-and-reuse-context',async h=>{
 await h.click('om-view','execution-choice');await h.click('om-action','D4A-MATCH-05-02');await h.click('om-skill','SK-06');assert.match(await h.page.locator('#main').innerText(),/Supports the human action/);await h.click('om-catalogue');assert.equal(await h.page.locator('.om-skill-list article').count(),12);await h.click('om-skill','SK-03');assert.match(await h.page.locator('.om-sample').innerText(),/Unknown|unknown/);assert.match(await h.page.locator('.om-sample').innerText(),/missing is not different/);assert.match(await h.page.locator('.om-sample').innerText(),/runSubjectSnapshots/);const o=O(await h.state());await h.click('om-inspect','SCN-SCOPE');let now=await h.state();assert.equal(O(now).action,o.action);assert.equal(O(now).unavailableScene,null);assert.deepEqual(now.data,h.before.data);assert.ok(await h.page.locator('[data-usage="SCN-SCOPE"]').isVisible());await h.click('om-scene','SCN-SCOPE');assert.match(await h.page.locator('#main').innerText(),/not included in the Person T pilot/);await h.click('om-return-pilot');assert.equal(O(await h.state()).action,o.action);assert.deepEqual((await h.state()).data,h.before.data);
});
await probe(['OM-12','OM-23'],'all-action-sources-three-locales',async h=>{
 for(const locale of ['zh-CN','en-US','en-AU']){await h.language(locale);for(const id of ['D4A-MATCH-04-01','D4A-MATCH-03-01','D4A-MATCH-05-02']){await h.click('om-view','execution-choice');await h.click('om-action',id);await h.page.locator('.om-source-disclosure summary').click();const text=await h.page.locator('[data-om-sources]').innerText();assert.match(text,/PPT-S[12]-SH/);assert.match(text,/D3-ISS-06/);assert.match(text,/D3-ISS-15/);if(locale!=='zh-CN')assert.doesNotMatch(await h.page.locator('.om-page').innerText(),/\p{Script=Han}/u);}}
 assert.deepEqual((await h.state()).data,h.before.data);
});
await probe(['OM-13','OM-14','OM-15','OM-16','OM-26'],'playback-pauses-and-gates',async h=>{
 await h.click('om-view','collaboration');assert.equal(O(await h.state()).playing,false);await h.click('om-play');await h.page.waitForFunction(()=>{const s=JSON.parse(sessionStorage.getItem('ctt-round-a-v1'));return s.navigation.operating.frame===3&&!s.navigation.operating.playing;},{timeout:8000});assert.equal(await h.page.locator('[data-frame="5"]').filter({visible:true}).count(),0);await h.click('om-next');assert.equal(O(await h.state()).frame,4);assert.equal(await h.page.locator('[data-action="om-next"]').isDisabled(),true);assert.equal(await h.page.locator('[data-frame="5"]').filter({visible:true}).count(),0);await h.click('om-preview');assert.equal(O(await h.state()).frame,5);assert.equal(O(await h.state()).checkpoint,'C-unresolved');await h.click('om-next');assert.equal(O(await h.state()).frame,6);await h.click('om-replay');await h.click('om-play');await h.click('om-view','skills');assert.equal(O(await h.state()).playing,false);await h.click('om-view','collaboration');assert.equal(O(await h.state()).playing,false);await h.click('om-play');await h.page.locator('.om-source-disclosure summary').click();await h.page.waitForFunction(()=>!JSON.parse(sessionStorage.getItem('ctt-round-a-v1')).navigation.operating.playing);assert.equal(O(await h.state()).playing,false);assert.deepEqual((await h.state()).data,h.before.data);
},{reduced:false});
await probe(['OM-14','OM-24'],'reduced-motion-does-not-reveal-outcome',async h=>{
 await h.click('om-view','collaboration');assert.equal(await h.page.locator('[data-frame="5"]').filter({visible:true}).count(),0);assert.equal(await h.page.locator('[data-frame="6"]').filter({visible:true}).count(),0);assert.equal(O(await h.state()).playing,false);for(let i=0;i<3;i++)await h.click('om-next');assert.equal(O(await h.state()).frame,4);assert.equal(await h.page.locator('[data-frame="5"]').filter({visible:true}).count(),0);await h.click('om-preview');assert.equal(O(await h.state()).frame,5);assert.ok(await h.page.locator('[data-frame="5"]').isVisible());assert.deepEqual((await h.state()).data,h.before.data);
});
await probe(['OM-22'],'history-and-stale-action-deep-link',async h=>{
 await h.click('om-view','execution-choice');const count=await h.page.evaluate(()=>history.length);await h.click('om-action','D4A-MATCH-03-01');await h.click('om-action-next');await h.click('om-fit');assert.equal(await h.page.evaluate(()=>history.length),count);await h.click('om-view','skills');await h.page.goBack();assert.equal(O(await h.state()).view,'execution-choice');await h.page.goForward();assert.equal(O(await h.state()).view,'skills');await h.page.goto('http://127.0.0.1:8765/prototype/?studio=operating-model&scene=SCN-MATCH&action=D4A-MATCH-OLD');assert.equal(O(await h.state()).action,null);assert.equal(O(await h.state()).staleAction,'D4A-MATCH-OLD');await h.click('om-journey');assert.equal((await h.state()).navigation.modal,false);assert.equal((await h.state()).navigation.scenario,'SCN-MATCH');
});
await probe(['OM-24'],'narrow-keyboard-and-static-fallback',async h=>{
 assert.ok(await h.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const button=h.page.locator('[data-action="om-view"][data-value="skills"]');await button.focus();await h.page.keyboard.press('Enter');assert.equal(O(await h.state()).view,'skills');await h.click('om-catalogue');await h.click('om-skill','SK-03');assert.ok(await h.page.locator('.om-sample').isVisible());assert.ok(await h.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(Number.parseFloat(await h.page.locator('.om-page').evaluate(e=>getComputedStyle(e).fontSize))>=16);assert.deepEqual((await h.state()).data,h.before.data);
},{width:390,height:844,missing:true});
await finish();
