// D5 rerun of D4 contract; historical receipts preserved.
import assert from 'node:assert/strict';import fs from 'node:fs';import {probe,finish}from './harness.mjs';
async function prepare(h){
 await h.click('product','population');await h.click('c-demo');await h.page.waitForSelector('[data-c-panel="population"]');await h.page.locator('#screening-rationale').fill('Explicit local Person T preliminary query; ownership inventory remains incomplete.');await h.click('c-action','prepare_preliminary');await h.click('c-action','request_preliminary');await h.page.locator('#screening-result-outcome').selectOption('completed');await h.click('c-action','receive_result');await h.click('return','scenario');await h.click('close');await h.click('scene','SCN-MATCH');await h.click('compare','current');
}
const options={url:'?scene=SCN-POPULATION&locale=en-AU'};
await probe(['OM-02','OM-17','OM-19','OM-21','OM-27'],'real-c-task-saved-roundtrip',async h=>{
 await prepare(h);await h.page.locator('[data-change-id="D3-MATCH-04"] > summary').click();await h.page.locator('[data-om-action="D4A-MATCH-04-01"]').filter({visible:true}).first().click();let n=(await h.state()).navigation;assert.equal(n.operating.action,'D4A-MATCH-04-01');assert.equal(n.operating.view,'execution-choice');assert.equal(n.operatingOrigin.comparison,'current');const origin=n.operatingOrigin;await h.click('om-view','collaboration');await h.page.evaluate(()=>window.scrollTo(0,600));await h.click('om-product');let s=await h.state();assert.equal(s.navigation.step,'screening');assert.equal(s.navigation.page,'product');assert.equal(s.navigation.returnToken.operating.context.findingRef,'DEMO-CTT-001/finding/person-t-c01');assert.ok(await h.page.locator('[data-c-panel="screening"]').isVisible());
 await h.page.locator('#screening-rationale').fill('OM host proof: distinguishing identity remains unknown; no disposition authorised.');await h.click('c-action','save_review_draft');const saved=(await h.state()).data;assert.match(saved.screeningReviewDrafts.at(-1).text,/OM host proof/);assert.equal(saved.screeningReviewDecisions.length,0);await h.language('zh-CN');await h.click('om-return');s=await h.state();assert.equal(s.navigation.studioPage,'operating-model');assert.equal(s.navigation.operating.action,'D4A-MATCH-04-01');assert.equal(s.navigation.operating.view,'collaboration');assert.equal(s.navigation.locale,'zh-CN');assert.equal(s.navigation.operating.playing,false);assert.deepEqual(s.data,saved);assert.match(await h.page.locator('.om-page [role="status"]').innerText(),/会话已变化/);await h.click('om-back');s=await h.state();assert.equal(s.navigation.comparison,'current');assert.equal(s.navigation.scenario,'SCN-MATCH');assert.equal(s.navigation.modal,true);assert.deepEqual(s.navigation.transformation,origin.transformation);assert.deepEqual(s.data,saved);fs.writeFileSync('prototype/qa/d5/om-regression/host/c-live-session.json',JSON.stringify(s,null,2));
},options);
await probe(['OM-20'],'dirty-save-stay-discard-and-failure',async h=>{
 await prepare(h);await h.click('om-open','overview');await h.click('om-product');const before=(await h.state()).data;const invalid='X'.repeat(10001);await h.page.locator('#screening-rationale').fill(invalid);await h.click('om-return');assert.ok(await h.page.locator('#dirty-dialog').isVisible());await h.click('guard','save');assert.equal((await h.state()).navigation.page,'product');assert.equal(await h.page.locator('#screening-rationale').inputValue(),invalid);assert.ok(await h.page.locator('#dirty-dialog [role="alert"]').isVisible());assert.deepEqual((await h.state()).data,before);await h.click('guard','stay');assert.equal(await h.page.locator('#screening-rationale').inputValue(),invalid);await h.click('om-return');await h.click('guard','discard');assert.equal((await h.state()).navigation.studioPage,'operating-model');assert.deepEqual((await h.state()).data,before);
 await h.click('om-product');await h.page.locator('#screening-rationale').fill('Save on returning to the same Operating Model work.');await h.click('om-return');await h.click('guard','save');let s=await h.state();assert.equal(s.navigation.studioPage,'operating-model');assert.match(s.data.screeningReviewDrafts.at(-1).text,/Save on returning/);assert.equal(s.data.screeningReviewDecisions.length,0);
},options);
await probe(['OM-17','OM-19','OM-27'],'product-source-and-journey-return-with-request',async h=>{
 await prepare(h);await h.click('om-open','overview');await h.click('om-product');await h.page.locator('#screening-rationale').fill('Request only distinguishing identity evidence for this Person T finding.');const before=(await h.state()).data;await h.click('c-action','request_identity');const saved=(await h.state()).data;assert.equal(saved.requestItems.length,before.requestItems.length+1);assert.deepEqual(saved.clearanceConditions,before.clearanceConditions);assert.equal(saved.case.publication_status,'not_requested');await h.click('return','scenario');let s=await h.state();assert.equal(s.navigation.modal,true);assert.equal(s.navigation.scenario,'SCN-MATCH');assert.equal(s.navigation.comparison,'current');assert.deepEqual(s.data,saved);await h.click('om-open','overview');await h.click('om-product');await h.click('return','journey');s=await h.state();assert.equal(s.navigation.modal,false);assert.equal(s.navigation.scenario,'SCN-MATCH');assert.deepEqual(s.data,saved);
},options);
await finish();
