import {chromium} from '/Users/christinaliu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const dir=fileURLToPath(new URL('./batch-a/',import.meta.url)),browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const p=await browser.newPage({viewport:{width:1440,height:900}}),out=[];
const state=()=>p.evaluate(()=>JSON.parse(sessionStorage.getItem('ctt-round-a-v1')));
const click=(a,v)=>p.locator(`[data-action="${a}"]${v?`[data-value="${v}"]`:''}`).filter({visible:true}).first().click();
async function check(ids,name,fn){try{await fn();out.push({ids,name,status:'passed'});}catch(e){out.push({ids,name,status:'failed',error:e.message});}}
try{
 await p.goto('http://127.0.0.1:8765/prototype/');await p.waitForSelector('.storyrail');
 await check(['RT-A16'],'Real horizontal drag then scene close restores pixel and semantic position',async()=>{const box=p.locator('.journey-scroll');await box.scrollIntoViewIfNeeded();const r=await box.boundingBox();await p.mouse.move(r.x+r.width-80,r.y+28);await p.mouse.down();await p.mouse.move(r.x+100,r.y+28,{steps:12});await p.mouse.up();const x=await box.evaluate(e=>e.scrollLeft),nav=(await state()).navigation;assert.ok(x>30);await click('scene','SCN-SCOPE');await click('close');assert.ok(Math.abs(await box.evaluate(e=>e.scrollLeft)-x)<2);assert.deepEqual((await state()).navigation.camera,nav.camera);});
 await click('scene','SCN-SCOPE');await click('product','scope');
 await check(['RT-A09'],'Discard only unsaved input; saved value and revision retained',async()=>{const before=(await state()).data;await p.locator('#batch-purpose').fill('discard only this');await click('return','scenario');await click('guard','discard');await click('product','scope');assert.equal(await p.locator('#batch-purpose').inputValue(),before.scopes[0].business_purpose);assert.equal((await state()).data.case.revision,before.case.revision);});
 await check(['RT-A19'],'Rejected form submission retains user input and creates no false save',async()=>{const before=(await state()).data.case.revision;const long='review '.repeat(160);await p.locator('#batch-purpose').fill(long);await click('batch-action','save_scope_draft');assert.ok(await p.locator('[role="alert"]').isVisible());assert.equal(await p.locator('#batch-purpose').inputValue(),long);assert.equal((await state()).data.case.revision,before);await click('return','scenario');await click('guard','discard');});
 await click('product','scope');
 await check(['RT-A13'],'Read-only simulated role cannot assess authority',async()=>{await p.locator('#product-role').selectOption('ROLE-CASEMGR');await click('step','authority');assert.ok(await p.locator('[data-action="batch-action"][data-value="assess_authority"]').isDisabled());assert.ok(await p.locator('.authority-table').isVisible());await p.locator('#product-role').selectOption('ROLE-KYCOPS');});
 await click('return','journey');
 await check(['RT-A25'],'Chinese print includes offscreen scope and all diagrams',async()=>{await p.locator('#locale').selectOption('zh-CN');await click('stage','S4');await click('mode','print');await p.locator('.batch-print img').first().waitFor();await p.evaluate(async()=>Promise.all([...document.querySelectorAll('.print-sheet img')].map(i=>i.decode())));await p.pdf({path:dir+'batch-a.zh-CN.pdf',format:'A4',printBackground:true});assert.equal((await state()).navigation.stage,'S4');});
 const touch=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),tp=await touch.newPage();await tp.goto('http://127.0.0.1:8765/prototype/?locale=zh-CN');await tp.waitForSelector('.storyrail');
 await check(['RT-A23'],'Touch help opens and closes under reduced motion',async()=>{await tp.locator('[data-action="scene"][data-value="SCN-ENTITY"]').first().tap();const h=tp.locator('#scenario-dialog .batch-help');await h.tap();assert.ok(await tp.locator('#authority-help').evaluate(e=>e.matches(':popover-open')));await tp.locator('#authority-help button').tap();assert.equal(await tp.locator('#authority-help').evaluate(e=>e.matches(':popover-open')),false);assert.ok(await tp.locator('.batch-blocker').isVisible());await tp.screenshot({path:dir+'touch-reduced-motion.png',fullPage:true});});
 await touch.close();
 await check([],'Legacy session migration is explicit and preserves saved drafts',async()=>{const legacy=JSON.parse(readFileSync(new URL('../../04_operating_model/round-a/synthetic-case-fixture.json',import.meta.url)));await p.evaluate(s=>sessionStorage.setItem('ctt-round-a-v1',JSON.stringify({data:s,drafts:{screening:'legacy saved draft'},versions:[]})),legacy);await p.reload();await p.waitForSelector('.storyrail');assert.equal((await state()).data.case.baseline_revision,undefined);await click('scene','SCN-SCOPE');await click('product','scope');await click('batch-start');const s=await state();assert.equal(s.archives.at(-1).drafts.screening,'legacy saved draft');assert.equal(s.archives.at(-1).data.entities[0].legal_name,'Harbour Institutional Holdings (Synthetic)');assert.equal(s.data.case.id,'DEMO-CTT-001');assert.equal(s.data.scopes[0].counterparty_entity_id,null);});
}finally{writeFileSync(dir+'extra-results.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));await browser.close();}
