import {id,readiness} from './case-engine.mjs';

const STAMP='2026-09-07T09:00:00Z', SOURCE=['SRC-015'], CASE_ID='DEMO-CTT-001';
const SCOPE_ID=id('scope','institutional'), ENTITY_A=id('entity','harbour');
export const COLLAB_IDS=Object.freeze({
 request:id('request','authority_gap'),authorityItem:id('request-item','authority-coordinate'),ownershipItem:id('request-item','ownership-control'),
 personT:id('person','person-t'),secondContributor:id('person','ownership-contributor'),recipientT:id('recipient','person-t'),recipientOther:id('recipient','ownership-contributor'),
 authorityRequirement:id('requirement','authority-coordinate'),ownershipRequirement:id('requirement','ownership-control')
});
const COMMON={case_id:CASE_ID,case_scope_id:SCOPE_ID,source_refs:SOURCE,source_status:'SYNTHETIC',synthetic:true,simulation_flag:true,provenance:'synthetic',purpose_class:'operational_product_candidate',implementation_fidelity:'local_simulation',business_validation_status:'user_confirmed_for_demo',sensitivity:'synthetic-restricted'};
const make=(kind,slug,fields={})=>({...COMMON,id:id(kind,slug),revision:1,created_at:STAMP,updated_at:STAMP,...fields});
const touch=(record,fields,now)=>Object.assign(record,fields,{revision:record.revision+1,updated_at:now});
const requestOf=s=>s.informationRequests.find(x=>x.id===COLLAB_IDS.request), itemOf=(s,itemId)=>s.requestItems.find(x=>x.id===itemId), recipientOf=(s,recipientId)=>s.requestRecipients.find(x=>x.id===recipientId);
const actionFingerprint=(a,requestId)=>JSON.stringify({type:a.type??null,role:a.role??null,userId:a.userId??null,recipientId:a.recipientId??null,sessionId:a.sessionId??null,requestId,itemId:a.itemId??null,text:a.text??null,rationale:a.rationale??null,channel:a.channel??null,intakeStatus:a.intakeStatus??null,reference:a.reference??null});
const cleanText=(value,label='Text')=>{if(typeof value!=='string'||!value.trim()||value.length>2000)throw Error(`${label} is required and must be 2,000 characters or fewer`);return value.trim();};
const isoNow=value=>{const now=value||new Date().toISOString();if(Number.isNaN(Date.parse(now)))throw Error('A valid current time is required');return now;};
const safeItem=item=>({id:item.id,alias:item.alias,purpose_code:item.purpose_code,client_reason:item.client_reason,revision:item.revision,response_status:item.response_status,response_draft:item.response_draft});
const commonProjection=(s,request)=>({allowed:true,case_id:s.case.id,case_revision:s.case.revision,request_id:request.id,request_revision:request.revision,entity_label:s.entities.find(x=>x.id===ENTITY_A)?.display_alias||'Entity A'});

export function createBatchB(input){
 if(input?.demoConfig?.batchB?.version==='D2-B-Collaboration-1.0')return input;
 const scope=input?.scopes?.[0],entity=input?.entities?.find(x=>x.id===ENTITY_A);
 if(scope?.scope_status!=='working_scope_recorded')throw Error('Batch B requires the Batch A working scope record');
 if(entity?.identity_resolution_status!=='resolved_for_scope')throw Error('Batch B requires Entity A identity resolved for scope');
 if(!input.informationRequests?.some(x=>x.id===COLLAB_IDS.request))throw Error('Batch B requires the existing Batch A authority gap request');
 const s=structuredClone(input);
 let authorityRequirement=s.requirements.find(x=>x.id===COLLAB_IDS.authorityRequirement||(x.subject_id===COLLAB_IDS.personT&&x.principal_entity_id===ENTITY_A&&x.purpose_code==='coordinate_information'));
 if(!authorityRequirement){authorityRequirement=make('requirement','authority-coordinate',{subject_id:COLLAB_IDS.personT,principal_entity_id:ENTITY_A,purpose_code:'coordinate_information',applicability:'required',applicability_review:'decided',status:'review_required',status_reason:'Purpose-specific coordination authority basis remains required',scope_revision:scope.revision});s.requirements.push(authorityRequirement);}
 let ownershipRequirement=s.requirements.find(x=>x.id===COLLAB_IDS.ownershipRequirement||(x.subject_id===ENTITY_A&&x.principal_entity_id===ENTITY_A&&x.purpose_code==='ownership_control'));
 if(!ownershipRequirement){ownershipRequirement=make('requirement','ownership-control',{subject_id:ENTITY_A,principal_entity_id:ENTITY_A,purpose_code:'ownership_control',applicability:'unknown',applicability_review:'in_review',status:'review_required',status_reason:'Ownership and control applicability remains under review',scope_revision:scope.revision});s.requirements.push(ownershipRequirement);}
 s.naturalPersons.push(make('person','ownership-contributor',{display_name:'Contributor O',employer_entity_id:ENTITY_A,business_role_title:'Synthetic company contributor'}));
 s.requestItems=[
  make('request-item','authority-coordinate',{alias:'ITEM-AUTHORITY',request_id:COLLAB_IDS.request,scope_revision:scope.revision,subject_id:COLLAB_IDS.personT,principal_entity_id:ENTITY_A,purpose_code:'coordinate_information',requirement_id:authorityRequirement.id,requirement_applicability:'required',response_status:'open',response_draft:'',client_reason:'Please provide a synthetic basis showing who may coordinate onboarding information for Entity A.',restricted_reason:'Internal: principal scope and purpose-specific authority are not established.',linked_evidence_refs:[],linked_evidence_revisions:{}}),
  make('request-item','ownership-control',{alias:'ITEM-OWNERSHIP',request_id:COLLAB_IDS.request,scope_revision:scope.revision,subject_id:ENTITY_A,principal_entity_id:ENTITY_A,purpose_code:'ownership_control',requirement_id:ownershipRequirement.id,requirement_applicability:'unknown',response_status:'open',response_draft:'',client_reason:'Please share synthetic ownership and control information if available while applicability is reviewed.',restricted_reason:'Internal: ownership/control applicability and complete CDD remain unresolved.',linked_evidence_refs:[],linked_evidence_revisions:{}})
 ];
 s.businessContacts=[
  make('contact','person-t',{person_ref:COLLAB_IDS.personT,principal_entity_ref:ENTITY_A,contact_routes:[{type:'synthetic_reference',value:'CONTACT-T'}],contact_review_ref:id('review','contact-person-t'),contact_reviewed:true,status:'reviewed_for_demo'}),
  make('contact','ownership-contributor',{person_ref:COLLAB_IDS.secondContributor,principal_entity_ref:ENTITY_A,contact_routes:[{type:'synthetic_reference',value:'CONTACT-O'}],contact_review_ref:id('review','contact-ownership'),contact_reviewed:true,status:'reviewed_for_demo'})
 ];
 s.interactionRecords=[];
 s.requestRecipients=[
  make('recipient','person-t',{request_id:COLLAB_IDS.request,person_ref:COLLAB_IDS.personT,permitted_item_refs:[COLLAB_IDS.authorityItem],contact_review_ref:id('review','contact-person-t'),contributor_type:'limited_contributor',status:'active'}),
  make('recipient','ownership-contributor',{request_id:COLLAB_IDS.request,person_ref:COLLAB_IDS.secondContributor,permitted_item_refs:[COLLAB_IDS.ownershipItem],contact_review_ref:id('review','contact-ownership'),contributor_type:'limited_contributor',status:'active'})
 ];
 s.requestAccessDecisions=[];s.notifications=[];s.portalInvitations=[];s.accessGrants=[];s.submissions=[];s.contributorSessions=[];
 s.channelPolicies=[make('channel-policy','official-site-reference',{region_context:'AU',channel:'official_site_reference',allowed_purposes:['coordinate_information','ownership_control'],disclosure_classes:['client_safe'],capture_method:'case_audit_event',approval_status:'configured_for_demo',simulation_adapter_ref:'local_simulation'})];
 const request=requestOf(s);Object.assign(request,{revision:request.revision+1,updated_at:STAMP,scope_revision:scope.revision,item_refs:[COLLAB_IDS.authorityItem,COLLAB_IDS.ownershipItem],owner_ref:'Unassigned',review_ref:null,review_status:'draft',dispatch_policy_ref:s.channelPolicies[0].id,dispatch_status:'not_requested',delivery_status:'unknown',reference:'CTT-DEMO-REF-001',client_summary:'',sent_revision_refs:[],purpose_class:'operational_product_candidate',implementation_fidelity:'local_simulation',business_validation_status:'user_confirmed_for_demo',source_refs:SOURCE,provenance:'synthetic'});
 s.demoConfig.batchB={version:'D2-B-Collaboration-1.0',reference:request.reference,authentication_policy_ref:'mock-fixed-identity-v1',grant_expires_at:'2026-09-08T23:59:59Z',production_authentication_validated:false,bank_policy_status:'unknown',bank_authority_ref:null,reviews:{contact:true,disclosure:true,access:true,reviewer_permission_ref:'SYNTHETIC-D2-B-REVIEWER-v1'},adapters:{authentication:{status:'local_simulation'},file_intake:{status:'local_simulation'},email:{status:'disabled_not_run'}},permissions:{'ROLE-KYCOPS':['save_request','review_request','dispatch','staff_submit','release_artifact','link_evidence','record_assessment','request_more','refer_review','revoke_grant','replace_recipient'],'ROLE-RM':['record_note','refer_question'],'ROLE-CLIENT':['start_session','save_response','submit_response','refer_question']}};
 return s;
}

function accessContext(s,{userId,sessionId,itemId,action,now}){
 const request=requestOf(s),scope=s.scopes[0],session=s.contributorSessions.find(x=>x.id===sessionId);
 if(!session||session.status!=='simulated_authenticated'||session.user_ref!==userId||session.reference!==request.reference)return {ok:false,reason:'authenticated_session_required'};
 if(session.scope_revision!==scope.revision)return {ok:false,reason:'session_scope_changed'};
 const grant=s.accessGrants.find(x=>{const recipient=s.requestRecipients.find(r=>r.id===x.recipient_ref);return x.user_ref===userId&&x.request_id===request.id&&x.status==='limited_active'&&recipient?.status==='active'&&recipient.person_ref===userId&&x.resource_scope.item_refs.every(ref=>recipient.permitted_item_refs.includes(ref))&&x.scope_revision===scope.revision&&x.request_revision===request.revision&&(!itemId||recipient.permitted_item_refs.includes(itemId)&&x.resource_scope.item_refs.includes(itemId))&&(!action||x.permitted_actions.includes(action))&&Date.parse(x.expires_at)>Date.parse(now);});
 return grant?{ok:true,grant,session}:{ok:false,reason:'current_limited_grant_required'};
}

export function collaborationAction(input,a){
 if(!a?.key)throw Error('Idempotency key required');
 const request=requestOf(input),fingerprint=actionFingerprint(a,request?.id),priorEvent=input.auditEvents.find(x=>x.correlation_id===a.key);
 if(priorEvent){if(priorEvent.idempotency_fingerprint===fingerprint)return input;throw Error('Idempotency key collision: action fingerprint differs from the recorded operation');}
 const item=a.itemId?itemOf(input,a.itemId):null,allowed=input.demoConfig?.batchB?.permissions?.[a.role]||[];
 if(!allowed.includes(a.type))throw Error('Demo permission not configured for collaboration action');
 if(!Number.isSafeInteger(a.expectedRevision)||a.expectedRevision!==input.case.revision)throw Error('Case revision changed; draft retained');
 if(!Number.isSafeInteger(a.expectedRequestRevision)||a.expectedRequestRevision!==request?.revision)throw Error('Request revision changed; draft retained');
 if(a.itemId&&(!item||!Number.isSafeInteger(a.expectedItemRevision)||a.expectedItemRevision!==item.revision))throw Error('Request item revision changed; draft retained');
 if(a.type!=='save_request'&&request.scope_revision!==input.scopes[0].revision)throw Error('Request scope revision changed; save and review the request again');
 const s=structuredClone(input),now=isoNow(a.now),req=requestOf(s),target=a.itemId?itemOf(s,a.itemId):null,objects=[];
 const rationale=()=>cleanText(a.rationale,'Rationale');
 const clientGuard=action=>{const result=accessContext(s,{userId:a.userId,sessionId:a.sessionId,itemId:a.itemId,action,now});if(!result.ok)throw Error(`Current grant required: ${result.reason}`);return result;};
 const addSubmission=({submittedBy,onBehalfOf,staffUploader,sourceChannel,text})=>{
  const response=cleanText(text,'Response text'),sequence=s.submissions.length+1;
  const submission=make('submission',`collab-${sequence}`,{request_id:req.id,request_revision:req.revision,request_item_refs:[target.id],submitted_by:submittedBy,on_behalf_of:onBehalfOf,staff_uploader_ref:staffUploader,source_channel:sourceChannel,submitted_at:now,response_text:response,artifact_refs:[],duplicate_candidate_refs:[],scope_revision:s.scopes[0].revision,created_at:now,updated_at:now});
  const duplicates=s.submissions.filter(x=>x.request_item_refs.includes(target.id)&&x.response_text===response);submission.duplicate_candidate_refs=duplicates.map(x=>x.id);for(const prior of duplicates)prior.duplicate_candidate_refs=[...new Set([...(prior.duplicate_candidate_refs||[]),submission.id])];
  const alias=`EV-A${String(5+s.submissions.length).padStart(2,'0')}`,artifact=make('evidence',`collaboration-${sequence}`,{alias,scope_revision:s.scopes[0].revision,subject_id:target.subject_id,evidence_revision:1,content_revision:1,source_record_ref:`SYNTHETIC-SOURCE/${alias}`,original_source_ref:sourceChannel,original_submitter_ref:submittedBy,request_item_refs:[target.id],linked_item_refs:[],acquired_at:now,covered_attributes:['synthetic_response'],content_ref:`synthetic:preset:${alias}`,content_attributes:{synthetic_preset:'collaboration_response'},receipt_status:'received',verification_status:'not_verified',intake_security_status:'received',status_reason:'Synthetic intake received; no real security scan performed',created_at:now,updated_at:now});
  submission.artifact_refs=[artifact.id];s.submissions.push(submission);s.evidence.push(artifact);touch(target,{response_draft:response,response_status:'under_review'},now);objects.push(submission.id,artifact.id,target.id);
 };
 switch(a.type){
  case 'save_request':{const summary=cleanText(a.text,'Client summary'),scopeChanged=req.scope_revision!==s.scopes[0].revision,wasApproved=req.review_status==='approved'||scopeChanged;touch(req,{client_summary:summary,scope_revision:s.scopes[0].revision,review_status:'pending_review',review_ref:null,dispatch_status:'not_requested'},now);if(scopeChanged){for(const requestItem of s.requestItems)touch(requestItem,{scope_revision:s.scopes[0].revision,linked_evidence_refs:[],linked_evidence_revisions:{}},now);for(const requirement of s.requirements.filter(x=>s.requestItems.some(item=>item.requirement_id===x.id)))touch(requirement,{scope_revision:s.scopes[0].revision,status:'review_required',status_reason:'Scope revision changed; applicability and evidence require review'},now);}if(wasApproved){for(const d of s.requestAccessDecisions.filter(x=>x.request_id===req.id&&x.status==='approved'))touch(d,{status:'superseded'},now);for(const g of s.accessGrants.filter(x=>x.request_id===req.id&&x.status==='limited_active'))touch(g,{status:'suspended',suspension_reason:'request_revision_changed'},now);}objects.push(req.id);break;}
  case 'review_request':{const reviews=s.demoConfig.batchB.reviews;if(!reviews?.contact||!reviews.disclosure||!reviews.access||!reviews.reviewer_permission_ref)throw Error('Contact, disclosure and access review configuration required');if(req.review_status!=='pending_review')throw Error('Request must be pending review');touch(req,{review_status:'approved',review_ref:id('review',`request-${req.revision}`)},now);for(const recipient of s.requestRecipients.filter(x=>x.status==='active')){const contact=s.businessContacts.find(x=>x.person_ref===recipient.person_ref);if(!contact?.contact_reviewed||contact.contact_review_ref!==recipient.contact_review_ref)throw Error('Contact review does not match recipient');const slug=`${recipient.id.split('/').at(-1)}-${req.revision}`,decision=make('access-decision',slug,{request_id:req.id,request_revision:req.revision,recipient_ref:recipient.id,item_refs:[...recipient.permitted_item_refs],basis_refs:[contact.contact_review_ref,req.review_ref],reviewer_permission_ref:reviews.reviewer_permission_ref,status:'approved',created_at:now,updated_at:now}),invitation=make('invitation',slug,{recipient_ref:recipient.id,request_scope:{request_id:req.id,item_refs:[...recipient.permitted_item_refs]},auth_policy_ref:s.demoConfig.batchB.authentication_policy_ref,expires_at:s.demoConfig.batchB.grant_expires_at,revoked_at:null,activated_at:null,status:'created',created_at:now,updated_at:now}),grant=make('grant',slug,{user_ref:recipient.person_ref,recipient_ref:recipient.id,request_id:req.id,request_revision:req.revision,scope_revision:s.scopes[0].revision,resource_scope:{request_id:req.id,item_refs:[...recipient.permitted_item_refs]},permitted_actions:['read_item','save_response','submit_response','refer_question','read_own_receipt'],provisioning_basis_ref:decision.id,status:'limited_active',expires_at:invitation.expires_at,revoked_at:null,created_at:now,updated_at:now});s.requestAccessDecisions.push(decision);s.portalInvitations.push(invitation);s.accessGrants.push(grant);objects.push(decision.id,grant.id);}break;}
  case 'dispatch':{const policy=s.channelPolicies.find(x=>x.channel===a.channel&&x.approval_status==='configured_for_demo');if(!policy)throw Error('Channel is not configured for dispatch');if(req.review_status!=='approved'||!req.review_ref)throw Error('Current request revision requires approved review');if(s.notifications.some(x=>x.request_id===req.id&&x.request_revision===req.revision&&x.channel===a.channel))return input;const sentItems=s.requestRecipients.filter(x=>x.status==='active').map(recipient=>{const notification=make('notification',`${recipient.id.split('/').at(-1)}-${req.revision}`,{request_id:req.id,request_revision:req.revision,scope_revision:s.scopes[0].revision,recipient_ref:recipient.id,channel:a.channel,dispatch_status:'sent',delivery_status:'unknown',adapter_event_ref:`local_simulation:${a.key}:${recipient.id.split('/').at(-1)}`,sent_at:now,sent_request_snapshot:{id:req.id,revision:req.revision,client_summary:req.client_summary},sent_item_snapshot:recipient.permitted_item_refs.map(itemId=>safeItem(itemOf(s,itemId))),created_at:now,updated_at:now});s.notifications.push(notification);objects.push(notification.id);return notification.id;});req.dispatch_status='sent';req.delivery_status='unknown';req.sent_at=now;req.sent_revision_refs=[...req.sent_revision_refs,{request_revision:req.revision,notification_refs:sentItems}];break;}
  case 'record_note':{const note=make('interaction',`note-${s.interactionRecords.length+1}`,{channel:a.channel||'phone',participants:[a.role],occurred_at:now,summary:cleanText(a.text,'Interaction note'),reviewed_by:a.role,review_status:'reviewed',request_item_refs:a.itemId?[a.itemId]:[],created_at:now,updated_at:now});s.interactionRecords.push(note);objects.push(note.id);break;}
  case 'refer_question':{if(a.role==='ROLE-CLIENT')clientGuard('refer_question');const work=make('work',`collaboration-question-${s.workItems.length+1}`,{work_type:'collaboration_question',request_item_ref:a.itemId||null,status:'referred',owner_role:'Unassigned',next_owner:'Unassigned',summary:cleanText(a.text||a.rationale,'Question'),scope_revision:s.scopes[0].revision,created_at:now,updated_at:now});s.workItems.push(work);objects.push(work.id);break;}
  case 'start_session':{if(a.reference!==req.reference)throw Error('Valid request reference required');if(![COLLAB_IDS.personT,COLLAB_IDS.secondContributor].includes(a.userId))throw Error('Synthetic identity is not configured');if(!a.sessionId||s.contributorSessions.some(x=>x.id===a.sessionId))throw Error('Unique session id required');const session={...make('contributor-session',a.sessionId,{id:a.sessionId}),user_ref:a.userId,reference:a.reference,status:'simulated_authenticated',session_authenticated:true,request_access_granted:false,business_authority_established:false,scope_revision:s.scopes[0].revision,authenticated_at:now,production_authentication_validated:false,created_at:now,updated_at:now};s.contributorSessions.push(session);objects.push(session.id);break;}
  case 'save_response':clientGuard('save_response');touch(target,{response_draft:cleanText(a.text,'Response draft'),response_status:'draft'},now);objects.push(target.id);break;
  case 'submit_response':clientGuard('submit_response');addSubmission({submittedBy:a.userId,onBehalfOf:a.userId,staffUploader:null,sourceChannel:'secure_web',text:a.text});break;
  case 'staff_submit':addSubmission({submittedBy:a.userId,onBehalfOf:a.userId,staffUploader:a.role,sourceChannel:'staff_assisted',text:a.text});break;
  case 'release_artifact':{if(!['released','rejected','quarantined'].includes(a.intakeStatus))throw Error('Named mock intake status required');const artifact=s.evidence.find(x=>x.id===a.reference&&x.request_item_refs?.includes(target.id));if(!artifact)throw Error('Batch B artifact not found for request item');touch(artifact,{intake_security_status:a.intakeStatus,status_reason:`Mock intake scenario: ${a.intakeStatus}; no real security scan performed`},now);objects.push(artifact.id);break;}
  case 'link_evidence':{const artifact=s.evidence.find(x=>x.id===a.reference&&x.request_item_refs?.includes(target.id));if(!artifact)throw Error('Evidence does not match request item');if(target.scope_revision!==s.scopes[0].revision||artifact.scope_revision!==s.scopes[0].revision||artifact.case_scope_id!==s.scopes[0].id)throw Error('Evidence scope revision does not match the current request item');if(!artifact.linked_item_refs.includes(target.id))touch(artifact,{linked_item_refs:[...artifact.linked_item_refs,target.id]},now);touch(target,{linked_evidence_refs:[...new Set([...target.linked_evidence_refs,artifact.id])],linked_evidence_revisions:{...target.linked_evidence_revisions,[artifact.id]:artifact.revision}},now);objects.push(artifact.id,target.id);break;}
  case 'record_assessment':{rationale();if(target.id!==COLLAB_IDS.authorityItem)throw Error('Only the named coordination sufficiency demo is configured');const artifact=s.evidence.find(x=>x.id===a.reference&&x.request_item_refs?.includes(target.id));if(!artifact||artifact.intake_security_status!=='released')throw Error('Released current evidence is required');if(target.scope_revision!==s.scopes[0].revision||artifact.scope_revision!==s.scopes[0].revision||artifact.case_scope_id!==s.scopes[0].id)throw Error('Evidence scope revision does not match the current request item');if(!artifact.linked_item_refs.includes(target.id)||!target.linked_evidence_refs.includes(artifact.id))throw Error('Evidence must be explicitly linked to purpose');if(target.linked_evidence_revisions?.[artifact.id]!==artifact.revision)throw Error('Linked evidence revision changed; review and link the current revision');const prior=s.evidenceUseAssessments.filter(x=>x.requirement_id===target.requirement_id).at(-1),assessment=make('assessment',`authority-coordinate-b${s.evidenceUseAssessments.length+1}`,{evidence_id:artifact.id,evidence_record_revision:artifact.revision,evidence_revision:artifact.evidence_revision,content_revision:artifact.content_revision,requirement_id:target.requirement_id,request_item_ref:target.id,subject_id:target.subject_id,principal_entity_id:target.principal_entity_id,purpose_code:target.purpose_code,sufficiency:'sufficient',coverage:'coordination_only',reason_code:'synthetic_coordination_basis_sufficient_for_demo',basis_refs:[artifact.id],assessed_by_ref:a.role,assessment_permission_ref:s.demoConfig.batchB.reviews.reviewer_permission_ref,assessed_at:now,scope_revision:s.scopes[0].revision,item_revision:target.revision,authority_ref:id('authority','coordinate_information'),supersedes_assessment_ref:prior?.id||null,currency:'current',rationale:a.rationale.trim(),created_at:now,updated_at:now});s.evidenceUseAssessments.push(assessment);const requirement=s.requirements.find(x=>x.id===target.requirement_id);touch(requirement,{status:'satisfied',status_reason:'Purpose-specific coordination evidence assessed sufficient for demo'},now);touch(target,{response_status:'closed'},now);const authority=s.authorities.find(x=>x.action_type==='coordinate_information'&&x.principal_entity_id===ENTITY_A);if(authority)touch(authority,{status:'established_for_demo',scope_match:'established_for_demo',evidence_use_refs:[...new Set([...(authority.evidence_use_refs||[]),assessment.id])]},now);for(const work of s.workItems.filter(x=>x.id===requestOf(s).task_ref||x.request_item_ref===target.id))touch(work,{status:'completed',waiting_for:null,output_refs:[...new Set([...(work.output_refs||[]),assessment.id])]},now);for(const dependency of s.dependencies.filter(x=>x.currency==='unknown'))touch(dependency,{currency:'needs_review'},now);objects.push(assessment.id,target.id,requirement.id);break;}
  case 'request_more':rationale();touch(target,{response_status:'needs_more_information'},now);objects.push(target.id);break;
  case 'refer_review':{rationale();const work=make('work',`collaboration-review-${s.workItems.length+1}`,{work_type:'collaboration_review',request_item_ref:target.id,status:'referred',owner_role:'Unassigned',next_owner:'Unassigned',scope_revision:s.scopes[0].revision,reason:a.rationale.trim(),created_at:now,updated_at:now});s.workItems.push(work);objects.push(work.id);break;}
  case 'revoke_grant':{const grants=s.accessGrants.filter(x=>x.recipient_ref===a.recipientId&&x.status==='limited_active');if(!grants.length)throw Error('Active grant not found');for(const grant of grants)touch(grant,{status:'revoked',revoked_at:now},now);objects.push(...grants.map(x=>x.id));break;}
  case 'replace_recipient':{rationale();const reviews=s.demoConfig.batchB.reviews,old=recipientOf(s,a.recipientId),replacement=s.requestRecipients.find(x=>x.person_ref===a.userId),contact=s.businessContacts.find(x=>x.person_ref===a.userId);if(req.review_status!=='approved'||!req.review_ref||!reviews?.contact||!reviews.disclosure||!reviews.access||!reviews.reviewer_permission_ref)throw Error('Current approved request and contact/disclosure/access review configuration required');if(!old||old.status!=='active'||!old.permitted_item_refs.includes(target?.id)||!replacement||replacement.id===old.id||replacement.status!=='active')throw Error('Request item must belong to the current old recipient and a distinct active replacement recipient');if(!contact?.contact_reviewed||contact.contact_review_ref!==replacement.contact_review_ref)throw Error('Replacement contact review is not current');for(const grant of s.accessGrants.filter(x=>x.recipient_ref===old.id&&x.status==='limited_active'))touch(grant,{status:'revoked',revoked_at:now},now);for(const invitation of s.portalInvitations.filter(x=>x.recipient_ref===old.id&&['created','activated'].includes(x.status)))touch(invitation,{status:'revoked',revoked_at:now},now);touch(old,{status:'replaced',permitted_item_refs:old.permitted_item_refs.filter(x=>x!==target.id)},now);touch(replacement,{permitted_item_refs:[...new Set([...replacement.permitted_item_refs,target.id])]},now);const decision=make('access-decision',`replacement-${s.requestAccessDecisions.length+1}`,{request_id:req.id,request_revision:req.revision,recipient_ref:replacement.id,item_refs:[target.id],basis_refs:[req.review_ref,replacement.contact_review_ref],reviewer_permission_ref:reviews.reviewer_permission_ref,status:'approved',replacement_for:old.id,created_at:now,updated_at:now}),grant=make('grant',`replacement-${s.accessGrants.length+1}`,{user_ref:replacement.person_ref,recipient_ref:replacement.id,request_id:req.id,request_revision:req.revision,scope_revision:s.scopes[0].revision,resource_scope:{request_id:req.id,item_refs:[target.id]},permitted_actions:['read_item','save_response','submit_response','refer_question','read_own_receipt'],provisioning_basis_ref:decision.id,status:'limited_active',expires_at:s.demoConfig.batchB.grant_expires_at,revoked_at:null,created_at:now,updated_at:now});s.requestAccessDecisions.push(decision);s.accessGrants.push(grant);objects.push(old.id,replacement.id,decision.id,grant.id);break;}
  default:throw Error('Unsupported collaboration action');
 }
 const fromRevision=s.case.revision;touch(s.case,{},now);
 const event=make('event',`collaboration-${s.case.revision}-${s.auditEvents.length+1}`,{event_type:{save_request:'request_draft_saved',review_request:'request_review_recorded',dispatch:'notification_dispatched',record_note:'interaction_note_recorded',start_session:'contributor_session_started',submit_response:'response_submitted',staff_submit:'response_submitted',release_artifact:'artifact_intake_released',record_assessment:'assessment_recorded'}[a.type]||a.type,actor_ref:a.role,object_ref:objects[0]||req.id,object_refs:objects,from_revision:fromRevision,to_revision:s.case.revision,correlation_id:a.key,idempotency_fingerprint:fingerprint,occurred_at:now,expected_revision:a.expectedRevision,expected_request_revision:a.expectedRequestRevision,expected_item_revision:a.expectedItemRevision??null,rationale:a.rationale?.trim()||null,created_at:now,updated_at:now});
 s.auditEvents.push(event);
 const state=readiness(s),snapshot=make('snapshot',`collaboration-${s.case.revision}`,{revision:s.case.revision,supersedes_ref:s.readinessSnapshots.at(-1)?.id||null,scope_revision:s.scopes[0].revision,condition_revisions:Object.fromEntries(s.clearanceConditions.map(c=>[c.id,c.revision])),result:state.result,blocking_condition_ids:state.blocking_condition_ids,unknown_condition_ids:state.unknown_condition_ids,evaluated_at:now,basis_event_refs:[event.id],created_at:now,updated_at:now});
 s.readinessSnapshots.push(snapshot);return s;
}

export function collaborationProjection(s,{audience,userId,sessionId,now}={}){
 const request=requestOf(s),common=commonProjection(s,request),at=isoNow(now);
 if(audience==='client'){
  const access=accessContext(s,{userId,sessionId,action:'read_item',now:at});if(!access.ok)return {...common,allowed:false,reason:access.reason,request:{id:request.id,revision:request.revision,reference:request.reference}};
  const itemIds=new Set(s.requestItems.filter(item=>accessContext(s,{userId,sessionId,itemId:item.id,action:'read_item',now:at}).ok).map(item=>item.id)),items=s.requestItems.filter(x=>itemIds.has(x.id)).map(safeItem);
  const submissions=s.submissions.filter(x=>x.submitted_by===userId&&x.request_item_refs.length>0&&x.request_item_refs.every(itemId=>accessContext(s,{userId,sessionId,itemId,action:'read_own_receipt',now:at}).ok)).map(x=>({id:x.id,revision:x.revision,request_item_refs:[...x.request_item_refs],submitted_at:x.submitted_at,source_channel:x.source_channel,response_text:x.response_text,artifact_receipts:x.artifact_refs.map(artifactId=>{const artifact=s.evidence.find(e=>e.id===artifactId);return {artifact_ref:artifactId,intake_security_status:artifact?.intake_security_status||'unknown'};}),intake_security_status:x.artifact_refs.length===1?s.evidence.find(e=>e.id===x.artifact_refs[0])?.intake_security_status||'unknown':'unknown'}));
  return {...common,allowed:true,request:{id:request.id,revision:request.revision,reference:request.reference,client_summary:request.client_summary},items,submissions,environment:{implementation_fidelity:'local_simulation',production_authentication_validated:false}};
 }
 if(audience==='rm')return {...common,request:{id:request.id,revision:request.revision,reference:request.reference,client_summary:request.client_summary,review_status:request.review_status,dispatch_status:request.dispatch_status,delivery_status:request.delivery_status},items:s.requestItems.map(safeItem),contacts:s.businessContacts.map(x=>({id:x.id,person_ref:x.person_ref,status:x.status,contact_reviewed:x.contact_reviewed})),interactionRecords:s.interactionRecords.filter(x=>x.review_status==='reviewed').map(x=>({id:x.id,channel:x.channel,occurred_at:x.occurred_at,summary:x.summary,reviewed_by:x.reviewed_by,request_item_refs:[...x.request_item_refs]}))};
 if(audience==='ops'){const assessments=s.evidenceUseAssessments.filter(x=>x.source_refs?.includes('SRC-015')||x.id===id('assessment','authority-coordinate')).map(x=>({...structuredClone(x),currency:x.scope_revision===s.scopes[0].revision?'current':'needs_review'})),requirementIds=new Set(s.requestItems.map(x=>x.requirement_id));return {...common,request:structuredClone(request),items:structuredClone(s.requestItems),requirements:structuredClone(s.requirements.filter(x=>requirementIds.has(x.id))),evidence:structuredClone(s.evidence.filter(x=>x.source_refs?.includes('SRC-015')&&x.request_item_refs)),tasks:structuredClone(s.workItems.filter(x=>x.id===request.task_ref||x.request_item_ref||x.work_type?.startsWith('collaboration'))),activity:structuredClone(s.auditEvents.filter(x=>x.source_refs?.includes('SRC-015'))),contacts:structuredClone(s.businessContacts),notifications:structuredClone(s.notifications),submissions:structuredClone(s.submissions),assessments,grants:structuredClone(s.accessGrants),access_decisions:structuredClone(s.requestAccessDecisions),recipients:structuredClone(s.requestRecipients),contributorSessions:structuredClone(s.contributorSessions),readiness:readiness(s),environment:{implementation_fidelity:'local_simulation',production_authentication_validated:false}};}
 return {...common,allowed:false,reason:'unsupported_audience'};
}
