const D=await fetch('registry.json').then(r=>{if(!r.ok)throw Error('流程登记无法读取');return r.json()});
const W=Object.fromEntries(D.works.map(w=>[w.parent_ref,w])),S=Object.fromEntries(D.scenes.map(s=>[s.id,s])),P=Object.fromEntries(D.personas.map(p=>[p.id,p]));
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const q=new URLSearchParams(location.search);let mode=q.has('scenario')?'scene':'process',selected=q.get('process')||q.get('scenario')||null,work=q.get('work'),side=q.get('side')==='before'?'before':'after';
const dir={retain:'= 保留',remove:'− 删除',enhance:'↑ 提升',add:'+ 新增',unconfirmed:'? 未确认'},groups={M0:'01 INITIATE · 入账范围',M1:'01 INITIATE · 受理与分流',M2:'02 DETERMINE · 适用要求',M3:'02 DETERMINE · 资料与证据',M4:'03 ASSESS · 筛查与判断',M5:'03 ASSESS · 强化尽调',M6:'04 RESOLVE · 质量检查',M7:'跨阶段 · 利益冲突（可从 M1 早启）',M8:'05 CLEAR · 就绪与发布',C1:'并行控制 · 法务',C2:'并行控制 · 信用'};
const tx=t=>e(t).replace(/\n/g,'<br>'),list=v=>'<ul>'+v.map(x=>'<li>'+tx(x)+'</li>').join('')+'</ul>';
const sceneTitle=s=>({ 'SCN-SCOPE':'明确客户关系与范围','SCN-ENTITY':'分清主体、关系与权限','SCN-REQUIREMENTS':'确定适用要求','SCN-SOURCE':'寻找可用资料','SCN-GAP':'索取具体缺失事实','SCN-VALIDATE':'按用途审查证据','SCN-POPULATION':'确定筛查对象','SCN-MATCH':'判断可能的匹配','SCN-EDD':'开展强化尽调','SCN-CONFLICTS':'调查与解决利益冲突','SCN-CREDIT':'评估信用与条件','SCN-LEGAL':'审查与签署协议','SCN-QA':'质量检查与改正','SCN-READINESS':'解释整体就绪状态','SCN-PUBLISH':'记录与传达结果'}[s.id]||s.title);
const title=a=>{const ws=a.work_ids.map(id=>W[id]);return ws.map(w=>w.experience.action).filter((x,i,arr)=>arr.indexOf(x)===i).slice(0,2).join(' / ')};
function save(){const u=new URL(location);u.search='';if(selected)u.searchParams.set(mode==='process'?'process':'scenario',selected);if(work)u.searchParams.set('work',work);u.searchParams.set('side',side);history.pushState(null,'',u);}
function catalogue(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));const term=document.querySelector('#search').value.trim().toLowerCase(),stage=document.querySelector('#stage').value;
 let items=mode==='process'?D.anchors:D.scenes;
 items=items.filter(a=>{const ids=mode==='process'?a.work_ids:a.parent_ids;const codes=mode==='process'?[a.id]:D.anchors.filter(p=>p.scenario_ids.includes(a.id)).map(p=>p.id);return(stage==='all'||codes.some(c=>c.startsWith(stage+'.')))&&(!term||JSON.stringify([a,...ids.map(id=>W[id])]).toLowerCase().includes(term))});
 const buckets=new Map();for(const a of items){const group=mode==='process'?a.id.split('.')[0]:a.journey_stage;if(!buckets.has(group))buckets.set(group,[]);buckets.get(group).push(a)}
 document.querySelector('#catalogue').innerHTML=items.length?[...buckets].sort((a,b)=>Object.keys(groups).indexOf(a[0])-Object.keys(groups).indexOf(b[0])).map(([g,arr])=>`<section class="group"><h2>${e(groups[g]||g)} <small>${arr.length} 项</small></h2><div class="cards">${arr.map(a=>{const ids=mode==='process'?a.work_ids:a.parent_ids;return `<button class="card ${a.id===selected?'selected':''}" data-select="${e(a.id)}"><span class="id">${e(a.id)}</span><b>${e(mode==='process'?title(a):sceneTitle(a))}</b><span>${ids.length} 个工作项 · ${ids.reduce((n,id)=>n+W[id].actions.length,0)} 个关联原子动作${mode==='process'&&a.unresolved?' · 含待校准来源':''}</span></button>`}).join('')}</div></section>`).join(''):'<p class="empty">没有匹配项。可搜索流程号、SCN、D3 或 D4A。</p>';
}
function sourceSection(w){return `<details class="sources"><summary>来源、变更映射与 Excel principle <small>技术标识作为次级信息保留</small></summary><h4>来源定位</h4>${list(w.qualified_process_refs)}<h4>源图的变更判断</h4>${w.source_change_relations.map(r=>`<p>${dir[r.semantic_type]||e(r.semantic_type)} · ${e(r.crosswalk_id)}<br>${e(r.relationship_labels.join(' / '))} · ${e(r.pairing_status)}</p>`).join('')}<h4>痛点依据</h4>${list(w.pain_ppt_refs)}<p class="status">PPT 定性观点支持背景；具体角色、时刻与原子痛点为设计推导，不是访谈、工时测量或银行 KPI。</p><h4>Excel 原则采用位置</h4><div class="fields">${Object.entries(w.principles.principle_links).map(([k,v])=>`<p>${e(k)} · ${e(Array.isArray(v)?v.join(' | '):v)}</p>`).join('')}</div><p class="status">WB-P01–07 是本项目阅读用标识，保留工作簿原有单元格引用。</p><h4>后续产品页面</h4><p>${e(w.d5_surface)} · 绑定候选；不是全部动作已经实现的声明。</p><a href="../?studio=journey&locale=zh-CN&scenario=${e(w.scenario_ref)}&work=${e(w.parent_ref)}" target="_top">打开既有 Studio 场景与页面设计 ↗</a></details>`}
function action(a,w,i){return `<details data-action="${e(a.action_id)}"><summary>${String(i+1).padStart(2,'0')} · ${e(a.label_zh)}<small>${e(a.action_id)} · ${e(a.execution_type)}${a.agent_candidate_ref?' · '+e(a.agent_candidate_ref):''}</small></summary><div class="action-body"><p class="review">本动作沿用工作项痛点：${e(w.experience.pain)}<br>机会：${e(w.experience.opportunity)}<br>${dir[w.solution_direction]}：${e(w.experience.to_be)}${w.remove_target?'<br><b>删除对象：</b>'+e(w.remove_target)+'；保留证据、判断与责任。':''}<br><small>上述体验证据继承自 ${e(w.parent_ref)}，不是逐动作新增的访谈发现。</small></p><div class="contract"><article><h4>开始前，需要什么</h4>${list(a.preconditions)}<p>${e(a.mvp_treatment)}</p></article><article><h4>这一步怎么做</h4><p>${e(a.target_treatment)}</p><p><b>为什么用这种分工</b><br>${e(a.why_not_simpler)}</p><p>${e(a.simpler_baseline)}</p></article><article><h4>不能继续时，谁接住问题</h4><p>${e(a.stop_condition)}</p><p>${e(a.human_role_hypothesis)}（角色假设）</p><p>交给人员的问题：${e(a.human_decision_pack.decision_question)}</p><p>保留：${e(a.human_decision_pack.unknowns)}</p></article><article><h4>补充后，从哪里继续</h4><p>${e(a.resume_condition)}</p><p>返回位置：${e(a.human_decision_pack.return_anchor)}</p><p>查询失败不是“不存在”；提交结果未知时先核实原结果，再决定是否重试。</p></article></div>${a.agent_candidate_ref?agent(a.agent_candidate_ref,a):''}<details><summary>字段、输出范围与验收条件</summary><div class="fields"><p>读取：${e(a.reads.join(' · '))}</p><p>输出：${e(a.outputs.join(' · '))}</p><p>WF：${e(a.workflow_id)} · Skill：${e(a.skill_refs.join(', '))}</p></div><p>${e(a.permitted_write_scope)}</p><h4>不能产生的影响</h4>${list(a.forbidden_effects)}<h4>UAT 判据（尚未执行）</h4><p>${e(a.test_oracle)}</p><p>${e(a.scene_control_test)}</p><p class="status">正向：输入与权限齐备，仅产生本项输出。否：停在所列缺口并由指定角色承接。未知：保持未定，重读当前版本；不能自动改判为通过。</p></details></div></details>`}
function agent(id,a){const g=D.agents.find(g=>g.id===id);return `<article class="review"><h4>${e(id)} · 受限规划展开</h4><p>${e(g.goal)}</p><ol><li>固定目标：${e(a.label_zh)}；只使用本动作获准的输入。</li><li>先检查确定性基线能否完成；能够完成则不启用自主规划。</li><li>在白名单 Skill 与来源内提出下一步，并说明依据。</li><li>执行前再次校验访问范围、当前版本与剩余任务预算；条件不明确则停止。</li><li>把返回材料和出处逐项核对，区分有用证据、矛盾、缺口与查询失败。</li><li>仅在同一目标与预算内提出下一步；重复无进展或需要专业判断时交人。</li><li>交付方案、引用和未决项，由既有工作流及获授权的人决定后续。</li></ol><p><b>停止：</b>${e(g.stop)}</p><p><b>禁止：</b>${e(g.writes)}</p><p class="status">这七步是基于既有 ${e(id)} 契约的本轮展开设计；预算值、工具权限与投产条件仍待银行确认。</p><a href="diagrams/${e(id)}.html?theme=light" target="_blank" rel="noopener">打开 Agent 候选的独立 Archify 流程 ↗</a></article>`}
function diagramName(){return work==='D3-SCOPE-02'&&side==='after'?'M0-1-after':work==='D3-SCOPE-03'&&side==='after'?'M0-2-after':work+'-'+side}
function detail(){document.querySelector('#catalogue').hidden=Boolean(selected);const anchor=mode==='process'?D.anchors.find(a=>a.id===selected):null,sc=mode==='scene'?S[selected]:null;const ids=anchor?.work_ids||sc?.parent_ids;if(!ids){document.querySelector('#detail').innerHTML='';return}if(!ids.includes(work))work=ids[0];const w=W[work],s=S[w.scenario_ref],p=P[w.diagram_persona_ref];
 document.querySelector('#detail').innerHTML=`<div class="detail-top"><div><small>${e(selected)} · ${mode==='process'?'来源流程定位':'业务场景'}</small><h2>${e(anchor?title(anchor):sceneTitle(sc))}</h2></div><button id="close">收起详情 ↑</button></div>${anchor?`<details class="sourcebox"><summary>${anchor.occurrences.length} 个源图实例 · 页码、泳道与原文</summary>${list(anchor.occurrences.map(o=>`${o.source_id} · 第 ${o.slide_no} 页 · ${o.visible_actor} · ${o.verbatim_text} [${o.format_observation}]`))}${anchor.id==='M0.1'?'<p>Target 的两个 M0.1 分开保存；同号不代表同一个工作实例。</p>':''}</details>`:''}<nav class="work-nav" aria-label="工作项">${ids.map(id=>`<button data-work="${e(id)}" aria-pressed="${id===work}">${e(W[id].experience.action)}<small>${e(id)}</small></button>`).join('')}</nav><div class="work-cover"><img class="scene-image" src="../studio-next/assets/${e(s.id)}.jpg" alt="${e(sceneTitle(s))} · 复用的合成场景图"><div><small>${e(s.id)} · ${e(w.parent_ref)}</small><h3>${e(w.experience.action)}</h3><p>${e(sceneTitle(s))} · Entity A / FX forward</p>${p?`<div class="person"><img src="../studio-next/assets/${e(p.id)}.jpg" alt="${e(p.name)} · 合成人物"><div><b>${e(p.name)}</b><small>${e(p.source.role_label)}</small></div></div>`:''}<p class="status">画像与职责用于设计阅读，不代表已经确认的银行权限。</p></div></div><div class="legend" aria-label="变更类型"><span>= 保留</span><span>− 删除</span><span class="enhance">↑ 提升</span><span class="add">+ 新增</span><span>? 未确认</span></div><p class="status">移交、拆分、合并、改序作为附属关系。Rule / Workflow / Skill / Agent / Human 是独立执行分工。Archify 章节栏的数量表示高亮变化，不是业务新增统计。</p><div class="toolbar"><div class="segment" role="tablist" aria-label="Before / After"><button role="tab" data-side="before" aria-selected="${side==='before'}">Before · 当前概括</button><button role="tab" data-side="after" aria-selected="${side==='after'}">After · 动作展开</button></div><a id="fullscreen" target="_blank" rel="noopener">打开完整演示 ↗</a></div><p class="status" id="diagram-status"></p><iframe class="diagram" title="${e(w.experience.action)} · ${side}"></iframe><img class="print-diagram" alt="完整流程静态图"><div class="experience"><article><h4>Before · 人的工作与困扰</h4><p>${e(w.experience.as_is)}</p><p><b>痛点：</b>${e(w.experience.pain)}</p></article><article><h4>After · 改善方向</h4><p><b>${dir[w.solution_direction]}</b> · ${e(w.experience.to_be)}</p><p><b>机会：</b>${e(w.experience.opportunity)}</p><p><b>边界：</b>${e(w.experience.boundary)}</p></article></div><section class="actions"><h3>逐个展开 ${w.actions.length} 个原子动作</h3><p class="status">D4A 编号不变；流程连线为本轮演示顺序，不能把编号相邻或字段同名当作已证实的执行依赖。</p>${w.actions.map((a,i)=>action(a,w,i)).join('')}</section>${sourceSection(w)}`;updateDiagram();}
function updateDiagram(){const name=diagramName(),url=`diagrams/${name}.html?theme=light`;document.querySelector('.diagram').src=url;document.querySelector('#fullscreen').href=url;document.querySelector('.print-diagram').src=`diagrams/${name}.svg`;document.querySelector('#diagram-status').textContent=side==='before'?'当前工作级概括；细节未逐项访谈验证。':'来源关联的动作设计；不是自动批准。缺失与未知路径保留，恢复条件在各动作下展开。';}
document.querySelector('#stats').innerHTML='<div class="stats">'+[['scenarios','场景'],['source_anchors','流程编号'],['works','工作项'],['actions','原子动作']].map(([k,t])=>`<span><b>${D.counts[k]}</b>${t}</span>`).join('')+'</div>';
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.mode){mode=b.dataset.mode;selected=null;work=null;catalogue();detail();save()}if(b.dataset.select){selected=b.dataset.select;work=null;catalogue();detail();save();document.querySelector('#detail').scrollIntoView({behavior:'instant'})}if(b.dataset.work){work=b.dataset.work;detail();save()}if(b.dataset.side){side=b.dataset.side;document.querySelectorAll('[data-side]').forEach(n=>n.setAttribute('aria-selected',String(n.dataset.side===side)));updateDiagram();save()}if(b.id==='close'){selected=null;work=null;detail();catalogue();save();document.querySelector('.filters').scrollIntoView()}});
document.querySelector('#search').addEventListener('input',catalogue);document.querySelector('#stage').addEventListener('change',catalogue);
window.addEventListener('popstate',()=>{const q=new URLSearchParams(location.search);mode=q.has('scenario')?'scene':'process';selected=q.get('process')||q.get('scenario');work=q.get('work');side=q.get('side')==='before'?'before':'after';catalogue();detail()});
window.addEventListener('beforeprint',()=>document.querySelectorAll('#detail details').forEach(d=>{d.dataset.printOpen=String(d.open);d.open=true}));window.addEventListener('afterprint',()=>document.querySelectorAll('#detail details').forEach(d=>{d.open=d.dataset.printOpen==='true'}));
catalogue();detail();if(selected)requestAnimationFrame(()=>document.querySelector('#detail').scrollIntoView({behavior:'instant'}));
document.addEventListener('keydown',ev=>{if(!ev.target.matches('[data-side]')||!['ArrowLeft','ArrowRight','Home','End'].includes(ev.key))return;ev.preventDefault();const target=ev.key==='Home'?'before':ev.key==='End'?'after':side==='before'?'after':'before';const b=document.querySelector('[data-side="'+target+'"]');b.click();b.focus()});
