export const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const badge=(s,kind='')=>`<span class="status ${kind}">${escape(s)}</span>`;
const field=(label,value,extra='')=>`<div><span class="field-label">${escape(label)}</span><span class="field-value ${extra}">${escape(value)}</span></div>`;
export function scopeView(p,t,index){return `<div class="request-card" data-focus-object="request"><div class="record-top"><span>${t('request')}</span><span>EV-A01 · Group A</span></div><blockquote>${t('request_body')}</blockquote><small>${t('fx_reason')}</small></div>
<div class="object-pair"><article class="object-card" data-focus-object="group-a"><span class="eyebrow">${t('group_label')}</span><h3>Group A</h3><p>${t('group_not_key')}</p>${badge(t('reported'))}</article><article class="object-card" data-focus-object="entity-a"><span class="eyebrow">${t('entity_a_role')}</span><h3>Entity A</h3><p>${t(p.counterparty_clarified?'intended_entity':'candidate_entity')}</p>${badge(t(p.counterparty_clarified?'scope_clarified':'claimed'),'neutral')}</article></div>
<div class="scope-fields" data-focus-object="scope">${field(t('product'),p.product)}${field(t('booking'),t('not_provided'),'gap-value')}${field(t('eligibility'),t('not_assessed'),'gap-value')}</div>
<div class="source-line">${p.counterparty_clarified?`<b>${t('clarification')}</b><br>${t('clarification_text')}`:t('clarification_pending')}</div>
${index>=4?`<div class="next-work">${t('next_work')}<span>${t('next_requirements')}</span><span>${t('next_authority')}</span></div>`:''}`}
export function authorityView(p,t,index){const source=p.entity_source_reviewed?`<b>EV-A04 · ${t('source_arrived')}</b><br>${t('source_limit')}`:t('source_pending');return `<div class="context-pills">${field(t('principal'),p.principal)}${field(t('employer'),p.employer)}${field(t('purpose'),t('coordinate'))}</div>
${index===4?`<div class="prep-panel" data-focus-object="requirements"><div class="record-top"><span>${t('preparation')}</span>${badge(t('prep_ready'),'neutral')}</div><h3>${t('requirements_draft')}</h3><p>${t('prep_gate')}</p><div class="prep-row"><span>${t('other_work')}</span>${badge(t('not_assessed'))}</div><div class="prep-row"><span>${t('authority_wait')}</span>${badge(t('evidence_required'),'review')}</div><small>${t('no_send')}</small></div>`:`<div class="evidence-pair"><article class="evidence-card" data-focus-object="person-t"><span class="evidence-id">EV-A03</span><h3>${t('ev03')}</h3>${badge(t('reported'))}<p>${t('job_support')}</p><p>${t('job_authenticity')}</p></article><article class="evidence-card review" data-focus-object="authority"><span class="evidence-id">Entity A / ${t('coordinate')}</span><h3>${t('evidence_required')}</h3>${badge(t('not_established'),'review')}<p>${t('gap_reason')}</p><p><b>EV-A05 · ${t('not_received')}</b></p></article></div>
<div class="purposes"><div>${t('declarations')}${badge(t('not_established'))}</div><div>${t('agreements')}${badge(t('not_established'))}</div><div>${t('trading')}${badge(t('not_assessed'))}</div></div>`}
<div class="source-line" data-focus-object="entity-a">${source}</div>
${p.gap_task_visible?`<div class="task-strip" data-focus-object="authority"><div><b>${t('gap_task')} / Entity A</b><small>${t('coordinate')} · ${t('no_send')}</small></div><div><span class="field-label">${t('owner')}</span><span class="field-value">${t('unassigned')}</span></div>${badge(t('awaiting_input'),'review')}</div><p class="source-line">${t('wait_disclosure')}</p>`:''}`}
export function relationRecords(asset,t){return asset==='DMO-A01'?`<div class="object-pair"><div class="static-card"><h3>Group A</h3><p>${t('group_not_key')}</p></div><div class="static-card"><h3>Entity A</h3><p>${t('intended_entity')}</p><p>${t('result_scope')}</p></div></div>`:`<div class="object-pair"><div class="static-card"><h3>Person T / Entity B</h3><p>${t('job_support')}</p><p>Entity B / Entity A · ${t('reported')}</p></div><div class="static-card"><h3>Person T / Entity A</h3><p>${t('coordinate')} · ${t('evidence_required')}</p><p>${t('gap_reason')}</p></div></div>`}
