import registry from './registry.mjs';
const nodes=['E01-check','E01-gap','E01-remediate','E01-rereview','E01-signoff','E02-scope','E02-prerequisites','E02-evaluate','E02-ready','E02-notready','E03-ready','E03-confirm','E03-decision','E03-publish','E03-communicate','E03-failure'];
const scenes=['SCN-QA','SCN-READINESS','SCN-PUBLISH'];
// Reuse source and observation identity/status. These are additional bindings, not new verification.
export const clearanceReferences=['SRC-017:R22','SRC-017:R18','SRC-017:R20','SRC-017:R26','SRC-017:R28'].map(ref=>{
 const b=registry.bindings.find(x=>x.observation_ref===ref);
 return {source:registry.sources.find(x=>x.source_id===b.source_ref),observation:registry.observations.find(x=>x.observation_id===ref),interpretation:registry.interpretations.find(x=>x.interpretation_id===b.interpretation_ref),binding:{...b,binding_id:'SRC-020:'+ref+':binding',scenario_refs:scenes,semantic_node_refs:nodes,support_kind:'inherited_research_design_inspiration_not_bank_policy'}};
});
clearanceReferences.push({source:{source_id:'SRC-007',title:'Process context: M6 QA and M8 clearance',publisher:'Clear to Trade project source mapping',source_kind:'project_source',canonical_url:null,source_version:'Original source version not specified; E Final v1.0 summary',publication_date:null,region_scope:'Approved synthetic workshop summary; restricted original excluded'},observation:{observation_id:'SRC-020:M6-M8',supported_statement:'已批准 E Final 保留 M6.1–M6.8 的要求、完整性、来源、充分性、筛查／EDD、缺口、重新复核与 QA 签核，以及 M8.1–M8.5 的前提核对、案件汇集、准入确认、时间戳和结果传达。图节点是合成设计推导，不是已验证的银行权限。',supported_statement_en:'The approved E Final retains M6.1–M6.8 requirements, completeness, sources, sufficiency, screening / EDD, gaps, re-review and QA sign-off, and M8.1–M8.5 prerequisite review, case finalisation, clearance confirmation, timestamp and permitted communication. Diagram nodes are synthetic design interpretations, not verified bank authority.',verification_status:'Approved Final summary only; original byte identity and exact source locator not independently verified.',verification_origin:'approved_final_summary_only',verified_at:null},interpretation:{why_it_matters:'具体补正、当前版本就绪与单独授权／发布分别记录。',adopt:'Preserve precise remediation and separate readiness, authority and publication.',adapt:'Apply only to the approved synthetic scope; bank responsibilities remain To Validate.',avoid:'Do not expose the restricted original or infer bank policy and production permissions.'},binding:{scenario_refs:scenes,semantic_node_refs:nodes,support_kind:'approved_project_summary_not_original'}});
