import {processes,journeyRoles,activities,activitiesFor,sourceSteps,pains} from './model.mjs';

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(value,nav)=>esc(typeof value==='string'?value:value?.[nav.locale]||value?.['en-AU']||'');
const l=(nav,en,zh)=>nav.locale==='zh-CN'?zh:en;
const control=(label,action,value='',extra='')=>`<button data-action="${action}" data-value="${esc(value)}" ${extra}>${label}</button>`;
const roleTitle=(id,nav)=>t(journeyRoles.find(r=>r.id===id)?.title||id,nav);
const processTitle=(id,nav)=>t(processes.find(p=>p.id===id)?.title||id,nav);
const painFor=a=>pains.filter(p=>a.pains.includes(p.id));
const sourceSummary=(a,mode,nav)=>a.role==='ROLE-CLIENT'?l(nav,'Unnumbered client touchpoint','客户接触点（原图未编号）'):[...new Set(a.refs[mode].map(key=>sourceSteps.find(s=>s.key===key)?.number).filter(Boolean))].join(' · ');
const compare=nav=>`<div class="segmented" aria-label="${l(nav,'Comparison','对照')}">${['current','target'].map(c=>control(c==='current'?'Current':'Target','compare',c,`aria-pressed="${nav.comparison===c}"`)).join('')}</div>`;
const processControl=(p,nav)=>control(`<span class="journey-process-id">${p.id}</span><span>${t(p.title,nav)}</span>${p.parallel?`<small>${l(nav,p.id==='M7'?'Early / parallel':'Parallel',p.id==='M7'?'早启 / 并行':'并行')}</small>`:''}`,'journey-process',p.id,`aria-pressed="${nav.journeyProcess===p.id}"`);

export function journeyHtml(nav){
 const selected=nav.journeyRole||'ROLE-KYCOPS',visibleRoles=journeyRoles.filter(r=>selected==='all'||r.id===selected);
 const mode=nav.comparison==='current'?'current':'target';
 const rowHeights=visibleRoles.map(role=>Math.max(1,...processes.map(p=>activitiesFor({role:role.id,process:p.id}).length))*176+24);
 return `<section class="source-journey" aria-label="${l(nav,'Source-aligned role journey','源流程角色旅程')}">
 <div class="journey-viewbar"><label for="journey-role">${l(nav,'Read the journey as','从这一角色阅读旅程')}<select id="journey-role"><option value="all" ${selected==='all'?'selected':''}>${l(nav,'All roles','所有角色')}</option>${journeyRoles.map(r=>`<option value="${r.id}" ${selected===r.id?'selected':''}>${t(r.title,nav)}</option>`).join('')}</select></label><p>${l(nav,'Viewpoint only. Product tasks use the current demo role:','仅切换阅读视角。产品任务使用当前演示角色：')} <strong>${roleTitle(nav.role,nav)}</strong></p></div>
 <nav class="journey-process-rail" aria-label="${l(nav,'Source processes; location, not completion','源流程定位，非完成状态')}">${processes.filter(p=>!p.parallel).map(p=>processControl(p,nav)).join('')}</nav>
 <div class="journey-parallel"><span>${l(nav,'Start alongside intake','与受理同步启动')}</span>${processes.filter(p=>p.parallel).map(p=>processControl(p,nav)).join('')}<p>${l(nav,'M1 → M7 starts the conflicts check. Credit terms feed Legal before execution.','M1 → M7 启动利益冲突检查。签署前，信贷条款输入法务。')}</p></div>
 <div class="journey-frame source-frame"><div class="role-column"><div class="role-title">${l(nav,'ROLE / VIEWPOINT','角色 / 视角')}</div>${visibleRoles.map((r,i)=>`<div class="role-label" style="height:${rowHeights[i]}px"><strong>${t(r.title,nav)}</strong><span>${activitiesFor({role:r.id}).length} ${l(nav,'activity views','项活动视图')}</span></div>`).join('')}</div>
 <div class="journey-scroll" tabindex="0" role="region" aria-label="${l(nav,'Role activities. Scroll horizontally, use arrow keys or drag blank space.','角色活动。横向滚动、使用方向键或拖动空白处。')}"><div class="journey-columns">${processes.map(p=>`<section class="stage-column ${nav.journeyProcess===p.id?'focus-stage':''}" data-stage="${p.stage}" data-process="${p.id}" data-anchor="${p.id}"><header class="stage-heading"><span class="trace-meta">${p.id}${p.parallel?' · '+l(nav,p.id==='M7'?'Early / parallel':'Parallel',p.id==='M7'?'早启 / 并行':'并行'):''}</span><h3>${t(p.title,nav)}</h3></header>${visibleRoles.map((r,i)=>{const items=activitiesFor({role:r.id,process:p.id});return `<div class="journey-cell" style="height:${rowHeights[i]}px">${items.length?items.map(a=>`<button class="journey-activity ${nav.journeyActivity===a.id?'selected':''}" data-action="journey-activity" data-value="${a.id}" data-scene="${a.scene}"><span class="journey-card-title">${t(a.title,nav)} <span aria-hidden="true">↗</span></span><span class="journey-card-copy">${t(a[mode],nav)}</span><span class="journey-card-cue">${mode==='current'?l(nav,'Pain: ','痛点：')+t(painFor(a)[0]?.title,nav):l(nav,'Handoff: ','交接：')+t(a.handoff,nav)}</span></button>`).join(''):`<p class="journey-empty">${l(nav,'No direct activity mapped in this view.','本视角此处未映射直接活动。')}</p>`}</div>`;}).join('')}</section>`).join('')}</div></div></div>
 <p class="journey-scroll-help">${l(nav,'Scroll to follow M0–M8 and the parallel Legal / Credit lanes. Open an activity to see its goal, handoff and exact source steps.','横向滚动查看 M0–M8 及法务／信贷并行泳道。打开活动，查看角色目标、交接与确切源步骤。')} <span id="camera-status">${esc(nav.journeyProcess||'M0')}</span></p>
 <details class="journey-pain-disclosure"><summary>${l(nav,'Pain points across the journey and adjacent lifecycle','旅程及相邻生命周期痛点')} · ${pains.length}</summary>${painRegister(nav)}</details></section>`;
}

function sourceList(a,mode,nav){return `<ol class="journey-source-list">${a.refs[mode].map(key=>{const step=sourceSteps.find(s=>s.key===key);if(!step)return '';return `<li data-source-ref="${esc(step.key)}"><strong>${step.number.startsWith('contextual:')?l(nav,'Unnumbered client touchpoint','客户接触点（原图未编号）'):esc(step.number)}</strong> · ${t(step.title,nav)}<small>SRC-007 · ${l(nav,'slide','页')} ${step.page} · ${esc(step.lane)}</small>${step.note?`<p class="journey-source-note ${step.status==='ambiguous'?'is-ambiguous':'is-contextual'}">${t(step.note,nav)}</p>`:''}${nav.locale==='zh-CN'?`<details><summary>${l(nav,'Original source text (English)','源文（英文）')}</summary><p lang="en">${t(step.title,{locale:'en-AU'})}</p></details>`:''}</li>`;}).join('')}</ol>`;}
function narrative(a,nav,mode,print=false){return `<section class="journey-narrative" data-comparison="${mode}"><p class="eyebrow">${mode==='current'?'Current':'Target'} · ${l(nav,mode==='current'?'Activity & pain':'Proposed change',mode==='current'?'活动与痛点':'拟议变化')}</p><p>${t(a[mode],nav)}</p>${mode==='current'?`<ul>${painFor(a).map(p=>`<li>${t(p.title,nav)} — ${t(p.description,nav)}</li>`).join('')}</ul>`:`<p class="small muted">${l(nav,'Source proposal; human decisions and product permissions follow the configured controls.','源流程提案；人工决定与产品权限仍遵循已配置控制。')}</p>`}${print?sourceList(a,mode,nav):`<details class="journey-exact-source"><summary>${l(nav,'Exact source steps','确切源步骤')} · ${sourceSummary(a,mode,nav)}</summary>${sourceList(a,mode,nav)}</details>`}</section>`;}
function activityBody(a,nav,both=false){return `<article class="journey-activity-reader" data-activity="${a.id}"><p class="journey-role-goal"><span class="eyebrow">${l(nav,'Role goal','角色目标')}</span><strong>${roleTitle(a.role,nav)} · ${t(a.goal,nav)}</strong></p><div class="journey-activity-comparison">${(both?['current','target']:[nav.comparison==='current'?'current':'target']).map(mode=>narrative(a,nav,mode,both)).join('')}</div><dl class="journey-io"><div><dt>${l(nav,'Required input','所需输入')}</dt><dd>${t(a.input,nav)}</dd></div><div><dt>${l(nav,'Expected local output','预期本项输出')}</dt><dd>${t(a.output,nav)}</dd></div><div><dt>${l(nav,'Handoff','交接')}</dt><dd>${t(a.handoff,nav)}</dd></div></dl>${both?'':`<p class="small muted">${l(nav,'Required inputs and expected outputs describe the work, not the readiness of this synthetic case. Grouped activity views share existing scenarios.','所需输入与预期输出用于描述工作，不代表本合成案件已经就绪。活动视图将相关源步骤归组，并复用现有场景。')}</p>`}</article>`;}
export function activityHtml(activity,nav){
 if(!activity)return '';
 return `<header class="modal-head journey-modal-head"><p class="eyebrow">${activity.process} · ${processTitle(activity.process,nav)} · ${l(nav,'Role activity / read only','角色活动 / 只读')}</p><h2 id="scene-title" tabindex="-1">${t(activity.title,nav)}</h2><select id="scene-locale" aria-label="${l(nav,'Activity language','活动语言')}">${[['en-AU','English (AU)'],['en-US','English (US)'],['zh-CN','简体中文']].map(([v,label])=>`<option value="${v}" ${nav.locale===v?'selected':''}>${label}</option>`).join('')}</select>${control('×','close','',`class="close" aria-label="${l(nav,'Close activity','关闭活动')}"`)}</header><div class="modal-body">${compare(nav)}${activityBody(activity,nav)}<aside class="journey-shared-context"><strong>${l(nav,'Shared synthetic case','共享合成案件')}</strong><p>${l(nav,'Entity A (Australia) requests FX forward. Entity B (Singapore) is its reported parent. Person T works at B and claims to coordinate for A; specific authority remains unknown. The detailed scenario shows the existing task, dependencies, diagrams and media.','Entity A（澳大利亚）申请外汇远期；Entity B（新加坡）为其已报告母公司。Person T 任职于 B，并声称为 A 协调；具体代表权限仍未知。详细场景展示现有任务、依赖、图示与媒体。')}</p><p>${l(nav,'Product opens under the current demo role','产品使用当前演示角色')} <strong>${roleTitle(nav.role,nav)}</strong>. ${l(nav,'This reading viewpoint grants no authority.','阅读视角不授予任何权限。')}</p><small>${activity.scene} · SRC-007</small></aside></div><footer class="modal-footer"><span class="small muted">${roleTitle(activity.role,nav)} · ${activity.process}</span><div class="controls">${control(l(nav,'Print this activity','打印本项活动'),'journey-activity-print')}${control(l(nav,'Open shared scenario → product task','打开共享场景 → 产品任务'),'journey-detail',activity.id,'class="primary"')}</div></footer>`;
}
function painRegister(nav){return `<div class="journey-pain-register">${pains.map(p=>{const mapped=activities.filter(a=>a.pains.includes(p.id));return `<article data-pain="${p.id}"><span class="trace-meta">SRC-007 · ${l(nav,'slide','页')} ${p.page} · ${l(nav,p.scope==='adjacent'?'Adjacent lifecycle':'Journey context',p.scope==='adjacent'?'相邻生命周期':'旅程情境')}</span><h3>${t(p.title,nav)}</h3><p>${t(p.description,nav)}</p>${mapped.length?`<p class="small">${[...new Set(mapped.map(a=>roleTitle(a.role,nav)))].join(' · ')}<br>${[...new Set(mapped.map(a=>a.process))].join(' · ')}</p>`:`<p class="small">${l(nav,'Downstream context; no new executable workflow is implied.','下游情境；不据此新增可执行业务流程。')}</p>`}</article>`;}).join('')}</div>`;}
export function journeyPrintHtml(nav){
 const scoped=nav.journeyPrint==='activity'?activities.find(a=>a.id===nav.journeyActivity):null;
 return `<main id="main" class="journey-print"><div class="no-print controls">${control(l(nav,'Back to view','返回原视图'),'exit-print')}${control(l(nav,'Print / Save PDF','打印 / 保存 PDF'),'print')}</div><article class="print-sheet"><h1>${l(nav,scoped?'Role activity':'Complete institutional journey',scoped?'角色活动':'完整机构业务旅程')}</h1><p>${l(nav,'Current / Target · source-aligned reading views · synthetic case · no business actions','Current / Target · 源流程阅读视图 · 合成案件 · 不执行业务操作')}</p><p class="journey-print-boundary">${l(nav,'Required inputs and expected outputs describe the work, not the readiness of this synthetic case. Grouped activity views share existing scenarios.','所需输入与预期输出用于描述工作，不代表本合成案件已经就绪。活动视图将相关源步骤归组，并复用现有场景。')}</p>${scoped?`<h2>${t(scoped.title,nav)}</h2>${activityBody(scoped,nav,true)}`:journeyRoles.map(role=>`<section class="journey-print-role"><h2>${t(role.title,nav)}</h2>${activitiesFor({role:role.id}).map(a=>`<section class="journey-print-activity"><h3>${a.process} · ${t(a.title,nav)} <small class="trace-meta">${a.scene}</small></h3>${activityBody(a,nav,true)}</section>`).join('')}</section>`).join('')}${scoped?'':`<section><h2>${l(nav,'All source pain points','全部源痛点')}</h2><p>${l(nav,'Qualitative source claims, not measured bank outcomes. Monitoring, offboarding and reporting are adjacent context.','源材料中的定性主张，不是银行实测结果。持续监控、退出与报告属于相邻情境。')}</p>${painRegister(nav)}</section>`}</article></main>`;
}
