import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {initialNavigation,navigate} from '../navigation.mjs';
const om=await import('../operating-model-state.mjs').catch(()=>null);
const fixtures=JSON.parse(readFileSync(new URL('../../04_operating_model/batch-c/screening-snapshots.json',import.meta.url))).snapshots;
test('role downgrade in Product is retained on every Operating Model return destination and original-source return',()=>{for(const destination of ['operating-model','scenario','journey']){let n=navigate(initialNavigation(),{type:'OPERATING_OPEN'});n=navigate(n,{type:'PRODUCT',step:'screening'});n=navigate(n,{type:'ROLE',value:'ROLE-RM'});n=navigate(n,{type:'RETURN',destination});assert.equal(n.role,'ROLE-RM');if(destination==='operating-model'){n=navigate(n,{type:'OPERATING_BACK'});assert.equal(n.role,'ROLE-RM');}}});
test('Previous or Next selecting a valid action clears an obsolete-link warning',()=>{assert.ok(om);const s=om.operatingState({action:'D4A-MATCH-OLD'});assert.equal(om.operatingAction(s,'action-next').staleAction,null);});
test('collaboration pauses at both human boundaries and ordinary navigation cannot reach authored outcome',()=>{assert.ok(om,'Operating reducer available');let s=om.operatingState();assert.equal(s.playing,false);s=om.operatingAction(s,'play');s=om.operatingAction(s,'next');s=om.operatingAction(s,'next');assert.equal(s.frame,3);assert.equal(s.playing,false);s=om.operatingAction(s,'next');assert.equal(s.frame,4);for(const intent of ['next','play','next'])s=om.operatingAction(s,intent);assert.equal(s.frame,4);assert.equal(s.playing,false);s=om.operatingAction(s,'preview-outcome');assert.equal(s.frame,5);assert.equal(s.authoredOutcome,true);assert.equal(om.operatingAction(s,'reference').playing,false);});
test('deep links retain obsolete action reference without silently selecting a similar action',()=>{assert.ok(om);const s=om.operatingState({action:'D4A-MATCH-OLD',view:'invalid'});assert.equal(s.action,null);assert.equal(s.staleAction,'D4A-MATCH-OLD');assert.equal(s.view,'overview');assert.equal(om.operatingState({scene:'unknown'}).scene,'SCN-MATCH');});
test('prototype target requires actual same Person T finding on active latest C run',()=>{assert.ok(om);assert.equal(om.operatingTarget(fixtures['C-entry']).available,false);assert.equal(om.operatingTarget(fixtures['C-pending']).available,false);const c=fixtures['C-result'],target=om.operatingTarget(c);assert.equal(target.available,true);assert.equal(target.findingRef,'DEMO-CTT-001/finding/person-t-c01');assert.equal(target.caseRef,c.case.id);const wrong=structuredClone(c);wrong.screeningFindings=wrong.screeningFindings.filter(x=>!x.source_refs.includes('SRC-016'));assert.equal(om.operatingTarget(wrong).available,false);const stale=structuredClone(c);stale.scopes[0].revision++;assert.equal(om.operatingTarget(stale).available,false);const d=structuredClone(c);d.demoConfig.batchD={version:'D2-D-Final-1.0'};assert.equal(om.operatingTarget(d).available,false);});
test('Operating origin and product return preserve Current, semantic position and newest locale without case data',()=>{
 const origin={...initialNavigation(),scenario:'SCN-MATCH',modal:true,comparison:'current',transformation:{compare:true,selectedChange:'D3-MATCH-05',openChanges:['D3-MATCH-05']}};
 let n=navigate(origin,{type:'OPERATING_OPEN',action:'D4A-MATCH-05-02',view:'execution-choice'});assert.equal(n.studioPage,'operating-model');assert.equal(n.modal,false);
 n=navigate(n,{type:'PRODUCT',step:'screening'});n=navigate(n,{type:'LOCALE',value:'zh-CN'});n=navigate(n,{type:'RETURN',destination:'operating-model'});assert.equal(n.operating.action,'D4A-MATCH-05-02');assert.equal(n.locale,'zh-CN');assert.equal(n.operating.playing,false);
 n=navigate(n,{type:'OPERATING_BACK'});assert.equal(n.comparison,'current');assert.equal(n.modal,true);assert.equal(n.transformation.selectedChange,'D3-MATCH-05');assert.equal(n.locale,'zh-CN');assert.equal(JSON.stringify(n).includes('screeningFindings'),false);
});
