import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {screeningAction,screeningProjection,C_IDS} from '../screening-engine.mjs';import {collaborationAction} from '../collaboration-engine.mjs';import {productProgress} from '../product-experience/projection.mjs';
function prepared(){
 let s=JSON.parse(readFileSync(new URL('../qa/operating-model/host/c-live-session.json',import.meta.url))).data;
 const c=(type,at,extra={})=>{s=screeningAction(s,{type,role:'ROLE-KYCOPS',key:`D5-${type}-${s.case.revision}`,expectedRevision:s.case.revision,expectedScopeRevision:s.scopes[0].revision,expectedInputRevisions:screeningProjection(s,{role:'ROLE-KYCOPS'}).inputRevisions,rationale:'Current identity information remains insufficient; no exclusion.',at,...extra});};
 const b=(type,now,extra={})=>{s=collaborationAction(s,{type,role:'ROLE-KYCOPS',key:`D5-${type}-${s.case.revision}`,requestId:C_IDS.request,itemId:C_IDS.identityItem,expectedRevision:s.case.revision,expectedRequestRevision:s.informationRequests.find(x=>x.id===C_IDS.request).revision,expectedItemRevision:s.requestItems.find(x=>x.id===C_IDS.identityItem).revision,rationale:'Current scoped identity request only',now,...extra});};
 c('request_identity','2026-09-08T09:00:00Z',{gap:'Birth date remains unknown'});b('save_request','2026-09-08T09:05:00Z',{text:s.demoConfig.batchC.collaboration.client_text});b('review_request','2026-09-08T09:10:00Z');b('dispatch','2026-09-08T09:15:00Z',{channel:'identity_secure_task'});
 b('start_session','2026-09-08T09:30:00Z',{role:'ROLE-CLIENT',userId:C_IDS.personT,sessionId:'D5-RESUME-SESSION',reference:'CTT-DEMO-ID-C01'});b('submit_response','2026-09-08T10:00:00Z',{role:'ROLE-CLIENT',userId:C_IDS.personT,sessionId:'D5-RESUME-SESSION',text:'Synthetic identity response, exact DOB still unknown'});
 const evidenceId=s.evidence.at(-1).id;b('release_artifact','2026-09-08T10:10:00Z',{reference:evidenceId,intakeStatus:'released'});b('link_evidence','2026-09-08T10:15:00Z',{reference:evidenceId});c('assess_identity','2026-09-08T11:00:00Z',{evidenceId,sufficiency:'insufficient'});
 return {data:s,evidenceId,branchId:s.workItems.find(x=>x.branch_type==='information_gap').id};
}
test('D5 current projection preserves native Resume eligibility after receipt/link/use assessment',()=>{
 const {data,evidenceId,branchId}=prepared(),native=screeningProjection(data,{role:'ROLE-KYCOPS',evidenceId,branchId});assert.equal(native.actions.resume_branch.allowed,true);
 const d5=productProgress(data,{role:'ROLE-KYCOPS',asOf:'2026-09-08T11:30:00Z'});assert.equal(d5.projection.actions.resume_branch.allowed,true);assert.deepEqual(d5.projection.actions.resume_branch,native.actions.resume_branch);
 assert.ok(d5.events.some(e=>e.type==='notification_dispatched'));assert.ok(d5.events.some(e=>e.type==='screening_identity_evidence_received'));assert.ok(d5.events.some(e=>e.type==='screening_evidence_use_assessed'));assert.equal(d5.steps[2].waiting_on_refs.includes('purpose_assessment'),false);
});
test('D5 resumed branch is in progress with no contradictory completion or active wait',()=>{
 const {data,branchId}=prepared(),s=screeningAction(data,{type:'resume_branch',role:'ROLE-KYCOPS',branchId,key:'D5-RESUME',expectedRevision:data.case.revision,expectedScopeRevision:data.scopes[0].revision,expectedInputRevisions:screeningProjection(data,{role:'ROLE-KYCOPS'}).inputRevisions,rationale:'Resume after current insufficient purpose assessment, no clearance.',at:'2026-09-08T12:00:00Z'});
 const x=productProgress(s,{role:'ROLE-KYCOPS',asOf:'2026-09-08T14:00:00Z'}),gap=x.steps[2];assert.equal(gap.state,'in_progress');assert.equal(gap.timing.waiting_since,null);assert.equal(gap.timing.completed_at,null);assert.equal(gap.timing.resumed_at,'2026-09-08T12:00:00Z');assert.deepEqual(gap.waiting_on_refs,[]);assert.equal(x.steps[4].state,'in_progress');assert.equal(x.clearance,'not_ready');
});
test('D5 changed or quarantined intake invalidates the old assessment before suggesting Resume',()=>{
 const {data,evidenceId,branchId}=prepared(),s=collaborationAction(data,{type:'release_artifact',role:'ROLE-KYCOPS',requestId:C_IDS.request,itemId:C_IDS.identityItem,reference:evidenceId,intakeStatus:'quarantined',expectedRevision:data.case.revision,expectedRequestRevision:data.informationRequests.find(r=>r.id===C_IDS.request).revision,expectedItemRevision:data.requestItems.find(i=>i.id===C_IDS.identityItem).revision,key:'D5-INTAKE-RECHECK',rationale:'Recheck intake against the current artifact revision',now:'2026-09-08T11:30:00Z'});
 const native=screeningProjection(s,{role:'ROLE-KYCOPS',evidenceId,branchId});assert.equal(native.actions.resume_branch.allowed,false);assert.ok(native.actions.resume_branch.reason_codes.includes('IDENTITY_ASSESSMENT_REQUIRED'));
 const gap=productProgress(s,{role:'ROLE-KYCOPS',asOf:'2026-09-08T12:00:00Z'}).steps[2];assert.equal(gap.waiting_on_refs.includes('resume_current_review'),false);assert.match(gap.next_action.label,/Recheck intake/);assert.equal(gap.next_action.allowed,false);assert.equal(gap.semantics.freshness,'stale');
});
test('D5 later quarantine after a real resume does not retain a current-assessment continuation message',()=>{
 const {data,evidenceId,branchId}=prepared();let s=screeningAction(data,{type:'resume_branch',role:'ROLE-KYCOPS',branchId,key:'D5-RESUME-BEFORE-RECHECK',expectedRevision:data.case.revision,expectedScopeRevision:data.scopes[0].revision,expectedInputRevisions:screeningProjection(data,{role:'ROLE-KYCOPS'}).inputRevisions,rationale:'Resume against the current assessed input',at:'2026-09-08T12:00:00Z'});
 s=collaborationAction(s,{type:'release_artifact',role:'ROLE-KYCOPS',requestId:C_IDS.request,itemId:C_IDS.identityItem,reference:evidenceId,intakeStatus:'quarantined',expectedRevision:s.case.revision,expectedRequestRevision:s.informationRequests.find(r=>r.id===C_IDS.request).revision,expectedItemRevision:s.requestItems.find(i=>i.id===C_IDS.identityItem).revision,key:'D5-POST-RESUME-RECHECK',rationale:'Recheck intake after resumed work',now:'2026-09-08T12:30:00Z'});
 const gap=productProgress(s,{role:'ROLE-KYCOPS',asOf:'2026-09-08T13:00:00Z'}).steps[2];assert.match(gap.next_action.label,/Recheck intake/);assert.doesNotMatch(gap.next_action.label,/current purpose assessment/);assert.equal(gap.next_action.allowed,false);assert.equal(gap.semantics.freshness,'stale');assert.equal(gap.timing.resumed_at,'2026-09-08T12:00:00Z');assert.equal(gap.timing.completed_at,null);
});
