'use strict';
// Workshop narration is a reading layer. It never calls the case engines.
const chapters = [
 {id:'initiate',refs:['SCOPE','ENTITY'],zh:{name:'发起',title:'先明确：谁在申请，谁能代表谁？',roles:'客户经理 · KYC 运营 · 客户',now:'关系、产品和联系人信息分散。母公司关系、任职关系与代表权限容易混在一起。',future:'围绕同一申请整理主体、产品和联系人，把缺失信息及授权问题明确列出。',human:'确认申请主体、业务范围和具体授权。',output:'一份共同使用的申请背景与待确认事项。',question:'Person T 可以为 A 做什么？',example:'A（澳大利亚）申请外汇远期；T 任职于申报母公司 B（新加坡），声称为 A 协调资料。',boundary:'任职于 B，不等于已获准代表 A 签署或交易。'},en:{name:'Initiate',title:'Who is applying, and who can act for whom?',roles:'Relationship Manager · KYC Operations · Client',now:'Relationship, product and contact information is fragmented. Employment, parent relationships and authority can be confused.',future:'Bring the entity, product and contacts into one request. Make missing facts and authority questions visible.',human:'Confirm the entity, scope and specific authority.',output:'One shared request context and a list of open questions.',question:'What can Person T do for A?',example:'A in Australia requests FX forwards. T works for the reported parent B in Singapore and says they coordinate for A.',boundary:'Employment by B does not establish authority to sign or trade for A.'}},
 {id:'determine',refs:['REQUIREMENTS','SOURCE','GAP','VALIDATE'],zh:{name:'确定要求',title:'先复用已有资料，再问真正缺少的内容',roles:'KYC 运营 · 客户经理 · 客户',now:'不同团队反复要资料。收到了文件，也未必知道它是否足以支持当前用途。',future:'汇总适用要求，先找可复用证据，再发出具体补件请求；按用途核验证据。',human:'确认要求是否适用，判断材料对该用途是否充分。',output:'带依据的要求清单、证据评估与剩余缺口。',question:'这一次，究竟还缺什么？',example:'验证 T 的身份，与证明 T 有权代表 A，是两个不同问题；同一份资料不自动同时解决两者。',boundary:'提交资料不等于复核通过；未知要求不能当作不适用。'},en:{name:'Determine',title:'Reuse available evidence, then ask for the missing facts',roles:'KYC Operations · Relationship Manager · Client',now:'Teams repeatedly ask for documents. Receipt alone does not tell them whether evidence is sufficient for its purpose.',future:'Consolidate requirements, find reusable evidence and send precise gap requests. Assess evidence for each purpose.',human:'Confirm applicability and assess evidence sufficiency.',output:'Requirements with a basis, evidence assessments and remaining gaps.',question:'What exactly is still missing?',example:'Establishing T’s identity and establishing authority to act for A are separate questions. One document does not automatically settle both.',boundary:'A submission is not acceptance. Unknown applicability is not “not required”.'}},
 {id:'assess',refs:['POPULATION','MATCH','EDD'],zh:{name:'评估',title:'把疑似命中变成一个有依据的判断',roles:'KYC 运营 · 风险 / 合规',now:'筛查结果与客户资料分散。事实不全时，复核人员需要反复追问和查找。',future:'把一致、冲突和未知事实放在一起。需要补件时，带着明确问题回到原复核任务。',human:'裁定重要命中；判断强化尽调是否适用并完成必要审批。',output:'有理由的筛查结论、未决问题及适用条件。',question:'哪些事实足以支持这个判断？',example:'T 出现在疑似筛查命中中。对比身份事实，必要时补件并复核；不要仅因姓名相似就作出结论。',boundary:'解决一个筛查命中，不代表整宗案件获准交易。'},en:{name:'Assess',title:'Turn a possible match into an evidenced decision',roles:'KYC Operations · Risk / Compliance',now:'Screening results and client evidence are separated. Missing facts lead to repeated searches and follow-ups.',future:'Compare matching, conflicting and unknown facts together. Return any requested evidence to the same review.',human:'Adjudicate material findings and decide on EDD and required approvals.',output:'A reasoned screening outcome, open questions and applicable conditions.',question:'Which facts support the decision?',example:'T appears in a possible screening match. Compare identifying facts, request evidence if needed, then review again.',boundary:'Resolving one match does not clear the whole relationship to trade.'}},
 {id:'resolve',refs:['CONFLICTS','CREDIT','LEGAL','QA'],zh:{name:'解决问题',title:'看清依赖，让可以推进的工作先推进',roles:'利益冲突控制 · 信贷 · 法务 · QA',now:'各团队靠邮件追进度，难以分清“可以继续做”和“必须等别人”的工作。',future:'让并行工作各自推进，明确依赖的输入与版本。质量复核只针对具体缺口要求整改。',human:'保留利益冲突、信贷、法务判断和质量签核。',output:'各条线的结论、条件、当前依赖及下一责任方。',question:'谁在等谁？哪些工作不必等？',example:'利益冲突检查从受理启动。信贷与法务并行准备，法务签署前要核对当前信贷条款。',boundary:'信贷条件变化后，相关法务或质量结论可能需要重新检查。'},en:{name:'Resolve',title:'Make dependencies clear so parallel work can move',roles:'Conflicts · Credit · Legal · QA',now:'Teams chase progress by email and cannot easily distinguish work that can continue from work waiting on an input.',future:'Progress each workstream on its available inputs. Name dependencies and versions, and remediate precise QA gaps.',human:'Retain Conflicts, Credit, Legal decisions and QA sign-off.',output:'Workstream outcomes, conditions, dependencies and the next responsible party.',question:'Who is waiting for whom? What can continue?',example:'Conflicts starts at intake. Credit and Legal prepare in parallel; Legal checks current Credit terms before execution.',boundary:'Changed Credit conditions can require Legal or QA to review dependent work again.'}},
 {id:'clear',refs:['READINESS','PUBLISH'],zh:{name:'确认就绪',title:'说清楚还差什么，再记录最终结果',roles:'案件经理 · 各审批角色 · 客户经理',now:'任务看起来都做过了，但全案还缺哪些前提、谁能确认结果，仍需人工逐项追问。',future:'汇总所有适用前提及未决问题，区分“单项已完成”“整体已就绪”和“结果已记录”。',human:'授权人员确认最终结果，由客户经理传达允许的下一步。',output:'限定主体与产品范围的就绪判断、记录及通知。',question:'还有什么阻止 A 进入下一步？',example:'即使 T 的筛查问题已解决，只要授权、协议或其他必要条件未满足，仍不能把 A 标成获准交易。',boundary:'本案例保留未决项；讲解到最后一页不会自动变成审批通过。'},en:{name:'Clear',title:'Explain what is still open before recording the outcome',roles:'Case Manager · Authorized reviewers · Relationship Manager',now:'Tasks appear complete, yet people still need to chase the whole-case prerequisites and decision authority.',future:'Bring applicable prerequisites and open questions together. Separate local completion, overall readiness and a recorded outcome.',human:'Authorized people confirm the outcome; the RM communicates permitted next steps.',output:'A readiness assessment, record and notification for the named entity and product scope.',question:'What still stops A from moving forward?',example:'Even if T’s screening issue is resolved, open authority, agreements or other required conditions can still block clearance.',boundary:'The case retains unresolved items. Reaching the final chapter does not approve it.'}}
];
const sceneNames = {SCOPE:['业务范围','Relationship scope'],ENTITY:['主体与授权','Entity and authority'],REQUIREMENTS:['适用要求','Applicable requirements'],SOURCE:['证据复用','Evidence reuse'],GAP:['精准补件','Specific gaps'],VALIDATE:['按用途核验','Evidence assessment'],POPULATION:['筛查对象','Screening population'],MATCH:['命中复核','Match review'],EDD:['强化尽调','Enhanced due diligence'],CONFLICTS:['利益冲突','Conflicts'],CREDIT:['信贷条件','Credit conditions'],LEGAL:['法务协议','Legal agreements'],QA:['质量复核','Quality assurance'],READINESS:['整体就绪','Readiness'],PUBLISH:['结果记录','Record outcome']};
const STORE='ctt-workshop-guide-v1';
let locale=new URLSearchParams(location.search).get('locale')==='en-US'?'en-US':'zh-CN';
let selected=0,notes={},saved=true;
try { const value=JSON.parse(localStorage.getItem(STORE)); if(value&&typeof value.notes==='object'&&value.notes)notes=value.notes; } catch { saved=false; }
try {const index=Number(sessionStorage.getItem(STORE+'-chapter'));if(Number.isInteger(index)&&index>=0&&index<5)selected=index;}catch{}
const requestedChapter=new URLSearchParams(location.search).get('chapter');
if(requestedChapter!==null){const i=Number(requestedChapter);selected=Number.isInteger(i)?Math.max(0,Math.min(4,i)):0;}
const root=document.querySelector('#guide');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tr=(zh,en)=>locale==='zh-CN'?zh:en;
const content=chapter=>chapter[locale==='zh-CN'?'zh':'en'];
const labels=()=>[tr('共识 / 建议','Agreement / proposal'),tr('待确认的问题','Open question'),tr('跟进人 / 下一步 / 时间','Owner / next step / date')];
const fields=['agreement','question','owner'];
const post=data=>{if(parent!==window&&location.origin!=='null')parent.postMessage({channel:'ctt-approved-map',...data},location.origin);};
function reportHeight(){post({type:'height',height:Math.ceil(document.body.getBoundingClientRect().height)+16});}
function summaryHtml(){return chapters.map((chapter,i)=>`<article class="summary-item"><h3>${i+1}. ${esc(content(chapter).name)}</h3><dl>${fields.map((key,k)=>`<dt>${labels()[k]}</dt><dd>${esc(typeof notes[chapter.id]?.[key]==='string'?notes[chapter.id][key]:tr('尚未记录','Not recorded'))||tr('尚未记录','Not recorded')}</dd>`).join('')}</dl></article>`).join('');}
function render(focus=false){
 const chapter=chapters[selected],c=content(chapter),n=notes[chapter.id]||{};
 const notesOpen=root.querySelector('#notes')?.open||false,summaryOpen=root.querySelector('#summary')?.open||false;
 document.documentElement.lang=locale;
 root.innerHTML=`<header class="heading"><div><span class="eyebrow">CLEAR TO TRADE / WORKSHOP</span><h1>${tr('从客户申请，到交易就绪','From request to readiness')}</h1><p>${tr('沿着一个案例，讨论五个关键问题。','One case. Five questions to discuss together.')}</p></div><small>${tr('讲解与讨论 · 建议 75 分钟','Walkthrough & discussion · Suggested 75 minutes')}</small></header>
 <section class="case" aria-label="${tr('合成案例背景','Synthetic case context')}"><strong>${tr('同一个案例','One case')}</strong><p>${tr('Entity A（澳大利亚）申请外汇远期。Entity B（新加坡）为申报母公司；Person T 任职于 B，声称为 A 协调资料，具体授权待确认。','Entity A (Australia) requests FX forwards. Entity B (Singapore) is its reported parent. Person T works for B and says they coordinate for A; specific authority remains unconfirmed.')}</p></section>
 <nav class="steps" aria-label="${tr('五阶段讲解导航','Five workshop chapters')}">${chapters.map((x,i)=>`<button data-step="${i}" aria-current="${selected===i?'step':'false'}"><span>0${i+1}</span><b>${esc(content(x).name)}</b></button>`).join('')}</nav>
 <article class="stage" aria-labelledby="chapter-title"><header class="stage-head"><div><span class="eyebrow">${tr('讨论','DISCUSSION')} 0${selected+1} / 05</span><h2 id="chapter-title" tabindex="-1">${esc(c.title)}</h2></div><p class="roles">${esc(c.roles)}</p></header><div class="stage-grid"><div class="story"><div class="comparison"><section><h3>${tr('现在的难点','Today’s difficulty')}</h3><p>${esc(c.now)}</p></section><section class="future"><h3>${tr('希望怎样改善','Proposed improvement')}</h3><p>${esc(c.future)}</p></section></div><dl class="outcomes"><div><dt>${tr('人的判断','Human judgment')}</dt><dd>${esc(c.human)}</dd></div><div><dt>${tr('这一阶段的产出','Stage output')}</dt><dd>${esc(c.output)}</dd></div></dl></div><aside class="discussion"><span class="eyebrow">${tr('请大家讨论','DISCUSS TOGETHER')}</span><h3>${esc(c.question)}</h3><p>${esc(c.example)}</p><small>${esc(c.boundary)}</small></aside></div><div class="parallel"><strong>${tr('贯穿旅程的并行工作','Parallel throughout')}</strong><span>${tr('利益冲突从受理启动；信贷与法务按可用输入推进；最终就绪需要汇总所有适用结论。','Conflicts starts at intake. Credit and Legal progress on available inputs. Readiness brings all applicable outcomes together.')}</span></div></article>
 <div class="bottom"><p>${tr('阶段是讲解顺序，不代表审批进度。','Chapters guide the discussion, not approval progress.')}</p><div><button data-step="${selected-1}" ${selected===0?'disabled':''}>${tr('上一步','Previous')}</button><button class="primary" ${selected===4?'data-summary':'data-step="'+(selected+1)+'"'}>${selected===4?tr('汇总讨论','Review discussion'):tr('下一阶段','Next chapter')}</button></div></div>
 <section class="secondary" aria-label="${tr('讨论记录与参考','Discussion notes and references')}"><details id="notes" ${notesOpen?'open':''}><summary>${tr('记录本阶段讨论','Record this discussion')}<small>${tr('共识、待确认、下一步','Agreement, open question, next step')}</small></summary><div class="notes">${fields.map((key,i)=>`<label for="note-${key}">${labels()[i]}${i===2?`<input id="note-${key}" data-note="${key}" maxlength="2000" value="${esc(typeof n[key]==='string'?n[key]:'')}">`:`<textarea id="note-${key}" data-note="${key}" maxlength="5000" rows="3">${esc(typeof n[key]==='string'?n[key]:'')}</textarea>`}</label>`).join('')}</div><p class="save-state" role="status">${saveMessage()}</p></details>
 <details><summary>${tr('需要时再看：本阶段的详细场景','Optional: detailed scenarios for this chapter')}</summary><div class="reference-links">${chapter.refs.map(id=>`<button data-scene="SCN-${id}">${esc(sceneNames[id][locale==='zh-CN'?0:1])}</button>`).join('')}</div><p class="reference-copy">${tr('这些入口打开完整原型中的详细流程。主持人可按问题选择，不必逐项演示。','These links open detailed flows in the full prototype. Use only those needed for the discussion.')}</p></details>
 <details id="summary" ${summaryOpen?'open':''}><summary>${tr('五阶段讨论汇总','All five discussions')}<small>${tr('会后导出，形成后续行动','Export for follow-up')}</small></summary><div class="summary-grid">${summaryHtml()}</div><div class="summary-tools"><button data-export>${tr('导出讨论记录 .md','Export notes .md')}</button><button data-print>${tr('打印讨论汇总','Print discussion notes')}</button></div></details></section>
 <footer class="footer"><span>${tr('合成案例 · 需求与改善方向供 workshop 验证','Synthetic case · Requirements and improvements to validate in the workshop')}</span><a href="../../08_inspire/01_原型需求说明.md" target="_blank" rel="noopener">${tr('阅读需求说明','Read requirements (Chinese)')}</a></footer>`;
 root.querySelectorAll('details').forEach(el=>el.addEventListener('toggle',reportHeight));
 if(focus)root.querySelector('#chapter-title').focus({preventScroll:true});
 reportHeight();
}
function saveMessage(){return saved?tr('仅保存在当前浏览器；会后请导出讨论记录。','Saved in this browser only; export notes after the session.'):tr('浏览器存储不可用；记录暂存在本页，请在关闭前导出。','Browser storage unavailable; notes are in this page only. Export before closing.');}
function exportText(){return '# Clear to Trade · Workshop\n\n'+tr('以下是讨论记录，不是审批结果。','Discussion notes, not approval outcomes.')+'\n\n'+chapters.map((ch,i)=>'## '+(i+1)+'. '+content(ch).name+'\n\n'+fields.map((key,k)=>'### '+labels()[k]+'\n\n'+((typeof notes[ch.id]?.[key]==='string'?notes[ch.id][key]:'')||tr('尚未记录','Not recorded'))+'\n').join('\n')).join('\n');}
root.addEventListener('click',event=>{
 const step=event.target.closest('[data-step]');
 if(step&&!step.disabled){const i=Number(step.dataset.step);if(!Number.isInteger(i)||i<0||i>=chapters.length)return;selected=i;try{sessionStorage.setItem(STORE+'-chapter',String(i));}catch{}render(true);post({type:'chapter',chapter:selected});document.querySelector('#status').textContent=tr('已切换至','Now showing ')+content(chapters[i]).name;return;}
 if(event.target.closest('[data-summary]')){const el=root.querySelector('#summary');el.open=true;el.querySelector('summary').focus();el.scrollIntoView({block:'start'});}
 const scene=event.target.closest('[data-scene]');if(scene){if(parent!==window)post({type:'select',kind:'scene',id:scene.dataset.scene});else location.href='../index.html?studio=fulljourney&locale='+locale+'&scenario='+encodeURIComponent(scene.dataset.scene);}
 if(event.target.closest('[data-export]')){const blob=new Blob(['\ufeff'+exportText()],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Clear-to-Trade-workshop-'+new Date().toISOString().slice(0,10)+'.md';document.body.append(a);a.click();a.remove();document.querySelector('#status').textContent=tr('讨论记录已生成，正在下载。','Discussion notes generated; download requested.');setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(event.target.closest('[data-print]')){root.querySelector('#summary').open=true;window.print();}
});
root.addEventListener('input',event=>{const key=event.target.dataset.note;if(!fields.includes(key))return;const id=chapters[selected].id;notes[id]={...notes[id],[key]:event.target.value};try{localStorage.setItem(STORE,JSON.stringify({notes}));saved=true;}catch{saved=false;}root.querySelector('.save-state').textContent=saveMessage();root.querySelector('.summary-grid').innerHTML=summaryHtml();reportHeight();});
window.addEventListener('message',event=>{if(event.source!==parent||event.origin!==location.origin)return;if(event.data?.channel==='ctt-locale'&&['zh-CN','en-US'].includes(event.data.locale)){locale=event.data.locale;render();}});
window.addEventListener('beforeprint',()=>{root.querySelector('#summary').open=true;});
new ResizeObserver(reportHeight).observe(root);
render();post({type:'ready'});post({type:'chapter',chapter:selected});
if(parent!==window&&location.origin!=='null')parent.postMessage({channel:'ctt-locale-request'},location.origin);
