export const tr=(locale,en,zh)=>locale==='zh-CN'?zh:locale==='en-US'?en.replaceAll('authorised','authorized').replaceAll('Authorised','Authorized').replaceAll('judgement','judgment').replaceAll('normalisation','normalization').replaceAll('Organise','Organize').replaceAll('organise','organize'):en;
export const groupNames=[['Bind query context','绑定查询背景'],['Compare identifiers','比较识别信息'],['Resolve the evidence gap','组织补证'],['Prepare the review pack','准备复核包'],['Human review','人工判断'],['Record the local outcome','记录局部结果']];
export const groupNotes=[['Rule binds the subject, query and source versions. It adds no query result.','规则绑定主体、查询和来源版本，不新增查询结果。'],['Rule preserves precision and unknowns; Skill prepares cited differences without an identity verdict.','规则保留精度与未知；能力准备有出处的差异，不判断是否同一人。'],['A conditional candidate may plan evidence gathering. Skill drafts the request; a human confirms access and disclosure. Skip this branch if no gap exists.','条件性候选可规划补证；能力起草请求，人确认访问与披露。没有缺口时无需此分支。'],['Skill prepares facts and unknowns; Rule checks access, citations and current versions. Preparation is not a decision.','能力编制事实与未知；规则核对访问、引用和当前版本。准备不是判断。'],['People retain materiality and disposition. Rule applies a scoped hold. Independent approval applies only where configured.','人保留重大性和处置判断；规则应用限定暂停。仅在配置要求时独立批准。'],['Rule records an authorised result, recalculates affected coverage and projects remaining conditions. The whole case stays open.','规则记录有权结果、重算受影响覆盖并投影剩余条件。全案仍未闭合。']];
const titles=['Bind the finding, subject snapshot, query scope and source version','Check record consistency and flag duplicate or related candidates','Preserve date precision, multiple values, original script and missing values','Prepare a cited matrix of similarities, differences and incomparable values','Choose the next permitted evidence source and stopping conditions','Turn remaining identity facts into a limited request draft','Confirm recipients, disclosure and access for personal evidence','Prepare cited facts, unknowns, contradictions and permitted actions','Check pack citations, access, current versions and unsupported conclusions','Prepare materiality facts and unresolved contradictions','Judge ambiguous or material matters and the need for escalation','Apply a hold to specific actions using explicit decisions and rules','Choose a supported local disposition or keep the finding unresolved','Obtain independent authority only where the configuration requires it','Validate current versions and authority, then record the local outcome','Calculate the limited finding and coverage impact of a disposition','Show remaining ownership, EDD, Legal and other conditions'];
const ids=['01-01','01-02','02-01','02-02','03-01','03-02','03-03','04-01','04-02','05-01','05-02','05-03','06-01','06-02','06-03','07-01','07-02'];
export const actionTitle=(a,l)=>tr(l,titles[ids.indexOf(a.action_id.replace('D4A-MATCH-',''))]||a.action_id,a.label_zh);
const why={record:'Writing and version checks have fixed inputs and outputs; a model does not need to choose the next step.',rule:'Approved conditions, fields and current versions determine this result. Missing rules require clarification; a model cannot invent them.',compare:'Comparison and synthesis need context, but a bounded comparison Skill can prepare the result without a professional conclusion.',adaptive:'Returned evidence may change the next permitted source or Skill. Only this limited evidence planning is an Agent candidate.',pack:'A cited preparation task has a clear deliverable. A pack is not approval; use a Skill for fixed inputs.',authority:'Formal authority belongs to the responsible person. Automated checks and recording cannot grant that authority to a model.',judgment:'Substantive judgement and uncertainty require an appropriately qualified, accountable person. Complex context does not authorise autonomous decisions.',projection:'A projection follows actual object states and permissions. A fixed query is appropriate for presenting the result.'};
const opportunities=['Record services preserve the original result and investigation subject.','Deterministic normalisation and semantic comparison prepare reviewable differences only.','Limited adaptive evidence planning may help; workflow retains request sending and authorisation.','Use a Skill for the fixed pack; bounded planning is relevant only to unknown evidence paths.','Give people the context needed for judgement; the product retains their final responsibility.','Separate human judgement from product validation and recording, preserving valid inputs.','Rules update only the affected scope and explain blockers to the appropriate roles.'];
const parentEn=[
 ['Operations adjudicates screening hits.','Bind immutable subject, run and provider records, preparing comparison context. Do not split aliases into people or silently delete duplicates.','A finding may become detached from its original query inputs or subject version.'],
 ['People review relevant client and hit information.','Build name and birth-date comparisons from current claims, retaining multiple values, precision, unknowns and each original source.','Missing or differently precise attributes may be misread as contradictory.'],
 ['The Current client lane already supports screening clarification.','Reuse the existing collaboration flow to create a finding-specific identity request item or revision. Use permitted existing sources before requesting more.','Ambiguous findings may lead to generic or repeated information requests.'],
 ['Operations adjudicates hits; the current preparation burden has not been quantified.','Organise evidence, differences, unknowns and related requests. Cite content and keep AI proposals separate from known facts.','Reviewers may have to reconstruct the evidence, finding context and unresolved items.'],
 ['Financial Crime, Risk and Compliance assess risk and materiality.','Prepare risk context and route ambiguous or material findings to the responsible person, preserving action permissions and hold scopes.','Necessary retained control. No pain point is manufactured for professional risk judgement.'],
 ['Financial Crime determines the screening outcome.','Record the finding disposition, rationale and reviewed evidence / scope versions. Keep additional approval separate where required.','Necessary retained control. Support authorised recording without cancelling approval.'],
 ['The outcome informs subsequent clearance-prerequisite checks.','Update linked finding and coverage only, with an explainable snapshot. Ownership population, EDD, Legal and Credit uncertainties remain.','Closing one finding may be mistaken for whole-case readiness.']];
export function parentContext(a,l){const en=parentEn[Number(a.parent_change_id.slice(-2))-1],p=a.parent;return {current:tr(l,en[0],p.source_change.current_work),target:tr(l,en[1],p.source_change.after_proposal),pain:tr(l,en[2],p.pain_hypothesis||'保留的必要控制，不强行建立痛点。'),opportunity:tr(l,opportunities[Number(a.parent_change_id.slice(-2))-1],p.opportunity)};}
export const recommendation=(a,l)=>tr(l,({HUMAN:'Human + prepared evidence',SEMANTIC_SKILL:'Workflow + Semantic Skill',BOUNDED_AGENT_CANDIDATE:'Bounded Agent candidate',RULE_CODE:'Workflow + Rule / Code',DETERMINISTIC_SKILL:'Workflow + Deterministic Skill'})[a.execution]||'Needs clarification',({HUMAN:'人工判断 + 准备好的证据',SEMANTIC_SKILL:'工作流 + 语义能力',BOUNDED_AGENT_CANDIDATE:'受限 Agent 候选',RULE_CODE:'工作流 + 规则 / 代码',DETERMINISTIC_SKILL:'工作流 + 确定性能力'})[a.execution]||'需要进一步确定');
export const reason=(a,l)=>tr(l,why[a.profile]||'Source rationale unavailable; no execution recommendation can be inferred.',a.why_not_simpler);
export const relation=(a,l)=>tr(l,a.skill_relation==='supports_human_action'?'Supports the human action':a.primary_executor==='SEMANTIC_SKILL'?'Skill prepares':a.primary_executor==='BOUNDED_AGENT_CANDIDATE'?'Conditional candidate uses Skills':'Rule uses Skill contract',a.skill_relation==='supports_human_action'?'支持该人工动作':a.primary_executor==='SEMANTIC_SKILL'?'能力准备':a.primary_executor==='BOUNDED_AGENT_CANDIDATE'?'条件性候选使用能力':'规则使用能力合同');
export function scoreRationale(a,key,l){
 if(l==='zh-CN')return a.score_rationale?.[key]||'未评估';
 if(a.score_values[key]===null)return 'Not assessed; missing values are not zero.';
 const gate=a.formal_gate.formal_judgement_or_authority,op=opportunities[Number(a.parent_change_id.slice(-2))-1];
 const texts={C:`Reads ${a.reads.join(', ')}; the ${a.profile} task anchor measures context processing, not permission to decide automatically.`,O:`Output is limited to ${a.outputs.join(', ')}; ${a.profile==='adaptive'?'source and task feedback requires coordination across multiple actions.':'handoffs follow the defined workflow; cross-system calls alone do not imply an Agent.'}`,D:a.profile==='adaptive'?'Results can change the next permitted Skill or source; this remains a bounded candidate.':'Prefer predefined steps and enumerable branches. A professional can judge without thereby authorising AI to plan autonomously.',B:`Inputs, outputs and stops can be designed for “${actionTitle(a,l)}”. This does not establish bank authority or verified safety.`,V:`${op} Local value hypothesis only; no frequency, effort or financial-benefit data.`,T:gate?'Experts must assess the actual judgement and supporting materials.':'Tests can be defined against inputs, outputs, states and source conditions; performance has not been measured.',H:`Errors can affect the output and its explicit consumers; ${gate?'formal judgement or approval must remain a human responsibility.':'deterministic implementation does not reduce the business consequence; controls require separate verification.'}`};
 return tr(l,`${a.score_values[key]}/5: ${texts[key]}`,'');
}
const controls={
 '创建或修改银行政策/权限':'Create or alter bank policy or permissions',
 '覆盖历史证据或决定':'Overwrite historical evidence or decisions',
 '切换语言时修改业务地区/名单/适用性':'Change business region, lists or applicability on a language switch',
 '无依据写全案Clear-to-Trade':'Record whole-case clearance without a valid basis',
 '把缺失前置或失败回执替换为成功':'Replace missing prerequisites or failed receipts with success',
 '把产品写入权当作业务判断权':'Treat product write access as business decision authority',
 '从similarity/无结果直接排除身份或宣布全球无风险':'Exclude identity or declare global absence of risk from similarity or no results',
 '将候选/建议标为已采信事实':'Mark candidates or proposals as accepted facts',
 '记录正式专业决定或授权':'Record formal professional decisions or authorisation',
 '向未获准收件人派发内容':'Dispatch content to unapproved recipients',
 '直接写sufficiency或readiness truth':'Directly write sufficiency or readiness truth',
 '输入对象存在且来源/版本明确':'Input objects exist with explicit source and version',
 '当前操作者/工具具有相应read/action scope':'The current actor or tool has the required read and action scope',
 '没有适用禁止hold':'No applicable prohibiting hold exists',
 '必需政策/责任未知时不自动执行':'Do not execute automatically if required policy or accountability is unknown'};
export const controlText=(value,l)=>l==='zh-CN'?value:controls[value]||'Untranslated source control — clarification required';
export const stopText=l=>tr(l,'Pause the affected work if population is incomplete, a source fails, identity information is insufficient, permission is missing or materiality awaits judgement. Keep this action pending when its required inputs or permissions are absent.','群体未全、来源失败、身份资料不足、缺权限或重大性待判断时暂停受影响工作。本动作所需输入或权限欠缺则保持待处理。');
export const resumeText=l=>tr(l,'After new evidence, query results or an authorised decision arrive, reassess only affected items. Recheck read/write permissions, current versions and the original task / return anchor. Opening a task or pressing Next never authorises resumption.','新资料、查询或有权决定到达后，只重评受影响项。重新校验读写权限、当前版本、原任务和返回锚点。打开任务或点击下一步不构成恢复授权。');
export const humanRole=(a,l)=>tr(l,a.human_role_hypothesis,({'Request / access authority':'请求 / 访问授权人','Financial Crime authority':'金融犯罪有权复核人员','Authorised screening reviewer':'获授权筛查复核人员','Configured additional approver where required':'配置要求时的独立批准人','Financial Crime / authorised screening reviewer':'金融犯罪 / 获授权筛查复核人员'})[a.human_role_hypothesis]||'待指定');
export const referenceTranslations={
 'REG-DFAT-LIST':['List records can contain multiple identifiers, aliases and incomplete information.','Preserve multiple values, precision, unknowns and the original record for a purpose-specific comparison.','A single attribute difference cannot automatically exclude a match. The Australian list does not establish coverage for every jurisdiction; no real listed person is imported.'],
 'IND-WOLFSBERG':['An alert does not establish risk. Review relevant information, record disposition reasons and make screening scope and configuration explicit.','Separate Population, Run, Finding, Review, Decision and Coverage; prepare evidence for a human decision.','The guidance does not directly establish our bank permissions, thresholds, pause scopes or reuse rules.'],
 'IB-ANZ-SECURE':['The example uses a reference and an OTP to registered contact details for entry. Save and submit are separate, with contributor restrictions on some fields.','Separate official-site entry from locating a request; keep item responses, submission receipts and review states distinct.','This is an information-update example, not the complete institutional clearance journey. It does not validate this case’s security level or representative authority.'],
 'XB-FHIR-R5':['Provenance links a resource version to an activity, participants and source entities.','Link a decision record to its specific input versions, actor and generating activity.','The word agent denotes a participant, not an AI Agent. This prototype does not implement FHIR; R4 and R5 remain distinct versions.'],
 'IC-PHKL':['The internal design uses one case across roles, AI preparation, a clinician signature, and independent insurer review and clarification.','Reuse the workbench pattern, preparation/decision/submission separation and explicit downstream event links.','Internal design reference only. Production deployment and business benefits have not been verified; this is not a public implementation success story.']};
export const issueTranslations={
 'D3-ISS-06':['Judgement and recording overlap in the Agentic lane','The Target map includes judgement and sign-off wording in automated groups while also providing human judgement and approval.','Separate preparation, execution, judgement, approval and recording. Conservative demo permissions remain a proposal; bank allocation is unconfirmed.'],
 'D3-ISS-15':['Each proposal needs a qualified source','Many references are standards, guidance or internal designs, rather than deployed bank examples.','Retain the exact source locator, observation, adaptation and limits for each change. Identify our design interpretation when no direct example exists.']};
const skillZh=[
 ['范围、所需事实和获准来源 / 权限','来源响应、回执与未知 / 失败','默认只读','无权限、来源不可用或主体含糊时明确缺口，不编造结果'],
 ['已释放来源资料和提取模式','候选声明、原文位置和提取状态','仅起草候选','不支持或冲突字段保留未知，不能用常识填充'],
 ['两组带版本的声明和获准比较范围','相似 / 不同 / 无法确定 / 不可比较及证据','仅候选对照','保留缺失、部分日期、原文字体与别名，不作身份结论'],
 ['获准版本规则和当前范围内事实','必需 / 不适用 / 未知及依据','仅经命令边界产生定义的规则结果','缺规则、事实或权限时保持未知或转复核，模型不生成政策'],
 ['预期清单和来源 / 声明 / 用途引用','缺失对象、候选覆盖及来源缺口','草稿检查或确定性发现，不作正式充分性判断','缺评估不等于资料无效；空清单或加载失败不能通过'],
 ['按角色过滤的事实、未知、来源和允许动作','带来源的版本化材料包草稿或解释','仅草稿，不批准、不对外派发','排除无依据声明和资料中的指令；权限撤销时暂停'],
 ['经校验的任务意图、范围、分派目录及依赖','任务、责任路由、移交和返回锚点','仅限定工作流记录','负责人未知时保持未分派；重复意图保持同一逻辑任务'],
 ['允许披露的缺口、响应选项和收件人授权','请求草稿、版本和逐项响应','草稿与实际发送分开，发送须独立有权命令','收件人未知或理由受限时保持草稿 / 暂停，不泄露'],
 ['经校验请求、允许端点和模型外凭证上下文','不可变回执、结果和接收状态','显式查询或上传；当前仅合成适配','部分响应、超时或访问失败不等于无命中或有效证据'],
 ['完整预期清单、当前版本、决定与暂停','受影响引用、未知影响与限定就绪快照','仅派生状态，不授予业务权力','过时、未知、缺清单或循环时保持未就绪或明确报错'],
 ['有权结果 / 观察事件、预期版本与因果关系','不可变版本记录与获准投影','限定追加 / 命令，不制造批准','输入过时或无权限则拒绝写入，保留草稿和历史'],
 ['角色 / 资源 / 动作范围与已签核版本内容','允许视图、通知及逐目标发布回执','投影只读；传输独立授权','拒绝或撤销访问时排除内容；派发失败保留决定']
];
export function skillContent(skill,l){const cn=skillZh[Number(skill.id.slice(-2))-1];return {id:skill.id,name:tr(l,skill.name,skill.zh),purpose:tr(l,skill.name,skill.zh),input:tr(l,skill.reads,cn[0]),output:tr(l,skill.output,cn[1]),boundaries:tr(l,skill.side_effect,cn[2]),stops:tr(l,skill.failure,cn[3]),kind:tr(l,skill.kind,skill.id==='SK-03'?'确定性规范化 + 语义候选解释':skill.id==='SK-06'?'语义编写；获准模板模式为确定性':skill.id==='SK-02'?'语义提取':skill.id==='SK-08'?'语义草稿；批准、派发、提交入口独立':'按动作合同区分确定性与语义入口')};}
export const frameContent=[
 ['Bind the original finding','绑定原始命中','Person T and synthetic record C01 share the original query time and subject version. Identity information is incomplete. No Target-only evidence is added.','Person T 与合成记录 C01 使用原始查询时点和主体版本。身份信息仍不足，没有新增 Target 独有资料。','D4A-MATCH-01-01'],
 ['Compare, preserving unknowns','比较并保留未知','The authored comparison shows a similar name. Person T’s birth date is missing; provider years 1970 / 1971 cannot be treated as a precise contradiction.','预编制对照显示姓名相似。Person T 缺出生日期；来源中的 1970 / 1971 年不能当作精确矛盾。','D4A-MATCH-02-02'],
 ['Stop at the evidence gap','在证据缺口暂停','Identity context remains insufficient. A scoped request may be prepared, but recipients, disclosure and personal-evidence access need confirmation. Playback creates no task or hold.','身份背景仍不足。可准备限定请求，但需确认收件人、披露和个人证据访问范围。播放不创建任务或暂停记录。','D4A-MATCH-03-01'],
 ['Give the decision pack to a person','把决策包交给人','Review the original evidence, unknowns, current scope and permitted consequences. Request information, remain unresolved or refer within existing permissions. Next cannot approve.','复核原证据、未知、当前范围和允许后果。按既有权限补件、保持未决或移交。下一步不能批准。','D4A-MATCH-05-02'],
 ['Authored outcome: remains unresolved','预编制结果：保持未决','The existing C-unresolved story records an unresolved local disposition. A reviewed identity-exclusion checkpoint is unavailable. This is an authored outcome, not your decision. Recheck permission, versions and holds before any actual resumption.','既有 C-unresolved 故事记录局部未决处置。尚无经复核的身份排除检查点。这是预编制结果，不是您刚作出的决定。实际恢复前须重新核验权限、版本和暂停。','D4A-MATCH-06-01'],
 ['Local outcome, open conditions','局部结果，条件仍未闭合','Ownership and population are incomplete; EDD applicability is unknown. Legal, Credit and other applicable conditions remain independently open. This finding is not whole-case clearance.','所有权和筛查群体未完整；EDD 适用性未知。法务、信贷及其他适用条件仍独立开放。此命中不代表全案准入。','D4A-MATCH-07-02']
];
