import {operatingProjection} from './model.mjs';
import {operatingDiagram} from './diagram-manifest.mjs';
import {tr,groupNames,groupNotes,actionTitle,recommendation,reason,relation,scoreRationale,controlText,stopText,resumeText,humanRole,skillContent,frameContent,referenceTranslations,issueTranslations} from './content.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=items=>'<ul>'+items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';
const field=(label,value)=>'<p><strong>'+esc(label)+':</strong> '+esc(value)+'</p>';
function reuse(uses,t){return `<table class="om-print-reuse"><thead><tr><th>${t('Action / scene','动作 / 场景')}</th><th>${t('Relation','关系')}</th><th>${t('Inputs','输入')}</th><th>${t('Outputs','输出')}</th></tr></thead><tbody>${uses.map(x=>`<tr><td>${esc(x.action_ref)}<br>${esc(x.scene_ref)}</td><td>${x.relation==='supports'?t('Supports human','支持人工'):t('Used by execution','供执行使用')}</td><td>${esc(x.reads.join('; '))}</td><td>${esc(x.outputs.join('; '))}</td></tr>`).join('')}</tbody></table>`;}
function sample(id,t){const compare=id==='SK-03';return `<div class="om-print-sample"><h3>${t('Authored sample · synthetic','预编制样例 · 合成')}</h3><p>${t('Original C-result query / subject version. Person T name is similar to synthetic record C01. Person T birth date is missing; provider years 1970 / 1971 retain year precision. No contradictory full date is invented.','原 C-result 查询 / 主体版本。Person T 姓名与合成记录 C01 相似。Person T 缺出生日期；来源 1970 / 1971 保留年精度，不编造完整日期矛盾。')}</p><p>${compare?t('Output: name = similar; birth date, place of birth and nationality = inconclusive. Contract vocabulary includes not_comparable. A differing field does not exclude identity.','输出：姓名为 similar；出生日期、出生地和国籍为 inconclusive。合同词汇含 not_comparable。单字段不同不排除身份。'):t('Draft output: can the finding be distinguished? Facts: similar synthetic name. Unknowns: missing subject birth date and partial provider context. Permitted options: save a draft, request scoped identity information, or keep unresolved / refer where authorised. No exclusion, approval or clearance.','草稿输出：能否区分命中？事实：合成姓名相似。未知：主体出生日期缺失，来源背景不全。允许选项：保存草稿、请求限定身份资料，或按权限保持未决 / 移交。不排除、批准或准入。')}</p><p class="om-meta">${t('Input locators','输入位置')}: screening-snapshots.json / C-result / runSubjectSnapshots / DEMO-CTT-001/run-subject/c-1 (r1); providerRecordSnapshots / DEMO-CTT-001/provider-snapshot/c-1 (r1). ${t('Output basis','输出依据')}: attributeComparisons / c-1-name, c-1-date_of_birth; SRC-016:M03; ${compare?'D4A-MATCH-02-02':'D4A-MATCH-04-01'}. ${t('Authored illustration, not a stored decision or Skill execution.','预编制说明，不是已存决定或能力执行。')}</p></div>`;}
function skillBrief(skill,model,l,allUses){const t=(en,zh)=>tr(l,en,zh),c=skillContent(skill,l),uses=model.reuse.filter(x=>x.skill_ref===skill.id&&(allUses||x.scene_ref==='SCN-MATCH'));return `<h2>${esc(c.id)} · ${esc(c.name)}</h2><div class="om-print-contract">${field(t('Purpose / kind','目标 / 类型'),c.purpose+' · '+c.kind)}${field(t('Input','输入'),c.input)}${field(t('Output','输出'),c.output)}${field(t('Boundaries','边界'),c.boundaries)}${field(t('Stops','停止'),c.stops)}${field(t('Human use','人工使用'),t('The authorised reviewer retains identity, materiality, sufficiency, representative authority and clearance decisions. Skills prepare or support.','获授权复核人员保留身份、重大性、充分性、代表权限及准入判断。能力准备或支持。'))}</div>${['SK-03','SK-06'].includes(c.id)?sample(c.id,t):'<p>'+t('Detailed sample not authored for this family.','此家族未编制详细样例。')+'</p>'}<p class="om-meta">contract_status: ${t('Defined proposal','已定义提案')} · sample_status: ${['SK-03','SK-06'].includes(c.id)?t('Authored synthetic sample','已编制合成样例'):t('Not authored in this pilot','本试点未编制')} · prototype_binding_status: ${t('Read-only interface','只读界面')} · implementation_evidence_status: ${t('Unverified; no runtime / model test','未验证；无运行 / 模型实测')}</p><h3>${t('Mapped usage · original associations','关联用法 · 原始关联')}</h3><p>${t('Each use independently checks current subject / purpose scope, permission and versions. Shared families do not share grants, prompts or professional standards.','每项用途独立核验当前主体 / 用途范围、权限和版本。共享家族不等于共享授权、提示词或专业标准。')}</p>${reuse(uses,t)}`;}
function action(a,l,commonForbidden){const t=(en,zh)=>tr(l,en,zh);return `<section class="om-print-action"><p class="om-meta">${a.action_id} · ${a.parent_change_id} · ${a.transformation_type}</p><h3>${esc(actionTitle(a,l))}</h3><p><strong>${esc(recommendation(a,l))}</strong> · ${esc(relation(a,l))} · ${a.skill_refs.join(' / ')}</p><p>${esc(reason(a,l))}</p>${field(t('Input','输入'),a.reads.join('; '))}${field(t('Output','输出'),a.outputs.join('; '))}${field(t('Human role hypothesis','人工角色假设'),humanRole(a,l))}${a.forbidden_effects.some(x=>!commonForbidden.includes(x))?field(t('Additional forbidden effects','额外禁止影响'),a.forbidden_effects.filter(x=>!commonForbidden.includes(x)).map(x=>controlText(x,l)).join('; ')):''}<p class="om-meta">Current: ${a.current_source_refs.join(' / ')}<br>To-be: ${a.target_source_refs.join(' / ')}<br>${t('References / issues','参考 / 问题')}: ${a.benchmark_refs.join(' / ')} · ${a.issue_refs.join(' / ')}</p></section>`;}
function sources(model,l){const t=(en,zh)=>tr(l,en,zh),unique=items=>[...new Map(items.map(x=>[x.source_id,x])).values()];return `<h2>${t('Sources and interpretation · shared register','来源与解释 · 共享登记')}</h2><p>${t('Inherited review of 7 September 2026; no new external verification. Each action above retains its exact Current / To-be mappings.','沿用 2026 年 9 月 7 日核验；本轮未重新外部核验。上文各动作保留精确 Current / To-be 映射。')}</p>${[['Current',unique(model.actions.flatMap(a=>a.currentSources))],['To-be',unique(model.actions.flatMap(a=>a.targetSources))]].map(([side,items])=>`<h3>${side}</h3><table><tbody>${items.map(r=>`<tr><td>${r.source_id}<br>${esc(r.deck_filename)} · ${t('slide','页')} ${r.slide_no} · ${t('shape','形状')} ${r.shape_id} · ${t('occurrence','位置')} ${r.occurrence_in_shape}</td><td>${esc(r.verbatim_text)}<br>${esc(r.visible_actor)} · ${esc(r.format_observation)}</td></tr>`).join('')}</tbody></table>`).join('')}<p>${t('Source-format flags: no action-specific formatting flag; authority overlap remains unresolved.','来源格式标记：本动作无特定格式标记；权限归属重叠仍未解决。')}</p>${model.issues.map(i=>{const en=issueTranslations[i.issue_id];return `<article><h3>${i.issue_id} · ${esc(t(en[0],i.title))}</h3><p>${esc(t(en[1],i.observation))}</p><p>${esc(t(en[2],i.proposed_handling))}</p><small>${esc(i.source_locator)}</small></article>`;}).join('')}${model.references.map(r=>{const en=referenceTranslations[r.id];return `<article data-reference="${r.id}"><h3>${esc(r.title)}</h3><p class="om-meta">${r.id} · ${r.kind} · ${esc(r.source_locator)} · ${r.verification_status}</p>${field(t('Observation','观察'),t(en[0],r.observation))}${field(t('Transfer','迁移'),t(en[1],r.adaptation))}${field(t('Cannot establish','不能证明'),t(en[2],r.limits))}${r.url?`<p>${esc(r.url)}</p>`:''}</article>`;}).join('')}`;}
export function printOperating({state,role,locale='en-AU',kind='scenario'}){
 const model=operatingProjection({role}),l=locale,t=(en,zh)=>tr(l,en,zh);if(!model)return `<main id="main"><p>${t('Author print unavailable for this role.','此角色不可打印作者内容。')}</p></main>`;
 const section=(html,name)=>`<tr><td class="om-print-section" data-print-section="${name}">${html}</td></tr>`;
 const implicitSkill=state.catalogue?model.skills[0]?.id:model.skills.find(x=>model.actions.find(a=>a.action_id===state.action)?.skill_refs.includes(x.id))?.id;
 const selected=model.skills.find(x=>x.id===(state.skill||implicitSkill))||model.skills.find(x=>x.id==='SK-06');
 const commonForbidden=model.actions[0].forbidden_effects.filter(x=>model.actions.every(a=>a.forbidden_effects.includes(x)));
 const common=`<h2>${t('Shared controls and resumption contract','共享控制与恢复合同')}</h2><p>${t('Applies to every action. Output scope and human gates remain action-specific above. Proposed writes use existing business commands; this author page performs none.','适用于每项动作。输出范围和人工边界按上文动作定义。拟议写入须经既有业务命令，本作者页不执行。')}</p><h3>${t('Preconditions','前置条件')}</h3>${list(model.actions[0].preconditions.map(x=>controlText(x,l)))}${field(t('Stop','停止'),stopText(l))}${field(t('Resume','恢复'),resumeText(l))}<h3>${t('Forbidden effects shared by all actions','所有动作共同的禁止影响')}</h3>${list(commonForbidden.map(x=>controlText(x,l)))}`;
 const diagram=operatingDiagram('overview',l);
 const overview=`<h1>${t('Scenario Operating Model','场景工作分工')}</h1><p>${t('Six reading groups do not define a mandatory runtime sequence. Evidence gathering is conditional; extra approval follows configuration. Same authored Person T / C01 inputs throughout.','六组不构成必经运行顺序。补证按条件进入；额外批准遵循配置。全程使用同一预编制 Person T / C01 输入。')}</p><table class="om-print-overview"><tbody>${model.groups.map((g,i)=>`<tr><th>${i+1}. ${tr(l,...groupNames[i])}</th><td>${tr(l,...groupNotes[i])}</td></tr>`).join('')}</tbody></table>${diagram?`<img class="om-print-map" src="${esc(diagram.src)}" alt="${esc(diagram.alt)}">`:''}`;
 const assessments=`<h2>${t('Inherited assessments · read only','沿用初评 · 只读')}</h2><p>${t('Analyst estimate; review required. Not bank validation or model evaluation. N = C + O + D; F = B + T. No score grants authority.','分析师初估，需复核。不是银行验证或模型实测。N = C + O + D；F = B + T。评分不授予权限。')}</p>${model.actions.map(a=>`<section class="om-print-assessment"><h3>${a.action_id} · ${esc(actionTitle(a,l))}</h3><p>N = ${a.adaptive_need} · F = ${a.test_boundary} · ${t('Formal human gate','正式人工边界')}: ${a.formal_gate.formal_judgement_or_authority?t('Yes','是'):t('No; common controls apply','否；共享控制适用')}</p><div class="om-print-rationales">${['C','O','D','B','V','T','H'].map(k=>`<p><strong>${k} · ${esc(t(model.rubric[k].name,model.rubric[k].zh))}</strong> ${esc(scoreRationale(a,k,l))}</p>`).join('')}</div></section>`).join('')}`;
 const frames=`<h2>${t('Static authored collaboration','静态预编制协作')}</h2>${frameContent.map((f,i)=>`<section class="om-print-frame"><h3>OM-F${i+1} · ${esc(tr(l,f[0],f[1]))}</h3><p>${esc(tr(l,f[2],f[3]))}</p><small>${f[4]} · ${i>=4?'C-unresolved / literal-oracle.json / expected.unresolved · SRC-016:M07':'C-result · SRC-016:M03'} · ${i===2||i===3?t('Pause boundary','暂停边界'):t('Authored frame','预编制帧')}</small></section>`).join('')}`;
 const rows=kind==='skill'?section(skillBrief(selected,model,l,true),'skill'):section(overview,'overview')+model.groups.map((g,i)=>section(`<h2>${i+1}. ${tr(l,...groupNames[i])}</h2><div class="om-print-action-grid">${g.actions.map(id=>action(model.actions.find(a=>a.action_id===id),l,commonForbidden)).join('')}</div>`,'group-'+(i+1))).join('')+section(common,'controls')+section(assessments,'assessments')+section(frames,'frames')+['SK-03','SK-06'].map(id=>section(skillBrief(model.skills.find(s=>s.id===id),model,l,false),id)).join('')+section(sources(model,l),'sources');
 const context=`<div class="om-meta">Person T · ${t('Screening Review · To-be','筛查复核 · 目标设计')} · SCN-MATCH / BR-07 / WF-05 · ${esc(state.action)} · ${esc(state.checkpoint)} · D4 v0.1 · ${t('Synthetic authored example','合成预编制示例')}<br>${t('Legend: Workflow contains work · Rule checks and records · Skill prepares · Human decides · Agent is a conditional candidate','图例：工作流承载工作 · 规则核验和记录 · 能力准备 · 人作判断 · Agent 为条件候选')}</div>`;
 const runningText=[`Person T · ${t('Screening Review · To-be','筛查复核 · 目标设计')} · SCN-MATCH / BR-07 / WF-05 · ${state.action||''} · ${state.checkpoint} · D4 v0.1 · ${t('Synthetic authored example','合成预编制示例')}`,t('Legend: Workflow contains work · Rule checks and records · Skill prepares · Human decides · Agent is a conditional candidate','图例：工作流承载工作 · 规则核验和记录 · 能力准备 · 人作判断 · Agent 为条件候选')].join('\n');
 const marginText=JSON.stringify(runningText).replace(/\\n/g,'\\A ');
 return `<main id="main" class="om-print-collection" data-print-scope="operating-model-${kind}"><style>@media print{@page operating-compact{margin:23mm 12mm 12mm;@top-left{content:${marginText};white-space:pre-wrap;font:9px Arial,sans-serif;color:#183149;vertical-align:middle}}}</style><div class="no-print om-header-actions"><button data-action="om-exit-print">${t('Back to view','返回视图')}</button><button data-action="print">${t('Print / Save PDF','打印 / 保存 PDF')}</button></div><article class="print-sheet om-print om-compact-print"><table class="om-print-pages"><thead class="om-running-head"><tr><td>${context}</td></tr></thead><tbody>${rows}</tbody></table></article></main>`;
}
