"""Build browser mapping data from the adopted guideline analysis, without changing it."""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
analysis = json.loads((ROOT / 'docs/scenario-mapping/scenario-source-mapping.json').read_text())
nodes = {r['Process_ID']: r for r in csv.DictReader((ROOT / '01_process/node_dictionary.csv').open())}
parents = json.loads((ROOT / 'prototype/studio-next/parent-ledger.en.json').read_text())['parents']
titles_zh = ['确定入驻范围', '确认主体与授权', '确定适用要求', '复用既有证据', '请求与提交缺失信息',
             '按用途评估证据', '建立筛查范围并执行筛查', '审阅潜在筛查匹配', '开展强化尽职调查',
             '开展利益冲突审查', '评估信贷与条件', '管理法律协议与条件', '开展质量审查',
             '汇总就绪条件', '确认并发布结果']
result = []
for s, title_zh in zip(analysis['scenarios'], titles_zh, strict=True):
    result.append({
        'id': s['scenario_id'], 'number': s['scenario_number'], 'title': s['guideline_title'],
        'titleZh': title_zh, 'stage': s['stage'], 'primary': s['primary'], 'related': s['related'],
        'rationale': s['rationale'], 'note': s['guideline_note'],
        'locators': s['inherited_occurrence_locators'], 'workIds': s['existing_work_item_ids'],
        'workSources': {code: [{'id': p['parent_ref'], 'title': p['title_en']}
                              for p in parents if p['scenario_ref'] == s['scenario_id']
                              and any(f'|{code}|' in ref for ref in p['qualified_process_refs'])]
                        for code in s['primary'] + s['related']},
    })
codes = {code for s in result for code in s['primary'] + s['related']}
sources = {code: {'title': nodes[code]['Node_Title'], 'currentLane': nodes[code]['Current_Lane'],
                  'targetLane': nodes[code]['Target_Lane'], 'note': nodes[code]['Notes']}
           for code in sorted(codes)}
output = '// Generated by scripts/build_scenario_mapping.py from the adopted mapping guideline.\n'
output += 'export const scenarioMappings = ' + json.dumps(result, ensure_ascii=False, indent=2) + ';\n'
output += 'export const sourceActions = ' + json.dumps(sources, ensure_ascii=False, indent=2) + ';\n'
(ROOT / 'prototype/studio-next/scenario-source-data.mjs').write_text(output)
print(f'Built {len(result)} scenarios and {len(sources)} source action labels.')
