#!/usr/bin/env python3
"""Copy the explicit runtime manifest into a static site; no network or npm build."""
import argparse
import hashlib
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARKER = '.kyc-generated'


def site_files(root=ROOT):
    config = json.loads((root / 'deploy/site-files.json').read_text())
    excluded = [Path(p) for p in config['exclude']]
    selected = set()
    for entry in config['include']:
        source = root / entry
        if not source.exists():
            raise ValueError(f'Missing runtime input: {entry}')
        for file in source.rglob('*') if source.is_dir() else [source]:
            rel = file.relative_to(root)
            if any(rel == p or p in rel.parents for p in excluded):
                continue
            if file.is_symlink():
                raise ValueError(f'Symlink is not a release input: {rel}')
            if file.is_file() and file.suffix.lower() in config['extensions']:
                if not file.resolve().is_relative_to(root.resolve()):
                    raise ValueError(f'Input is outside repository: {rel}')
                selected.add(rel)
    return sorted(selected)


def prepare_output(output, root=ROOT):
    output = output.resolve()
    if output == root.resolve() or root.resolve().is_relative_to(output):
        raise ValueError('Output must not contain the source repository')
    if output.exists():
        if not (output / MARKER).is_file() or (output / '.git').exists():
            raise ValueError(f'Refusing to replace non-generated directory: {output}')
        shutil.rmtree(output)
    output.mkdir(parents=True)
    (output / MARKER).write_text('Generated by Clear-to-Trade release tooling.\n')
    return output


def copy_files(files, output, root=ROOT):
    manifest = []
    for rel in files:
        source, target = root / rel, output / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        manifest.append({'path':rel.as_posix(), 'bytes':source.stat().st_size,
                         'sha256':hashlib.sha256(source.read_bytes()).hexdigest()})
    return manifest


def build_site(output, root=ROOT):
    config = json.loads((root / 'deploy/site-files.json').read_text())
    for entry in config['include']:
        if output.resolve().is_relative_to((root / entry).resolve()):
            raise ValueError('Output must not be inside a runtime input')
    files = site_files(root)
    output = prepare_output(output, root)
    manifest = copy_files(files, output, root)
    (output / '.nojekyll').touch()
    (output / 'build-manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2)+'\n')
    return manifest


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=ROOT/'.build/site')
    args = parser.parse_args()
    manifest = build_site(args.output)
    print(f'Built {len(manifest)} files, {sum(f["bytes"] for f in manifest)/1024**2:.1f} MiB at {args.output}')
