/** Round A authored synthetic schema seed. Run with --artifacts to emit JSON for apply_patch.
 * This script never writes files. It is a reproducible source for reviewable generated assets. */
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const stamp = '2026-09-07T00:00:00Z';
const id = (kind, slug) => `DEMO-CTT-001/${kind}/${slug}`;
const scopeId = id('scope', 'institutional');
const entityId = id('entity', 'harbour');
const authorityId = id('authority', 'demo-reviewer');
const ruleId = id('rule', 'purpose-review-v1');
const sourceStates = ['USER-CONFIRMED','SOURCE-SUPPORTED','INDUSTRY-REFERENCE','DESIGN-HYPOTHESIS','SYNTHETIC','OPEN','SUPERSEDED'];
const f = (type, label, definition, options = {}) => ({type, title:label, description:definition, ...options});
const str = (label, definition, options) => f('string',label,definition,options);
const nullable = (label, definition, options) => f(['string','null'],label,definition,options);
const list = (label, definition, options = {}) => f('array', label, definition,{items:{type:'string'},...options});
const ref = (label, target, options = {}) => str(label,`Reference to ${target}.`, {'x-reference':target,...options});
const refs = (label, target) => list(label,`References to ${target}.`,{'x-reference':target});
const en = (label, values) => str(label,`Explicit ${label.toLowerCase()} independent of other object states.`,{enum:values});
const num = (label, minimum = 1) => f('integer',label,`${label}; increment for material revisions.`,{minimum});
const common = {
 id:str('稳定编号','Stable synthetic local identifier.'),
 case_id:ref('案件','Case'),
 case_scope_id:ref('案件范围','Scope'),
 revision:num('版本'),
 supersedes_ref:nullable('前版本','Previous immutable record reference, null for first revision.',{'x-reference':'Any'}),
 source_refs:list('设计依据','Registered design sources; distinct from synthetic evidence provenance.'),
 source_status:en('来源状态',sourceStates),
 simulation_flag:f('boolean','合成标记','Always true for Round A business records.',{const:true}),
 owner_role:str('责任角色','Synthetic role assignment, not bank delegation.'),
 validation_owner:str('验证负责人','Working review owner.'),
 authority_status:en('权限状态',['demo_configured','unknown','not_applicable']),
 sensitivity:en('敏感等级',['synthetic-restricted']),
 created_at:str('创建时间','UTC timestamp for authored synthetic data.',{format:'date-time'}),
 updated_at:str('更新时间','UTC timestamp; display locale never changes the value.',{format:'date-time'}),
 as_of:str('资料时点','UTC currency of this authored record.',{format:'date-time'}),
 question_ref:nullable('待确认问题','Required when bank authority or policy is unknown.'),
 audit_event_refs:refs('审计事件','AuditEvent')
};
const props = {
 Case:{trigger_id:str('触发','Authored new_relationship trigger.'),lifecycle:en('生命周期',['active','closed']),publication_status:en('发布状态',['not_requested','pending','published','failed']),transaction_status:en('交易状态',['out_of_scope'])},
 Scope:{entity_ids:refs('主体','Entity'),product_scope_ids:list('产品范围','Synthetic product codes only.'),booking_entity_ref:nullable('记账实体','Bank booking entity unknown; no fictitious real bank identifier.'),sales_location:en('销售地区',['unknown','AU','US']),jurisdiction_contexts:list('地区上下文','Context separate from locale and policy.'),policy_profile_ref:nullable('银行政策版本','Unknown bank policy remains null.'),scope_status:en('范围状态',['draft','confirmed_for_demo','needs_clarification'])},
 Entity:{legal_name:str('法定名称','Synthetic entity name.'),entity_type:en('主体类型',['synthetic_corporation']),incorporation_jurisdiction:str('注册地','Synthetic registration context.'),registration_number:nullable('注册编号','No real registration number in fixture.'),lei:nullable('LEI','No invented real LEI.'),identity_status:en('身份状态',['unverified','review_required','verified_for_demo'])},
 Representative:{display_name:str('代表名称','Synthetic representative name.'),entity_id:ref('代表主体','Entity'),role:str('代表角色','Proposed relationship role, not demonstrated authority.'),authority_ref:ref('代表权限','Authority')},
 Authority:{subject_ref:nullable('权限主体','Representative reference, null for generic demo reviewer role.',{'x-reference':'Representative'}),authority_kind:en('权限类型',['representative','demo_action_permission']),scope_description:str('权限范围','Separates demo UI permissions from unknown bank mandates.'),bank_authority_ref:nullable('银行授权','Unknown bank delegation remains null.'),demo_permission_ref:nullable('演示配置','Local configuration key; never a real bank authority.'),status:en('状态',['unknown','configured_for_demo'])},
 Requirement:{subject_id:ref('要求主体','Entity'),purpose_code:str('用途','A purpose cannot be inferred from an evidence artifact.'),set_revision:num('要求集版本'),applicability:en('适用性',['required','not_required','unknown']),rule_ref:str('演示规则','Local authored rule key.'),rule_revision:num('规则版本'),bank_policy_ref:nullable('银行政策','Unknown bank policy remains null.'),status:en('要求状态',['draft','review_required','satisfied','unknown']),status_reason:str('状态原因','Explicit reason for requirement state.')},
 Evidence:{subject_id:ref('资料主体','Entity'),evidence_revision:num('资料版本'),source_record_ref:str('资料来源记录','Synthetic source record; not a design-source ID.'),acquired_at:nullable('接收时间','Null until received.',{format:'date-time'}),covered_attributes:list('资料覆盖属性','Explicit content coverage, no global validity.'),content_ref:str('内容引用','Synthetic inline content key.'),receipt_status:en('接收状态',['available','missing','received']),verification_status:en('核验状态',['not_verified','review_required','verified']),status_reason:str('状态原因','Why artifact is present or absent.')},
 EvidenceUseAssessment:{evidence_id:ref('证据','Evidence'),evidence_revision:num('证据版本'),requirement_id:ref('要求','Requirement'),subject_id:ref('用途主体','Entity'),purpose_code:str('用途','Exact purpose of this assessment.'),sufficiency:en('充分性',['not_assessed','sufficient','insufficient','unknown']),reason_code:nullable('原因','Required unless sufficient.'),basis_refs:list('判断依据','Evidence, source or local rule refs; required for determinate judgments.'),assessed_by_ref:nullable('评估者','Synthetic actor role required for completed assessment.'),authority_ref:nullable('判断授权','Null does not grant permission.',{'x-reference':'Authority'}),assessed_at:nullable('评估时间','UTC time required when assessment completed.',{format:'date-time'}),design_rule_ref:str('演示规则','Explicit demo-only assessment rule.'),supersedes_assessment_ref:nullable('前次评估','Null at revision 1; preserve prior judgment on reassessment.',{'x-reference':'EvidenceUseAssessment'})},
 WorkItem:{activity_id:str('源活动','Source-scoped activity reference.'),scenario_id:str('场景','Preserved SCN alias.'),requirement_ids:refs('关联要求','Requirement'),status:en('任务状态',['ready','awaiting_input','awaiting_review','in_progress','completed','paused','referred']),waiting_for:nullable('等待对象字段','Exact object/field/response; null only when no wait.'),input_refs:refs('输入','Any'),output_refs:refs('输出','Any'),action_revision:num('动作版本'),hold_scope:en('暂停范围',['task','linked_requirement','case_scope','none']),next_owner:str('下一责任角色','Synthetic role that can supply the next input.')},
 Dependency:{source_key:str('源限定依赖','SRC-010:DEP-nn; bare DEP keys are ambiguous.'),ia_crosswalk_keys:list('IA对照','SRC-009 scoped alternatives with explicit semantic mapping.'),from_ref:ref('起点','Any'),to_ref:ref('终点','Any'),relation_type:en('关系类型',['requires_input','waits_for','triggers_review','aggregates_conditions']),required_input_revision:num('所需输入版本'),status:en('依赖状态',['pending','satisfied','blocked']),wait_field:str('等待字段','Named input field or judgment.'),resume_event:str('恢复事件','Event that may release this scoped dependency.'),parallel_rule:str('并行规则','Why unrelated branches may continue; synthetic proposal.')},
 ScreeningFinding:{subject_id:ref('筛查主体','Entity'),run_id:str('筛查运行','Synthetic run alias, source not a real screening provider.'),run_kind:en('筛查类型',['preliminary','comprehensive']),population_revision:num('群体版本'),provider_record_ref:str('提供方记录','Synthetic comparison record.'),matched_attributes:list('相同属性','Authored match attributes.'),different_attributes:list('不同属性','Authored differing attributes.'),unknown_attributes:list('未知属性','Attributes requiring evidence.'),evidence_use_ids:refs('证据用途评估','EvidenceUseAssessment'),materiality_status:en('重大性',['unknown','review_required','assessed_for_demo']),review_status:en('复核状态',['awaiting_evidence','awaiting_human','paused','referred','resolved']),decision_ref:nullable('决定','Null until an authorised demo human records disposition.',{'x-reference':'Decision'})},
 Decision:{decision_type:en('决定类型',['screening_disposition','evidence_assessment']),outcome:en('决定结果',['not_a_match','potential_match','insufficient_evidence','refer']),authority_ref:ref('演示权限','Authority'),bank_authority_ref:nullable('银行权限','Never inferred from configured demo action.'),basis_refs:list('决定依据','Evidence-use refs and explicit authored rule.'),input_revisions:f('object','输入版本','Exact input object revisions at decision time.',{additionalProperties:{type:'integer',minimum:1}}),recorded_by:str('决定者','Synthetic human reviewer.'),recorded_at:str('决定时间','UTC timestamp.',{format:'date-time'}),currency:en('当前适用性',['current','needs_review','historical'])},
 ClearanceCondition:{domain:en('条件领域',['evidence','screening','legal','credit','qa','conflicts','edd']),applicability:en('适用性',['required','not_required','unknown']),status:en('条件状态',['unknown','review_required','satisfied','awaiting_execution','condition_pending','pending']),status_reason:str('阻塞原因','Named reason; task completion cannot overwrite unrelated conditions.'),scope_revision:num('范围版本'),basis_refs:refs('条件依据','Any'),next_action:str('下一动作','Action required from the responsible role.')},
 ReadinessSnapshot:{scope_revision:num('范围版本'),condition_revisions:f('object','条件版本','Version map; immutable snapshot basis.',{additionalProperties:{type:'integer',minimum:1}}),result:en('就绪结果',['not_ready','candidate_ready']),blocking_condition_ids:refs('阻塞条件','ClearanceCondition'),unknown_condition_ids:refs('未知条件','ClearanceCondition'),evaluated_at:str('计算时间','UTC snapshot timestamp.',{format:'date-time'}),basis_event_refs:refs('计算事件','AuditEvent')},
 AuditEvent:{event_type:str('事件类型','Authored or simulated action; no production immutability claim.'),actor_ref:str('执行者','Synthetic human/rule/tool identity.'),object_ref:ref('目标','Any'),from_revision:f(['integer','null'],'前版本','Null for record creation.',{minimum:1}),to_revision:num('新版本'),correlation_id:str('关联动作','Idempotent local action key.'),occurred_at:str('发生时间','UTC timestamp.',{format:'date-time'})},
 StoryRoute:{case_revision:num('案件版本'),trigger_id:str('路线触发','Same authored trigger as case.'),scenario_ids:list('路线场景','Six authored scenes in Round A; no completion implied.'),skeleton_scenario_ids:list('骨架场景','Remaining SCN aliases reserved, not authored product slices.'),entry_scenario_id:str('入口场景','SCN-REQUIREMENTS for this slice.'),terminal_scenario_id:str('结束场景','SCN-READINESS for blocked outcome.'),playback_executes_actions:f('boolean','播放不执行','Always false; navigation does not mutate business state.',{const:false})}
};
const collections = {Case:'case',Scope:'scopes',Entity:'entities',Representative:'representatives',Authority:'authorities',Requirement:'requirements',Evidence:'evidence',EvidenceUseAssessment:'evidenceUseAssessments',WorkItem:'workItems',Dependency:'dependencies',ScreeningFinding:'screeningFindings',Decision:'decisions',ClearanceCondition:'clearanceConditions',ReadinessSnapshot:'readinessSnapshots',AuditEvent:'auditEvents',StoryRoute:'storyRoutes'};
props.Evidence.content_attributes={...f('object','合成资料属性','Explicit fictional string values for the bounded comparison. Missing evidence content must not be displayed as received; no single value grants automatic sufficiency.',{additionalProperties:{type:'string'}}),'x-required':false};
props.ScreeningFinding.provider_attributes={...f('object','合成提供方属性','Explicit fictional provider comparison values; no real registry/provider lookup or policy determination.',{additionalProperties:{type:'string'}}),'x-required':false};
props.WorkItem.status.enum.push('awaiting_response');
props.WorkItem.status.description='Work state; awaiting_response identifies a recorded residual request waiting for its named client response, distinct from input prerequisites before sending.';
props.Decision.record_status={...en('记录状态',['recorded']), 'x-required':false};
props.Decision.submission_key={...str('提交去重键','Local idempotency key; repeated submission returns the existing decision.'),'x-required':false};
props.AuditEvent.rationale={...str('操作理由','Synthetic actor explanation, separate from bank authority.'),'x-required':false};
props.AuditEvent.input_revisions={...f('object','输入版本','Exact input record revision map.',{additionalProperties:{type:'integer',minimum:1}}),'x-required':false};
const definitions = Object.fromEntries(Object.entries(props).map(([name, fields]) => [name,{type:'object',additionalProperties:false,properties:{...common,...fields},required:Object.keys({...common,...fields}).filter(key=>fields[key]?.['x-required']!==false)}]));
const schema = {$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:clear-to-trade:round-a:shared-case-spine:v0.1',title:'Shared Case Spine v0.1 — synthetic prototype draft',description:'Not bank policy, production schema or authorised clearance. All records are synthetic.',type:'object',additionalProperties:false,properties:Object.fromEntries(Object.entries(collections).map(([name,key])=>[key,name==='Case'?{$ref:`#/$defs/${name}`}:{type:'array',items:{$ref:`#/$defs/${name}`}}])),required:[...Object.values(collections),'demoConfig'],$defs:definitions};
schema.properties.demoConfig={type:'object',additionalProperties:false,required:['id','source_status','simulation_flag','bank_authority_status','bank_policy_status','allowed_actions_by_role','rules','questions'],properties:{id:{type:'string'},source_status:{const:'SYNTHETIC'},simulation_flag:{const:true},bank_authority_status:{const:'unknown'},bank_policy_status:{const:'unknown'},allowed_actions_by_role:{type:'object',additionalProperties:{type:'array',items:{type:'string'}}},rules:{type:'object',additionalProperties:{type:'string'}},questions:{type:'object',additionalProperties:{type:'string'}}}};
const base=(kind,slug,owner='ROLE-KYCOPS')=>({id:id(kind,slug),case_id:'DEMO-CTT-001',case_scope_id:scopeId,revision:1,supersedes_ref:null,source_refs:['SRC-009','SRC-010'],source_status:'SYNTHETIC',simulation_flag:true,owner_role:owner,validation_owner:'Christina',authority_status:'unknown',sensitivity:'synthetic-restricted',created_at:stamp,updated_at:stamp,as_of:stamp,question_ref:'ROUND-A-Q-AUTHORITY',audit_event_refs:[]});
const identityReq=id('requirement','identity'), screeningReq=id('requirement','screening-purpose'), identityEv=id('evidence','registry'), supplementEv=id('evidence','supplement');
const assessment=(slug,ev,req,purpose)=>({...base('assessment',slug),evidence_id:ev,evidence_revision:1,requirement_id:req,subject_id:entityId,purpose_code:purpose,sufficiency:'not_assessed',reason_code:'awaiting_purpose_review',basis_refs:[],assessed_by_ref:null,authority_ref:null,assessed_at:null,design_rule_ref:ruleId,supersedes_assessment_ref:null});
const task=(slug,scenario,activity,reqs,wait,inputs,outputs,owner='ROLE-KYCOPS')=>({...base('work',slug,owner),activity_id:`SRC-007:slide2:Target:${activity}`,scenario_id:scenario,requirement_ids:reqs,status:wait?'awaiting_input':'ready',waiting_for:wait,input_refs:inputs,output_refs:outputs,action_revision:1,hold_scope:wait?'task':'none',next_owner:owner});
const condition=(domain,status,reason,owner,action,basis=[])=>({...base('condition',domain,owner),domain,applicability:'required',status,status_reason:reason,scope_revision:1,basis_refs:basis,next_action:action});
const fixture={
case:{...base('case','unused','ROLE-CASEMGR'),id:'DEMO-CTT-001',trigger_id:'new_relationship',lifecycle:'active',publication_status:'not_requested',transaction_status:'out_of_scope'},
scopes:[{...base('scope','institutional','ROLE-CASEMGR'),entity_ids:[entityId],product_scope_ids:['SYNTHETIC-INSTITUTIONAL-PRODUCT'],booking_entity_ref:null,sales_location:'unknown',jurisdiction_contexts:['AU'],policy_profile_ref:null,scope_status:'confirmed_for_demo',question_ref:'ROUND-A-Q-POLICY'}],
entities:[{...base('entity','harbour'),legal_name:'Harbour Institutional Holdings (Synthetic)',entity_type:'synthetic_corporation',incorporation_jurisdiction:'AU',registration_number:null,lei:null,identity_status:'review_required'}],
representatives:[{...base('representative','alex'),display_name:'Alex Morgan (Synthetic)',entity_id:entityId,role:'client_contact',authority_ref:id('authority','representative')}],
authorities:[{...base('authority','representative'),subject_ref:id('representative','alex'),authority_kind:'representative',scope_description:'Client contact; legal signing authority is unknown.',bank_authority_ref:null,demo_permission_ref:null,status:'unknown'},{...base('authority','demo-reviewer','ROLE-FINCRIME'),authority_status:'demo_configured',subject_ref:null,authority_kind:'demo_action_permission',scope_description:'Local screening disposition simulation only; no real bank delegation.',bank_authority_ref:null,demo_permission_ref:id('config','permissions-v1'),status:'configured_for_demo'}],
requirements:[{...base('requirement','identity'),subject_id:entityId,purpose_code:'entity_identity',set_revision:1,applicability:'required',rule_ref:ruleId,rule_revision:1,bank_policy_ref:null,status:'draft',status_reason:'Awaiting synthetic requirements confirmation',question_ref:'ROUND-A-Q-POLICY'},{...base('requirement','screening-purpose'),subject_id:entityId,purpose_code:'screening_identity_disambiguation',set_revision:1,applicability:'required',rule_ref:ruleId,rule_revision:1,bank_policy_ref:null,status:'draft',status_reason:'Specific identifying fact absent; scope of bank evidence standard unknown',question_ref:'ROUND-A-Q-POLICY'}],
evidence:[{...base('evidence','registry'),subject_id:entityId,evidence_revision:1,source_record_ref:'SYNTHETIC-SOURCE/registry/extract-v1',acquired_at:stamp,covered_attributes:['legal_name','incorporation_jurisdiction'],content_ref:'synthetic:inline:registry-extract',receipt_status:'available',verification_status:'not_verified',status_reason:'Available to review for entity identity; no screening disambiguation fact'},{...base('evidence','supplement'),subject_id:entityId,evidence_revision:1,source_record_ref:'SYNTHETIC-SOURCE/client/response-v1',acquired_at:null,covered_attributes:['screening_distinguishing_identifier'],content_ref:'synthetic:inline:supplement-placeholder',receipt_status:'missing',verification_status:'not_verified',status_reason:'Requested item placeholder; content is not received evidence'}],
evidenceUseAssessments:[assessment('identity',identityEv,identityReq,'entity_identity'),assessment('registry-screening',identityEv,screeningReq,'screening_identity_disambiguation'),assessment('supplement-screening',supplementEv,screeningReq,'screening_identity_disambiguation')],
workItems:[task('requirements','SCN-REQUIREMENTS','M2.1-M2.5',[identityReq,screeningReq],null,[scopeId],[identityReq,screeningReq]),task('reuse','SCN-SOURCE','M3.1-M3.2',[identityReq],`${identityReq}.status`,[identityEv,identityReq],[id('assessment','identity')]),task('residual-request','SCN-GAP','M3.2-M3.3',[screeningReq],`${id('assessment','registry-screening')}.sufficiency`,[screeningReq,id('assessment','registry-screening')],[supplementEv]),task('review-receive','SCN-VALIDATE','M3.4-M3.5',[screeningReq],`${supplementEv}.receipt_status`,[supplementEv,screeningReq],[id('assessment','supplement-screening')]),task('screening-review','SCN-MATCH','M4.5-M4.7',[screeningReq],`${id('assessment','supplement-screening')}.sufficiency`,[id('finding','possible-match'),id('assessment','supplement-screening')],[id('condition','screening')],'ROLE-FINCRIME'),task('readiness','SCN-READINESS','M8.1',[],null,[id('condition','screening'),id('condition','legal'),id('condition','credit'),id('condition','qa')],[id('snapshot','initial')],'ROLE-CASEMGR')],
dependencies:[],
screeningFindings:[{...base('finding','possible-match','ROLE-FINCRIME'),subject_id:entityId,run_id:'SYNTHETIC-RUN/comprehensive/1',run_kind:'comprehensive',population_revision:1,provider_record_ref:'SYNTHETIC-PROVIDER/possible-match/1',matched_attributes:['similar_name'],different_attributes:[],unknown_attributes:['screening_distinguishing_identifier'],evidence_use_ids:[id('assessment','registry-screening'),id('assessment','supplement-screening')],materiality_status:'review_required',review_status:'awaiting_evidence',decision_ref:null}],
decisions:[],
clearanceConditions:[condition('evidence','review_required','Purpose-specific evidence review remains open','ROLE-KYCOPS','Review available evidence and residual response',[identityReq,screeningReq]),condition('screening','review_required','Possible match requires evidence and human disposition','ROLE-FINCRIME','Review distinguishing evidence then record permitted demo disposition',[id('finding','possible-match')]),condition('legal','awaiting_execution','Applicable agreement remains unexecuted','ROLE-LEGAL','Obtain executed agreement'),condition('credit','condition_pending','Credit condition remains unresolved','ROLE-CREDIT','Complete outstanding credit condition'),condition('qa','pending','Final QA review and sign-off remain pending','ROLE-QA','Recheck case after prerequisite work'),{...condition('conflicts','satisfied','Synthetic independent conflicts outcome retained','ROLE-CONFLICTS','No new action in Round A'),authority_status:'demo_configured'},{...condition('edd','unknown','Applicability requires separate risk rationale; no automatic EDD from a name match','ROLE-FINCRIME','Confirm risk-based applicability'),applicability:'unknown',question_ref:'ROUND-A-Q-EDD'}],
readinessSnapshots:[],
auditEvents:[{...base('event','seed','ROLE-DEMO-AUTHOR'),authority_status:'not_applicable',event_type:'synthetic_fixture_authored',actor_ref:'ROLE-DEMO-AUTHOR',object_ref:'DEMO-CTT-001',from_revision:null,to_revision:1,correlation_id:'ROUND-A-SEED-001',occurred_at:stamp}],
storyRoutes:[{...base('route','unused','ROLE-DEMO-AUTHOR'),id:'ROUTE-NEW-REL-01',case_revision:1,trigger_id:'new_relationship',scenario_ids:['SCN-REQUIREMENTS','SCN-SOURCE','SCN-GAP','SCN-VALIDATE','SCN-MATCH','SCN-READINESS'],skeleton_scenario_ids:['SCN-SCOPE','SCN-ENTITY','SCN-POPULATION','SCN-EDD','SCN-CONFLICTS','SCN-LEGAL','SCN-CREDIT','SCN-QA','SCN-PUBLISH'],entry_scenario_id:'SCN-REQUIREMENTS',terminal_scenario_id:'SCN-READINESS',playback_executes_actions:false}],
demoConfig:{id:id('config','permissions-v1'),source_status:'SYNTHETIC',simulation_flag:true,bank_authority_status:'unknown',bank_policy_status:'unknown',allowed_actions_by_role:{'ROLE-KYCOPS':['confirm_requirements','reuse_identity','send_residual_request','receive_supplement','assess_supplement','request_evidence','pause','refer'],'ROLE-CASEMGR':['view_readiness'],'ROLE-FINCRIME':['record_disposition','request_evidence','pause','refer']},rules:{[ruleId]:'Synthetic only: available registry extract may support entity identity after human review; the same extract is insufficient for screening disambiguation. Supplement receipt triggers review, not satisfaction. Only a configured demo reviewer can record a disposition after sufficient purpose-linked assessment.'},questions:{'ROUND-A-Q-AUTHORITY':'Bank mandates for requirements, evidence, screening, QA and publication remain unknown. Local action permission is an authored demo configuration only.','ROUND-A-Q-POLICY':'Bank policy profiles, field thresholds and source permissions require bank validation.','ROUND-A-Q-EDD':'EDD applicability requires a separate risk rationale and validation; unknown is not not_required.'}}
};
fixture.evidence[0].content_attributes={legal_name:'Harbour Institutional Holdings (Synthetic)',incorporation_jurisdiction:'AU'};
fixture.evidence[1].content_attributes={registration_reference:'SYN-A-104',incorporation_jurisdiction:'AU',entity_type:'synthetic_corporation'};
fixture.screeningFindings[0].provider_attributes={registration_reference:'SYN-B-207',incorporation_jurisdiction:'NZ',legal_name:'Harbour Institutional Holdings (Provider Demo)',entity_type:'synthetic_corporation'};
fixture.authorities.push({...base('authority','demo-kycops','ROLE-KYCOPS'),authority_status:'demo_configured',subject_ref:null,authority_kind:'demo_action_permission',scope_description:'Local KYC requirements/evidence/request simulations only; no real bank delegation.',bank_authority_ref:null,demo_permission_ref:id('config','permissions-v1'),status:'configured_for_demo'});
const deps=[['04',['04'],'requirement','identity','work','reuse','requires_input','status','requirements_confirmed'],['05',['04'],'assessment','registry-screening','work','residual-request','triggers_review','sufficiency','residual_gap_confirmed'],['05',['04'],'evidence','supplement','work','review-receive','waits_for','receipt_status','supplement_received'],['07',['08'],'assessment','supplement-screening','work','screening-review','requires_input','sufficiency','purpose_assessment_recorded'],['12',['11'],'condition','screening','work','readiness','aggregates_conditions','status','condition_changed']];
fixture.dependencies=deps.map(([key,ia,fk,fs,tk,ts,rel,field,event],i)=>({...base('dependency',`d2-${key}-${i+1}`),source_key:`SRC-010:DEP-${key}`,ia_crosswalk_keys:ia.map(x=>`SRC-009:DEP-${x}`),from_ref:id(fk,fs),to_ref:id(tk,ts),relation_type:rel,required_input_revision:1,status:'pending',wait_field:field,resume_event:event,parallel_rule:'Only named input dependency holds this task; Legal, Credit and Conflicts have independent authored conditions.'}));
fixture.readinessSnapshots=[{...base('snapshot','initial','ROLE-RULE'),authority_status:'not_applicable',scope_revision:1,condition_revisions:Object.fromEntries(fixture.clearanceConditions.map(x=>[x.id,x.revision])),result:'not_ready',blocking_condition_ids:fixture.clearanceConditions.filter(x=>x.applicability==='required'&&x.status!=='satisfied').map(x=>x.id),unknown_condition_ids:fixture.clearanceConditions.filter(x=>x.applicability==='unknown').map(x=>x.id),evaluated_at:stamp,basis_event_refs:[id('event','seed')]}];

const aliases=['SCOPE','ENTITY','REQUIREMENTS','SOURCE','GAP','VALIDATE','POPULATION','MATCH','EDD','CONFLICTS','LEGAL','CREDIT','QA','READINESS','PUBLISH'];
const journeys={REQUIREMENTS:['J-M2-01','J-M3-03'],SOURCE:['J-M3-01'],GAP:['J-M3-02','J-M3-03'],VALIDATE:['J-M3-04']};
const process={SCOPE:'M0.1-M0.4|M1.1',ENTITY:'M1.3-M1.5|M3.4',REQUIREMENTS:'M2.1-M2.5',SOURCE:'M3.1-M3.2',GAP:'M2.5|M3.2-M3.3',VALIDATE:'M3.4-M3.5',POPULATION:'M4.1-M4.4',MATCH:'M4.5-M4.7',EDD:'M5',CONFLICTS:'M7',LEGAL:'C1',CREDIT:'C2',QA:'M6',READINESS:'M8.1',PUBLISH:'M8.2-M8.5'};
const goals={REQUIREMENTS:['明确适用要求','Make requirements explicit'],SOURCE:['使用已有证据','Use available evidence'],GAP:['仅请求剩余缺口','Request residual gaps'],VALIDATE:['接收并评估具体用途','Receive and assess purpose'],MATCH:['处理疑似命中','Resolve a possible match'],READINESS:['明确未就绪原因','Explain what remains']};
const contracts={
REQUIREMENTS:{trigger:'Confirmed synthetic scope revision is available',preconditions:['Scope.revision=1','Requirement.rule_ref references synthetic rule; bank_policy_ref=null'],current_work:'Interpret AML/non-AML requirements and consolidate requirements (M2.1–M2.5); interpretation friction is ASM-002 hypothesis.',target_work:'Prepare versioned requirements; KYC Ops confirms this synthetic set.',human_decision:'Confirm demo requirements; unknown bank policy stays visible.',wait:'Scope context or applicability judgment; owner ROLE-KYCOPS',output:'Requirement.status=review_required; set_revision retained; requirements task completed',resume:'requirements_confirmed at current scope revision',impact:'Evidence reuse may begin; no requirement satisfied by confirmation',acceptance:['Confirmation is distinct from send','Unknown policy remains unknown','Back does not revert requirement revision']},
SOURCE:{trigger:'Synthetic requirements confirmed',preconditions:['Identity evidence receipt_status=available','Identity requirement current revision'],current_work:'Search public/commercial sources and locate residual gaps (M3.1–M3.2); repeated retrieval friction is ASM-002 hypothesis.',target_work:'Show registry provenance and evaluate each purpose separately.',human_decision:'Review identity reuse; registry use for screening remains insufficient.',wait:'Subject ambiguity/source provenance; owner ROLE-KYCOPS',output:'Identity EvidenceUseAssessment sufficient; screening use insufficient; identity Requirement satisfied',resume:'identity_reuse_reviewed',impact:'Only identity requirement closes; screening residual request becomes actionable',acceptance:['Same artifact has two distinct purpose assessments','Missing source cannot be silently accepted','Return preserves scope and scene']},
GAP:{trigger:'Screening-purpose registry assessment is insufficient',preconditions:['Residual gap names screening_distinguishing_identifier','Confirmed requirements and completed identity reuse'],current_work:'Identify gaps and request missing information (M3.2–M3.3); request fragmentation is ASM-002 hypothesis.',target_work:'Prepare one synthetic request containing the unresolved screening fact only.',human_decision:'Configured KYC Ops sends locally simulated request.',wait:'Client response for evidence/supplement; owner ROLE-KYCOPS',output:'Residual-request WorkItem becomes awaiting_input until response; audit event records local send',resume:'supplement_received',impact:'Unrelated Legal/Credit/Conflicts continue; request sending does not satisfy evidence',acceptance:['Identity evidence is excluded from residual request','Repeated send does not duplicate event','Return restores draft and request state']},
VALIDATE:{trigger:'Synthetic supplement receipt',preconditions:['Residual request sent','Evidence revision and purpose association intact'],current_work:'Capture/validate evidence and preserve sourcing trail (M3.4–M3.5).',target_work:'Receive supplement, then separately assess verification and purpose sufficiency.',human_decision:'Configured KYC Ops assesses or pauses with a reason.',wait:'Supplement content/provenance or reviewer judgment; owner ROLE-KYCOPS',output:'Receipt alone leaves assessment not_assessed; later sufficient assessment updates linked requirement',resume:'purpose_assessment_recorded for current evidence revision',impact:'Screening human review becomes actionable; Legal/Credit/QA remain unchanged',acceptance:['Receipt never auto-satisfies requirement','Missing rationale or stale evidence blocks assessment','Return preserves receipt and review as separate states']},
MATCH:{trigger:'Synthetic possible match exists and purpose evidence becomes sufficient',preconditions:['Supplement assessment sufficient','Finding subject/purpose/revisions align','ROLE-FINCRIME demo action permission'],current_work:'Adjudicate hit, assess materiality and determine outcome (M4.5–M4.7).',target_work:'Compare matching/different/unknown attributes and preserve evidence basis for human disposition.',human_decision:'Configured demo reviewer records not_a_match, requests evidence, pauses or refers; no score grants authority.',wait:'Purpose evidence or human disposition; owner ROLE-FINCRIME',output:'Decision with input_revisions; finding resolved only for valid disposition; screening condition updated',resume:'disposition_recorded',impact:'Local screening outcome may resolve; EDD remains separate applicability question and overall readiness remains blocked',acceptance:['Wrong role is blocked','Incomplete basis/stale revision is blocked','Duplicate action creates no second decision','Back preserves recorded disposition']},
READINESS:{trigger:'Any linked condition version changes',preconditions:['Current scope revision','All condition statuses and applicability explicit'],current_work:'Confirm clearance prerequisites (M8.1).',target_work:'Derive versioned blocker summary from current conditions.',human_decision:'No approval granted by readiness calculation; publication remains not_requested.',wait:'Legal awaiting execution; Credit condition pending; QA pending; EDD applicability unknown',output:'New ReadinessSnapshot result=not_ready with exact blocker and unknown IDs',resume:'A named condition changes version',impact:'Local screening completion cannot clear Legal/Credit/QA or unknown applicability',acceptance:['No false green after screening','Unknown EDD is not not_required','Locale/navigation/playback never changes readiness']}
};
const authoredAliases=Object.keys(contracts);
for(const [alias,contract] of Object.entries(contracts)){
 contract.applicability={case_scope_id:scopeId,subject_id:entityId,value:true,basis:'Authored Round A scope only; bank applicability requires validation',confirmed_by:'ROLE-DEMO-AUTHOR'};
 contract.objective=goals[alias][1];
 contract.concurrency={may_continue:['SCN-LEGAL','SCN-CREDIT','SCN-CONFLICTS'],minimum_input:'Each branch has its own sufficiently identified synthetic scope/input',hold_scope:'Only named task or linked requirement; no new case-wide hold inferred'};
 contract.decision={actions:alias==='MATCH'?['record_disposition','request_evidence','pause','refer']:[contract.human_decision],authority_basis:'demoConfig.allowed_actions_by_role only',bank_authority_status:'unknown',prohibited:['Auto-approve from confidence score','Publish clearance','Execute trade'],escalation:'Missing evidence, unresolved applicability or absent configured demo permission'};
 contract.story={tension:contract.wait,key_reveal:contract.impact,consequence:contract.output,next_scene_ids:authoredAliases.indexOf(alias)<authoredAliases.length-1?[`SCN-${authoredAliases[authoredAliases.indexOf(alias)+1]}`]:[]};
 contract.ui_media={journey_card:['objective','wait'],scenario_modal:['current_work','target_work','human_decision','impact'],prototype_target:`SCN-${alias}`,print_fallback:'Static scene contract and current blockers',diagram_status:'Owned by separate Round A diagram work; not asserted here'};
 contract.benchmark={refs:[],status:'DEFERRED_THIS_ROUND'};
 contract.acceptance.push('Wrong configured demo role cannot execute the action');
}
const registry=aliases.map((alias,i)=>({scenario_id:`SCN-${alias}`,revision:1,case_id:'DEMO-CTT-001',route_id:'ROUTE-NEW-REL-01',authoring_status:goals[alias]?'authored_round_a':'skeleton',source_status:'DESIGN-HYPOTHESIS',source_refs:['SRC-007','SRC-009','SRC-010','SRC-011'],process_refs:process[alias].split('|').map(x=>`SRC-007:slide2:Target:${x}`),current_process_refs:process[alias].split('|').map(x=>`SRC-007:slide1:Current:${x}`),source_mapping_status:'ACTIVITY_SEEDS_FROM_SRC-009/010; atomic lane/occurrence validation deferred',journey_crosswalk:journeys[alias]||[],crosswalk_status:journeys[alias]?'existing_exact_ids':'no_existing_journey_id',label_zh:goals[alias]?.[0]||alias,label_en_au:goals[alias]?.[1]||alias,label_en_us:goals[alias]?.[1]||alias,print_order:i+1,work_item_ids:fixture.workItems.filter(x=>x.scenario_id===`SCN-${alias}`).map(x=>x.id),contract:contracts[alias]||null}));

const csv=(rows)=>rows.map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n')+'\n';
const headers=['object_name','field_name','label_zh','label_en_au','label_en_us','type','required_when','nullable','enum_or_format','definition','source_or_derivation','source_ref','owner_role','editable_by','validation_rule','revision_rule','dependency_refs','ui_binding','sensitivity','evidence_status','synthetic_example'];
const conditional={reason_code:'When sufficiency is not sufficient; key always present',basis_refs:'At least one when sufficiency sufficient/insufficient; key always present',assessed_at:'Non-null when sufficiency sufficient/insufficient; otherwise null allowed',assessed_by_ref:'Non-null when sufficiency sufficient/insufficient; otherwise null allowed',authority_ref:'Non-null when recording a permitted demo judgment; unknown bank authority never grants permission',supersedes_assessment_ref:'Non-null on reassessment revision >1; first revision null',acquired_at:'Non-null when receipt_status available/received; null when missing',decision_ref:'Non-null when screening finding resolved; null before judgment',question_ref:'Non-null when policy/applicability/authority unknown; all keys present'};
const rows=Object.entries(definitions).flatMap(([name,def])=>Object.entries(def.properties).map(([key,p])=>{const sample=name==='Decision'?null:name==='Case'?fixture.case:fixture[collections[name]][0]; const examples={decision_type:'screening_disposition',outcome:'not_a_match',input_revisions:{[id('assessment','supplement-screening')]:2},authority_ref:authorityId,recorded_by:'ROLE-FINCRIME',recorded_at:stamp,currency:'current'};return [name,key,p.title,key.replaceAll('_',' '),key.replaceAll('_',' '),Array.isArray(p.type)?p.type.join('|'):p.type,conditional[key]||'Always present on each object record',Array.isArray(p.type)&&p.type.includes('null')?'true':'false',p.enum?.join('|')||p.format||(p['x-reference']?`ref:${p['x-reference']}`:''),p.description,'IA §7.2/7.3/7.4 and D2 §8 seeds; field-level implementation is proposed','SRC-009:7|SRC-010:8',sample?.owner_role||'ROLE-FINCRIME',name==='Decision'?'ROLE-FINCRIME via demoConfig':'State reducer after configured demo action',p['x-reference']?`Must resolve ${p['x-reference']} and same case/scope; explicit revision where used`:'JSON type + enum/conditional constraints; no empty strings for unknown','Increment material revision; retain prior assessment/decision/event; new snapshots immutable',name==='EvidenceUseAssessment'?'SRC-010:DEP-04|SRC-010:DEP-05|SRC-010:DEP-07':name==='ReadinessSnapshot'?'SRC-010:DEP-12':'See source-scoped dependency records',`${name}.${key}; exposed where relevant in Scenario/Product/Assurance`,'synthetic-restricted','DESIGN-HYPOTHESIS',JSON.stringify(sample?.[key]??examples[key]??null)];}));
for(const row of rows)if(definitions[row[0]].properties[row[1]]['x-required']===false)row[6]='Optional runtime metadata; when present must satisfy its declared non-null type';
const sourceNames=[['SRC-009','Clear_to_Trade_Experience_Principles_IA_Baseline_v0.4.md'],['SRC-010','Clear_to_Trade_Discussion_2_Living_Story_Scenarios_Benchmark_Spec_v0.1.md'],['SRC-011','Clear_to_Trade_Journey_Content_and_Interaction_Playbook_v0.1.md'],['SRC-012','Confidential_Banking_Living_Case_Parallel_Module_Integration.md']];
const sources=sourceNames.map(([source_id,name])=>{const relative=`../0907 studio building/${name}`;const bytes=readFileSync(path.resolve(root,relative));return {source_id,path:relative,sha256:createHash('sha256').update(bytes).digest('hex'),availability_status:'AVAILABLE',source_status:source_id==='SRC-009'?'USER-CONFIRMED':'DESIGN-HYPOTHESIS',validation_status:'WORKING_NOT_BANK_VALIDATED',scope_note:'Design source; status does not confer bank policy/authority. Mixed claims retain per-claim status.'};});
const artifacts={
'04_operating_model/round-a/shared-case-spine.schema.json':JSON.stringify(schema,null,2)+'\n',
'04_operating_model/round-a/synthetic-case-fixture.json':JSON.stringify(fixture,null,2)+'\n',
'04_operating_model/round-a/field_dictionary.csv':csv([headers,...rows]),
'04_operating_model/round-a/field_dictionary.md':`# Shared Case Spine field dictionary v0.1\n\nDraft prototype logical contract; all ${rows.length} field rows are DESIGN-HYPOTHESIS. See field_dictionary.csv for all 21 IA §7.2 metadata columns and shared-case-spine.schema.json for types. Key presence is mandatory; nullable values preserve explicitly unknown facts. No bank field threshold, policy or authority is asserted.\n\nBusiness records are SYNTHETIC; their definitions are DESIGN-HYPOTHESIS. Unknown banking policy is retained with question_ref. A demo permission is explicitly separate from a bank mandate.\n\nEvidenceUseAssessment carries evidence revision, requirement, subject and purpose. Artifact receipt, verification, use sufficiency, requirement satisfaction, human decision, condition and readiness are independent fields. A decision must pin input revisions. Published state and trade execution are separate; Round A has no publication or trade action.\n\nCaseScope is named Scope in this draft; Party/LegalEntity is Entity; EvidenceArtifact is Evidence; Task/TaskDependency is WorkItem/Dependency. Representative and Authority remain separate objects. Source-qualified dependency mapping is documented in dependency-crosswalk.md. No production table/API contract is claimed.\n`,
'03_personas_journey/round-a/scenario_registry.json':JSON.stringify(registry,null,2)+'\n',
'03_personas_journey/round-a/scenario_registry.csv':csv([['scenario_id','authoring_status','process_refs','journey_crosswalk','crosswalk_status','source_status','work_item_ids'],...registry.map(x=>[x.scenario_id,x.authoring_status,x.process_refs.join('|'),x.journey_crosswalk.join('|'),x.crosswalk_status,x.source_status,x.work_item_ids.join('|')])]),
'00_governance/round-a/source_manifest.json':JSON.stringify({version:'0.1',review_date:'2026-09-07',scope:'Round A local additions only; existing source register unchanged',sources,missing_referenced_source:{title:'Confidential_Banking_Clear_to_Trade_Workshop_Prework_P0_P1(1).md',availability_status:'NOT_FOUND_IN_WORKSPACE',source_status:'OPEN',search_scope:'Workspace rg --files filtered prework|p0.p1; 0907 studio building inventory',derivative_found:'docs/superpowers/specs/2026-09-04-clear-to-trade-prework-design.md',consequence:'No claim of reading/validating original P0/P1; scope comes from active user request and supplied IA/D2.'}},null,2)+'\n'
};
if(globalThis.process.argv.includes('--artifacts')) globalThis.process.stdout.write(JSON.stringify(artifacts));
if(globalThis.process.argv.includes('--chunk')) { const n=Number(globalThis.process.argv.at(-1)); const content=JSON.stringify(artifacts); globalThis.process.stdout.write(JSON.stringify({chunk:content.slice(n*16000,(n+1)*16000),total:Math.ceil(content.length/16000)})); }
export {schema,fixture,registry,artifacts};
