// Emits review artifacts for apply_patch; never overwrites the earlier Round A fixture.
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {createBatchA,batchAction,preparation} from '../../prototype/batch-a-engine.mjs';
const read=p=>JSON.parse(readFileSync(new URL(p,import.meta.url)));
const base=read('./synthetic-case-fixture.json'),schema=read('./shared-case-spine.schema.json');
const snapshots={};let state=createBatchA(base);snapshots['SNAP-A0']=structuredClone(state);
const run=type=>{state=batchAction(state,{type,role:'ROLE-KYCOPS',expectedRevision:state.case.revision,expectedScopeRevision:state.scopes[0].revision,key:`AUTHORED-${type}`,rationale:'Reviewed synthetic Batch A example; no bank authority inferred.',at:'2026-09-07T08:01:00Z'});};
run('clarify_counterparty');snapshots['SNAP-A1']=structuredClone(state);
run('record_working_scope');snapshots['SNAP-A2']=structuredClone(state);
run('receive_registry');run('review_entity');run('assess_authority');run('open_authority_gap');snapshots['SNAP-A3']=structuredClone(state);
const crosswalk=[['01','01','Intake → Conflicts'],['02','02','Entity → preliminary screening'],['02','06','Population → comprehensive screening'],['03','03','Scope → Requirements'],['04','04','Requirements → retrieval'],['04','05','Evidence gap → residual request'],['05','09','Scope → Legal'],['06','10','Scope → Credit'],['07',null,'Credit → Legal agreement revision'],['08','07','Finding → human review'],['08','08','Independent risk → EDD'],['09',null,'Continuous QA / final sign-off'],['10','11','QA gap → remediation'],['11','12','Conditions → readiness'],['12','13','Readiness / authority → publication'],[null,'14','Evidence adequacy change → re-evaluation']].flatMap(([ia,d2,meaning])=>[[ia,'SRC-009'],[d2,'SRC-010']].filter(([n])=>n).map(([num,source])=>({source_ref:source,raw_id:`DEP-${num}`,semantic_relation:meaning,canonical_dependency_id:`${d2?'SRC-010':'SRC-009'}:DEP-${d2||ia}`,runtime_record_ids:base.dependencies.filter(x=>x.source_key===`SRC-010:DEP-${d2}`).map(x=>x.id),source_status:'DESIGN-HYPOTHESIS',scope:'A uses preparation gates only; other relations retained as interfaces'})));
const mapping={case:'Case',scopes:'Scope',entities:'Entity',representatives:'Representative',authorities:'Authority',requirements:'Requirement',evidence:'Evidence',evidenceUseAssessments:'EvidenceUseAssessment',workItems:'WorkItem',dependencies:'Dependency',screeningFindings:'ScreeningFinding',decisions:'Decision',clearanceConditions:'ClearanceCondition',readinessSnapshots:'ReadinessSnapshot',auditEvents:'AuditEvent',storyRoutes:'StoryRoute',naturalPersons:'NaturalPerson',partyRelationships:'PartyRelationship',informationRequests:'InformationRequest'};
// Extensions are a prototype schema seed, not a claim of final production cardinality.
const infer=v=>v===null?{type:['string','null']}:Array.isArray(v)?{type:'array',items:v.length?infer(v[0]):{}}:typeof v==='object'?{type:'object',additionalProperties:true}:typeof v==='number'?{type:'integer'}:{type:typeof v};
const delta=[];
for(const [collection,kind]of Object.entries(mapping)){
 const records=Object.values(snapshots).flatMap(s=>Array.isArray(s[collection])?s[collection]:[s[collection]]).filter(Boolean);
 if(!schema.$defs[kind]){schema.$defs[kind]={type:'object',additionalProperties:false,required:['id','case_id','revision','simulation_flag'],properties:{}};schema.properties[collection]={type:'array',items:{$ref:`#/$defs/${kind}`}};}
 for(const rec of records)for(const [field,value]of Object.entries(rec))if(!schema.$defs[kind].properties[field]){schema.$defs[kind].properties[field]={...infer(value),description:`Batch A ${kind}.${field}; SRC-013 Final v1.0 §7; synthetic / reviewed_for_demo only.`};delta.push({object_name:kind,field_name:field,physical_binding:`${collection}.${field}`,type:JSON.stringify(schema.$defs[kind].properties[field].type),required_when:'When this Batch A object / action is present',nullable:value===null,source_ref:'SRC-013 §7',source_status:'SYNTHETIC-DEMO / DESIGN-HYPOTHESIS',owner_role:'Demo role; bank owner unconfirmed',editable_by:['business_purpose','group_display_name'].includes(field)?'Configured Scope demo role':'Controlled action or fixture only',validation_rule:'Action guards + draft schema; no bank rule inferred',revision_rule:'Material action creates revision / retained prior session',dependency_refs:kind==='Scope'?'SRC-010:DEP-03;SRC-010:DEP-09;SRC-010:DEP-10':'SRC-010:DEP-02;SRC-010:DEP-05',ui_binding:kind==='Scope'?'Scope / Scenario / Print':'Parties / Authority / Tasks / Activity / Print',sensitivity:'synthetic-restricted',synthetic_example:JSON.stringify(value)});}
}
schema.$id='urn:clear-to-trade:shared-case-spine:d2-batch-a-v1';
schema.title='Shared Case Spine — additive D2 Batch A prototype contract';
schema.properties.demoConfig.properties.batchA={type:'object',required:['version','permissions','bank_authority_ref','rule_pack_ref','holds'],properties:{bank_authority_ref:{type:'null'},holds:{type:'array',items:{type:'object'}}},additionalProperties:true};
const p=(kind,field,definition)=>schema.$defs[kind].properties[field]={...schema.$defs[kind].properties[field],...definition};
p('Scope','scope_status',{enum:['draft','confirmed_for_demo','needs_clarification','clarification_required','working_scope_recorded','superseded']});
p('Authority','status',{enum:['unknown','configured_for_demo','evidence_required','not_established','not_assessed']});
p('EvidenceUseAssessment','requirement_id',{type:['string','null']});p('EvidenceUseAssessment','subject_id',{'x-reference':'Any'});p('Evidence','subject_id',{'x-reference':'Any'});
p('AuditEvent','source_revision',{type:'string'});p('AuditEvent','expected_revision',{type:['integer','null']});p('AuditEvent','rationale',{type:['string','null']});
p('Entity','identifiers',{type:'array',items:{type:'object',required:['scheme','value','source_ref','status'],properties:{scheme:{const:'synthetic_registry_key'},value:{type:'string'},source_ref:{type:'string'},status:{enum:['reported','source_reviewed','unknown','conflicted']}},additionalProperties:false}});
p('Entity','identity_resolution_status',{enum:['unresolved','under_review','resolved_for_scope']});p('Entity','verification_status',{enum:['not_started','in_review','established','unresolved']});
p('Scope','product_scope_status',{enum:['draft','needs_review','recorded']});p('Scope','dd_assessment_status',{enum:['not_assessed','under_review','recorded']});p('Scope','confirmation_purpose',{const:'working_scope'});
const sourcePaths=['/Users/christinaliu/Downloads/Clear_to_Trade_D2_Batch_A_Scope_Entity_Final_v1.0.md','/Users/christinaliu/Downloads/Clear_to_Trade_D2_Batch_A_Media_Format_and_Demo_Brief_v1.0.md'];
const sources=sourcePaths.map((path,i)=>({source_id:`SRC-01${i+3}`,path,sha256:createHash('sha256').update(readFileSync(path)).digest('hex'),status:i?'PRODUCTION-BRIEF / visual candidates not selected':'USER-APPROVED Batch A only',bank_validation_status:'NOT_BANK_POLICY'}));
const manifest=['MED-A-PER-T','MED-A-PER-OPS','MED-A-STILL-SCOPE','MED-A-STILL-ENTITY','DMO-A01','DMO-A02','DMO-A03','VID-A01'].map(asset_id=>({asset_id,variant_id:null,asset_revision:null,source_batch:'D2-A',source_document_revision:'Final v1.0',scenario_refs:['SCN-SCOPE','SCN-ENTITY'],beat_refs:[],diagram_refs:['DG-SCOPE-A','DG-ENTITY-A','DG-ENABLE-A'],case_fixture_revision:'D2-A-Final-1.0',source_snapshot_ref:null,asset_type:asset_id.startsWith('VID')?'video':asset_id.startsWith('DMO')?'controlled_demo':'image',file_format:null,dimensions:null,duration:null,fps:null,file_size:null,source_files:[],preview_file:null,poster_file:null,static_fallback:'prototype/batch-a-ui.mjs (HTML object / purpose / result fallback)',locale:['zh-CN','en-AU','en-US'],caption_tracks:[],alt_text_refs:[],motion_mode:'static',controls_supported:[],allowed_intents:['focus_requested','story_beat_requested','open_product_requested','return_requested'],data_mutation_scope:'none',licence_or_generation_provenance:null,content_status:'brief_approved',visual_status:'not_received',test_status:'fallback_tested_separately',promotion_status:'not_selected',known_limitations:['No image/video candidate received; no media playback claimed'],review_owner:'Christina',review_ref:null}));
for(const row of delta){row.label_en_au=row.field_name.replaceAll('_',' ');row.label_en_us=row.label_en_au;row.label_zh=({business_purpose:'业务用途',group_display_name:'集团展示名称',counterparty_entity_id:'交易主体',principal_entity_id:'被代表主体',employer_entity_id:'任职主体',person_id:'人员编号',action_type:'权限用途',scope_revision:'范围版本',product_scope_status:'申请产品范围状态',product_eligibility_assessment_ref:'产品资格评估',dd_level:'尽调等级',dd_assessment_status:'尽调评估状态',identity_resolution_status:'主体界定状态',identity_verification_ref:'身份核验引用',beneficial_ownership_status:'受益所有权状态',evidence_use_refs:'证据用途引用',assessment_permission_ref:'评估操作权限',scope_match:'权限范围匹配',assignee_ref:'分派人员',work_type:'工作类型',wait_reason:'等待原因',required_inputs:'所需输入',blocked_actions:'受阻操作',due_at:'截止日期',provenance_refs:'出处引用',value_status:'值状态',source_revision:'来源版本',expected_revision:'期望版本',causation_ref:'因果事件',before_after_refs:'前后版本引用',synthetic:'合成标记',validation_status:'验证状态'})[row.field_name]||row.field_name;row.definition=schema.$defs[row.object_name].properties[row.field_name].description||('Prototype '+row.field_name);row.enum_or_format=JSON.stringify(schema.$defs[row.object_name].properties[row.field_name].enum||'See additive schema; no bank enum inferred');}
const csv=rows=>{const fields=Object.keys(rows[0]);return [fields.join(','),...rows.map(r=>fields.map(f=>'"'+String(r[f]??'').replaceAll('"','""')+'"').join(','))].join('\n')+'\n';};
const artifacts={'04_operating_model/round-a/batch-a-fixture.json':snapshots['SNAP-A0'],'04_operating_model/round-a/batch-a-story-snapshots.json':{presentation_only:true,snapshots},'04_operating_model/round-a/batch-a-spine.schema.json':schema,'04_operating_model/round-a/batch-a-dependency-crosswalk.json':crosswalk,'04_operating_model/round-a/batch-a-field-delta.csv':csv(delta),'00_governance/round-a/batch-a-sources.json':sources,'prototype/diagrams/batch-a/media-manifest.json':manifest,'04_operating_model/round-a/batch-a-preparation-example.json':preparation(state)};
console.log(JSON.stringify(process.argv[2]?artifacts[process.argv[2]]:artifacts));
