import {readFileSync,writeFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=new URL('./',import.meta.url),spec=readFileSync('/Users/christinaliu/Downloads/Clear_to_Trade_D2_Batch_C_Screening_Review_and_EDD_Final_v1.0.md','utf8');
const archify='/Users/christinaliu/.codex/skills/archify/bin/archify.mjs';
const configs=[
 {id:'DG-C-POPULATION',prefix:'P',title:['筛查对象与覆盖','Population and coverage'],groups:[['context',['P01','P02'],0,'main',['范围与纳入','Scope and membership']],['preliminary',['P03','P04','P05','P06'],1,'main',['已知子集查询','Known-subset query']],['comprehensive',['P07','P08','P09'],1,'upper',['完整计划判断','Full-plan assessment']],['coverage',['P10','P11'],2,'main',['范围覆盖结果','Scoped coverage result']],['waiting',['P12'],1,'lower',['明确缺口与等待','Named gaps and waits']]],edges:[['context','preliminary',['具名输入与权限','Named inputs / permission']],['context','comprehensive',['独立评估完整性','Independent completeness']],['context','waiting',['不足、未知、受限','Missing / unknown / held']],['preliminary','coverage',['重评 · 非自动满足','Reassess, not auto-clear']],['comprehensive','coverage',['确认后执行或复用','Confirmed plan / reuse']]],path:['context','preliminary','coverage']},
 {id:'DG-C-MATCH',prefix:'M',title:['疑似命中复核','Possible match review'],groups:[['context',['M01','M02'],0,'main',['结果与保护范围','Result and protection']],['evidence',['M03','M04','M05'],1,'main',['对照与精确缺口','Comparison and exact gap']],['decision',['M06','M07','M08','M09'],2,'main',['人工权限与记录','Human authority / record']],['referral',['M10'],1,'lower',['移交或保留未决','Refer or stay unresolved']],['impact',['M11','M12'],3,'main',['影响与未决条件','Impact and open conditions']]],edges:[['context','evidence',['有限准备','Bounded preparation']],['evidence','decision',['用途、版本与权限','Use / versions / authority']],['decision','impact',['成功记录事件','Recorded event only']],['context','referral',['紧急或专业处置','Urgent / specialist concern']],['referral','impact',['未决，不生成排除','Unresolved, not exclusion']]],path:['context','evidence','decision','impact']},
 {id:'DG-C-EDD',prefix:'E',title:['EDD 独立适用性','Independent EDD applicability'],groups:[['context',['E01','E02'],0,'main',['风险、范围与依据','Risk, scope and basis']],['required',['E05','E06','E07','E08','E09','E10','E12'],1,'main',['必要的针对性工作','Required targeted work']],['notrequired',['E03'],1,'upper',['本范围不适用','Not required for scope']],['unknown',['E04'],1,'lower',['适用性仍待判断','Applicability unknown']],['impact',['E11'],2,'main',['独立条件与准备状态','Conditions and readiness']]],edges:[['context','required',['required · 有依据','required · with basis']],['context','notrequired',['not_required · 当前有权','not_required · authorised']],['context','unknown',['unknown / stale / 缺权限','unknown / stale / no authority']],['required','impact',['有权结果及未决条件','Authorised result / conditions']],['notrequired','impact',['仅本适用性','Applicability only']],['unknown','impact',['仍待判断，不关闭','Still pending, not closed']]],path:['context','required','impact']}
];
const predicates={P01:'context',P02:'preliminary',P03:'preliminary',P04:'preliminary',P05:'result',P06:'review',P07:'comprehensive',P08:'comprehensive',P09:'comprehensive',P10:'coverage',P11:'coverage',P12:'resume',M01:'review',M02:'referral',M03:'review',M04:'identity',M05:'request',M06:'review',M07:'review',M08:'disposition',M09:'disposition',M10:'referral',M11:'coverage',M12:'coverage',E01:'edd',E02:'edd',E03:'edd',E04:'edd',E05:'edd',E06:'edd',E07:'edd',E08:'edd',E09:'edd',E10:'edd',E11:'coverage',E12:'referral'};
const actions={P03:'prepare_preliminary',P04:'request_preliminary',P05:'receive_result',P06:'save_review_draft',P07:'confirm_population',P08:'prepare_comprehensive',P09:'request_comprehensive',P10:'reassess_coverage',P11:'reassess_coverage',P12:'resume_branch',M01:'save_review_draft',M02:'refer',M03:'save_review_draft',M04:'assess_identity',M05:'request_identity',M06:'save_review_draft',M07:'record_unresolved',M08:'record_disposition',M09:'record_disposition',M10:'refer',M11:'reassess_coverage',M12:'reassess_coverage',E01:'record_edd_applicability',E02:'record_edd_applicability',E03:'record_edd_applicability',E04:'record_edd_applicability',E05:'prepare_edd_pack',E06:'prepare_edd_pack',E07:'prepare_edd_pack',E08:'prepare_edd_pack',E11:'reassess_coverage',E12:'refer'};
const model={version:'1.0',source_document:'SRC-016',source_section:'20',archify_version:'2.17',strategy:'Grouped overview plus complete semantic decision/edge table; no executable graph writes',failed_candidate:'population.candidate.json: composition crossing/shared corridors; stopped after bounded non-improving repairs',families:[]},receipts=[];
for(const c of configs){
 const block=spec.split('### 20.'+({P:2,M:3,E:4}[c.prefix]))[1].split('### 20.')[0];
 const nodes=block.split('\n').filter(l=>new RegExp('^\\| '+c.prefix+'\\d{2} \\| (input|decision|action|state|wait|branch) ').test(l)).map(l=>{const a=l.split('|').slice(1,-1).map(x=>x.trim()),split=a[2].lastIndexOf(' / '),titles=[a[2].slice(0,split),a[2].slice(split+3)];return{id:a[0],type:a[1],title_en:titles[0],title_zh:titles[1],contract:a[3],reference_aliases:a[4].split(';').map(x=>x.trim()),source_document:'SRC-016',source_process_refs:[{source:'SRC-007',locator_status:'high_level_M4_mapping_only_no_node_exact_locator',support_kind:'project_process_context'}],predicate_ref:predicates[a[0]],action_ref:actions[a[0]]||null,input_refs:['case_ref','scope_revision','inputRevisions'],required_input_revisions:'current projection',authority_policy_ref:'demoConfig.batchC / explicit action-time guard',hold_evaluation_ref:'screeningPredicates',writes:[],forbidden_writes:'All business writes: presentation only',performer_kind:{Current:'human',Target:a[1]==='decision'?'rule_and_authorised_human':a[1]==='input'?'product':a[1]==='action'?'product_or_human':'product'},display_group:c.groups.find(g=>g[1].includes(a[0]))[0]};});
 const edges=block.split('\n').filter(l=>new RegExp('^\\| '+c.prefix+'\\d{2} \\| '+c.prefix+'\\d{2} \\|').test(l)).map(l=>{const a=l.split('|').slice(1,-1).map(x=>x.trim());return{id:a[0]+'-'+a[1],from:a[0],to:a[1],condition:a[2],support_kind:'design_interpretation',source_ref:'SRC-016#20',predicate_ref:predicates[a[0]],executable:false};});
 model.families.push({id:c.id,scene:'SCN-'+({P:'POPULATION',M:'MATCH',E:'EDD'}[c.prefix]),nodes,edges,groups:c.groups.map(g=>({archify_node_id:g[0],semantic_nodes:g[1]}))});
 for(const locale of (process.argv.includes('--model-only')?[]:['zh-CN','en-AU','en-US']))for(const mode of ['Current','Target']){
 const z=locale==='zh-CN',i=z?0:1,name=c.id+'.'+mode+'.'+locale+'.r02';
 const candidate={schema_version:2,diagram_type:'workflow',meta:{title:c.title[i]+' · '+(z?(mode==='Current'?'现状':'目标'):mode),locale:z?'zh-CN':'en',quality_profile:'showcase',animation:'none'},lanes:[{id:'upper',label:z?'独立判断':'Independent assessment'},{id:'main',label:z?(mode==='Current'?'人工工作与判断':'产品准备 · 规则检查 · 人工决定'):(mode==='Current'?'Human work and judgement':'Product preparation · rule checks · human decisions')},{id:'lower',label:z?'未决、保护与返回':'Unresolved, protection and return',variant:'exception'}],mainPath:c.path,nodes:c.groups.map(([id,ns,col,lane,label])=>({id,col,lane,type:mode==='Current'?'frontend':'security',label:label[i],sublabel:ns.join(' · ')})),edges:c.edges.map(([from,to,label],index)=>({id:'edge'+index,from,to,label:label[i],...(index===0||c.path.indexOf(from)+1===c.path.indexOf(to)?{}:{role:'branch'})}))};
 if(!z||c.prefix==='E')candidate.nodes.forEach(n=>{n.width=240;});
 // Semantic IDs are already mapped in model.json and the full host decision table.
 // Remove this redundant context line only in candidates diagnosed below the readable minimum.
 if((!z&&c.prefix!=='E')||(z&&c.prefix==='E'))candidate.nodes.forEach(n=>{delete n.sublabel;});
 // r02 follows actual perceptual review: remove the unused Match lane, give
 // overview groups vertical volume, and label them as views rather than policy.
 candidate.lanes=candidate.lanes.filter(l=>candidate.nodes.some(n=>n.lane===l.id));
 candidate.nodes.forEach(n=>{n.height=150;n.type='frontend';});
 candidate.meta.legend={mode:'auto',entries:{frontend:{label:z?'只读分组':'Read-only groups'}}};
 if(c.prefix==='E'||(z&&c.prefix==='P'))candidate.edges[1].route='up-channel';
 writeFileSync(new URL(name+'.json',root),JSON.stringify(candidate,null,2)+'\n');
 if(process.argv.includes('--deliver')){
 const check=spawnSync(process.execPath,[archify,'validate','workflow',fileURLToPath(new URL(name+'.json',root)),'--quality','showcase','--json'],{encoding:'utf8'});let receipt;try{receipt=JSON.parse(check.stdout)}catch{receipt={stdout:check.stdout,stderr:check.stderr}};
 receipts.push({name,phase:'validate',exit_code:check.status,receipt});
 if(check.status===0){const run=spawnSync(process.execPath,[archify,'deliver','workflow',fileURLToPath(new URL(name+'.json',root)),fileURLToPath(new URL(name+'.html',root)),'--quality','showcase','--json'],{encoding:'utf8'});receipts.push({name,phase:'deliver',exit_code:run.status,receipt:JSON.parse(run.stdout)});}else console.log('FAILED '+name+' '+JSON.stringify(receipt.diagnostics??receipt).slice(-2400));
 }
 }
}
writeFileSync(new URL('model.json',root),JSON.stringify(model,null,2)+'\n');writeFileSync(new URL('model.mjs',root),'// Generated semantic content from approved Final §20; presentation only.\nexport default '+JSON.stringify(model,null,2)+';\n');
if(receipts.length)writeFileSync(new URL('delivery-receipts.json',root),JSON.stringify(receipts,null,2)+'\n');
console.log(JSON.stringify({families:model.families.map(f=>({id:f.id,nodes:f.nodes.length,edges:f.edges.length})),receipts:receipts.map(r=>({name:r.name,phase:r.phase,exit:r.exit_code}))}));
