import {chromium} from '/Users/christinaliu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {readFileSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const dir=new URL('./',import.meta.url),delivered=JSON.parse(readFileSync(new URL('active-delivery-receipts.json',dir))).filter(r=>r.phase==='deliver'&&r.exit_code===0),receipts=[];
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:900},acceptDownloads:true});
for(const {name} of delivered){await page.goto(new URL(name+'.html',dir).href);await page.locator('#btn-export').click();const pending=page.waitForEvent('download');await page.locator('#export-menu button[data-format="svg"]').click();const download=await pending;await download.saveAs(fileURLToPath(new URL(name+'.svg',dir)));const svg=readFileSync(new URL(name+'.svg',dir));const canonical=await page.locator('html').getAttribute('data-last-export-canonical');if(canonical!=='true'||/<script[\s>]/i.test(svg.toString()))throw Error('Noncanonical SVG '+name);const sizes=[];for(const [width,height] of [[1440,900],[1600,1000],[1920,1080],[2048,1320]]){await page.setViewportSize({width,height});sizes.push({width,height,...await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight}))});}receipts.push({name,canonical:true,method:'Archify viewer Export → SVG',sha256:createHash('sha256').update(svg).digest('hex'),sizes});}
}finally{await browser.close();}
writeFileSync(new URL('canonical-export-receipts.json',dir),JSON.stringify(receipts,null,2)+'\n');
console.log(JSON.stringify({exports:receipts.length,overflow:receipts.filter(r=>r.sizes.some(s=>s.scrollWidth>s.width||s.scrollHeight>s.height)).map(r=>r.name)}));
// Bounded viewer evidence is separate from deterministic delivery and manual visual review.
for(const {name} of delivered){const result=spawnSync(process.execPath,['/Users/christinaliu/.codex/skills/archify/bin/archify.mjs','visual-check',fileURLToPath(new URL(name+'.html',dir)),'--json'],{encoding:'utf8'});console.log(JSON.stringify({name,visual_exit:result.status,summary:result.stdout.slice(-300)}));}
