import {chromium} from '../../../audit/tooling/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const run=process.env.F_RUN||'host-green',dir=new URL('./'+run+'/',import.meta.url);fs.mkdirSync(dir,{recursive:true});
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),key='ctt-round-a-v1',results=[],errors=[];
const state=()=>page.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),key),hash=s=>createHash('sha256').update(JSON.stringify(s)).digest('hex');
const click=(action,value)=>page.locator(`[data-action="${action}"]${value===undefined?'':`[data-value="${value}"]`}`).filter({visible:true}).first().click();
const check=async(id,fn)=>{await fn();results.push({id,status:'passed'});console.log('PASS',id);};
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
try{
 await page.goto('http://127.0.0.1:8765/prototype/?studio=product-definition');await page.waitForSelector('#main');
 await check('F-SECONDARY',async()=>{assert.equal(await page.locator('[data-f-definition]').count(),1,'Product Definition must be available as secondary Studio view');assert.equal(await page.locator('.topnav button').count(),2);assert.equal(await page.locator('[data-f-scene]').count(),20);assert.equal(await page.locator('[data-f-capability]').count(),10);});
 if(process.env.F_FOCUS==='entry')process.exitCode=0;
 else{
 await page.screenshot({path:fileURLToPath(new URL('definition.desktop-top.png',dir))});
 const before=hash((await state()).data);await page.locator('.f-lab>summary').click();
 await check('F-READONLY-GRAPHS-LAB',async()=>{for(const v of ['work','assurance','outcome'])await click('f-lens',v);for(const v of ['DG-F01','DG-F02','DG-F03']){await click('f-graph',v);await page.locator('[data-f-diagram]').scrollIntoViewIfNeeded();await page.screenshot({path:fileURLToPath(new URL(v+'.desktop-viewport.png',dir))});if(v!=='DG-F02')assert.equal(await page.locator('[data-f-diagram] img').evaluate(e=>e.complete&&e.naturalWidth>0),true);}await click('f-next');assert.equal(hash((await state()).data),before);assert.match(await page.locator('[data-f-live]').innerText(),/unavailable|Unavailable/);await click('f-graph','DG-F02');await click('f-references','F02-unknown');assert.ok(await page.locator('#scenario-dialog[open]').count());await click('reference-close');assert.equal((await state()).navigation.studioPage,'product-definition');assert.equal(await page.locator('[data-f-diagram="DG-F02"] img').count(),0);assert.match(await page.locator('[data-f-diagram="DG-F02"]').innerText(),/fallback|not pass/);});
 await check('F-LOCALE-PRINT',async()=>{await page.locator('#f-region').selectOption('SG');assert.equal((await state()).navigation.region,'SG');assert.equal(hash((await state()).data),before);await page.locator('#locale').selectOption('zh-CN');assert.equal((await state()).navigation.studioPage,'product-definition');await click('f-print');assert.equal(await page.locator('[data-f-scene]').count(),20);assert.equal(await page.locator('[data-f-question]').count(),12);assert.equal(await page.locator('[data-f-diagram]').count(),3);await page.pdf({path:fileURLToPath(new URL('definition.zh-CN.pdf',dir)),format:'A4',printBackground:true});if(await page.locator('[data-action="exit-print"]').count())await click('exit-print');assert.equal(hash((await state()).data),before);await page.locator('#locale').selectOption('en-AU');await click('f-print');await page.pdf({path:fileURLToPath(new URL('definition.en-AU.pdf',dir)),format:'A4',printBackground:true});if(await page.locator('[data-action="exit-print"]').count())await click('exit-print');});
 await check('F-STORY-RETURN',async()=>{await click('f-scene','E2');assert.equal((await state()).navigation.clearanceBeat,'E2');assert.equal(hash((await state()).data),before);await page.locator('[data-e-action="entry-review"]').click();await page.locator('[data-e-action="entry-reviewed"]').click();await page.waitForFunction(k=>!!JSON.parse(sessionStorage.getItem(k)).data.demoConfig.batchE,key);assert.equal(hash((await state()).archives.at(-1).data),before);await click('product','qa-remediation');await page.locator('#e-rationale').fill('F current revision return proof');await page.locator('[data-e-action="save"]').click();const saved=hash((await state()).data);await page.locator('#locale').selectOption('en-US');await click('return','scenario');assert.equal((await state()).navigation.clearanceBeat,'E2');assert.equal((await state()).navigation.locale,'en-US');assert.equal(hash((await state()).data),saved);await click('close');await click('f-open');assert.equal(await page.locator('[data-f-definition]').count(),1);assert.equal(await page.locator('[data-f-live]').getAttribute('data-f-revision'),String((await state()).data.case.revision));for(const lens of ['work','assurance','outcome'])await click('f-lens',lens);assert.equal(hash((await state()).data),saved);});
 await check('F-CONTEXT-BACK',async()=>{const before=await state();await click('f-back');assert.equal((await state()).navigation.clearanceBeat,'E2');assert.equal((await state()).navigation.locale,'en-US');assert.deepEqual((await state()).data,before.data);await page.goBack();await page.waitForSelector('[data-f-definition]');assert.deepEqual((await state()).data,before.data);});
 await check('F-RESPONSIVE',async()=>{await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:fileURLToPath(new URL('definition.mobile-top.png',dir))});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:fileURLToPath(new URL('definition.active-desktop-top.png',dir))});});
 await check('F-CONSOLE',async()=>assert.deepEqual(errors,[]));
 }
}catch(e){results.push({id:'F-FAILURE',status:'failed',error:e.message});console.error(e);process.exitCode=1;}finally{fs.writeFileSync(new URL('receipt.json',dir),JSON.stringify({run,date:new Date().toISOString(),results,errors},null,2));await browser.close();}
