const dict=await(await fetch(new URL('./zh-CN.json?v=source-map-3',import.meta.url))).json();
const KEY='ctt_locale_v1',allowed=['en-US','zh-CN'];
let locale=new URLSearchParams(location.search).get('locale');if(!allowed.includes(locale)){try{locale=localStorage.getItem(KEY)}catch{}locale=allowed.includes(locale)?locale:'en-US'}
const originals=new WeakMap(),attributes=new WeakMap();let changing=false,queued=false;
const phrases=Object.keys(dict).filter(k=>k.length>=3).sort((a,b)=>b.length-a.length);
const phraseRE=new RegExp('(?<![\\p{L}\\p{N}_./-])(?:'+phrases.map(k=>k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')(?![\\p{L}\\p{N}_./-])','gu');
const originalTitle=document.title;
export function translate(value){if(locale!=='zh-CN'||typeof value!=='string')return value;const lead=value.match(/^\s*/)[0],tail=value.match(/\s*$/)[0],s=value.trim();if(!s)return value;if(/^(SRC-|PPT-)/.test(s))return value;if(s.startsWith('Fields and outputs:'))return lead+'字段与输出：'+s.slice(19)+tail;let out=dict[s]||s.replace(phraseRE,k=>dict[k]);out=dict[out]||out.replace(phraseRE,k=>dict[k]);
 out=out.replace(/(\d+) of (\d+) 项前置工作已记录/g,'已记录 $1／$2 项前置工作').replace(/\bpage (\d+)/g,'第 $1 页').replace(/\bPage (\d+) · line (\d+)/g,'第 $1 页 · 第 $2 行');
 return lead+out+tail;
}
function apply(){if(changing)return;changing=true;try{const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const n=walker.currentNode;if(n.parentElement?.closest('script,style,noscript,textarea,code,pre,.sn-id,[data-i18n-source],[contenteditable=true],[data-i18n-control]'))continue;const old=originals.get(n);if(!old||n.textContent!==old.translated&&n.textContent!==old.original)originals.set(n,{original:n.textContent,translated:n.textContent});const pair=originals.get(n);if(n.parentElement?.tagName==='OPTION'&&!n.parentElement.hasAttribute('value'))n.parentElement.value=pair.original;const translated=translate(pair.original);if(n.textContent!==translated)n.textContent=translated;pair.translated=translated;}
 for(const el of document.querySelectorAll('[title],[placeholder],[aria-label],[alt]')){if(el.closest('[data-i18n-control]'))continue;let record=attributes.get(el)||{};for(const name of ['title','placeholder','aria-label','alt']){const val=el.getAttribute(name);if(val==null)continue;const r=record[name];if(!r||val!==r.translated&&val!==r.original)record[name]={original:val,translated:val};const next=translate(record[name].original);if(next!==val)el.setAttribute(name,next);record[name].translated=next;}attributes.set(el,record)}
 for(const el of document.querySelectorAll('a[href*="studio-next/static"],a[href="static.html"],a[href^="./studio-next/process/"],.sn-macro img')){const attr=el.tagName==='IMG'?'src':'href',v=el.getAttribute(attr);if(!v)continue;const base=v.replace('.zh-CN.html','.html').replace('.zh-CN.svg','.svg');const next=locale==='zh-CN'?base.replace('static.html','static.zh-CN.html').replace('_Redraw.svg','_Redraw.zh-CN.svg'):base;if(next!==v)el.setAttribute(attr,next);}
 document.documentElement.lang=locale;document.title=translate(originalTitle);installControl();for(const select of document.querySelectorAll('[data-i18n-control] select'))select.value=locale;
 }finally{changing=false}}
function installControl(){if(document.querySelector('[data-i18n-control]'))return;let target=document.querySelector('.topbar')||document.querySelector('.sn-en')||document.querySelector('.module-return');if(!target)return;const wrap=document.createElement('label');wrap.className='ctt-language';wrap.dataset.i18nControl='';wrap.innerHTML='<span>Language / 语言</span><select aria-label="Language / 语言"><option value="en-US">English</option><option value="zh-CN">简体中文</option></select>';wrap.querySelector('select').value=locale;wrap.querySelector('select').addEventListener('change',e=>setLocale(e.target.value));wrap.querySelector('select').addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();setLocale(['ArrowUp','Home'].includes(e.key)?'en-US':'zh-CN')}});if(target.matches('.sn-en'))target.replaceWith(wrap);else target.append(wrap);}
export function setLocale(next,broadcast=true){if(!allowed.includes(next))return;locale=next;try{localStorage.setItem(KEY,locale)}catch{}const q=new URLSearchParams(location.search);q.set('locale',locale);history.replaceState(history.state,'',location.pathname+'?'+q+location.hash);apply();if(broadcast){if(parent!==window)parent.postMessage({channel:'ctt-locale',locale},location.origin);for(const frame of document.querySelectorAll('iframe'))frame.contentWindow?.postMessage({channel:'ctt-locale',locale},location.origin)}}
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.data?.channel==='ctt-locale'&&allowed.includes(e.data.locale)){setLocale(e.data.locale,false);if(parent===window)for(const frame of document.querySelectorAll('iframe'))frame.contentWindow?.postMessage(e.data,location.origin)}});
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.data?.channel==='ctt-locale-request')e.source?.postMessage({channel:'ctt-locale',locale},location.origin)});
window.addEventListener('storage',e=>{if(e.key===KEY&&allowed.includes(e.newValue))setLocale(e.newValue,false)});
const observer=new MutationObserver(()=>{if(!queued){queued=true;queueMicrotask(()=>{queued=false;apply()})}});observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label','alt']});
const oldConfirm=window.confirm.bind(window);window.confirm=message=>oldConfirm(translate(message));const oldAlert=window.alert.bind(window);window.alert=message=>oldAlert(translate(message));
window.addEventListener('beforeprint',apply);window.addEventListener('popstate',()=>{const l=new URLSearchParams(location.search).get('locale');if(allowed.includes(l))setLocale(l)});window.CTTLanguage={get locale(){return locale},set:setLocale,translate,refresh:apply};
setLocale(locale,false);
if(parent!==window)parent.postMessage({channel:'ctt-locale-request'},location.origin);
