export const ROLES={rm:['Alex Morgan','Relationship Manager','PERSONA-RM'],manager:['Jamie Park','Case Manager','PERSONA-CASEMGR'],ops:['Morgan Lee','KYC Operations','PERSONA-KYCOPS'],specialist:['Sam Ellis','Financial Crime Specialist','PERSONA-RISK'],client:['Person T','Limited information contributor','PERSONA-CLIENT-T'],control:['Taylor Shaw','Conflicts specialist','PERSONA-CONTROL'],credit:['Jordan Blake','Credit specialist','PERSONA-CREDIT'],legal:['Casey Reed','Legal specialist','PERSONA-LEGAL'],qa:['Robin Hale','QA reviewer','PERSONA-QA'],approver:['Demo approver','Authorised confirmation seat',null],executive:['Portfolio viewer','Executive demo seat',null]};
export const ORDER=['SCOPE','ENTITY','REQUIREMENTS','SOURCE','GAP','VALIDATE','POPULATION','MATCH','EDD','CONFLICTS','CREDIT','LEGAL','QA','READINESS','PUBLISH'];
export const OWNER={SCOPE:'rm',ENTITY:'ops',REQUIREMENTS:'manager',SOURCE:'ops',GAP:'rm',VALIDATE:'ops',POPULATION:'ops',MATCH:'specialist',EDD:'specialist',CONFLICTS:'control',CREDIT:'credit',LEGAL:'legal',QA:'qa',READINESS:'manager',PUBLISH:'approver'};
const tracks=['Screening','EDD','Conflicts','Credit','Legal','QA'];
export function freshCase(id,name,variant='hero'){
 return {id,name,variant,synthetic:true,relationship:'New institutional onboarding',country:'Australia',product:'FX forward',parent:variant==='hero'?'Entity B · Singapore':'Reported parent — synthetic group',subject:variant==='hero'?'Person T':name+' contributor',scopeVersion:1,inputVersion:1,requestVersion:1,authority:'Not established',signingAuthority:'Not established',scope:{salesLocation:'Australia',bookingEntity:'Unknown — requires RM confirmation',bookingBasis:''},requirements:[],evidence:[{id:'EV-REG-01',name:'Company registry extract',purpose:'Entity identification',status:'Candidate',version:1,source:'Synthetic registry fixture; not an ASIC lookup'},{id:'EV-ADDR-01',name:'Address record',purpose:'Address verification',status:'Candidate',version:1,source:'Synthetic submitted fixture'},{id:'EV-STRUCT-01',name:'Group structure',purpose:'Ownership context',status:'Older version — review only',version:1,source:'Synthetic client fixture'}],done:[],request:'Not created',requestItems:['Identity evidence for screening','Evidence of information-coordination authority'],uploads:[],responseDraft:'',controls:Object.fromEntries(tracks.map(x=>[x,{status:'Not started',version:1}])),reviewPack:null,decision:null,decisionDraft:{choice:'',note:''},eddRequired:variant==='edd',qaFinding:null,creditConditions:null,agreement:null,readinessVersion:null,confirmation:null,publications:{caseRegister:'Not sent',clientStatus:'Not sent'},history:[],notes:[],messages:[],prepared:{},archived:false};
}
export function addEvent(c,action,actor,detail,scenario){c.history.push({id:`DEMO-${c.id}-E${String(c.history.length+1).padStart(3,'0')}`,at:new Date().toISOString(),action,actor:ROLES[actor]?.[0]||actor,detail,scenario:scenario?'SCN-'+scenario:null,inputVersion:c.inputVersion,synthetic:true})}
function done(c,...ids){for(const id of ids)if(!c.done.includes(id))c.done.push(id)}
function need(ok,msg){if(!ok)throw new Error(msg)}
function has(c,id){return c.done.includes(id)}
export function readiness(c){const reasons=ORDER.filter(x=>!['READINESS','PUBLISH'].includes(x)&&!has(c,x)).map(x=>x==='MATCH'?'A current human screening decision is needed':x==='QA'?'Independent QA sign-off is needed':x+' is still open');if(c.authority!=='Information coordination only')reasons.push('Information-coordination authority is not established');if(c.decision?.inputVersion!==c.inputVersion)reasons.push('Screening evidence version is not current');if(has(c,'LEGAL')&&(!c.agreement||c.agreement.creditVersion!==c.creditConditions?.version||!c.creditConditions?.fulfilled))reasons.push('Agreement must consume the current fulfilled Credit conditions');if(c.qaFinding)reasons.push('QA finding requires remediation and independent re-review');return {ready:reasons.length===0,reasons:[...new Set(reasons)]}}
export function overall(c){if(c.archived)return 'Archived — withdrawn';if(c.confirmation)return Object.values(c.publications).every(x=>x==='Delivered')?'Published — synthetic outcome':'Confirmed — publication pending';return readiness(c).ready?'Ready for authorised confirmation':'Not ready'}
export function nextStep(c){return ORDER.find(x=>!has(c,x))||'PUBLISH'}
export function transact(input,action,role,p={}){
 const c=structuredClone(input);need(!c.archived,'Archived cases are read-only.');
 const owner=OWNER[action];if(owner)need(role===owner,`Use the ${ROLES[owner][1]} demo seat for this action.`);
 const note=String(p.note||'').trim();
 if(!['NOTE','MESSAGE','DRAFT','FORM_DRAFT','PREPARE','NEW_EVIDENCE'].includes(action))need(!c.confirmation||['RETRY','PUBLISH_DELIVERY'].includes(action),'This case has a recorded confirmation. Reopen the affected evidence explicitly first.');
 if(ORDER.includes(action))need(!has(c,action),'This work is already recorded. Open its history or a different case.');
 if(action==='SCOPE'){need(p.bookingEntity&&p.bookingBasis,'Record the booking entity and its basis.');need(p.reviewed===true,'Review the relationship fields before confirming scope.');need(p.legalName===c.name&&p.country==='Australia'&&p.product==='FX forward','Keep the selected case identity and product context.');c.scope={salesLocation:p.salesLocation||'Australia',bookingEntity:p.bookingEntity,bookingBasis:p.bookingBasis,legalName:p.legalName,country:p.country,product:p.product,purpose:p.purpose||'',reviewed:true};done(c,action);c.controls.Conflicts.status='Ready to start from M1';c.controls.Credit.status='Preparing in parallel';c.controls.Legal.status='Preparing in parallel';}
 else if(action==='ENTITY'){need(has(c,'SCOPE'),'Define the scope first.');need(p.reviewed===true&&p.legalName===c.name&&p.country==='Australia','Review the entity profile and keep the selected applicant identity.');need(p.registrationId&&p.legalForm&&p.address&&p.incorporationDate,'Complete the required profile fields or preserve the unresolved work.');c.entityProfile={...p,revision:(c.entityProfile?.revision||0)+1,source:'Authored v3 sample / explicit manual review'};c.authorityClaim={principal:c.name,employer:c.parent,purpose:p.claimPurpose||'Information coordination',status:'Claim only — not authority'};done(c,action);}
 else if(action==='REQUIREMENTS'){need(has(c,'ENTITY'),'Separate the entity and relationship first.');c.requirements=['Entity identification','Ownership context','Identity disambiguation','Information-coordination authority','Credit conditions','Agreement execution','QA sign-off'];done(c,action);}
 else if(action==='SOURCE'){need(has(c,'REQUIREMENTS'),'Confirm applicable requirements first.');need(!p.sourceFailure,'Synthetic source unavailable. Retry or document the unresolved gap; no evidence was retrieved.');c.evidence[0].status='Sufficient for entity identification';c.evidence[1].status='Sufficient for address only';done(c,action);}
 else if(action==='GAP'){need(has(c,'SOURCE'),'Check permitted evidence before requesting more.');c.request='Issued';done(c,action);}
 else if(action==='UPLOAD'){need(role==='client','Use the Client demo seat.');need(['Issued','Draft response','Clarification requested','Partial response'].includes(c.request),'An open scoped request is required.');need(['identity','authority'].includes(p.item),'Choose one of the two permitted request items.');if(!c.uploads.includes(p.item))c.uploads.push(p.item);c.request='Draft response';}
 else if(action==='FORM_DRAFT'){need(p.form&&p.values,'Provide a form draft.');c.formDrafts??={};c.formDrafts[role+':'+p.form]=p.values;}
 else if(action==='CLIENT_RESPONSE'){need(role==='client','Use the Client demo seat.');need(['Issued','Draft response','Partial response','Clarification requested'].includes(c.request),'An open request is required.');need(p.attestation===true,'Confirm this is your response before submitting.');need(p.response||c.uploads.length||p.addressCorrect,'Answer a question or attach a requested fixture.');if(p.addressCorrect==='no')need(p.address,'Provide the corrected address.');c.clientResponse={...p,receivedAt:new Date().toISOString(),revision:(c.clientResponse?.revision||0)+1};c.inputVersion++;c.request=c.uploads.length===2?'Submitted':'Partial response';for(const item of c.uploads){const id=item==='identity'?'EV-EMP-01':'EV-AUTH-01';c.evidence=c.evidence.filter(e=>e.id!==id);c.evidence.push({id,name:item==='identity'?'Identity and employment fixture':'Authority confirmation fixture',purpose:item==='identity'?'Identity disambiguation':'Information coordination only',status:'Received — intake pending',version:c.inputVersion,source:'Authored v3 sample through scoped client response'});}c.assessments={};c.intake={};c.authority='Not established';}
 else if(action==='INTAKE'){need(role==='ops','KYC Operations records intake checks.');need(note,'Record the intake-check basis.');const e=c.evidence.find(x=>x.id===p.document);need(e&&['EV-EMP-01','EV-AUTH-01'].includes(e.id),'Select received evidence.');c.intake??={};c.intake[e.id]={version:e.version,note};e.status='Available for purpose review';}
 else if(action==='ASSESS'){need(role==='ops','KYC Operations records purpose assessments.');need(note,'Record the source, purpose and assessment basis.');const id=p.purpose==='identity'?'EV-EMP-01':p.purpose==='coordination'?'EV-AUTH-01':null;need(id&&p.document===id,'Use evidence relevant to the selected purpose.');const e=c.evidence.find(x=>x.id===id);need(e&&c.intake?.[id]?.version===e.version,'Complete the current document intake checks first.');need(['sufficient','insufficient','more_info'].includes(p.outcome),'Select an explicit purpose outcome.');c.assessments??={};c.assessments[p.purpose]={outcome:p.outcome,note,document:id,inputVersion:c.inputVersion,documentVersion:e.version};e.status=p.outcome==='sufficient'?'Sufficient for '+e.purpose.toLowerCase():'Further evidence needed for '+e.purpose.toLowerCase();c.authority=c.assessments.coordination?.outcome==='sufficient'?'Information coordination only':'Not established';if(['identity','coordination'].every(k=>c.assessments[k]?.outcome==='sufficient'&&c.assessments[k]?.inputVersion===c.inputVersion)){done(c,'VALIDATE');c.request='Purpose assessed';}else c.done=c.done.filter(x=>!['VALIDATE','MATCH','QA','READINESS','PUBLISH'].includes(x));}
 else if(action==='SUBMIT_RESPONSE'||action==='VALIDATE'){throw new Error('Use the structured response and separate evidence-purpose forms.');}
 else if(action==='POPULATION'){need(has(c,'ENTITY'),'The subject relationships must be reviewed first.');c.population={subjects:[c.name,c.parent,c.subject],queryVersion:1,coverage:p.partial?'Partial':'Complete',source:'Synthetic screening response'};need(!p.partial,'Coverage is partial. Retry the missing subject; complete coverage has not been recorded.');c.controls.Screening.status='Human review required';done(c,action);}
 else if(action==='PREPARE'){need(['ops','specialist','manager','rm'].includes(role),'Choose a preparation role.');const kind=p.kind||'summary';c.prepared[kind]={inputVersion:c.inputVersion,text:kind==='review'?'Cited comparison prepared; authorised human judgement remains required.':kind==='blockers'?readiness(c).reasons.join('; '):`${c.name}: ${overall(c)}. Next work: ${nextStep(c)}.`,sourceRefs:c.evidence.map(e=>e.id)};if(kind==='review')c.reviewPack={inputVersion:c.inputVersion,sourceRefs:c.evidence.map(e=>e.id)};}
 else if(action==='MATCH'){need(has(c,'POPULATION'),'Complete the subject query coverage first.');need(note,'A decision needs a rationale.');need(['false_positive','more_info','escalate'].includes(p.choice),'Choose a scoped disposition.');if(p.choice==='false_positive'){need(has(c,'VALIDATE'),'Received evidence must be assessed for the screening purpose first.');need(c.reviewPack?.inputVersion===c.inputVersion,'Prepare a review pack against the current evidence version.');c.decision={result:'False positive — scoped finding only',note,inputVersion:c.inputVersion,reviewer:ROLES[role][0]};c.controls.Screening.status='Complete';done(c,action);}else if(p.choice==='more_info'){c.request='Clarification requested';c.uploads=[];c.authority='Not established';c.done=c.done.filter(x=>!['VALIDATE','READINESS','QA'].includes(x));c.controls.Screening.status='Waiting for targeted clarification';}else{c.controls.Screening.status='Escalated — human decision pending';c.eddRequired=true;c.eddQuestion=note;c.done=c.done.filter(x=>!['EDD','QA','READINESS'].includes(x));c.controls.EDD.status='Assessment required';c.controls.QA.status='Re-review required';}}
 else if(action==='EDD'){need(has(c,'REQUIREMENTS'),'Record applicability against the requirement set.');need(note,'Record the applicability basis or the specialist assessment.');c.controls.EDD.status=c.eddRequired?'Assessed — conditions recorded':'Not applicable — basis recorded';c.controls.EDD.note=note;done(c,action);}
 else if(action==='CONFLICTS'){need(has(c,'SCOPE'),'Conflicts can begin as soon as M1 scope is recorded.');need(note,'Record the search scope and specialist judgement.');c.controls.Conflicts.status=p.hold?'Scoped hold':'Complete';c.controls.Conflicts.note=note;if(!p.hold)done(c,action);}
 else if(action==='CREDIT'){need(has(c,'SCOPE'),'Record the case scope first.');need(note,'Specify the credit condition and fulfilment basis.');c.creditConditions={version:1,text:note,fulfilled:true};c.controls.Credit.status='Complete';done(c,action);}
 else if(action==='LEGAL'){need(c.creditConditions?.fulfilled,'Legal can prepare in parallel; final execution must consume the current Credit condition.');need(note,'Record the agreement version and execution evidence.');c.agreement={version:1,creditVersion:c.creditConditions.version,executionEvidence:note};c.controls.Legal.status='Complete';done(c,action);}
 else if(action==='QA'){need(['VALIDATE','MATCH','EDD','CONFLICTS','CREDIT','LEGAL'].every(x=>has(c,x)),'Complete the applicable evidence and professional controls before QA sign-off.');need(note,'Record the QA check and result.');if(p.finding){c.qaFinding={note,status:'Open',source:'EV-AUTH-01'};c.controls.QA.status='Targeted remediation required';}else{need(!c.qaFinding||c.qaFinding.status==='Remediated','A remediation must be recorded before independent QA re-review.');c.qaFinding=null;c.controls.QA.status='Complete';done(c,action);}}
 else if(action==='REMEDIATE'){need(role==='ops','KYC Operations records the correction; QA performs re-review.');need(c.qaFinding&&note,'A targeted finding and remediation note are required.');c.qaFinding.status='Remediated';c.qaFinding.remediation=note;c.controls.QA.status='Awaiting independent re-review';}
 else if(action==='READINESS'){const r=readiness(c);need(r.ready,r.reasons.join('. '));c.readinessVersion=c.inputVersion;done(c,action);}
 else if(action==='PUBLISH'){need(has(c,'READINESS')&&readiness(c).ready&&c.readinessVersion===c.inputVersion,'Current complete readiness is required before confirmation.');need(note,'Record the authorised confirmation rationale.');c.confirmation={id:'CONF-'+c.id,inputVersion:c.inputVersion,actor:ROLES[role][0],note,at:new Date().toISOString()};done(c,action);}
 else if(action==='PUBLISH_DELIVERY'||action==='RETRY'){need(role==='rm'||role==='manager','Use the RM or Case Manager demo seat for publication.');need(c.confirmation,'Record the authorised confirmation first.');need(['caseRegister','clientStatus'].includes(p.target),'Choose a publication destination.');need(c.publications[p.target]!=='Delivered','This destination already has a delivery receipt.');c.publications[p.target]=p.fail?'Failed — retry available':'Delivered';}
 else if(action==='NEW_EVIDENCE'){need(role==='ops','Use KYC Operations to register changed evidence.');c.inputVersion++;c.request='Submitted';c.evidence.push({id:'EV-EMP-01',name:'Updated identity fixture',purpose:'Identity disambiguation',status:'Received — not assessed',version:c.inputVersion,source:'Synthetic changed-input fixture'});c.assessments={};c.intake={};c.authority='Not established';c.reviewPack=null;c.decision=null;c.confirmation=null;c.readinessVersion=null;c.controls.Screening.status='Re-review — input changed';c.controls.QA.status='Re-review required';c.done=c.done.filter(x=>!['VALIDATE','MATCH','QA','READINESS','PUBLISH'].includes(x));c.publications={caseRegister:'Not sent',clientStatus:'Not sent'};}
 else if(action==='NOTE'){need(note,'Write a note first.');c.notes.push({note,actor:ROLES[role][0]});}
 else if(action==='MESSAGE'){need(note,'Write a message first.');c.messages.push({note,actor:ROLES[role][0],channel:'Local demo thread only'});}
 else if(action==='DRAFT'){c.decisionDraft={choice:p.choice||'',note};}
 else throw new Error('Unknown demo action.');
 addEvent(c,action,role,note||p.kind||p.item||p.target||action,ORDER.includes(action)?action:null);return c;
}
export function seedCases(){
 const hero=freshCase('CTT-DEMO-001','Entity A');const maple=freshCase('CTT-P-002','Maple Group','gap');const north=freshCase('CTT-P-003','Northbridge Holdings','legal');const aurora=freshCase('CTT-P-008','Aurora Resources','edd');const archived=freshCase('CTT-P-013','Redgum International','archived');
 for(const c of [maple,north,aurora]){done(c,'SCOPE','ENTITY','REQUIREMENTS','SOURCE','GAP');c.scope.bookingEntity='Demo AU booking entity';c.scope.bookingBasis='Synthetic reviewed context';c.request='Issued';c.requirements=['Identity disambiguation','Information-coordination authority','Professional controls'];c.controls.Credit.status='In progress';c.controls.Legal.status='Preparing in parallel';c.controls.Conflicts.status='Ready to start';addEvent(c,'SEED','manager','Authored starting state; not a completed live workflow');}
 done(north,'VALIDATE','POPULATION','MATCH','EDD','CONFLICTS','CREDIT');north.authority='Information coordination only';north.request='Purpose assessed';north.creditConditions={version:1,text:'Synthetic FX limit and signed agreement condition',fulfilled:true};north.evidence.push({id:'EV-EMP-01',name:'Identity and employment fixture',purpose:'Identity disambiguation',status:'Sufficient for identity disambiguation',version:1,source:'Synthetic reviewed starting-state evidence'},{id:'EV-AUTH-01',name:'Information-coordination confirmation',purpose:'Information coordination only',status:'Sufficient for information coordination only',version:1,source:'Synthetic reviewed starting-state evidence'});north.decision={result:'False positive — scoped finding only',inputVersion:1,reviewer:'Sam Ellis'};for(const t of ['Screening','EDD','Conflicts','Credit'])north.controls[t].status='Complete';
 for(const c of [maple,north,aurora]){c.entityProfile={legalName:c.name,country:'Australia',registrationId:'DEMO-AU-'+c.id.slice(-3),legalForm:'Company',incorporationDate:'2014-03-12',address:'12 Market Street, Sydney, Australia',claimPurpose:'Information coordination',reviewed:true,revision:1,source:'Authored v3 profile fixture applied to this separate synthetic case'};if(c.done.includes('VALIDATE')){c.intake={};c.assessments={};for(const [purpose,id] of [['identity','EV-EMP-01'],['coordination','EV-AUTH-01']]){const e=c.evidence.find(x=>x.id===id);c.intake[id]={version:e.version,note:'Authored reviewed starting state'};c.assessments[purpose]={outcome:'sufficient',document:id,documentVersion:e.version,inputVersion:c.inputVersion,note:'Authored reviewed starting state'};}}}
 archived.archived=true;addEvent(archived,'WITHDRAWN','rm','Synthetic new relationship withdrawn before clearance');return [hero,maple,north,aurora,archived];
}
