import {id} from './case-engine.mjs';
import {D_IDS,specialistProjection} from './specialist-engine.mjs';
import {C_IDS} from './screening-engine.mjs';
import {COLLAB_IDS} from './collaboration-engine.mjs';
export const E_SOURCE='SRC-020';
const VERSION='D2-E-Final-1.0', STAMP='2026-09-08T08:00:00Z', SCOPE=id('scope','institutional');
export const E_IDS=Object.freeze({requirement:COLLAB_IDS.ownershipRequirement,evidence:id('evidence','e-ownership'),use:id('assessment','e-ownership'),check:id('qa-check','e-04'),gap:id('gap','e-qa-01'),remediation:id('work','e-remediation-01'),authority:id('authority','e-clearance-reviewer'),signatory:id('authority','e-signatory'),signer:id('person','e-signatory-s'),context:id('decision','e-context'),kyc:id('decision','e-kyc'),edd:id('edd-applicability','e-independent'),population:id('population','e-confirmed'),coverageDecision:id('decision','e-coverage'),conflictDecision:id('decision','e-conflicts'),package:'SYNTHETIC-E-CLOSURE-v1'});
const freeze=x=>{Object.values(x).forEach(v=>{if(v&&typeof v==='object')freeze(v);});return Object.freeze(x);};
export const E_ACTION_ROLES=freeze({open_qa_gap:['ROLE-QA'],submit_remediation:['ROLE-KYCOPS'],complete_remediation:['ROLE-KYCOPS'],qa_rereview:['ROLE-QA'],qa_signoff:['ROLE-QA'],record_demo_context:['ROLE-CASEMGR'],review_kyc_evidence:['ROLE-KYCOPS'],resolve_conflicts:['ROLE-CONFLICTS'],confirm_screening_coverage:['ROLE-FINCRIME'],record_edd_applicability:['ROLE-FINCRIME'],establish_signatory_authority:['ROLE-LEGAL'],execute_legal:['ROLE-LEGAL'],confirm_clearance:['ROLE-CLEARANCE-REVIEWER'],publish_outcome:['ROLE-CASEMGR'],revise_evidence:['ROLE-FACILITATOR'],revise_scope:['ROLE-FACILITATOR'],save_draft:['ROLE-QA','ROLE-KYCOPS','ROLE-CASEMGR','ROLE-CONFLICTS','ROLE-FINCRIME','ROLE-LEGAL','ROLE-CLEARANCE-REVIEWER','ROLE-FACILITATOR']});
const READERS=[...new Set(Object.values(E_ACTION_ROLES).flat()),'ROLE-CREDIT','ROLE-REVIEWER','ROLE-RM','ROLE-CLIENT'];
const authorityConfig=()=>({id:E_IDS.authority,label:'Authorised Clearance Reviewer',role:'ROLE-CLEARANCE-REVIEWER',actions:['confirm_clearance'],case_id:'DEMO-CTT-001',case_scope_id:SCOPE,product_scope_ids:['FX_FORWARD'],status:'configured_for_demo',permission_ref:'SYNTHETIC-E-CONFIRM-PERMISSION-v1',bank_authority_ref:null,bank_role_status:'TO_VALIDATE'});
/** Named authored facts require separate review events; none is a bank policy or retrospective C conclusion. */
export const E_APPROVED_PACKAGE=freeze({id:E_IDS.package,version:1,source_ref:'SRC-020:4:E4;16',status:'approved_synthetic_scenario_package',case_id:'DEMO-CTT-001',case_scope_id:SCOPE,scope_revision:3,entity_refs:[C_IDS.entityA],product_scope_refs:['FX_FORWARD'],bank_policy_ref:null,bank_authority_ref:null,
 context:{booking_context_ref:'SYNTHETIC-E-BOOKING-AU',product_eligibility:'eligible_for_demo',dd_level:'standard_for_demo',ownership_applicability:'required'},
 kyc:{requirement_refs:[id('requirement','identity'),id('requirement','screening-purpose'),COLLAB_IDS.authorityRequirement,C_IDS.identityRequirement],evidence_label:'Independent synthetic entity and Person T identity verification dossier',result:'sufficient_for_each_named_purpose'},
 ownership:{evidence_label:'Synthetic ownership and control dossier E-01',assessment_result:'sufficient',purpose:'ownership_control'},
 screening:{category:'sanctions_name_match',inventory:[{party_ref:C_IDS.entityA,membership:'included'},{party_ref:C_IDS.entityB,membership:'included'},{party_ref:C_IDS.personT,membership:'included'},{party_ref:E_IDS.signer,membership:'included'},{party_ref:COLLAB_IDS.secondContributor,membership:'excluded',basis:'Reviewed synthetic contributor-only relationship; excluded from this category'}],result:'completed',finding_disposition:'not_a_match',finding_basis:'New independently verified synthetic identity dossier; earlier C evidence and unresolved decision remain historical',dataset_ref:'SYNTHETIC-E-DATASET-v1'},
 conflicts:{decision:'resolved_for_demo',finding_ref:D_IDS.conflictFinding},legal:{agreement_ref:D_IDS.agreement,agreement_revision:3,credit_input_ref:D_IDS.agreementInput,credit_input_revision:1,signer_ref:E_IDS.signer,authority_basis:'Independent synthetic board mandate for Signatory S; no inference from Person T coordination authority',execution:'executed_for_demo'},
 edd:{applicability:'not_required',basis:'Independent synthetic E risk review for current scope; not inferred from screening disposition'},publication:{permitted_target_refs:['SYNTHETIC-E-OUTCOME-REGISTER'],outcomes:['succeeded','failed']}});
export const E_ALIAS_CHAIN=freeze([['REQ-B05',E_IDS.requirement,'requirements','reuse_existing_B_ownership_control'],['EUA-05',E_IDS.use,'evidenceUseAssessments','new_purpose_assessment'],['QA-04',E_IDS.check,'qaChecks','new'],['GAP-QA-01',E_IDS.gap,'qaFindings','new'],['RT-01',E_IDS.remediation,'workItems','reuse_work_store']].map(([raw_alias,object_ref,collection,mapping])=>({source_alias:`SRC-020:${raw_alias}`,raw_alias,object_ref,collection,mapping})));
const DOMAIN=['evidence','screening','edd','qa','conflicts','legal','credit'];
const D_EDGES=['conflicts-start','credit-start','legal-start','assessment-decision-1','decision-condition-1','condition-input-1','credit-legal-1'].map(x=>id('dependency',`d-${x}`));
const HISTORICAL_DEPENDENCIES=[
 ...['d2-04-1','d2-05-2','d2-05-3','d2-07-4','d2-12-5'].map(slug=>({id:id('dependency',slug),basis_ref:'SRC-020:5:PREREQ-01/02',reason:'Unchanged legacy A evidence/screening workflow; superseded in E by explicit purpose assessments and full population coverage'})),
 ...['conflicts','credit','legal'].map(domain=>({id:id('dependency','d-readiness-'+domain),basis_ref:'SRC-020:5:PREREQ-03',reason:'Unchanged D-entry readiness contribution; E derives the current specialist prerequisite from current scoped outputs'}))
];
const SCREENING_COLLECTIONS=['screeningPopulations','screeningMemberships','screeningRuns','runSubjectSnapshots','screeningResultSnapshots','screeningFindings','screeningReviewDecisions','screeningCoverageItems','screeningQueryPlans','providerRecordSnapshots','attributeComparisons'];
const E_EDGES=[['requirement-use','requirements',E_IDS.requirement,'evidenceUseAssessments',E_IDS.use,'SRC-009:DEP-09'],['use-qa','evidenceUseAssessments',E_IDS.use,'qaChecks',E_IDS.check,'SRC-009:DEP-09'],['qa-gap','qaChecks',E_IDS.check,'qaFindings',E_IDS.gap,'SRC-009:DEP-10'],['gap-task','qaFindings',E_IDS.gap,'workItems',E_IDS.remediation,'SRC-010:DEP-11'],['task-qa','workItems',E_IDS.remediation,'qaChecks',E_IDS.check,'SRC-010:DEP-11']];
const latest=(s,n,ref)=>s?.[n]?.filter(x=>!ref||x.id===ref).at(-1);
const current=(s,n)=>[...new Map((s?.[n]||[]).map(x=>[x.id,x])).values()];
const fail=code=>{const e=new Error(code);e.code=code;throw e;};
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const equal=(a,b)=>JSON.stringify(canonical(a))===JSON.stringify(canonical(b));
export function clearanceFingerprint(v){const t=JSON.stringify(canonical(v));let a=2166136261,b=5381;for(let i=0;i<t.length;i++){a=Math.imul(a^t.charCodeAt(i),16777619);b=Math.imul(b,33)^t.charCodeAt(i);}return `${t.length}:${a>>>0}:${b>>>0}`;}
const rec=(s,ref,fields={},at=STAMP)=>({id:ref,case_id:s.case.id,case_scope_id:s.scopes[0].id,case_scope_ref:s.scopes[0].id,scope_revision:s.scopes[0].revision,revision:1,source_refs:[E_SOURCE],source_status:'SYNTHETIC',synthetic:true,simulation_flag:true,provenance:'authored_synthetic_scenario',bank_policy_ref:null,bank_authority_ref:null,authority_status:'demo_only_bank_unknown',created_at:at,updated_at:at,...fields});
const scoped=(s,x)=>Boolean(x&&s.scopes?.[0]&&x.case_id===s.case.id&&x.case_scope_id===s.scopes[0].id&&(!Object.hasOwn(x,'case_scope_ref')||x.case_scope_ref===s.scopes[0].id)&&x.scope_revision===s.scopes[0].revision&&Number.isSafeInteger(x.revision)&&x.revision>0);
const append=(s,n,prior,fields,at)=>{const x={...structuredClone(prior),...fields,source_refs:[...new Set([...(prior.source_refs||[]),E_SOURCE])],scope_revision:s.scopes[0].revision,revision:prior.revision+1,supersedes_revision:prior.revision,updated_at:at};s[n].push(x);return x;};
function contextValid(s){return s?.case?.id==='DEMO-CTT-001'&&s?.scopes?.length===1&&s.scopes[0].id===SCOPE&&s.scopes[0].case_id===s.case.id&&Number.isSafeInteger(s.scopes[0].revision)&&s.scopes[0].revision>0&&s.demoConfig?.batchE?.version===VERSION;}
function packageValid(s){return equal(s.demoConfig?.batchE?.closure_package,E_APPROVED_PACKAGE)&&s.scopes?.[0]?.revision===3&&equal(s.scopes[0].entity_ids,E_APPROVED_PACKAGE.entity_refs)&&equal(s.scopes[0].product_scope_ids,E_APPROVED_PACKAGE.product_scope_refs);}
function authorityValid(s){const cfg=s.demoConfig?.batchE?.authority,a=latest(s,'authorities',E_IDS.authority);return equal(cfg,authorityConfig())&&equal(s.demoConfig.batchE.action_roles,E_ACTION_ROLES)&&scoped(s,a)&&a.owner_role===cfg.role&&a.demo_permission_ref===cfg.permission_ref&&a.bank_authority_ref===null&&a.status==='configured_for_demo'&&equal(a.action_scope,['confirm_clearance'])&&equal(a.product_scope_ids,['FX_FORWARD']);}
const effectiveHolds=s=>current(s,'holds').concat(s.demoConfig?.batchA?.holds||[],s.demoConfig?.batchC?.holds||[]).filter(h=>h.status!=='released');
function businessBasis(s){const excluded=new Set(['case','readinessSnapshots','auditEvents','clearancePrerequisites','clearanceDecisions','publicationEvents','clearanceConditions','conditionHistory']);return Object.fromEntries(Object.entries(s).filter(([k])=>!excluded.has(k)).map(([k,v])=>[k,k==='workItems'?v.filter(x=>x.work_type!=='e_action_draft'):v]));}
const basisHash=s=>clearanceFingerprint(businessBasis(s||{}));
function inputs(s){const records=Object.values(s).filter(Array.isArray).flat().filter(x=>x?.id&&x.revision);return {...Object.fromEntries(records.map(x=>[x.id,x.revision])),[s.case.id]:s.case.revision,'SRC-020:content':clearanceFingerprint(s)};}
function newEvidence(s,slug,subject,purpose,at){const x=rec(s,id('evidence',slug),{subject_id:subject,purpose_code:purpose,evidence_revision:1,content_revision:1,receipt_status:'received',intake_security_status:'released',verification_status:'verified_for_demo',content_ref:`synthetic:${E_IDS.package}:${slug}`,content_attributes:{package_ref:E_IDS.package,purpose},source_record_ref:`${E_IDS.package}:${slug}`},at);s.evidence.push(x);return x;}
function assessment(s,r,e,ref,at,fields={}){const x=rec(s,ref,{requirement_id:r.id,requirement_revision:r.revision,evidence_id:e.id,evidence_revision:e.evidence_revision,evidence_record_revision:e.revision,evidence_fingerprint:clearanceFingerprint(e),content_revision:e.content_revision,subject_id:r.subject_id,purpose_code:r.purpose_code,sufficiency:'sufficient',basis_refs:[e.id,E_IDS.package],assessed_by_ref:'ROLE-KYCOPS',assessment_permission_ref:'SYNTHETIC-E-PURPOSE-REVIEW-v1',assessed_at:at,...fields},at);s.evidenceUseAssessments.push(x);return x;}
function useValid(s,r){if(!r)return false;const u=s.evidenceUseAssessments?.filter(x=>x.requirement_id===r.id).at(-1),e=latest(s,'evidence',u?.evidence_id);return reviewEventValid(s,u,u?.review_event_ref,r.id===E_IDS.requirement?'complete_remediation':'review_kyc_evidence')&&u.assessed_by_ref==='ROLE-KYCOPS'&&scoped(s,r)&&r.applicability==='required'&&r.status==='satisfied'&&scoped(s,u)&&scoped(s,e)&&u.evidence_fingerprint===clearanceFingerprint(e)&&u.requirement_revision===r.revision&&u.sufficiency==='sufficient'&&u.purpose_code===r.purpose_code&&u.subject_id===r.subject_id&&e.subject_id===r.subject_id&&u.evidence_revision===e.evidence_revision&&u.evidence_record_revision===e.revision&&u.content_revision===e.content_revision&&e.receipt_status==='received'&&e.intake_security_status==='released'&&u.basis_refs?.includes(e.id)&&u.assessment_permission_ref==='SYNTHETIC-E-PURPOSE-REVIEW-v1';}
function creditValid(s){const credit=latest(s,'creditAssessments',D_IDS.creditAssessment),condition=latest(s,'creditConditions',D_IDS.creditCondition),input=latest(s,'agreementInputs',D_IDS.agreementInput),decision=latest(s,'decisions',credit?.decision_ref),entry=s.demoConfig?.batchE?.credit_baseline;return [credit,condition,input,decision].every(x=>scoped(s,x))&&entry&&equal({credit,condition,input,decision},entry)&&credit.revision===1&&input.revision===E_APPROVED_PACKAGE.legal.credit_input_revision&&condition.revision===1&&credit.applicability==='required'&&credit.assessment_status==='complete'&&decision.outcome==='approved_subject_to_condition'&&condition.credit_assessment_revision===credit.revision&&condition.status==='approved'&&input.credit_condition_revision===condition.revision&&input.condition_text===condition.condition_text&&input.credit_decision_ref===decision.id&&decision.input_revisions?.[credit.id]===credit.revision;}
function dependenciesValid(s){return D_EDGES.every(ref=>{const d=latest(s,'dependencies',ref),original=s.demoConfig?.batchE?.dependency_baseline?.find(x=>x.id===ref);return d&&original&&equal(d,original)&&scoped(s,d)&&d.validation_status==='reviewed_for_demo'&&d.status==='satisfied'&&['task','branch','case'].includes(d.impact_scope);});}
function eDependenciesValid(s){return E_EDGES.every(([slug,fc,fr,tc,tr])=>{const d=latest(s,'dependencies',id('dependency','e-'+slug)),from=latest(s,fc,fr),to=latest(s,tc,tr);return scoped(s,d)&&from&&to&&d.from_object_ref===fr&&d.to_object_ref===tr&&d.from_revision===from.revision&&d.to_revision===to.revision&&d.validation_status==='reviewed_for_demo'&&d.status==='satisfied';});}
function refreshEdges(s,at){for(const [slug,fc,fr,tc,tr,alias] of E_EDGES){const from=latest(s,fc,fr),to=latest(s,tc,tr),ref=id('dependency','e-'+slug),previous=latest(s,'dependencies',ref),fields={from_ref:fr,to_ref:tr,from_object_ref:fr,from_revision:from?.revision??null,to_object_ref:tr,to_revision:to?.revision??null,dependency_type:'e_purpose_remediation',impact_scope:'task',dependency_condition:'Current purpose-specific reference required',status:from&&to?'satisfied':'unknown',validation_status:'reviewed_for_demo',source_aliases:[alias,'SRC-020:4:E2'],created_from_ref:'SRC-020:4:E2',required_input_revision:from?.revision??null};if(!previous)s.dependencies.push(rec(s,ref,fields,at));else if(Object.entries(fields).some(([k,v])=>!equal(previous[k],v)))append(s,'dependencies',previous,fields,at);}}
function holdImpact(s,h,domains){
 if(['released','inactive'].includes(h.status))return 'unaffected';
 if(h.status==='unknown'||!['task','branch','case'].includes(h.hold_scope||h.scope))return 'unknown';
 if((h.hold_scope||h.scope)==='case')return 'affected';
 const refs=h.object_scope_refs?.length?h.object_scope_refs:h.target_object_ref?[h.target_object_ref]:[];
 if(!refs.length)return 'unknown';
 const mappings={evidence:[E_IDS.requirement,E_IDS.evidence,E_IDS.use,E_IDS.kyc,E_IDS.context],qa:[E_IDS.check,E_IDS.gap,E_IDS.remediation],screening:[E_IDS.population,E_IDS.coverageDecision,C_IDS.finding,C_IDS.population],edd:[E_IDS.edd,C_IDS.edd],conflicts:[D_IDS.conflictReview,D_IDS.conflictFinding],credit:[D_IDS.creditAssessment,D_IDS.creditCondition,D_IDS.agreementInput],legal:[D_IDS.agreement,E_IDS.signatory]};
 let unknown=false;
 for(const ref of refs){if([s.case.id,s.scopes[0].id].includes(ref))return 'affected';if(latest(s,'workItems',ref)?.work_type==='e_action_draft')continue;
  const related=Object.entries(mappings).filter(([,ids])=>ids.includes(ref)).map(([domain])=>domain);
  if(!related.length){unknown=true;continue;}if(related.some(x=>domains.includes(x)))return 'affected';
 }
 return unknown?'unknown':'unaffected';
}
function recordBinding(collection,record){return {collection,id:record.id,revision:record.revision,fingerprint:clearanceFingerprint(record)};}
function screeningBindings(s){return SCREENING_COLLECTIONS.flatMap(collection=>current(s,collection).map(record=>recordBinding(collection,record))).sort((a,b)=>(a.collection+':'+a.id).localeCompare(b.collection+':'+b.id));}
function recordByRef(s,ref){return [s.case,...Object.entries(s).filter(([key,value])=>Array.isArray(value)&&!['conditionHistory','readinessSnapshots','clearancePrerequisites'].includes(key)).flatMap(([,value])=>value)].filter(x=>x?.id===ref).at(-1);}
function extraDependencyState(s,domains){
 const expected=new Set([...D_EDGES,...E_EDGES.map(([slug])=>id('dependency','e-'+slug))]),history=s.demoConfig?.batchE?.historical_dependency_exclusions||[],blocking=[],applicable=[];
 for(const d of current(s,'dependencies')){
  if(expected.has(d.id))continue;
  const exclusion=history.find(x=>x.id===d.id),rule=HISTORICAL_DEPENDENCIES.find(x=>x.id===d.id);
  if(exclusion&&rule&&exclusion.basis_ref===rule.basis_ref&&exclusion.reason===rule.reason&&equal(exclusion.binding,recordBinding('dependencies',d)))continue;
  const from=d.from_object_ref||d.from_ref,to=d.to_object_ref||d.to_ref;
  const impact=holdImpact(s,{hold_scope:d.impact_scope,status:'active',object_scope_refs:[to]},domains);
  if(impact==='unaffected')continue;
  applicable.push(d.id);
  const a=recordByRef(s,from),b=recordByRef(s,to);
  if(!scoped(s,d)||!['task','branch','case'].includes(d.impact_scope)||impact==='unknown'
   ||!a||!b||d.from_revision!==a.revision||d.to_revision!==b.revision
   ||d.from_ref&&d.from_ref!==from||d.to_ref&&d.to_ref!==to
   ||d.status!=='satisfied'||d.validation_status!=='reviewed_for_demo')blocking.push(d.id);
 }
 return {blocking,applicable};
}
function decisionScope(s){return {entity_refs:[...s.scopes[0].entity_ids],product_refs:[...s.scopes[0].product_scope_ids],scope_revision:s.scopes[0].revision};}
const reviewActions={demo_context:'record_demo_context',kyc_evidence:'review_kyc_evidence',conflicts_resolution:'resolve_conflicts',screening_coverage:'confirm_screening_coverage',legal_execution:'execute_legal'};
const outputBinding=x=>({id:x.id,revision:x.revision,fingerprint:clearanceFingerprint(x)});
// Exact authored review output versions are required; legacy unbound records stay readable but need review.
function reviewEventValid(s,record,eventRef,action){
 const event=s.auditEvents?.find(x=>x.id===eventRef);
 return scoped(s,record)&&scoped(s,event)&&event.event_type===action&&E_ACTION_ROLES[action]?.includes(event.actor_ref)
  &&event.actor_type==='human_demo'&&event.source_refs?.includes(E_SOURCE)&&event.package_ref===E_IDS.package
  &&event.bank_authority_ref===null&&record.bank_authority_ref===null&&event.object_refs?.includes(record.id)
  &&event.occurred_at===record.updated_at&&event.output_bindings?.some(b=>equal(b,outputBinding(record)));
}
function proof(s,ref,type){const d=latest(s,'decisions',ref),event=s.auditEvents?.find(x=>x.id===d?.event_ref);
 return scoped(s,d)&&d.decision_type===type&&d.package_ref===E_IDS.package&&d.record_status==='recorded'
  &&reviewEventValid(s,d,d.event_ref,reviewActions[type])&&d.demo_role_ref===event.actor_ref&&equal(d.input_revisions,event.expected_input_revisions);
}
function qaCurrent(s){
 const q=latest(s,'qaChecks',E_IDS.check),u=latest(s,'evidenceUseAssessments',E_IDS.use),r=latest(s,'requirements',E_IDS.requirement),
  reviewed=s.qaChecks?.find(x=>x.id===q?.id&&x.revision===q?.rereview_revision);
 return scoped(s,q)&&q.reviewed_by_ref==='ROLE-QA'&&useValid(s,r)&&q.reviewed_use_revision===u?.revision&&q.reviewed_requirement_revision===r?.revision
  &&reviewEventValid(s,reviewed,q.rereview_ref,'qa_rereview')&&reviewed.reviewed_by_ref==='ROLE-QA'
  &&reviewed.reviewed_use_revision===u.revision&&reviewed.reviewed_requirement_revision===r.revision
  &&(q.check_status==='passed'&&q.revision===reviewed.revision||q.check_status==='signed_off'&&reviewEventValid(s,q,q.signoff_ref,'qa_signoff'));
}
function screenValid(s){
 const pop=latest(s,'screeningPopulations',E_IDS.population),pkg=E_APPROVED_PACKAGE.screening,review=latest(s,'decisions',E_IDS.coverageDecision);
 if(!scoped(s,pop)||pop.inventory_status!=='complete_for_scope'||pop.population_review_status!=='confirmed'||!proof(s,E_IDS.coverageDecision,'screening_coverage')
  ||!equal(review.reviewed_screening_bindings,screeningBindings(s)))return false;
 if(!equal([...current(s,'entities'),...current(s,'naturalPersons')].map(x=>x.id).sort(),pkg.inventory.map(x=>x.party_ref).sort()))return false;
 const membership=current(s,'screeningMemberships').filter(x=>x.population_ref===pop.id),cov=current(s,'screeningCoverageItems').filter(x=>x.population_ref===pop.id);
 if(membership.length!==pkg.inventory.length||cov.length!==4||!equal([...pop.membership_refs].sort(),membership.map(x=>x.id).sort()))return false;
 const disposition=latest(s,'screeningReviewDecisions',id('screening-decision','e-person-t')),finding=latest(s,'screeningFindings',C_IDS.finding);
 if(!scoped(s,disposition)||!scoped(s,finding)||disposition.disposition!=='not_a_match'||disposition.decision_status!=='recorded'
  ||disposition.finding_ref!==finding.id||disposition.finding_revision!==finding.revision||disposition.finding_fingerprint!==clearanceFingerprint(finding)
  ||finding.subject_ref!==C_IDS.personT||finding.category!==pkg.category||disposition.new_evidence_ref!==id('evidence','e-kyc-person-t')
  ||!useValid(s,latest(s,'requirements',C_IDS.identityRequirement)))return false;
 // Only the exact older placeholder captured before E is outside this current review; no new finding is silently excluded.
 for(const f of current(s,'screeningFindings')){
  if(f.id===C_IDS.finding)continue;
  const historical=review.historical_finding_exclusions?.find(x=>x.id===f.id);
  if(f.id!==id('finding','possible-match')||!historical||historical.basis_ref!=='SRC-020:5:PREREQ-02'
   ||!equal(historical.binding,recordBinding('screeningFindings',f)))return false;
 }
 for(const item of pkg.inventory){
  const m=membership.find(x=>x.party_ref===item.party_ref),party=latest(s,'entities',item.party_ref)||latest(s,'naturalPersons',item.party_ref);
  if(!scoped(s,m)||m.membership_decision!==item.membership||m.party_revision!==party?.revision||m.party_fingerprint!==clearanceFingerprint(party)
   ||m.screening_category!==pkg.category||m.criterion_ref!==`${E_IDS.package}:screening:${item.party_ref.split('/').at(-1)}`)return false;
  if(item.membership==='excluded'){if(m.exclusion_basis!==item.basis)return false;continue;}
  const slug=item.party_ref.split('/').at(-1),c=cov.find(x=>x.party_ref===item.party_ref),run=latest(s,'screeningRuns',c?.run_ref),
   result=latest(s,'screeningResultSnapshots',run?.result_snapshot_refs?.[0]),subject=latest(s,'runSubjectSnapshots',run?.subject_snapshot_refs?.[0]);
  if(![c,run,result,subject].every(x=>scoped(s,x))||c.coverage_status!=='complete'||c.category!==pkg.category
   ||c.run_ref!==id('screening-run','e-'+slug)||run.run_status!=='completed'||run.category!==pkg.category||run.required!==true
   ||run.dataset_ref!==pkg.dataset_ref||run.population_ref!==pop.id||run.population_revision!==pop.population_revision
   ||!equal(run.subject_refs,[item.party_ref])||!equal(run.result_snapshot_refs,[id('screening-result','e-'+slug)])
   ||!equal(run.subject_snapshot_refs,[id('run-subject','e-'+slug)])||subject.party_ref!==item.party_ref
   ||subject.party_revision!==party.revision||subject.category!==pkg.category||subject.population_ref!==pop.id
   ||result.result_status!=='completed'||result.run_ref!==run.id||result.run_revision!==run.revision||result.data_snapshot_ref!==pkg.dataset_ref)return false;
  const expectedCount=item.party_ref===C_IDS.personT?1:0;
  if(result.result_count!==expectedCount||result.disposition_ref!==(expectedCount?disposition.id:null))return false;
  if(expectedCount&&disposition.result_ref!==result.id)return false;
 }
 return true;
}
function signatoryValid(s){const a=latest(s,'authorities',E_IDS.signatory),u=latest(s,'evidenceUseAssessments',a?.evidence_use_refs?.[0]),e=latest(s,'evidence',u?.evidence_id);
 return [a,u,e].every(x=>scoped(s,x))&&reviewEventValid(s,a,a.decision_ref,'establish_signatory_authority')
  &&reviewEventValid(s,u,u.review_event_ref,'establish_signatory_authority')&&u.assessed_by_ref==='ROLE-LEGAL'&&a.status==='established_for_demo'&&a.action_type==='execute_agreement'&&a.subject_ref===E_IDS.signer
  &&a.principal_entity_id===C_IDS.entityA&&a.bank_authority_ref===null&&equal(a.product_scope_refs,['FX_FORWARD'])
  &&u.purpose_code==='execute_agreement'&&u.sufficiency==='sufficient'&&u.subject_id===E_IDS.signer
  &&u.evidence_revision===e.evidence_revision&&u.evidence_record_revision===e.revision&&u.evidence_fingerprint===clearanceFingerprint(e);
}
function legalValid(s){
 const a=latest(s,'legalAgreements',D_IDS.agreement),authority=latest(s,'authorities',E_IDS.signatory),doc=latest(s,'evidence',a?.executed_document_ref),
  execution=latest(s,'decisions',id('decision','e-legal-execution'));
 return creditValid(s)&&signatoryValid(s)&&scoped(s,a)&&a.execution_status==='executed'
  &&a.credit_input_revision===latest(s,'agreementInputs',D_IDS.agreementInput)?.revision&&a.approval_status==='internally_approved'
  &&a.signatory_authority_refs?.includes(E_IDS.signatory)&&scoped(s,authority)&&authority.action_type==='execute_agreement'
  &&authority.subject_ref===E_IDS.signer&&authority.principal_entity_id===C_IDS.entityA&&authority.status==='established_for_demo'
  &&authority.bank_authority_ref===null&&authority.package_ref===E_IDS.package&&scoped(s,doc)
  &&doc.subject_id===C_IDS.entityA&&doc.purpose_code==='legal_execution'&&doc.receipt_status==='received'
  &&doc.intake_security_status==='released'&&doc.verification_status==='verified_for_demo'
  &&proof(s,id('decision','e-legal-execution'),'legal_execution')&&execution.executed_document_ref===doc.id
  &&execution.executed_document_revision===doc.revision&&execution.executed_evidence_revision===doc.evidence_revision
  &&execution.executed_content_revision===doc.content_revision&&execution.executed_document_fingerprint===clearanceFingerprint(doc)
  &&execution.agreement_ref===a.id&&execution.agreement_revision===a.revision&&execution.agreement_fingerprint===clearanceFingerprint(a)
  &&execution.credit_input_revision===a.credit_input_revision&&execution.signatory_authority_ref===authority.id;
}
function evaluate(s={}, {checkStored=true}={}){
 const valid=contextValid(s),scope=s.scopes?.[0],qs=latest(s,'qaChecks',E_IDS.check),base={readiness_state:'NOT_READY',scope_revision:scope?.revision??null,fingerprint:basisHash(s),blocking_condition_refs:[],unknown_condition_refs:[]};if(!valid)return {conditions:[],prerequisites:[],readiness:{...base,blocking_condition_refs:['E_CONTEXT_REQUIRED']}};
 const requirements=current(s,'requirements'),reqRefs=[E_IDS.requirement,...E_APPROVED_PACKAGE.kyc.requirement_refs],context=latest(s,'decisions',E_IDS.context),contextOk=proof(s,E_IDS.context,'demo_context')&&equal(context.context,E_APPROVED_PACKAGE.context);
 const evidenceOk=contextOk&&proof(s,E_IDS.kyc,'kyc_evidence')&&reqRefs.every(ref=>useValid(s,requirements.find(x=>x.id===ref)))&&requirements.length===reqRefs.length&&requirements.every(r=>reqRefs.includes(r.id)&&useValid(s,r));
 const edd=latest(s,'eddApplicabilityAssessments',E_IDS.edd),eddOk=reviewEventValid(s,edd,edd?.decision_ref,'record_edd_applicability')&&edd.decided_by_ref==='ROLE-FINCRIME'&&edd.permission_ref==='SYNTHETIC-E-EDD-REVIEW-v1'&&scoped(s,edd)&&edd.applicability==='not_required'&&edd.review_status==='decided'&&edd.policy_basis_ref==='SYNTHETIC-E-INDEPENDENT-RISK-REVIEW-v1'&&edd.package_ref===E_IDS.package;
 const conflict=latest(s,'conflictReviews',D_IDS.conflictReview),finding=latest(s,'conflictFindings',D_IDS.conflictFinding),conflictsOk=proof(s,E_IDS.conflictDecision,'conflicts_resolution')&&scoped(s,conflict)&&scoped(s,finding)&&conflict.clearance_status==='recorded'&&finding.resolution_status==='resolved'&&conflict.decision_ref===E_IDS.conflictDecision;
 const states={evidence:evidenceOk?'satisfied':'pending',screening:screenValid(s)?'satisfied':'pending',edd:eddOk?'not_required':'unknown',qa:qaCurrent(s)&&qs.check_status==='signed_off'?'satisfied':'pending',conflicts:conflictsOk?'satisfied':'pending',legal:legalValid(s)?'satisfied':'pending',credit:creditValid(s)?'satisfied':'pending'};
 const owners={evidence:'ROLE-KYCOPS',screening:'ROLE-FINCRIME',edd:'ROLE-FINCRIME',qa:'ROLE-QA',conflicts:'ROLE-CONFLICTS',legal:'ROLE-LEGAL',credit:'ROLE-CREDIT'},actions={evidence:'review_kyc_evidence',screening:'confirm_screening_coverage',edd:'record_edd_applicability',qa:qs?.check_status==='passed'?'qa_signoff':'qa_rereview',conflicts:'resolve_conflicts',legal:'execute_legal',credit:'review_current_credit_inputs'};
 const conditions=DOMAIN.map(domain=>{const raw=s.clearanceConditions?.find(c=>c.id===id('condition',domain));let status=states[domain],applicability=domain==='edd'?(eddOk?'not_required':'unknown'):'required';const missing=!raw||raw.case_id!==s.case.id||raw.case_scope_id!==scope.id||!Number.isSafeInteger(raw.revision);
  if(missing||(checkStored&&(!['required','not_required','unknown'].includes(raw.applicability)||!['satisfied','not_required','pending','unknown'].includes(raw.status)))){status='unknown';applicability='unknown';}
  if(checkStored&&raw&&(raw.status!==status||raw.applicability!==applicability||raw.scope_revision!==scope.revision)&&['satisfied','not_required'].includes(status))status='pending';
  return {id:id('condition',domain),domain,applicability,status,condition_status:status,owner_role_ref:owners[domain],owner:owners[domain],revision:raw?.revision??null,scope_revision:scope.revision,reason:status==='satisfied'?'current_scoped_outputs_verified':status==='not_required'?'independent_applicability_decision':'current_scoped_review_required',waitingFor:['satisfied','not_required'].includes(status)?[]:[actions[domain]],next_action:actions[domain],dependency_refs:(s.dependencies||[]).filter(d=>d.from_object_ref===id('condition',domain)).map(d=>d.id)};});
 const defs=[['PREREQ-01','kyc_evidence',['evidence','qa','edd'],'ROLE-QA'],['PREREQ-02','screening',['screening','edd'],'ROLE-FINCRIME'],['PREREQ-03','specialists',['conflicts','credit','legal'],'ROLE-CASEMGR']],depsOk=dependenciesValid(s)&&eDependenciesValid(s);
 const prerequisites=defs.map(([alias,type,domains,owner])=>{const cs=conditions.filter(c=>domains.includes(c.domain)),blocking=cs.filter(c=>!['satisfied','not_required'].includes(c.status)).map(c=>c.id);if(!depsOk)blocking.push('E_REQUIRED_DEPENDENCY_UNKNOWN');const additionalDependencies=extraDependencyState(s,domains);blocking.push(...additionalDependencies.blocking);const holdImpacts=effectiveHolds(s).map(h=>holdImpact(s,h,domains));if(holdImpacts.some(x=>x!=='unaffected'))blocking.push(holdImpacts.includes('unknown')?'E_HOLD_IMPACT_UNKNOWN':'E_HOLD_REQUIRES_REVIEW');return {id:id('prerequisite',`e-${alias.toLowerCase()}`),alias,case_scope_ref:scope.id,scope_revision:scope.revision,prerequisite_type:type,applicability:'required',condition_refs:cs.map(c=>c.id),dependency_refs:[...D_EDGES,...E_EDGES.map(([slug])=>id('dependency','e-'+slug)),...additionalDependencies.applicable],status:blocking.length?'pending':'satisfied',blocking_reason_refs:blocking,owner_role_ref:owner,last_evaluated_at:s.case.updated_at};});
 const extraUnknown=s.clearanceConditions?.length!==DOMAIN.length||(s.clearanceConditions||[]).some(c=>!DOMAIN.includes(c.domain)||c.id!==id('condition',c.domain)),ready=packageValid(s)&&authorityValid(s)&&!extraUnknown&&prerequisites.every(x=>x.status==='satisfied'),decision=latest(s,'clearanceDecisions'),snapshot=s.readinessSnapshots?.find(x=>x.id===decision?.readiness_snapshot_ref),currentDecision=ready&&decision&&scoped(s,decision)&&scoped(s,snapshot)&&equal(decision.decision_scope,decisionScope(s))&&equal(snapshot.decision_scope,decisionScope(s))&&equal(decision.decision_scope.product_refs,authorityConfig().product_scope_ids)&&snapshot.readiness_state==='READY_FOR_AUTHORISED_CONFIRMATION'&&snapshot.fingerprint===base.fingerprint&&decision.basis_fingerprint===base.fingerprint&&decision.authority_ref===E_IDS.authority&&decision.confirmed_by_ref===authorityConfig().role&&decision.decision==='CLEARED_TO_TRADE'&&s.auditEvents.some(e=>e.event_type==='confirm_clearance'&&e.object_refs?.includes(decision.id));
 return {conditions,prerequisites,readiness:{...base,readiness_state:currentDecision?'CLEARED_TO_TRADE':ready?'READY_FOR_AUTHORISED_CONFIRMATION':'NOT_READY',blocking_condition_refs:[...new Set(prerequisites.flatMap(x=>x.blocking_reason_refs).concat(!packageValid(s)?['E_PACKAGE_OR_SCOPE_INVALID']:[],extraUnknown?['E_UNMODELLED_CONDITION']:[]))],unknown_condition_refs:conditions.filter(c=>c.applicability==='unknown'||c.status==='unknown').map(c=>c.id)},currentDecision:currentDecision?decision:null};
}
function refresh(s,at,eventRef,{updateConditions=true}={}){if(updateConditions)refreshEdges(s,at);for(const c of updateConditions?evaluate(s,{checkStored:false}).conditions:[]){const raw=s.clearanceConditions.find(x=>x.id===c.id);if(!raw)continue;const fields={applicability:c.applicability,status:c.status,status_reason:c.reason,scope_revision:s.scopes[0].revision,owner_role:c.owner_role_ref,dependency_refs:c.dependency_refs};if(Object.entries(fields).some(([k,v])=>!equal(raw[k],v))){s.conditionHistory.push(structuredClone(raw));Object.assign(raw,fields,{revision:raw.revision+1,updated_at:at});}}
 const now=evaluate(s),refs=[];for(const p of now.prerequisites){const x=rec(s,`${p.id}-${s.case.revision}`,{...p,id:`${p.id}-${s.case.revision}`,evaluated_case_revision:s.case.revision},at);s.clearancePrerequisites.push(x);refs.push(x.id);}
 s.readinessSnapshots.push(rec(s,id('snapshot',`e-${s.case.revision}`),{...now.readiness,decision_scope:decisionScope(s),evaluated_at:at,prerequisite_snapshot_refs:refs,basis_refs:now.conditions.map(c=>c.id),basis_event_refs:[eventRef],condition_revisions:Object.fromEntries(s.clearanceConditions.map(c=>[c.id,c.revision])),supersedes_ref:s.readinessSnapshots.at(-1)?.id||null},at));}
/** Explicit E entry adds a present-but-unassessed dossier and closes no upstream unknown. */
export function createBatchE(input){if(input?.demoConfig?.batchE){if(!contextValid(input))fail('E_CONTEXT_REQUIRED');return input;}
 const dEntry=specialistProjection(input,{role:'ROLE-FACILITATOR'});
 if(!dEntry.available||dEntry.legal?.current_credit_input_revision!==1||dEntry.legal?.agreement_revision!==3||dEntry.legal?.input_currency!=='current'||dEntry.legal?.execution_status!=='pending'||input.scopes?.[0]?.revision!==3||!input.requirements?.some(r=>r.id===E_IDS.requirement&&r.purpose_code==='ownership_control'))fail('E_D_CONTEXT_REQUIRED');
 const s=structuredClone(input);for(const n of ['qaChecks','qaFindings','clearancePrerequisites','clearanceDecisions','publicationEvents','conditionHistory'])s[n]||=[];const credit=latest(s,'creditAssessments',D_IDS.creditAssessment);
 s.demoConfig.batchE={version:VERSION,source_refs:[E_SOURCE],entry:'E-entry',entry_scope_revision:s.scopes[0].revision,closure_package:structuredClone(E_APPROVED_PACKAGE),authority:authorityConfig(),action_roles:structuredClone(E_ACTION_ROLES),bank_authority_ref:null,bank_policy_ref:null,bank_role_status:'TO_VALIDATE',aliases:structuredClone(E_ALIAS_CHAIN),credit_baseline:{credit:structuredClone(credit),condition:structuredClone(latest(s,'creditConditions',D_IDS.creditCondition)),input:structuredClone(latest(s,'agreementInputs',D_IDS.agreementInput)),decision:structuredClone(latest(s,'decisions',credit.decision_ref))},dependency_baseline:structuredClone(s.dependencies.filter(d=>D_EDGES.includes(d.id))),closure_input_baseline:{scope:structuredClone(s.scopes[0]),conflictReview:structuredClone(latest(s,'conflictReviews',D_IDS.conflictReview)),conflictFinding:structuredClone(latest(s,'conflictFindings',D_IDS.conflictFinding)),agreement:structuredClone(latest(s,'legalAgreements',D_IDS.agreement))}};
 s.demoConfig.batchE.historical_dependency_exclusions=HISTORICAL_DEPENDENCIES.map(rule=>({...rule,binding:recordBinding('dependencies',latest(s,'dependencies',rule.id))}));
 s.naturalPersons.push(rec(s,E_IDS.signer,{display_name:'Signatory S (Synthetic)',role:'Prospective independent Entity A signatory',identity_status:'reported_only',signing_authority_status:'not_established'}));
 s.demoConfig.batchE.party_input_baseline=[...current(s,'entities'),...current(s,'naturalPersons')].map(x=>[x.id,x.revision]).sort();
 const r=latest(s,'requirements',E_IDS.requirement),e=newEvidence(s,'e-ownership',C_IDS.entityA,'ownership_control',STAMP);e.verification_status='not_assessed';assessment(s,r,e,E_IDS.use,STAMP,{sufficiency:'not_assessed',reason_code:'ownership_purpose_sufficiency_not_established',assessed_by_ref:null,assessed_at:null});
 s.qaChecks.push(rec(s,E_IDS.check,{alias:'QA-04',check_type:'ownership_control_evidence_sufficiency',requirement_refs:[r.id],evidence_use_refs:[E_IDS.use],condition_refs:[id('condition','evidence'),id('condition','qa')],check_status:'not_final',finding_refs:[],reviewed_by_ref:null,reviewed_at:null,reviewed_use_revision:null,reviewed_requirement_revision:null}));
 s.authorities.push(rec(s,E_IDS.authority,{owner_role:authorityConfig().role,authority_kind:'demo_action_permission',demo_permission_ref:authorityConfig().permission_ref,action_scope:['confirm_clearance'],product_scope_ids:['FX_FORWARD'],status:'configured_for_demo',bank_authority_ref:null}));
 s.case.revision++;s.case.updated_at=STAMP;const event=rec(s,id('event',`e-entry-${s.case.revision}`),{event_type:'e_entry_authored',object_refs:[e.id,E_IDS.use,E_IDS.check],occurred_at:STAMP,correlation_id:`E-ENTRY-${s.case.revision}`});s.auditEvents.push(event);refresh(s,STAMP,event.id);return s;}
function eligibility(s,type,role,e){const reasons=[];if(!contextValid(s))reasons.push('E_CONTEXT_REQUIRED');if(!E_ACTION_ROLES[type]?.includes(role)||!equal(s.demoConfig?.batchE?.action_roles,E_ACTION_ROLES))reasons.push('E_PERMISSION_REQUIRED');if(!['revise_scope','revise_evidence','publish_outcome','save_draft'].includes(type)&&!packageValid(s))reasons.push('E_PACKAGE_INVALID');if(type==='confirm_clearance'&&!authorityValid(s))reasons.push('E_AUTHORITY_INVALID');
 const q=latest(s,'qaChecks',E_IDS.check),r=latest(s,'workItems',E_IDS.remediation),requirements={open_qa_gap:q?.check_status==='not_final',submit_remediation:r?.status==='open',complete_remediation:r?.status==='submitted',qa_rereview:r?.status==='completed'&&q?.check_status==='re_review_required'&&useValid(s,latest(s,'requirements',E_IDS.requirement)),qa_signoff:q?.check_status==='passed'&&qaCurrent(s),record_demo_context:!proof(s,E_IDS.context,'demo_context'),review_kyc_evidence:proof(s,E_IDS.context,'demo_context')&&!proof(s,E_IDS.kyc,'kyc_evidence'),resolve_conflicts:!proof(s,E_IDS.conflictDecision,'conflicts_resolution'),confirm_screening_coverage:proof(s,E_IDS.kyc,'kyc_evidence')&&!proof(s,E_IDS.coverageDecision,'screening_coverage'),record_edd_applicability:proof(s,E_IDS.context,'demo_context')&&!latest(s,'eddApplicabilityAssessments',E_IDS.edd),establish_signatory_authority:!latest(s,'authorities',E_IDS.signatory),execute_legal:creditValid(s)&&dependenciesValid(s)&&proof(s,E_IDS.conflictDecision,'conflicts_resolution')&&signatoryValid(s)&&latest(s,'legalAgreements',D_IDS.agreement)?.execution_status==='pending',confirm_clearance:e.readiness.readiness_state==='READY_FOR_AUTHORISED_CONFIRMATION',publish_outcome:e.readiness.readiness_state==='CLEARED_TO_TRADE',revise_evidence:Boolean(latest(s,'evidence',E_IDS.evidence)),revise_scope:true,save_draft:true};if(!requirements[type])reasons.push('E_ACTION_PREREQUISITE_REQUIRED');
 const baseline=s.demoConfig?.batchE?.closure_input_baseline;
 if(!['revise_scope','revise_evidence','save_draft','publish_outcome'].includes(type)&&!equal(s.scopes[0],baseline?.scope))reasons.push('E_PACKAGE_INPUT_CHANGED');
 if(type==='resolve_conflicts'&&(!equal(latest(s,'conflictReviews',D_IDS.conflictReview),baseline?.conflictReview)||!equal(latest(s,'conflictFindings',D_IDS.conflictFinding),baseline?.conflictFinding)))reasons.push('E_PACKAGE_INPUT_CHANGED');
 if(type==='execute_legal'&&!equal(latest(s,'legalAgreements',D_IDS.agreement),baseline?.agreement))reasons.push('E_PACKAGE_INPUT_CHANGED');
 if(type==='confirm_screening_coverage'&&!equal([...current(s,'entities'),...current(s,'naturalPersons')].map(x=>[x.id,x.revision]).sort(),s.demoConfig.batchE.party_input_baseline))reasons.push('E_PACKAGE_INPUT_CHANGED');
 if(effectiveHolds(s).filter(h=>h.status==='active'||h.status==='unknown').some(h=>!(type==='resolve_conflicts'&&h.id===D_IDS.conflictHold)&&(!h.action_scope?.length||h.action_scope.includes(type)||h.action_scope.includes('*')||h.hold_scope==='case'||h.hold_scope==='unknown')))reasons.push('E_ACTIVITY_HELD');return {allowed:reasons.length===0,reasons};}
export function clearanceProjection(s,{role}={}){const e=evaluate(s),common={available:contextValid(s)&&READERS.includes(role),caseId:s?.case?.id??null,scopeId:s?.scopes?.[0]?.id??null,revision:s?.case?.revision??null,scopeRevision:s?.scopes?.[0]?.revision??null,readiness:e.readiness};if(!common.available)return {...common,readiness:{...e.readiness,readiness_state:'NOT_READY'},reason:'E_CONTEXT_OR_PERMISSION_REQUIRED',conditions:[],prerequisites:[],actionEligibility:{},inputRevisions:{}};
 const internal=!['ROLE-RM','ROLE-CLIENT'].includes(role),pub=latest(s,'publicationEvents'),q=latest(s,'qaChecks',E_IDS.check),task=latest(s,'workItems',E_IDS.remediation);
 return structuredClone({...common,source_ref:E_SOURCE,synthetic:true,bank_authority_status:'TO_VALIDATE',trade_execution:'NOT_PART_OF_PROTOTYPE',scope:{entity_refs:[...s.scopes[0].entity_ids],product_refs:[...s.scopes[0].product_scope_ids],booking_context:latest(s,'decisions',E_IDS.context)?.context?.booking_context_ref||null,bank_booking_entity_ref:s.scopes[0].booking_entity_ref,bank_policy_ref:s.scopes[0].policy_profile_ref},conditions:e.conditions,prerequisites:e.prerequisites,inputRevisions:internal?inputs(s):{},actionEligibility:Object.fromEntries(Object.keys(E_ACTION_ROLES).map(type=>[type,eligibility(s,type,role,e)])),qa:{chain:{requirement_ref:E_IDS.requirement,evidence_use_ref:E_IDS.use,qa_check_ref:E_IDS.check,gap_ref:E_IDS.gap,remediation_ref:E_IDS.remediation},check:internal?q:{check_status:q?.check_status},remediation:internal?(task||null):task?{status:task.status}:null,...(internal?{requirement:latest(s,'requirements',E_IDS.requirement),evidence:latest(s,'evidence',E_IDS.evidence),assessment:latest(s,'evidenceUseAssessments',E_IDS.use),gap:latest(s,'qaFindings',E_IDS.gap)||null}:{})},clearance:{current:e.currentDecision?{id:e.currentDecision.id,decision:e.currentDecision.decision,confirmed_at:e.currentDecision.confirmed_at,scope_revision:e.currentDecision.scope_revision}:null,historical_count:s.clearanceDecisions.length,authority_ref:internal?E_IDS.authority:null},publication:{status:pub?.publication_status||'not_requested',current_applicability:Boolean(e.currentDecision&&pub?.clearance_decision_ref===e.currentDecision.id),event_ref:pub?.id||null,published_at:pub?.published_at||null,failure_refs:pub?.failure_refs||[],permitted_targets:[...E_APPROVED_PACKAGE.publication.permitted_target_refs]},draft:internal?latest(s,'workItems',id('work',`e-draft-${role.toLowerCase()}`))||null:null,snapshot_ref:s.readinessSnapshots.at(-1)?.id,activity:internal?s.auditEvents.filter(x=>x.source_refs?.includes(E_SOURCE)).map(x=>({id:x.id,event_type:x.event_type,occurred_at:x.occurred_at,object_refs:x.object_refs})):[]});}
export function clearanceLenses(s,options={}){const p=clearanceProjection(s,options);return Object.fromEntries(['outcome','work','assurance'].map(lens=>[lens,{...structuredClone(p),lens,readOnly:true}]));}
/** Immutable guarded local simulation; success returns state, rejection throws Error.code. */
export function clearanceAction(input,c={}){
 const type=c.type;if(!Object.hasOwn(E_ACTION_ROLES,type))fail('E_ACTION_NOT_SUPPORTED');if(!contextValid(input))fail('E_CONTEXT_REQUIRED');const allowed=['type','role','caseId','scopeId','expectedRevision','expectedScopeRevision','expectedInputRevisions','key','rationale','at','packageRef',...(type==='confirm_clearance'?['authorityRef','snapshotFingerprint']:[]),...(type==='publish_outcome'?['targetSystemRefs','outcome']:[]),...(type==='save_draft'?['draftAction','draftRationale']:[])];if(Object.keys(c).some(k=>!allowed.includes(k)))fail('E_COMMAND_FIELD_NOT_ALLOWED');if(!E_ACTION_ROLES[type].includes(c.role))fail('E_PERMISSION_REQUIRED');if(type==='confirm_clearance'&&!authorityValid(input))fail('E_AUTHORITY_INVALID');
 if(c.caseId!==input.case.id)fail('E_CASE_MISMATCH');if(c.scopeId!==input.scopes[0].id)fail('E_SCOPE_MISMATCH');if(typeof c.key!=='string'||!c.key.trim()||c.key.length>200)fail('E_KEY_REQUIRED');if(typeof c.rationale!=='string'||!c.rationale.trim()||c.rationale.length>2000)fail('E_RATIONALE_REQUIRED');if(typeof c.at!=='string'||!Number.isFinite(Date.parse(c.at)))fail('E_INVALID_TIMESTAMP');
 const fingerprint=clearanceFingerprint(c),prior=input.auditEvents.find(x=>x.correlation_id===c.key);if(prior){if(prior.command_fingerprint!==fingerprint)fail('E_IDEMPOTENCY_CONFLICT');return input;}if(c.expectedRevision!==input.case.revision)fail('E_STALE_CASE');if(c.expectedScopeRevision!==input.scopes[0].revision)fail('E_STALE_SCOPE');if(!equal(c.expectedInputRevisions,inputs(input)))fail('E_STALE_INPUT');if(!['confirm_clearance','publish_outcome','revise_scope','revise_evidence','save_draft'].includes(type)&&c.packageRef!==E_IDS.package)fail('E_PACKAGE_REQUIRED');
 const evaluation=evaluate(input),elig=eligibility(input,type,c.role,evaluation);if(!elig.allowed)fail(elig.reasons[0]);if(type==='confirm_clearance'&&(c.authorityRef!==E_IDS.authority||c.snapshotFingerprint!==evaluation.readiness.fingerprint||!scoped(input,input.readinessSnapshots.at(-1))||!equal(input.readinessSnapshots.at(-1)?.decision_scope,decisionScope(input))||input.readinessSnapshots.at(-1)?.readiness_state!=='READY_FOR_AUTHORISED_CONFIRMATION'||input.readinessSnapshots.at(-1)?.fingerprint!==c.snapshotFingerprint))fail('E_READY_SNAPSHOT_REQUIRED');if(type==='publish_outcome'&&(!equal(c.targetSystemRefs,E_APPROVED_PACKAGE.publication.permitted_target_refs)||!E_APPROVED_PACKAGE.publication.outcomes.includes(c.outcome)))fail('E_PUBLICATION_TARGET_OR_OUTCOME_INVALID');
 if(type==='save_draft'&&(!E_ACTION_ROLES[c.draftAction]?.includes(c.role)||c.draftAction==='save_draft'))fail('E_DRAFT_ACTION_FORBIDDEN');
 if(type==='save_draft'&&(typeof c.draftRationale!=='string'||c.draftRationale.length>2000))fail('E_DRAFT_INVALID');
 const s=structuredClone(input),at=c.at,eventRef=id('event',`e-${s.case.revision+1}`),outputs=[];
 const decision=(ref,decision_type,fields={})=>{const d=rec(s,ref,{decision_type,record_status:'recorded',package_ref:E_IDS.package,event_ref:eventRef,demo_role_ref:c.role,rationale:c.rationale,basis_refs:[E_IDS.package],input_revisions:c.expectedInputRevisions,...fields},at);s.decisions.push(d);outputs.push(d.id);return d;};
 const q=latest(s,'qaChecks',E_IDS.check),task=latest(s,'workItems',E_IDS.remediation),r=latest(s,'requirements',E_IDS.requirement);
 switch(type){
 case 'save_draft':{const ref=id('work',`e-draft-${c.role.toLowerCase()}`),prior=latest(s,'workItems',ref),fields={work_type:'e_action_draft',owner_role_ref:c.role,action_type:c.draftAction,rationale:c.draftRationale,status:'draft'};if(prior)append(s,'workItems',prior,fields,at);else s.workItems.push(rec(s,ref,fields,at));outputs.push(ref);break;}
 case 'open_qa_gap':s.qaFindings.push(rec(s,E_IDS.gap,{alias:'GAP-QA-01',source_check_ref:E_IDS.check,requirement_ref:r.id,evidence_use_ref:E_IDS.use,reason_code:'ownership_purpose_sufficiency_not_established',status:'open',required_action:'Assess current ownership/control dossier for this requirement and return for QA re-review'},at));s.workItems.push(rec(s,E_IDS.remediation,{alias:'RT-01',work_type:'qa_remediation',source_check_ref:E_IDS.check,affected_object_refs:[r.id,E_IDS.use,E_IDS.evidence],reason_code:'ownership_purpose_sufficiency_not_established',required_action:'Review current evidence for ownership_control',owner_role_ref:'ROLE-KYCOPS',status:'open',resolution_refs:[],re_review_required:true},at));append(s,'qaChecks',q,{check_status:'gap_open',finding_refs:[E_IDS.gap]},at);outputs.push(E_IDS.gap,E_IDS.remediation,E_IDS.check);break;
 case 'submit_remediation':append(s,'workItems',task,{status:'submitted',submission_ref:eventRef},at);outputs.push(task.id);break;
 case 'complete_remediation':{const reviewed=append(s,'requirements',r,{applicability:'required',applicability_review:'decided',applicability_decision_ref:eventRef,status:'satisfied',status_reason:'Current synthetic ownership dossier assessed for this purpose'},at),e=latest(s,'evidence',E_IDS.evidence),previous=latest(s,'evidenceUseAssessments',E_IDS.use);assessment(s,reviewed,e,E_IDS.use,at,{review_event_ref:eventRef,revision:previous.revision+1,supersedes_revision:previous.revision,reason_code:'synthetic_ownership_purpose_sufficient'});append(s,'workItems',task,{status:'completed',resolution_refs:[E_IDS.use,eventRef],re_review_required:true},at);append(s,'qaChecks',q,{check_status:'re_review_required'},at);outputs.push(r.id,E_IDS.use,task.id,q.id);break;}
 case 'qa_rereview':append(s,'qaChecks',q,{rereview_ref:eventRef,rereview_revision:q.revision+1,check_status:'passed',reviewed_by_ref:c.role,reviewed_at:at,reviewed_use_revision:latest(s,'evidenceUseAssessments',E_IDS.use).revision,reviewed_requirement_revision:r.revision},at);append(s,'qaFindings',latest(s,'qaFindings',E_IDS.gap),{status:'resolved',resolution_ref:eventRef},at);outputs.push(q.id,E_IDS.gap);break;
 case 'qa_signoff':append(s,'qaChecks',q,{check_status:'signed_off',signoff_ref:eventRef,reviewed_by_ref:c.role,reviewed_at:at},at);outputs.push(q.id);break;
 case 'record_demo_context':decision(E_IDS.context,'demo_context',{context:structuredClone(E_APPROVED_PACKAGE.context),decision_scope:{entity_refs:[C_IDS.entityA],product_refs:['FX_FORWARD'],scope_revision:3}});break;
 case 'review_kyc_evidence':{const entity=newEvidence(s,'e-kyc-entity-a',C_IDS.entityA,'entity_identity',at),person=newEvidence(s,'e-kyc-person-t',C_IDS.personT,'screening_identity',at);for(const ref of E_APPROVED_PACKAGE.kyc.requirement_refs){const old=latest(s,'requirements',ref),rr=ref===COLLAB_IDS.authorityRequirement?old:append(s,'requirements',old,{applicability:'required',status:'satisfied',applicability_review:'decided',applicability_decision_ref:eventRef},at);
 const reviewedEvidence=ref===COLLAB_IDS.authorityRequirement?latest(s,'evidence',latest(s,'evidenceUseAssessments',id('assessment','authority-coordinate-b5'))?.evidence_id):rr.subject_id===C_IDS.entityA?entity:person;
 assessment(s,rr,reviewedEvidence,id('assessment',`e-kyc-${ref.split('/').at(-1)}`),at,{review_event_ref:eventRef});outputs.push(id('assessment',`e-kyc-${ref.split('/').at(-1)}`));}decision(E_IDS.kyc,'kyc_evidence',{evidence_refs:[entity.id,person.id],requirement_refs:[...E_APPROVED_PACKAGE.kyc.requirement_refs]});break;}
 case 'resolve_conflicts':decision(E_IDS.conflictDecision,'conflicts_resolution',{outcome:'resolved_for_demo',finding_ref:D_IDS.conflictFinding});append(s,'conflictFindings',latest(s,'conflictFindings',D_IDS.conflictFinding),{resolution_status:'resolved',decision_ref:E_IDS.conflictDecision},at);append(s,'conflictReviews',latest(s,'conflictReviews',D_IDS.conflictReview),{review_status:'complete',clearance_status:'recorded',decision_ref:E_IDS.conflictDecision},at);append(s,'holds',latest(s,'holds',D_IDS.conflictHold),{status:'released',released_at:at,release_decision_ref:E_IDS.conflictDecision},at);break;
 case 'confirm_screening_coverage':{const pkg=E_APPROVED_PACKAGE.screening,membershipRefs=[];for(const item of pkg.inventory){const slug=item.party_ref.split('/').at(-1),party=latest(s,'entities',item.party_ref)||latest(s,'naturalPersons',item.party_ref),m=rec(s,id('membership',`e-${slug}`),{population_ref:E_IDS.population,party_ref:item.party_ref,party_revision:party.revision,party_fingerprint:clearanceFingerprint(party),screening_category:pkg.category,membership_decision:item.membership,criterion_ref:`${E_IDS.package}:screening:${slug}`,exclusion_basis:item.basis||null,decision_ref:E_IDS.coverageDecision},at);s.screeningMemberships.push(m);membershipRefs.push(m.id);if(item.membership==='excluded')continue;const runRef=id('screening-run',`e-${slug}`),resultRef=id('screening-result',`e-${slug}`);const subjectSnapshot=rec(s,id('run-subject',`e-${slug}`),{party_ref:item.party_ref,party_revision:party.revision,population_ref:E_IDS.population,category:pkg.category},at);s.runSubjectSnapshots.push(subjectSnapshot);s.screeningRuns.push(rec(s,runRef,{subject_snapshot_refs:[subjectSnapshot.id],population_ref:E_IDS.population,population_revision:1,subject_refs:[item.party_ref],run_status:'completed',category:pkg.category,dataset_ref:pkg.dataset_ref,result_snapshot_refs:[resultRef],required:true},at));s.screeningResultSnapshots.push(rec(s,resultRef,{run_ref:runRef,run_revision:1,result_status:'completed',result_count:item.party_ref===C_IDS.personT?1:0,disposition_ref:item.party_ref===C_IDS.personT?id('screening-decision','e-person-t'):null,data_snapshot_ref:pkg.dataset_ref},at));s.screeningCoverageItems.push(rec(s,id('coverage',`e-${slug}`),{population_ref:E_IDS.population,party_ref:item.party_ref,category:pkg.category,run_ref:runRef,coverage_status:'complete',blocking_reason_refs:[],decision_ref:E_IDS.coverageDecision},at));}
  s.screeningPopulations.push(rec(s,E_IDS.population,{population_revision:1,membership_refs:membershipRefs,inventory_status:'complete_for_scope',inventory_gap_refs:[],population_review_status:'confirmed',completeness_basis_refs:[E_IDS.package,E_IDS.kyc],confirmed_by_ref:c.role,confirmed_at:at,confirmation_permission_ref:'SYNTHETIC-E-POPULATION-REVIEW-v1'},at));s.screeningReviewDecisions.push(rec(s,id('screening-decision','e-person-t'),{finding_ref:C_IDS.finding,finding_revision:latest(s,'screeningFindings',C_IDS.finding).revision,finding_fingerprint:clearanceFingerprint(latest(s,'screeningFindings',C_IDS.finding)),result_ref:id('screening-result','e-person-t'),disposition:'not_a_match',decision_status:'recorded',new_evidence_ref:id('evidence','e-kyc-person-t'),basis_refs:[E_IDS.package,id('assessment','e-kyc-screening-identity-c')],supersedes_decision_ref:s.screeningReviewDecisions.filter(d=>d.finding_ref===C_IDS.finding).at(-1)?.id,reviewed_by_ref:c.role,recorded_at:at,rationale:c.rationale},at));decision(E_IDS.coverageDecision,'screening_coverage',{population_ref:E_IDS.population,reviewed_screening_bindings:screeningBindings(s),historical_finding_exclusions:[{id:id('finding','possible-match'),basis_ref:'SRC-020:5:PREREQ-02',reason:'Exact unchanged legacy fixture placeholder; E has a new reviewed population, required runs and current purpose evidence',binding:recordBinding('screeningFindings',latest(s,'screeningFindings',id('finding','possible-match')))}]});break;}
 case 'record_edd_applicability':s.eddApplicabilityAssessments.push(rec(s,E_IDS.edd,{applicability:'not_required',review_status:'decided',policy_basis_ref:'SYNTHETIC-E-INDEPENDENT-RISK-REVIEW-v1',package_ref:E_IDS.package,trigger_reason_refs:[`${E_IDS.package}:edd`],basis_refs:[E_IDS.context],decision_ref:eventRef,decided_by_ref:c.role,permission_ref:'SYNTHETIC-E-EDD-REVIEW-v1'},at));outputs.push(E_IDS.edd);break;
 case 'establish_signatory_authority':{const ev=newEvidence(s,'e-signatory-mandate',E_IDS.signer,'execute_agreement',at),use=rec(s,id('assessment','e-signatory'),{evidence_id:ev.id,evidence_revision:ev.evidence_revision,evidence_record_revision:ev.revision,evidence_fingerprint:clearanceFingerprint(ev),subject_id:E_IDS.signer,principal_entity_id:C_IDS.entityA,purpose_code:'execute_agreement',sufficiency:'sufficient',basis_refs:[ev.id,E_IDS.package],assessed_by_ref:c.role,review_event_ref:eventRef},at);s.evidenceUseAssessments.push(use);s.authorities.push(rec(s,E_IDS.signatory,{subject_ref:E_IDS.signer,principal_entity_id:C_IDS.entityA,action_type:'execute_agreement',product_scope_refs:['FX_FORWARD'],status:'established_for_demo',bank_authority_ref:null,package_ref:E_IDS.package,evidence_use_refs:[use.id],decision_ref:eventRef},at));outputs.push(E_IDS.signatory,ev.id,use.id);break;}
 case 'execute_legal':{const a=latest(s,'legalAgreements',D_IDS.agreement),doc=newEvidence(s,'e-executed-agreement',C_IDS.entityA,'legal_execution',at);append(s,'legalAgreements',a,{agreement_revision:a.agreement_revision+1,execution_status:'executed',executed_document_ref:doc.id,signatory_authority_refs:[E_IDS.signatory],credit_input_revision:latest(s,'agreementInputs',D_IDS.agreementInput).revision,execution_decision_ref:id('decision','e-legal-execution')},at);decision(id('decision','e-legal-execution'),'legal_execution',{agreement_ref:a.id,credit_input_revision:1,signatory_authority_ref:E_IDS.signatory,executed_document_ref:doc.id,executed_document_revision:doc.revision,executed_evidence_revision:doc.evidence_revision,executed_content_revision:doc.content_revision,executed_document_fingerprint:clearanceFingerprint(doc),agreement_revision:latest(s,'legalAgreements',a.id).revision,agreement_fingerprint:clearanceFingerprint(latest(s,'legalAgreements',a.id))});break;}
 case 'confirm_clearance':{const d=rec(s,id('clearance-decision',`e-${s.case.revision+1}`),{readiness_snapshot_ref:s.readinessSnapshots.at(-1).id,decision:'CLEARED_TO_TRADE',decision_scope:{entity_refs:[...s.scopes[0].entity_ids],product_refs:[...s.scopes[0].product_scope_ids],scope_revision:s.scopes[0].revision},confirmed_by_ref:c.role,authority_ref:c.authorityRef,confirmed_at:at,rationale:c.rationale,basis_fingerprint:evaluation.readiness.fingerprint},at);s.clearanceDecisions.push(d);outputs.push(d.id);break;}
 case 'publish_outcome':{const d=evaluation.currentDecision;s.publicationEvents.push(rec(s,id('publication-event',`e-${s.case.revision+1}`),{clearance_decision_ref:d.id,published_scope:structuredClone(d.decision_scope),target_system_refs:[...c.targetSystemRefs],publication_status:c.outcome,published_at:c.outcome==='succeeded'?at:null,attempted_at:at,failure_refs:c.outcome==='failed'?['SYNTHETIC-E-PUBLICATION-FAILURE']:[],trade_execution:'NOT_PART_OF_PROTOTYPE'},at));outputs.push(s.publicationEvents.at(-1).id);break;}
 case 'revise_evidence':{const old=latest(s,'evidence',E_IDS.evidence);append(s,'evidence',old,{evidence_revision:old.evidence_revision+1,content_revision:old.content_revision+1,verification_status:'not_assessed',content_ref:`synthetic:${E_IDS.package}:ownership-changed`},at);append(s,'qaChecks',q,{check_status:'re_review_required'},at);outputs.push(old.id,q.id);break;}
 case 'revise_scope':s.scopes[0]={...s.scopes[0],revision:s.scopes[0].revision+1,scope_revision:s.scopes[0].revision+1,updated_at:at};outputs.push(s.scopes[0].id);break;
 }
 s.case.revision++;s.case.updated_at=at;s.auditEvents.push(rec(s,eventRef,{event_type:type,actor_ref:c.role,actor_type:'human_demo',object_refs:outputs,output_bindings:outputs.map(ref=>recordByRef(s,ref)).filter(Boolean).map(outputBinding),from_revision:input.case.revision,to_revision:s.case.revision,correlation_id:c.key,command_fingerprint:fingerprint,rationale:c.rationale,occurred_at:at,expected_input_revisions:c.expectedInputRevisions,causation_ref:input.auditEvents.at(-1)?.id||null,package_ref:c.packageRef||null},at));refresh(s,at,eventRef,{updateConditions:type!=='save_draft'});return s;
}
