// Accepts an audience-specific allowlist projection, never the complete case.
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderCollaboration({projection:p,audience='ops',tab='requirements',locale='en-AU',draftText,selectedItemId,error='',message='',print=false}){
 const L=(en,zh)=>locale==='zh-CN'?zh:locale==='en-US'?en.replaceAll('authorised','authorized'):en;
 const labels={open:['Open','未完成'],draft:['Draft','草稿'],submitted:['Submitted','已提交'],under_review:['Under review','复核中'],needs_more_information:['More information needed','需要补充资料'],closed:['Closed for this purpose','此用途已闭合'],approved:['Reviewed','已审阅'],pending_review:['Pending review','待审阅'],superseded:['Review superseded','审阅已过期'],sent:['Dispatched · simulation','已派发 · 模拟'],not_requested:['Not dispatched','尚未派发'],unknown:['Unknown','未知'],received:['Received','已收到'],released:['Released for review','可进行复核'],quarantined:['Quarantined','隔离中'],rejected:['Rejected','已拒收'],not_assessed:['Not assessed','尚未评估'],sufficient:['Sufficient for this purpose','对此用途充分'],insufficient:['Insufficient','不足'],required:['Required in fixture','合成示例中适用'],not_required:['Not required','不适用'],review_required:['Review required','需要复核']};
 const label=s=>labels[s]?L(...labels[s]):esc(s||L('Not provided','尚未提供'));
 const isIdentity=i=>i?.purpose_code==='screening_identity'||i?.alias==='ITEM-IDENTITY-C';
 const title=i=>isIdentity(i)?L('Identity information for screening review','筛查复核所需身份信息'):i?.alias==='ITEM-AUTHORITY'?L('Authority to coordinate information','协调资料的权限依据'):i?.alias==='ITEM-OWNERSHIP'?L('Ownership and control','所有权与控制信息'):esc(i?.purpose_code);
 const fixtureReasons={'Please provide a synthetic basis showing who may coordinate onboarding information for Entity A.':'请提供合成依据，说明谁可以为 Entity A 协调开户资料。','Please share synthetic ownership and control information if available while applicability is reviewed.':'适用性仍在复核中。如有，请提供合成的所有权与控制信息。'};
 const reason=i=>esc(locale==='zh-CN'?(fixtureReasons[i.client_reason]||i.client_reason):i.client_reason);
 const action=(type,en,zh,item,disabled=false)=>print?'':`<button data-action="collab-action" data-value="${type}" ${item?`data-item="${esc(item.id)}"`:''} ${disabled?'disabled':''}>${L(en,zh)}</button>`;
 const nav=(value,en,zh)=>`<button data-action="collab-tab" data-value="${value}" aria-pressed="${tab===value}">${L(en,zh)}</button>`;
 const badge=s=>`<span class="badge">${label(s)}</span>`;
 const editor=(value,labelText)=>print?'':`<label class="field">${labelText}<textarea id="collab-text" rows="4">${esc(draftText??value??'')}</textarea></label>`;
 const head=heading=>`<div class="collab-heading"><div><span class="eyebrow">${esc(p.entity_label||'Entity A')}</span><p class="trace-meta">${esc(p.case_id||'DEMO-CTT-001')}</p><h1>${heading}</h1></div>${audience!=='client'?`<div>${badge('unknown')}<p class="small">${L('Case not ready','案件尚未就绪')} · v${p.case_revision}</p></div>`:''}</div>`;
 const receipts=()=>`<section class="collab-receipts"><h2>${L('Submitted','已提交')}</h2>${(p.submissions||[]).length?(p.submissions||[]).map(s=>`<article class="record"><strong>${L('Submission receipt','提交回执')}</strong><p>${esc(s.response_text||s.response||'')}</p><p>${label(s.intake_security_status||s.artifact_intake_status||'received')}</p><small>${esc(s.id)}</small></article>`).join(''):`<p>${L('No response submitted yet.','尚未提交响应。')}</p>`}</section>`;
 if(p.allowed===false)return `<section class="collab-workspace">${head(L('Your tasks','你的任务'))}<div class="error" role="alert"><h2>${L('Access unavailable','暂不可访问')}</h2><p>${locale==='zh-CN'?'需要有效的模拟身份会话与针对本项目的访问授权。Reference 仅用于定位请求。': 'A valid simulated identity session and a grant for this item are required. The reference only locates the request.'}</p><code class="trace-meta">${esc(p.reason)}</code></div></section>`;
 const items=p.items||[],selected=items.find(i=>i.id===selectedItemId)||items[0];
 const itemCards=items.map(i=>`<article class="record collab-item" data-request-item="${esc(i.id)}"><div class="section-head"><h3>${title(i)}</h3>${badge(i.response_status)}</div><p>${reason(i)}</p><small>${L('Purpose','用途')}: ${esc(i.purpose_code)} · v${i.revision}</small>${audience!=='client'&&!print?`<p><span class="mono">${esc(i.requirement_id)}</span></p>`:''}</article>`).join('');
 let html='';
 if(audience==='client'){
  html=head(L('Your tasks','你的任务'));
  if(!print)html+=`<nav class="collab-tabs" aria-label="${L('Your tasks navigation','你的任务导航')}">${nav('tasks','Your tasks','你的任务')}${nav('documents','Documents','资料')}${nav('submitted','Submitted','已提交')}${nav('help','Help','帮助')}</nav>`;
  if(print||tab==='tasks')html+=itemCards+(selected&&!print?`<section class="collab-response"><h2>${L('Your response','你的响应')}</h2><p class="small">${isIdentity(selected)?L('Provide only the synthetic identity context requested in this secure task. Do not enter real personal information.','仅提供此安全任务所请求的合成身份信息。请勿输入真实个人信息。'):L('Accepted response: the prepared synthetic authority statement. Do not enter real personal information.','响应方式：预置合成权限声明。请勿输入真实个人信息。')}</p>${editor(selected.response_draft,L('Response / statement','响应 / 声明'))}<div class="controls">${action('save_response','Save draft','保存草稿',selected)}${action('submit_response','Submit response','提交响应',selected,selected.response_status==='closed')}${action('refer_question','Ask a question','提出问题',selected)}</div></section>`:'');
  if(print||tab==='submitted')html+=receipts();
  if(tab==='documents'&&!print)html+=`<h2>${L('Documents','资料')}</h2><p>${L('Only material associated with your assigned items appears here.','此处仅显示与你获分配项目相关的资料。')}</p>${receipts()}`;
  if(tab==='help'&&!print)html+=`<h2>${L('Help','帮助')}</h2><p>${L('Access lets you respond to the assigned request. It does not authorise signing or trading for Entity A. A submitted response remains subject to review.','访问权限仅允许响应分配给你的请求，不赋予代表 Entity A 签约或交易的权限。提交后仍需复核。')}</p>${editor('',L('Question','问题'))}${action('refer_question','Ask a question','提出问题',selected)}`;
 }else if(audience==='rm'){
  html=head(L('Client requests','客户请求'))+`<p class="collab-summary">${L('Next action','下一步')}: ${items.some(i=>i.response_status==='under_review')?L('Await purpose review','等待用途复核'):L('Review open requests with the contributor','与贡献者核对未完成请求')} · ${L('Owner: Unassigned','责任人：未分派')}</p>`+itemCards;
  html+=`<h2>${L('Recent contact','最近联系')}</h2>${(p.interactionRecords||[]).map(x=>`<article class="record"><p>${esc(x.summary)}</p><small>${esc(x.channel)} · ${esc(x.reviewed_by||L('Not reviewed','尚未审阅'))}</small></article>`).join('')||`<p>${L('No reviewed contact note.','尚无已审阅的联系记录。')}</p>`}${editor('',L('Interaction note / question','联系记录 / 问题'))}<div class="controls">${action('record_note','Add interaction note','添加联系记录')}${action('refer_question','Refer question','转交问题')}${!print?nav('requests','Open request','打开请求'):''}</div>`;
 }else{
  const titles={requirements:L('Requirements','要求'),requests:L('Requests','请求'),evidence:L('Evidence','证据'),contacts:L('Contacts','联系人'),tasks:L('Tasks','任务'),activity:L('Activity','活动')};
  html=head(titles[tab]||titles.requirements);
  if(!print)html+=`<nav class="collab-tabs" aria-label="${L('Case work','案件工作')}">${Object.entries(titles).map(([k,v])=>nav(k,v,v)).join('')}</nav>`;
  if(tab==='requirements')html+=`<div class="notice">${L('Booking, eligibility and complete ownership/CDD remain unresolved. Unknown applicability is not an exemption.','Booking、产品资格及完整 ownership/CDD 仍未解决。适用性未知不等于豁免。')}</div>${items.map(i=>{const r=(p.requirements||[]).find(r=>r.id===i.requirement_id);return `<article class="record"><h2>${title(i)}</h2><p>${reason(i)}</p><div class="controls">${badge(r?.applicability||'unknown')}${badge(r?.status||'not_assessed')}</div><p>${L('Subject / purpose','主体 / 用途')}: ${esc(i.subject_id)} / ${esc(i.purpose_code)}</p><small>${esc(i.requirement_id)}</small></article>`;}).join('')}${!print?nav('requests','Open requests','打开请求'):''}`;
  if(tab==='requests')html+=`<div class="collab-request-status">${badge(p.request?.review_status||'draft')}<span>${L('Dispatch','派发')}: ${label(p.request?.dispatch_status||'not_requested')}</span><span>${L('Delivery','送达')}: ${label(p.request?.delivery_status||'unknown')}</span></div><p class="trace-meta">${esc(p.request_id)} · v${p.request_revision}</p>${itemCards}${editor(p.request?.client_summary,L('Client-safe request summary','可向客户披露的请求摘要'))}<div class="controls">${action('save_request','Save draft','保存草稿')}${action('review_request','Review request & recipients','审阅请求与收件人')}${action('dispatch','Dispatch notification','派发通知',null,p.request?.review_status!=='approved')}</div><p class="small">${L('Notification adapter: local simulation. Delivery observation remains separate.','通知适配器：本地模拟。送达观测状态独立保存。')}</p>`;
  if(tab==='evidence')html+=`${items.length>1?`<label class="field">${L('Request item','请求项目')}<select id="collab-item">${items.map(i=>`<option value="${esc(i.id)}" ${selected?.id===i.id?'selected':''}>${title(i)}</option>`).join('')}</select></label>`:''}${selected?`<article class="record"><h2>${title(selected)}</h2><p>${reason(selected)}</p><p>${esc(selected.subject_id)} / ${esc(selected.purpose_code)}</p>${badge(selected.response_status)}</article>`:''}${(p.evidence||[]).map(e=>`<article class="record"><h3>${L('Submitted evidence','已提交资料')}</h3><small class="trace-meta">${esc(e.alias||e.id)}</small><p>${L('Intake','接收')}: ${label(e.intake_security_status||'received')} · ${L('Content revision','内容版本')} ${e.content_revision||e.evidence_revision}</p><p>${L('Original submitter','原提交人')}: ${esc(e.original_submitter_ref)}<br>${L('Original source','原始来源')}: ${esc(e.original_source_ref)}</p><small>${esc(e.id)}</small></article>`).join('')||`<p>${L('No submitted evidence yet.','尚无已提交证据。')}</p>`}<details><summary>${L('Assessment history','评估历史')}</summary>${(p.assessments||[]).map(a=>`<p>${label(a.sufficiency)} · ${esc(a.purpose_code)} · ${esc(a.id)}<br>${esc(a.rationale||a.basis||a.reason_code)}</p>`).join('')}</details>${editor('',L('Assessment rationale','评估理由'))}<div class="controls">${action('release_artifact','Run mock intake: release','模拟接收：允许复核',selected)}${action('link_evidence','Link evidence','关联证据',selected)}${isIdentity(selected)?`<button data-action="c-back-review" data-value="screening-evidence">${L('Back to Screening Evidence assessment','返回筛查证据评估')}</button>`:action('record_assessment','Record assessment','记录评估',selected)}${action('request_more','Request more information','请求补充资料',selected)}${action('refer_review','Refer for review','转交复核',selected)}</div><p class="notice">${isIdentity(selected)?L('Released and linked does not mean sufficient. Screening identity sufficiency is assessed in Screening Evidence; this coordination workspace cannot record it.','放行并关联不代表充分。筛查身份充分性须在“筛查证据”中评估；此协作工作台不能记录该结论。'):L('Released does not mean sufficient. Only the coordination purpose can close here; signing, trading and overall clearance stay separate.','可复核不代表充分。此处仅可能闭合协调资料用途；签约、交易和整体准入保持独立。')}</p>`;
  if(tab==='contacts')html+=(p.contacts||[]).map(c=>`<article class="record"><h2>${esc(c.display_name||c.person_ref)}</h2><p>${L('Contact review','联系人审阅')}: ${esc(c.status)} · ${esc(c.contact_review_ref)}</p><p>${L('Principal','被代表主体')}: ${esc(c.principal_entity_ref)}</p></article>`).join('')+`<p class="notice">${L('Contact review, authentication, request access and business authority are four separate judgments.','联系人审阅、身份认证、请求访问及业务代表权限是四个独立判断。')}</p>`;
  if(tab==='tasks')html+=(p.tasks||[]).map(t=>`<article class="record"><h2>${L('Review the request item','复核请求项目')}</h2><small class="trace-meta">${esc(t.work_type||t.id)}</small><p>${label(t.status)} · ${esc(t.owner_role||'Unassigned')}</p><p>${esc(t.waiting_for)}</p><small>${esc(t.id)}</small></article>`).join('');
  if(tab==='activity')html+=(p.activity||[]).slice().reverse().map(a=>`<article class="activity"><strong>${esc(a.event_type)}</strong><p>${esc(a.actor_ref)} · ${esc(a.occurred_at)}</p><small>${esc(a.id)}</small></article>`).join('');
 }
 return `<section class="collab-workspace ${print?'collab-print':''}">${message?`<p role="status" class="toast">${esc(message)}</p>`:''}${error?`<p role="alert" class="error">${esc(error)}</p>`:''}${html}</section>`;
}
