import {consolidatedProjection,dependencyProjection} from './consolidation.mjs';
import {eStatus} from './clearance-ui.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,value='')=>`<button data-action="${action}" data-value="${esc(value)}">${esc(label)}</button>`;
const graphText={
 'DG-F01':[['Case and current scope','案件与当前范围'],['Parties: entity and person','参与方：实体与人员'],['Authority: separate mandate','权限：单独建立授权'],['Requirement: purpose and scope','适用要求：用途与范围'],['Evidence: use assessment','证据：用途评估'],['Work / decision: receipt is not sufficiency','工作／决定：收到不等于充分'],['Specialists: current conditions','专业条线：当前条件'],['Prerequisites: all applicable inputs','准入前提：全部适用输入'],['Readiness is not authorisation','就绪状态不等于已授权'],['Human decision: scoped authority','人工决定：限定范围权限'],['Publication: no trade execution','发布：不执行交易']],
 'DG-F02':[['Identify change or issue','识别变化或问题'],['Identify the affected dependency','识别受影响依赖'],['Determine impact scope','确定影响范围'],['Task scope','任务范围'],['Branch scope','条线范围'],['Case scope','案件范围'],['Unknown scope','未知范围'],['Show affected work','显示受影响工作'],['Show explicitly unaffected work','显示明确不受影响工作'],['Show unknown dependencies','显示未知依赖'],['Resolve or reassess','解决或重新评估'],['Reevaluate current readiness','重新评估当前就绪状态']],
 'DG-F03':[['Read the same Shared Case Spine','读取同一共享案件数据'],['Studio: understand the work','Studio：理解工作'],['Product: perform permitted work','产品：执行获准工作'],['Optional Lab: inspect read-only lenses','可选 Lab：检查只读视角'],['Print the selected shared content','打印所选共享内容']]
};
const qzh=['案件经理协调与 KYC 运营判断的职责边界是什么？','谁可以确认哪些主体、产品与 booking 范围的最终准入？','哪些相关方和类别纳入筛查群体，谁确认完整性？','谁确定 EDD 适用性、作出判断并批准结果？','法务与信贷提前开始准备的最低输入条件是什么？','哪些客户提交、安全任务、认证与披露渠道已获准？','客户经理可以查看哪些筛查、利益冲突和风险详情？','谁确定任务、条线或案件暂停范围并批准解除？','哪些下游系统接收结构化准入结果，如何确认接收？','谁负责发布失败、重试、核对与通知？','哪些关系或产品变化允许复用证据，哪些需要重新评估？','本合成主案例是否足以支持 Workshop 验证？'];
export function fDiagramHtml(manifest,id,locale,focus=0,print=false){
 const zh=locale==='zh-CN',loc=zh?'zh-CN':'en-AU',d=manifest?.diagrams?.find(x=>x.id===id),title=d?.title?.[loc]||({'DG-F01':zh?'共享案件结构':'Shared Case Spine','DG-F02':zh?'依赖与暂停范围':'Dependency and Hold Pattern','DG-F03':zh?'体验结构':'Experience Architecture'})[id],path=d?.locales?.[loc],src=path?(print?path.replace('.host.svg','.print.svg'):path):null;
 const texts=d?.fallback?.[loc]||graphText[id].map(x=>x[zh?1:0]);
 return `<section class="f-diagram" data-f-diagram="${id}"><p class="trace-meta">${id} · ${esc(manifest?.sourceStatus||'approved_demo_design_not_bank_validation')}</p><h2>${esc(title)}</h2>${src?`<div class="f-graph-scroll"><img src="./diagrams/batch-f/${esc(src)}" alt="${esc(title)}"></div>`:`<p class="notice">${zh?'静态语义备选。图示未通过验证或尚不可用；下方文字保留完整逻辑。':'Static semantic fallback. Graph validation did not pass or is unavailable; the complete logic remains below.'}</p>`}<ol>${texts.map((text,i)=>`<li data-f-node="${esc(d?.steps?.[i]||`${id}-${i}`)}" ${i===focus?'aria-current="step"':''}>${esc(text)}</li>`).join('')}</ol>${!print?button(zh?'下一段说明':'Next explanation','f-next')+button(zh?'图示依据':'Diagram references','f-references',id==='DG-F01'?'F01-evidence':id==='DG-F02'?'F02-unknown':'F03-lab'):''}<p class="trace-meta">${zh?'说明控件只改变阅读位置。未收到音频或视频。':'Explanation controls change reading position only. No audio or video received.'}</p></section>`;
}
export function definitionHtml({definition:d,manifest,state,nav,print=false}={}){
 const locale=nav.locale||'en-AU',zh=locale==='zh-CN',t=(en,cn)=>zh?cn:en,local=v=>typeof v==='object'?(v?.[locale]||v?.['en-AU']||''):v,p=consolidatedProjection(state,{role:nav.role,lens:nav.definitionLens}),graph=nav.definitionGraph||'DG-F01',story=d?.story||[],caps=d?.capabilities||[],reqs=d?.requirements||[],chosen=p.dependencies.find(e=>e.id===nav.definitionDependency)||p.dependencies.find(e=>e.id.endsWith('e-task-qa'))||p.dependencies[0],impact=p.available&&p.dependencies.length?dependencyProjection(state,{changedRefs:chosen?[chosen.from_object_ref]:[],candidateRefs:[...new Set(p.dependencies.map(e=>e.to_object_ref))]}):null;
 return `<main id="main" class="f-definition" data-f-definition ${print?'data-print-scope="batch-f-complete"':''}><nav class="controls no-print">${print?button(t('Back to view','返回原视图'),'exit-print')+button(t('Print / Save PDF','打印 / 保存 PDF'),'print'):button(t('Back to journey','返回旅程'),'f-back')+button(t('Print definition','打印产品定义'),'f-print')+button(t('References','研究依据'),'reference-global')}</nav><p class="eyebrow">D2 · ${t('Product Definition','产品定义')}</p><h1>${t('One case, connected work','一个案件，连贯的工作')}</h1><p>${t('Entity A requests FX forward. Entity B is the reported Singapore parent; Person T works for B. Coordination, identity, signing and trading authority remain separate.','主体 A 申请外汇远期；主体 B 为申报的新加坡母公司，Person T 任职于 B。协调、身份、签署与交易权限分别判断。')}</p><p class="notice">${t('Approved synthetic design. Bank rules and authority require validation. No final MVP ranking or production integration is claimed.','获批准的合成设计。银行规则与权限仍待验证；不声明最终 MVP 排名或生产集成。')}</p>
 <section><h2>${t('From evidence to product behaviour','从依据到产品行为')}</h2><p>${t('Method → Personas → Current / Target Journey → Scenario → Product Experience → Human boundaries → Product Definition → Open questions. The existing journey retains role groups and trigger variants; this consolidation adds no business scenario.','方法 → 角色 → 当前／目标旅程 → 场景 → 产品体验 → 人工边界 → 产品定义 → 开放问题。既有旅程保留角色群体与触发变体，本次整合不增加业务场景。')}</p><p>${t('Current and Target describe work design. MVP retains explicit human review; target autonomy remains a hypothesis. Baseline and changed sessions keep their own revisions and archives.','当前与目标描述工作设计。MVP 保留明确人工复核；目标自主程度仍是假设。基线与变化会话保留各自版本和归档。')}</p>${!print?`<label class="no-print">${t("View region","查看地区")}<select id="f-region">${["AU","US","SG"].map(v=>`<option value="${v}" ${v===(nav.region||"AU")?"selected":""}>${v}</option>`).join("")}</select></label>`:''}<p>${t("Region is presentation context only; it does not change policy assumptions.","地区仅为展示背景，不改变政策假设。")}</p></section>
 <section data-f-live data-f-revision="${esc(p.revision)}"><h2>${t('Current saved case','当前已保存案件')}</h2><p>${esc(p.caseId)} · ${t('Case revision','案件版本')} ${esc(p.revision)} · ${t('Scope revision','范围版本')} ${esc(p.scopeRevision)}</p><p>${p.available?eStatus(p.readinessState,locale):t('Clearance projection unavailable for the current context or role. This is not a factual Not ready result.','当前背景或角色无法取得准入投影；这不是“未就绪”的事实结果。')}</p>${p.available?`<p>${t('Publication','发布')}: ${p.publicationStatus==='historical_not_current'?t('Historical outcome; not current after change','历史结果；变化后不再适用'):eStatus(p.publicationStatus,locale)} · ${t('No trade is executed.','不执行交易。')}</p>`:''}</section>
 <section><h2>${t('Living Story','完整主线故事')}</h2><p>${t('Reading never loads outcomes. Open a scene to reach its Product task and exact return context. Reviewed D / E continuation explicitly archives the prior session.','阅读不载入结果。打开场景可进入对应产品任务并精确返回。已复核 D／E 延续会明确归档先前会话。')}</p><div class="f-story">${story.map(s=>`<article data-f-scene="${s.beat_id}"><h3>${esc(local(s.title))}</h3><p class="trace-meta">${esc(s.beat_id)} · ${esc(s.scene_id)} · ${esc(s.process_refs.join(' · '))}</p><dl><dt>${t('Trigger','触发')}</dt><dd>${t('New relationship; current scope and required inputs','新关系；当前范围与所需输入')}</dd><dt>${t('Current work','当前工作')}</dt><dd>${esc(local(s.current_work))}</dd><dt>${t('Target work','目标工作')}</dt><dd>${esc(local(s.target_work))}</dd><dt>${t('Decision','决定')}</dt><dd>${esc(local(s.decision_refs[0]))}</dd><dt>${t('State change / next scene','状态变化／下一场景')}</dt><dd>${esc(local(s.outputs[0]))} · ${esc(s.next_beat_ref||t('End of story','故事结束'))}</dd></dl>${!print?button(t('Open scene','打开场景'),'f-scene',s.beat_id):''}</article>`).join('')}</div></section>
 <section><h2>${t('Shared objects and state distinctions','共享对象与状态区别')}</h2><div class="f-domain-list">${(d?.domains||[]).map(x=>`<details ${print?'open':''}><summary>${esc(x.domain)}</summary><dl>${Object.entries(x.objects).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl></details>`).join('')}</div><p>${t('Unknown ≠ Not applicable. Completed ≠ Satisfied. Satisfied ≠ Authorised. Authorised ≠ Published. Published ≠ Trade executed.','未知 ≠ 不适用。完成 ≠ 满足。满足 ≠ 获授权。获授权 ≠ 已发布。已发布 ≠ 已执行交易。')}</p></section>
 <section><nav class="controls no-print">${['DG-F01','DG-F02','DG-F03'].map(id=>button(id,'f-graph',id)).join('')}</nav>${(print?['DG-F01','DG-F02','DG-F03']:[graph]).map(id=>fDiagramHtml(manifest,id,locale,nav.definitionFocus||0,print)).join('')}</section>
 <section><h2>${t('Dependency impact','依赖影响')}</h2><p>${t('Projection only. The original qualified IDs and endpoint revisions are retained. No edge is not proof of independence. Historical mapping can be unknown in this conservative impact view without overriding the engine readiness decision.','仅为投影。保留原始限定编号与端点版本。缺少边不证明独立；本保守视图可将历史映射显示为未知，不覆盖引擎就绪判断。')}</p>${impact?`${!print?`<label>${t('Inspect a dependency','检查一条依赖')}<select id="f-dependency">${p.dependencies.map(e=>`<option value="${esc(e.id)}" ${e.id===chosen?.id?'selected':''}>${esc(e.dependency_type||e.id)} · ${esc(e.id.split('/').at(-1))}</option>`).join('')}</select></label>`:''}<div class="f-impact">${['affected','unaffected','unknown'].map((k,i)=>`<section><h3>${t(['Affected','Explicitly unaffected','Unknown'][i],['受影响','明确不受影响','未知'][i])}</h3><ul>${impact[k].map(id=>`<li>${esc(id)}</li>`).join('')||`<li>${t('None established','尚未确定')}</li>`}</ul></section>`).join('')}</div>`:`<p>${t('Current internal dependency projection unavailable for this context or role.','当前背景或角色无法取得内部依赖投影。')}</p>`}</section>
 <section><h2>${t('Capability and requirement hypotheses','能力与需求假设')}</h2>${caps.map(c=>{const r=reqs.find(r=>r.Capability_ID===c.Capability_ID);return `<details data-f-capability="${c.Capability_ID}" ${print?'open':''}><summary>${esc(zh?c.Name_zh:c.Capability_Name)}</summary><p>${esc(zh?r?.Product_Behaviour_zh:r?.Product_Behaviour)}</p><p>${t('Human boundary','人工边界')}: ${esc(zh?c.Human_Boundary_zh:c.Human_Boundary)}</p><p>${t('Observable acceptance','可观察验收')}: ${esc(zh?r?.Acceptance_Hypothesis_zh:r?.Acceptance_Hypothesis)}</p><p class="trace-meta">${esc(c.Capability_ID)} · ${esc(r?.Requirement_ID)} · ${esc(r?.Scene_Refs)} · ${esc(r?.Process_ID)} · ${esc(r?.Source_ID)} · ${esc(r?.Assumption_ID)}</p></details>`;}).join('')}</section>
 <section><h2>${t('Friday validation questions','周五验证问题')}</h2>${(d?.questions||[]).map((q,i)=>`<article data-f-question="${esc(q.question_id)}"><h3>${esc(zh?q.question_zh:q.question)}</h3><p>${t('Current assumption','当前假设')}: ${esc(zh?q.current_assumption_zh:q.current_assumption)}</p><p>${t('Confirming role','确认角色')}: ${esc(zh?q.required_confirming_role_zh:q.required_confirming_role)}</p><p class="trace-meta">${esc(q.question_id)} · ${esc(q.affected_scene_refs)} · ${esc(q.affected_requirement_refs)} · ${t('Open; no client answer inferred','开放；未推断客户答案')}</p></article>`).join('')}</section>
 <details class="f-lab" ${print||nav.definitionLabOpen?'open':''}><summary>${t('Living Case Lab · optional read-only lenses','Living Case Lab · 可选只读视角')}</summary><p>${t('Outcome, Work and Assurance read the same saved case revision. Shadow injection is disabled; no candidate delta is applied to mainline.','结果、工作与保障视角读取同一已保存案件版本。影子注入已禁用；不向主线应用候选变更。')}</p><nav class="controls no-print">${['outcome','work','assurance'].map((v,i)=>button(t(['Outcome','Work','Assurance'][i],['结果','工作','保障'][i]),'f-lens',v)).join('')}</nav><p data-f-lens="${esc(p.lens)}">${esc(p.lens)} · ${t('Same case revision','同一案件版本')} ${esc(p.revision)} · ${p.available?eStatus(p.readinessState,locale):t('Unavailable','不可用')}</p>${p.available&&p.lens!=='outcome'?`<ul>${p.conditions.map(c=>`<li>${esc(c.domain)} · ${eStatus(c.status,locale)}${p.lens==='assurance'?` · ${esc(c.id)} · v${esc(c.revision)}`:''}</li>`).join('')}</ul>`:''}</details>
 <section class="f-limits"><h2>${t('Evidence and remaining limits','依据与剩余限制')}</h2><p>${t('49 registered observations retain inherited verification. Separately dated retrieval/title checks returned 39 of 40 registered official URLs; one PDF retrieval was inconclusive. The provider may use cached crawls; this is not observation, policy, origin-uptime or media re-verification. FHIR R4 / R5 stay distinct.','49 条登记观察保留原验证状态。另行记录日期的检索／标题检查返回了 40 个官方链接中的 39 个；一个 PDF 检索无结论。服务可能使用缓存抓取，不代表观察、政策、源站可用性或媒体重新验证。FHIR R4／R5 保持独立。')}</p><p>${t('DG-F01/F03 static exports passed, while their standalone viewers failed vertical containment and are not primary previews. DG-F02 did not pass the bounded Archify graphical gate; complete semantic fallback is provided. E English DG-E03 also uses semantic fallback. Full schema meta-validation is NOT_RUN. D5 UX-010 permission configuration variants remain a separate residual. The full Workshop-ready acceptance is not claimed.','DG-F01／F03 静态导出通过，但独立查看器未通过垂直容纳检查，不作为主要预览。DG-F02 未通过有限轮次 Archify 图示验证，已提供完整语义备选。E 英文 DG-E03 同样使用语义备选。完整 Schema 元验证未执行。D5 UX-010 权限配置变体仍单独列为残留问题。不声明已满足全部 Workshop-ready 验收。')}</p><p class="trace-meta">SRC-021 · <a href="../00_governance/batch-f/final-fix-verification/red-team-master.json">G1–G6 ${t('actual evidence register','实际证据登记')}</a> · <a href="../00_governance/batch-f/build-inventory.json">${t('Derived source inventory','衍生来源清单')}</a></p></section></main>`;
}
