import {screeningGraphHtml} from './screening-graph.mjs';
import {referenceHtml} from './reference-ui.mjs';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const translator=locale=>(en,zh)=>locale==='zh-CN'?zh:locale==='en-US'?en.replaceAll('authorised','authorized').replaceAll('Authorised','Authorized'):en;
const stateLabel=(value,L)=>({included:L('Included','已纳入'),unresolved:L('Unresolved','未决'),incomplete:L('Incomplete','不完整'),draft:L('Draft','草稿'),pending:L('Pending','等待中'),partial:L('Partial','部分返回'),failed:L('Failed','失败'),completed:L('Completed','已完成'),zero:L('Zero results','零结果'),unknown:L('Unknown','未知'),not_assessed:L('Not assessed','尚未评估'),insufficient:L('Insufficient','不足'),awaiting_input:L('Awaiting input','等待输入'),awaiting_evidence:L('Awaiting evidence','等待证据'),referred:L('Referred','已转交'),not_ready:L('Not ready','尚未就绪')})[value]||esc(value||L('Not available','不可用'));
const badge=(value,L)=>`<span class="badge">${stateLabel(value,L)}</span>`;
const button=(label,value,{disabled=false,primary=false,item='',extra=''}={})=>`<button ${primary?'class="primary" ':''}data-action="c-action" data-value="${esc(value)}"${item?` data-item="${esc(item)}"`:''}${disabled?' disabled':''}${extra?` ${extra}`:''}>${label}</button>`;
const guardReason=(action,L)=>action?.allowed?'':`<p class="action-reason">${L('Unavailable','不可用')}: ${esc(action?.reason_codes?.join(' · ')||'PERMISSION_REQUIRED')}</p>`;
export const isScreeningStep=step=>['population','screening','screening-evidence','edd','screening-activity'].includes(step);
export function screeningSafeActivityHtml({projection:p={},locale='en-AU'}={}){const L=translator(locale);return `<section class="c-safe-workspace" data-safe-activity><h2>${L('Activity detail unavailable','活动详情不可用')}</h2><p>${L('This role receives screening progress only; Batch C event actors, rationales and correlation details are not included.','此角色仅接收筛查进度；不包含 Batch C 事件执行人、理由或关联详情。')}</p><p>${L('Case revision','案件版本')} ${esc(p.revision??'—')} · ${L('Next owner','下一责任人')}: ${esc(p.next_owner||'Unassigned')}</p></section>`;}
export function screeningActivityEvents(events=[],projection={}){const allowed=new Set((projection.activity||[]).map(x=>x.id));return events.filter(x=>!x.source_refs?.includes('SRC-016')||allowed.has(x.id));}

export function screeningEntryHtml({locale='en-AU',canContinue=false}={}){
 const L=translator(locale);
 return `<section class="c-entry"><p class="trace-meta">${L('Local simulation','本地模拟')} · Batch C · SRC-016</p><h2>${L('Screening Review','筛查复核')}</h2><p>${L('Continue the same synthetic Batch B case. Population remains incomplete; no result, evidence or decision is created until an explicit action below.','继续同一个 Batch B 合成案件。群体仍不完整；只有明确执行下方操作后才会创建结果、证据或决定。')}</p><div class="controls"><button class="primary" data-action="c-start"${canContinue?'':' disabled'}>${L('Continue current Batch B case','继续当前 Batch B 案件')}</button><button data-action="c-demo">${L('Archive session & open approved partial fixture','归档当前会话并打开已批准的部分状态样例')}</button></div>${!canContinue?`<p class="action-reason">${L('Current case is not yet at the Batch B collaboration context. Use the archival fixture only as an explicit demonstration choice.','当前案件尚未进入 Batch B 协作上下文；仅在明确需要演示时使用归档样例。')}</p>`:''}</section>`;
}

function populationPanel(p,L,print,outcome){
 const latest=p.runs?.at(-1),actions=p.actions||{};
 const members=(p.memberships||[]).map(m=>`<article class="c-record"><div><strong>${esc(m.party_ref.split('/').at(-1)==='person-t'?'Person T':m.party_ref.split('/').at(-1)==='entity-b'?'Entity B':'Entity A')}</strong><small>${esc(m.party_ref)}</small></div>${badge(m.membership_decision,L)}<p>${L('Query input','查询输入')}: ${stateLabel(m.query_input_status,L)}</p></article>`).join('');
 return `<section data-c-panel="population"><div class="c-statusbar"><div><span class="eyebrow">${L('Population revision','群体版本')}</span><strong>v${p.population?.population_revision||'—'}</strong></div><div><span class="eyebrow">${L('Inventory','主体清单')}</span>${badge(p.population?.inventory_status,L)}</div><div><span class="eyebrow">${L('Coverage','覆盖')}</span>${badge(p.coverageSummary?.status,L)}</div></div><div class="c-records">${members}</div><div class="notice">${L('Entity B membership and ownership input remain unresolved. The permitted preliminary run for Person T does not confirm comprehensive population coverage.','Entity B 的成员关系及 ownership 输入仍未决。对 Person T 的获准初筛不代表完整群体覆盖已确认。')}</div>${(p.coverage||[]).map(x=>`<article class="c-result"><strong>${L('Dataset / input currency','数据集 / 输入时效')}: ${stateLabel(x.currency_status,L)}</strong><p>${esc(x.query_scope_ref)} · ${L('Execution','执行')}: ${stateLabel(x.execution_status,L)} · ${L('Outcome','结果')}: ${stateLabel(x.outcome_status,L)}</p></article>`).join('')}${latest?`<article class="c-result"><strong>${L('Latest preliminary run','最近一次初筛')}</strong>${badge(latest.run_status,L)}<p>${esc(latest.id)} · ${L('Result count','结果数')}: ${latest.result_count??L('Not returned','未返回')}</p></article>`:''}${print?'':`<label class="field" for="screening-result-outcome">${L('Facilitator synthetic outcome','主持人选择合成返回结果')}<select id="screening-result-outcome">${['completed','zero','partial','failed','pending'].map(x=>`<option value="${x}" ${outcome===x?'selected':''}>${stateLabel(x,L)}</option>`).join('')}</select></label><div class="work-actions">${button(L('Prepare preliminary query','准备初筛查询'),'prepare_preliminary',{disabled:!actions.prepare_preliminary?.allowed})}${button(L('Request preliminary query','发起初筛查询'),'request_preliminary',{disabled:!actions.request_preliminary?.allowed})}${button(L('Receive selected synthetic result','接收所选合成结果'),'receive_result',{disabled:!latest||!actions.receive_result?.allowed,primary:true})}${button(L('Reassess coverage','重新评估覆盖'),'reassess_coverage',{disabled:!actions.reassess_coverage?.allowed})}</div>${guardReason(actions.prepare_preliminary,L)}${guardReason(actions.request_preliminary,L)}${guardReason(actions.receive_result,L)}`}</section>`;
}

function comparisonTable(p,L){
 const value=v=>v==null?L('Unknown','未知'):Array.isArray(v)?v.map(value).join(' / '):typeof v==='object'?Object.entries(v).map(([k,x])=>`${k}: ${value(x)}`).join(' · '):String(v);
 const provider=(v,c)=>Array.isArray(v)?v.map(x=>`${value(x.value??x)}${x?.precision?` [${x.precision}]`:''}`).join(' / '):value(v);
 return `<table class="compare-table c-compare"><thead><tr><th>${L('Attribute','属性')}</th><th>Person T</th><th>${L('Synthetic source record','合成来源记录')}</th><th>${L('Review state','复核状态')}</th></tr></thead><tbody>${(p.comparisons||[]).map(c=>`<tr><td>${esc(c.attribute_code)}</td><td>${esc(value(c.subject_value??L('Not provided','未提供')))}</td><td>${esc(provider(c.provider_value,c))}</td><td>${stateLabel(c.comparison_result,L)}<br><small>${esc(c.comparison_basis)}</small></td></tr>`).join('')}</tbody></table>`;
}
function reviewPanel(p,L,{rationale='',dirty=false,print=false}={}){
 const a=p.actions||{},f=p.finding;
 if(!f)return `<section data-c-panel="screening"><div class="notice">${L('No current Person T finding. Prepare and run the permitted preliminary query from Population. A completed legacy Entity A finding is not Person T screening completion.','当前没有 Person T 命中。请从“筛查群体”准备并执行获准的初筛。旧的 Entity A 已完成命中不代表 Person T 筛查完成。')}</div></section>`;
 return `<section data-c-panel="screening"><div class="c-finding-head"><div><span class="eyebrow">${L('Current finding','当前命中')}</span><h3>${L('Review the possible match','复核疑似命中')}</h3><small class="trace-meta">${esc(f.id)}</small><p>Person T · ${esc(f.category)} · v${f.revision}</p></div>${badge(f.review_status,L)}</div>${comparisonTable(p,L)}<div class="notice">${L('Similarity is not a disposition. Identity detail remains unresolved and any received material still needs a purpose-specific use assessment.','相似并不构成处置结论。身份细节仍未决，收到的资料仍须进行针对用途的使用评估。')}</div>${(p.decisions||[]).slice(-2).map(d=>`<article class="c-result"><strong>${stateLabel(d.disposition,L)}</strong><p>${esc(d.rationale)}</p><small>${esc(d.id)}</small></article>`).join('')}${print?'':`<label class="field" for="screening-rationale">${L('Review rationale / precise identity gap','复核理由 / 精确身份缺口')}<textarea id="screening-rationale">${esc(rationale)}</textarea></label><p class="small muted">${dirty?L('Unsaved input retained','未保存输入已保留'):p.draft?L('Saved model draft is current','模型草稿已保存'):L('Required for every screening write','每次筛查写入都需要理由')}</p><div class="work-actions">${button(L('Save review draft','保存复核草稿'),'save_review_draft',{disabled:!a.save_review_draft?.allowed})}${button(L('Request identity information','请求身份信息'),'request_identity',{disabled:!a.request_identity?.allowed})}${button(L('Refer to specialist','转交专业复核'),'refer',{disabled:!a.refer?.allowed})}${button(L('Record unresolved','记录为未决'),'record_unresolved',{disabled:!a.record_unresolved?.allowed,primary:true})}${button(L('Record disposition','记录处置'),'record_disposition',{disabled:true})}</div><p class="action-reason">${L('Record disposition unavailable: Exclusion is disabled pending reviewed fixture and permission configuration. No emergency or EDD reason is silently enabled.','记录处置不可用：排除结论等待经复核的样例及权限配置。不会静默启用紧急或 EDD 理由。')}</p>${guardReason(a.record_unresolved,L)}`}</section>`;
}
function evidencePanel(p,L,print){
 const artifacts=p.evidence||[],assessments=p.assessments||[],latest=artifacts.at(-1),a=p.actions||{};
 return `<section data-c-panel="screening-evidence"><div class="notice">${L('Evidence receipt, intake release, linking and screening-purpose sufficiency are separate states. Use the existing Batch B collaboration request and return to this finding.','资料接收、接收放行、证据关联及筛查用途充分性是不同状态。请复用现有 Batch B 协作请求，并返回本命中。')}</div>${(p.branches||[]).map(b=>`<article class="c-branch"><span class="trace-meta">${esc(b.branch_type)}</span><h3>${stateLabel(b.status,L)}</h3><p>${esc(b.wait_reason||b.waiting_for)}</p><p>${L('Owner','责任人')}: ${esc(b.owner_ref||'Unassigned')} · ${L('Attempt','轮次')} ${b.attempt_count}</p><small>${esc(b.fixed_return_target?.finding_ref||b.return_object_ref)}</small></article>`).join('')}${artifacts.map(e=>`<article class="c-record"><div><strong>${esc(e.alias||e.id)}</strong><small>${esc(e.id)}</small></div>${badge(e.intake_security_status,L)}<p>${L('Original submitter retained','保留原提交人')}: ${esc(e.original_submitter_ref)}</p></article>`).join('')||`<p>${L('No screening identity artifact has been received.','尚未收到筛查身份资料。')}</p>`}${assessments.map(x=>`<article class="c-result"><strong>${stateLabel(x.sufficiency,L)}</strong><p>${esc(x.rationale||x.reason_code)}</p><small>${esc(x.id)}</small></article>`).join('')}${print?'':`<div class="work-actions">${p.branches?.some(x=>x.branch_type==='information_gap')?`<button data-action="c-collaboration" class="primary">${L('Open identity request','打开身份请求')}</button>`:''}${button(L('Assess as insufficient','评估为不足'),'assess_identity_insufficient',{disabled:!latest||!a.assess_identity?.allowed})}${button(L('Assess as unknown','评估为未知'),'assess_identity_unknown',{disabled:!latest||!a.assess_identity?.allowed})}${button(L('Resume review','恢复复核'),'resume_branch',{disabled:!p.branches?.some(x=>x.branch_type==='information_gap')||!a.resume_branch?.allowed})}</div>${guardReason(a.assess_identity,L)}${guardReason(a.resume_branch,L)}<button data-action="c-back-review">← ${L('Back to Review finding','返回复核命中')}</button>`}</section>`;
}
function eddPanel(p,L,print){return `<section data-c-panel="edd"><div class="c-statusbar"><div><span class="eyebrow">${L('Applicability','适用性')}</span>${badge(p.edd?.applicability,L)}</div><div><span class="eyebrow">${L('Assessment','评估')}</span>${badge(p.eddAssessment?.status||'not_assessed',L)}</div><div><span class="eyebrow">${L('Approval','批准')}</span>${badge(p.eddAssessment?.approval_status||'unknown',L)}</div></div><div class="notice">${L('No reviewed EDD reason is configured in the approved mainline fixture. Applicability remains unknown; screening findings, EDD and readiness remain separate.','已批准主线样例未配置经复核的 EDD 理由。适用性保持未知；筛查命中、EDD 与就绪状态相互独立。')}</div><article class="c-record"><div><strong>${L('Confirm whether enhanced review applies','确认是否适用强化复核')}</strong><small class="trace-meta">C-Q-EDD-APPLICABILITY</small><small>${L('Owner: Unassigned · bank control owner pending','责任人：未分配 · 银行控制责任人待定')}</small></div><p>${L('Unresolved question: Is EDD applicable to this scoped relationship, and on what reviewed risk basis?','未决问题：EDD 是否适用于此范围内的关系，其经复核的风险依据是什么？')}</p></article>${p.eddAssessment?`<article class="c-record"><div><strong>${L('Enhanced review assessment','强化复核评估')}</strong><small class="trace-meta">${esc(p.eddAssessment.id)}</small><small>${L('Open issues','未决问题')}: ${esc(p.eddAssessment.open_issue_refs?.join(' · '))}</small></div></article>`:''}${print?'':`<button disabled>${L('EDD decision not configured','EDD 决定未配置')}</button>`}</section>`;}
function activityPanel(p,L){return `<section data-c-panel="screening-activity"><p class="small muted">${L('Batch C synthetic activity; not a production audit ledger.','Batch C 合成活动；不是生产审计账本。')}</p>${(p.activity||[]).slice().reverse().map(x=>`<article class="activity"><strong>${esc(x.event_type)}</strong><p>${esc(x.actor_ref)} · ${esc(x.occurred_at)}</p><small>${esc(x.object_refs?.join(' · '))}</small></article>`).join('')}</section>`;}
function printEvidenceUse(p,L){
 const evidence=p.evidence||[],assessments=p.assessments||[];
 return `<section class="c-print-evidence"><h3>${L('Relevant identity evidence and use assessment','相关身份资料及用途评估')}</h3>${evidence.map(e=>`<article class="c-record"><strong>${esc(e.alias||e.id)}</strong><p>${esc(e.id)} · ${L('Intake','接收')}: ${stateLabel(e.intake_security_status,L)} · ${L('Evidence revision','证据版本')}: ${esc(e.evidence_revision??L('Unknown','未知'))}</p></article>`).join('')||`<p>${L('Identity artifact: Unknown / not received.','身份资料：未知 / 尚未收到。')}</p>`}${assessments.map(a=>`<article class="c-result"><strong>${L('Screening-purpose use','筛查用途')}: ${stateLabel(a.sufficiency,L)}</strong><p>${esc(a.id)} · ${esc(a.evidence_id||L('Evidence unknown','证据未知'))}</p><p>${esc(a.rationale||a.reason_code||L('Rationale unknown','理由未知'))}</p></article>`).join('')||`<p>${L('Screening-purpose assessment: Unknown / not assessed.','筛查用途评估：未知 / 尚未评估。')}</p>`}</section>`;
}

export function screeningWorkspaceHtml({projection:p,role='ROLE-KYCOPS',step='screening',locale='en-AU',rationale='',dirty=false,outcome='completed',print=false}={}){
 const L=translator(locale);
 if(!p||p.allowed===false)return `<section class="c-safe-workspace"><h2>${L('Screening workspace unavailable','筛查工作台不可用')}</h2><p>${esc(p?.reason||'PERMISSION_REQUIRED')}</p></section>`;
 if(role==='ROLE-RM'||role==='ROLE-CLIENT')return `<section class="c-safe-workspace" data-safe-role="${esc(role)}"><p class="eyebrow">${L('Permitted progress view','获准进度视图')}</p><h2>${L('Review in progress','复核进行中')}</h2><p>${L('Next owner','下一责任人')}: ${esc(p.next_owner||'Unassigned')} · ${L('Case revision','案件版本')} ${p.revision}</p>${p.collaboration?`<p>${L('An assigned client-safe request is available in Collaboration.','协作中有一项已分配的客户安全请求。')}</p>`:''}</section>`;
 const panels={population:()=>populationPanel(p,L,print,outcome),screening:()=>reviewPanel(p,L,{rationale,dirty,print}),'screening-evidence':()=>evidencePanel(p,L,print),edd:()=>eddPanel(p,L,print),'screening-activity':()=>activityPanel(p,L)};
 const sharedRationale=!print&&!['screening','screening-activity','edd'].includes(step)?`<label class="field" for="screening-rationale">${L('Action rationale / precise gap','操作理由 / 精确缺口')}<textarea id="screening-rationale">${esc(rationale)}</textarea></label><p class="small muted">${dirty?L('Unsaved input retained','未保存输入已保留'):L('Prepared against the visible case and input revisions','已基于当前可见案件及输入版本准备')}</p>`:'';
 return `<section class="c-workspace ${print?'c-print':''}" data-c-role="${esc(role)}"><div class="c-casehead"><div><span class="trace-meta">${esc(p.case_id||'DEMO-CTT-001')} · SRC-016</span><h2>${L('Screening','筛查')}</h2><p>Entity A · Person T · ${L('scope','范围')} v${p.scopeRevision} · ${L('case','案件')} v${p.revision}</p></div><div>${badge(p.readiness?.result,L)}<p class="small">${L('Population','筛查群体')}: ${stateLabel(p.population?.inventory_status,L)}</p></div></div>${sharedRationale}${panels[step]?panels[step]():reviewPanel(p,L,{rationale,dirty,print})}${print?printEvidenceUse(p,L):''}</section>`;
}

export function screeningSceneHtml({scene='SCN-MATCH',locale='en-AU',mode='Target',projection={},focus=null,print=false}={}){
 const L=translator(locale),graph=screeningGraphHtml({scene,locale,mode,predicates:projection.predicates||{},facts:projection.facts||{},actions:projection.actions||{},focus,print});
 return `<section class="c-scene-logic">${graph}${print?`<section class="c-scene-references"><h3>${L('References','研究依据')}</h3>${referenceHtml({locale,scene,print:true})}</section>`:`<div class="c-reference-entry"><button data-action="reference-scene">${L('References / research','研究依据')}</button><p>${L('Open the shared read-only library for this scene. Research is not case evidence.','打开此场景共用的只读研究库。研究资料不是案件证据。')}</p></div>`}</section>`;
}
