export const pair=(en,zh)=>({'en-AU':en,'en-US':en,'zh-CN':zh});
export const stages=[['S1','Initiate & scope','发起与界定','M0 · M1'],['S2','Determine & source','明确要求与取证','M2 · M3'],['S3','Screen & assess','筛查与评估','M4 · M5'],['S4','Assure & resolve','复核与解决','M6 · C1 · C2 · M7'],['S5','Clear to trade','交易准入','M8']];
export const roles=[['ROLE-CLIENT','Client','客户'],['ROLE-RM','Relationship Manager','客户经理'],['ROLE-KYCOPS','Case Manager / KYC Ops','案件经理 / KYC 运营'],['ROLE-REVIEWER','Risk / Financial Crime / QA','风险 / 金融犯罪 / QA'],['ROLE-SPECIALISTS','Legal / Credit / Conflicts','法务 / 信贷 / 利益冲突']];
const s=(id,stage,en,zh,process,current,target,wait,output,human,journey=[])=>({id,stage,title:pair(en,zh),process,current:pair(...current),target:pair(...target),wait:pair(...wait),output:pair(...output),human:pair(...human),journey,source:'SRC-007',status:'DESIGN-HYPOTHESIS',revision:1});
const d=(...args)=>({...s(...args),source:'SRC-019',revision:2});
export const scenes=[
 s('SCN-SCOPE','S1','Define the relationship','明确本次关系范围','M0.1–M0.4 · M1.1',
 ['RM and Ops clarify the requested relationship, proposed legal entity, product and booking context. Current already performs this work.','客户经理与运营澄清申请关系、拟交易法人、产品和 booking 背景。Current 已包含这些工作。'],
 ['Product organises Group A, Entity A and requested FX forward as separate, sourced fields. Human records the working scope and visible unknowns.','产品将 Group A、Entity A 与申请的 FX forward 分为有来源的字段。人工记录工作范围并保留未知事项。'],
 ['Counterparty clarification; booking, eligibility and DD remain unresolved.','等待交易主体澄清；booking、产品资格与尽调等级尚未确定。'],
 ['A versioned working scope feeds entity review and a requirements draft. It is not a product, KYC or clearance approval.','版本化工作范围供主体复核与要求草稿使用，不代表产品、KYC 或准入批准。'],
 ['Explicit demo permission to record working scope; actual bank authority remains a validation question.','以明确演示权限记录工作范围；银行实际权限仍待验证。']),
 s('SCN-ENTITY','S1','Establish entity and authority','确认主体与代表权限','M1.3–M1.5 · M3.4',
 ['Ops checks legal entity details and supplied evidence. Specific representative authority is assessed separately; authority detail is an industry-informed extension.','运营核对法人资料与所提供证据。代表权限单独评估；具体权限建模为行业参考扩展。'],
 ['Separate Entity A, reported parent B and Person T. Assess EV-A03 only for coordinating information for A; open a purpose-specific gap.','分开 Entity A、声称的母公司 B 与 Person T。仅评估 EV-A03 对为 A 协调资料的支持，并建立用途级缺口。'],
 ['Person T is employed by B. Evidence establishing the specific authority for A has not arrived.','Person T 任职于 B，尚未收到建立为 A 行事之具体权限的证据。'],
 ['Entity context becomes clearer, authority work awaits evidence, and only eligible preparation continues. Overall Not ready.','主体背景更清楚；权限任务等待证据；仅满足门槛的准备工作继续。整体尚未就绪。'],
 ['A configured employee records an evidence-use assessment, not a blanket approval of Person T. Unknown task owner is Unassigned.','配置的员工记录证据用途评估，而非全权批准 Person T。未知任务责任人保留未分派。']),

 s('SCN-REQUIREMENTS','S2','Make requirements explicit','明确适用要求','M2.1–M2.5',
 ['Determine AML and non-AML requirements, exceptions and risk indicators for the relationship.','按关系范围确定 AML 与非 AML 要求、例外及风险指标。'],
 ['Prepare a versioned requirement set. Show the subject, purpose and basis of each requirement; retain unknown applicability.','编制版本化要求集；逐项关联主体、用途和依据，保留未知适用性。'],
 ['Scope and policy context must be known. Exceptions require a designated reviewer.','需明确范围与政策背景；例外须交指定复核人员。'],
 ['Requirements confirmed for this synthetic scope; evidence still needs assessment.','仅确认本合成范围内的要求；证据仍待评估。'],
 ['Confirm the demo requirement set. No client policy is inferred.','确认演示要求集，不据此推断客户政策。'],['J-M2-01']),
 s('SCN-SOURCE','S2','Use evidence already available','复用已有证据','M3.1–M3.2',
 ['Search public and commercial sources, then identify residual gaps. This already exists in the Current map.','检索公开与商业来源并识别剩余缺口；Current 源图已包含这些活动。'],
 ['Link a source item to a specific subject, requirement and purpose, with its original version intact.','将来源资料关联到具体主体、要求和用途，保留原版本。'],
 ['Access permission, source provenance and purpose-specific sufficiency.','等待来源许可、出处核验及特定用途的充分性判断。'],
 ['Entity identity may be supported; screening disambiguation remains a separate use.','主体身份可获得支持；筛查身份区分仍是独立用途。'],
 ['Review proposed reuse. One accepted file does not satisfy every requirement.','复核拟议复用；接受一份文件不等于满足所有要求。'],['J-M3-01']),
 s('SCN-GAP','S2','Ask only for remaining gaps','只询问剩余缺口','M2.5 · M3.2–M3.3',
 ['Issue requirements and request outstanding information from the client.','发布要求并向客户请求尚缺信息。'],
 ['Consolidate only unresolved facts into a purpose-specific request, with an owner and response link.','仅将未解决事实汇总为用途明确的请求，并指定责任人与响应关联。'],
 ['A permitted sender confirms the request; the review then waits for the named response.','允许发送的角色确认请求后，复核等待指定响应。'],
 ['Request recorded locally. No email is sent. Receipt returns evidence to review.','本地记录请求，不发送邮件；收到响应后回到证据复核。'],
 ['Review the missing fact, purpose and response owner before simulating release.','模拟发出前复核缺失事实、用途与响应责任人。'],['J-M3-02','J-M3-03']),
 s('SCN-VALIDATE','S2','Assess evidence for its purpose','按用途评估证据','M3.4–M3.5',
 ['Capture and validate evidence; maintain outstanding gaps and the sourcing trail.','接收并核验证据，维护剩余缺口与来源记录。'],
 ['Keep the artifact and its use assessment separate. A received supplement needs its own reviewed assessment.','分开保存资料与用途评估；收到补充资料后仍须独立复核。'],
 ['The received supplement and a reasoned sufficiency assessment for the screening purpose.','等待收到补充资料，以及针对筛查用途的充分性理由。'],
 ['Evidence use assessed. Screening still requires a separate human disposition.','完成证据用途评估；筛查仍须独立人工处置。'],
 ['A configured demo reviewer records sufficiency with rationale; bank authority remains open.','配置的演示复核角色记录充分性及理由；银行权限仍未确认。'],['J-M3-04']),
 s('SCN-POPULATION','S3','Screen the right subjects','明确筛查群体','M4.1–M4.4',
 ['Teams assemble parties and categories from available case material, while unconfirmed ownership and related-party membership remain open.','团队依据现有案件资料整理主体与类别；未确认的 ownership 及关联方成员关系保持未决。'],
 ['A versioned population shows Entity A, Entity B and Person T separately. A permitted preliminary run can proceed for Person T without claiming comprehensive coverage.','版本化筛查群体分别展示 Entity A、Entity B 与 Person T。可对 Person T 执行获准初筛，但不宣称完整覆盖。'],
 ['Ownership input and an upstream-confirmed complete inventory interface.','等待 ownership 输入及上游确认完整清单的接口。'],
 ['Population remains incomplete; the permitted subject and any missing members are explicit.','群体保持不完整；明确显示获准筛查主体及缺失成员。'],
 ['A human reviews inclusion basis and current inputs. No hidden category or comprehensive run is configured.','人工复核纳入依据与当前输入；不配置隐藏类别或完整筛查。']),
 s('SCN-MATCH','S3','Resolve a possible match','处理疑似筛查命中','M4.5–M4.7',
 ['Adjudicate possible hits, assess materiality and record the screening outcome.','处置疑似命中、判断重大性并记录筛查结果。'],
 ['Prepare subject-to-record comparisons and evidence-use links. A human records the disposition or requests more information.','整理主体与记录的逐项对照及证据用途；由人工记录处置或请求更多信息。'],
 ['Sufficient current evidence, rationale and explicit simulated authority. Similarity is not a decision.','等待当前充分证据、理由及明确演示权限；相似性不等于决定。'],
 ['A bounded decision records unresolved or referral against current inputs. Identity, population, EDD and other case conditions remain separately visible.','针对当前输入记录有范围的未决或转交决定；身份、筛查群体、EDD 及其他案件条件继续分别可见。'],
 ['Only a configured reviewer may record the permitted unresolved outcome. Exclusion is disabled; there is no autonomous approval or automatic EDD.','仅配置的复核人员可记录获准的未决结果。排除结论未开放；不自主批准，也不自动触发 EDD。']),
 s('SCN-EDD','S3','Assess elevated risk, if applicable','按适用性进入 EDD','M5',
 ['EDD applicability is assessed separately from sanctions finding review; missing reasons remain unknown.','EDD 适用性与制裁命中复核分开评估；缺少理由时保持未知。'],
 ['Show required, not required or unknown with its exact reviewed basis. If required, open only a bounded targeted pack and keep approval unknown.','以精确的经复核依据展示 required、not required 或 unknown。若为 required，仅建立有限的针对性资料包，并保持批准未知。'],
 ['A reviewed, current-scope reason and explicit permission. The approved default contains neither.','等待当前范围内经复核的理由及明确权限；已批准默认状态两者均未配置。'],
 ['Applicability remains unknown and readiness remains Not ready; screening and EDD do not overwrite one another.','适用性保持未知，就绪状态仍为尚未就绪；筛查与 EDD 不相互覆盖。'],
 ['A human records applicability and any specialist assessment. No EDD approval or clearance writer is configured.','由人工记录适用性及专业评估；未配置 EDD 批准或准入写入。']),
 d('SCN-CONFLICTS','S1','Start conflicts early','尽早启动利益冲突检查','M1 → M7',
 ['Conflicts is often understood through disconnected searches, findings and late clearance checks. An open finding can be difficult to relate to the original scope.','利益冲突通常通过分散的搜索、发现及后期准入检查来理解；未决发现难以关联到原始范围。'],
 ['Start the scoped search from intake, retain the finding and Hold separately, and show its independent contribution to readiness.','从受理阶段启动有范围的搜索，分别保留发现与 Hold，并显示其对就绪状态的独立贡献。'],
 ['A configured specialist review; the search being complete does not resolve the finding.','等待已配置的专业复核；搜索完成并不代表发现已解决。'],
 ['Search complete, finding open, specialist review pending and clearance pending remain distinct states.','搜索完成、发现未决、等待专业复核及准入待定保持为不同状态。'],
 ['Only configured Conflicts roles see restricted detail. No misconduct finding, clearance decision or whole-case approval is inferred.','仅已配置的利益冲突角色可查看受限详情；不据此推断不当行为、准入决定或全案批准。'],['D1','D2']),
 d('SCN-CREDIT','S4','Resolve credit conditions','解决信贷条件','C2.1–C2.3',
 ['Credit assessment, decision, condition and Legal handoff can appear current even when their consumed versions are not explicit.','当使用的版本未明确时，信贷评估、决定、条件及法务交接可能看似均为最新。'],
 ['Keep CD-01, CC-01 and AI-01 revision-addressed. A revised Credit input visibly makes the existing Legal consumer stale without overwriting history.','保持 CD-01、CC-01 与 AI-01 带版本；信贷输入修订后，明确标记既有法务使用方为旧输入，同时不覆盖历史。'],
 ['Documentation incorporation before execution; Credit approval does not fulfil Legal documentation or signing.','等待签署前纳入文件条件；信贷批准不等于完成法务文件或签署。'],
 ['Credit condition approved, documentation incorporation pending and Legal execution pending are shown separately.','分别显示信贷条件已批准、文件纳入待完成及法务签署待完成。'],
 ['The facilitator may simulate one guarded revision. It is not a monetary decision, policy change, approval or case clearance.','主持人可模拟一次受保护的版本修订；这不是金额决定、政策变更、批准或案件准入。'],['D3']),
 d('SCN-LEGAL','S4','Complete applicable agreements','完成适用协议','C1.1–C1.3',
 ['Legal drafting and approval can obscure which Credit input a document consumed and whether signatory authority is known.','法务起草与内部批准可能掩盖文件所使用的信贷输入版本，以及签署权限是否已知。'],
 ['Freeze AGR-01 revision 03 with its consumed AI-01 revision. Flag stale Credit input while keeping review, internal approval and execution separate.','冻结显示 AGR-01 版本 03 及其使用的 AI-01 版本；标记旧信贷输入，同时分开显示复核、内部批准与签署。'],
 ['A current Credit input, validated signatory authority and execution. Conflicts and other case conditions remain independent.','等待当前信贷输入、经验证的签署权限及签署；利益冲突及其他案件条件保持独立。'],
 ['Agreement revision 03 remains internally approved and execution pending; stale upstream input is visible after revision.','协议版本 03 保持内部已批准且等待签署；上游修订后明确显示旧输入。'],
 ['Internal approval is not execution or signing authority. The prototype exposes no Legal approval, execution or clearance writer.','内部批准不等于签署或签署权限；原型不提供法务批准、签署或准入写入。'],['D4']),
 s('SCN-READINESS','S5','Know exactly what remains','明确还剩哪些条件','M8.1',
 ['Confirm completion of all applicable clearance prerequisites.','核对所有适用准入前置条件是否完成。'],
 ['Derive a versioned snapshot from explicit conditions, each with its own owner, reason and next action.','依据明确条件计算版本化快照；每项保留责任人、理由和下一步。'],
 ['Legal execution, Credit conditions, QA review and any unresolved applicability.','等待协议执行、信贷条件、QA 复核及所有未知适用性。'],
 ['Not ready is an explainable result, not a percentage. Authorisation and publication stay separate.','未就绪是可解释结果，而非百分比；授权确认与发布保持独立。'],
 ['Final bank authority is not configured. Publishing and real trades are outside this slice.','未配置银行最终授权；发布及真实交易不属于本切片。'])
];
export const skeleton=[['SCN-QA','S4','Close a specific quality gap','关闭具体质量缺口','M6'],['SCN-PUBLISH','S5','Publish the scoped outcome','发布有范围的结果','M8.2–M8.5']];
export const byId=id=>scenes.find(x=>x.id===id)||(()=>{const a=skeleton.find(x=>x[0]===id);return a?{id:a[0],stage:a[1],title:pair(a[2],a[3]),process:a[4],skeleton:true}:scenes[0];})();
export const txt=(value,locale)=>typeof value==='object'?(value[locale]??value['en-AU']):value;
