import model from './diagrams/batch-c/model.mjs';
import {contracts,conditions} from './diagrams/batch-c/english.mjs';
import diagramDimensions from './diagrams/batch-c/dimensions.mjs';
export function graphProjection(familyId,predicates={},facts={},actions={}){const f=model.families.find(x=>x.id===familyId);if(!f)return null;return{...f,nodes:f.nodes.map(n=>({...n,fact:facts[({P02:'membership_decision',P05:'result_status',P07:'inventory_status',P10:'coverage_status',M04:'identity_sufficiency',M12:'coverage_status',E02:'edd_applicability',E07:'edd_evidence_status',E09:'edd_approval_status'})[n.id]]??'not_evaluated',guard:(n.action_ref?actions[n.action_ref]:null)??predicates[n.predicate_ref]??{allowed:false,outcome:'not_evaluated',reason_codes:['No current business predicate; read-only explanation']}}))};}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function screeningGraphHtml({scene='SCN-MATCH',locale='en-AU',mode='Target',predicates={},facts={},actions={},focus=null,print=false}={}){
 const family=model.families.find(x=>x.scene===scene);if(!family)return'';const f=graphProjection(family.id,predicates,facts,actions),zh=locale==='zh-CN';
 if(!zh){f.nodes=f.nodes.map(n=>({...n,contract:contracts[n.id]}));f.edges=f.edges.map(e=>({...e,condition:conditions[e.id]}));}
 const t=(a,b)=>zh?a:b,selected=focus&&!print?f.nodes.filter(n=>n.id===focus):f.nodes;
 const asset=`${f.id}.${mode}.${locale}${((f.id==='DG-C-MATCH')||(f.id==='DG-C-POPULATION'&&locale!=='zh-CN'))?'.r02':''}.svg`,size=diagramDimensions[asset];
 const intrinsic=size?`width="${size.width}" height="${size.height}" style="height:auto"`:'';
 return `<section class="screening-graph"><p class="eyebrow">Archify 2.17 · ${esc(f.id)} · ${t('只读逻辑视图','Read-only logic view')}</p><img class="c-diagram" src="./diagrams/batch-c/${asset}" ${intrinsic} alt="${esc(f.id)} ${t('分组总览；完整判断见下表','grouped overview; complete decisions below')}" onerror="this.hidden=true"><p>${t('连线表示讲解关系，不执行业务动作。完整分支、权限与等待条件如下。','Connections explain the design; they do not execute business actions. All branches, permission and wait conditions remain below.')}</p>${!print?`<nav aria-label="${t('聚焦判断','Focus decision')}"><button data-c-node="">${t('全部判断','All decisions')}</button>${f.nodes.map(n=>`<button data-c-node="${n.id}" aria-pressed="${focus===n.id}">${n.id}</button>`).join('')}</nav>`:''}<div class="c-decision-table">${selected.map(n=>`<article id="node-${n.id}" data-semantic-node="${n.id}"><h4>${n.id} · ${esc(zh?n.title_zh:n.title_en)}</h4><p>${esc(n.contract)}</p><p>${t('当前事实','Current fact')}: ${esc(n.fact)}</p><p>${t('相关动作检查（不是此节点的自动裁决）','Related action guard (not automatic node adjudication)')}: ${esc(n.guard.outcome)} · ${esc(n.guard.reason_codes?.join(' / '))}</p><small>${esc(n.predicate_ref)} · ${t('本项目设计推导，不是银行规则批准','Our interpretation, not approved bank policy')}</small>${!print?`<button data-c-ref="${n.id}" aria-label="${t('查看该判断的依据','View sources for decision')} ${n.id}">R</button>`:''}<ul>${f.edges.filter(e=>e.from===n.id).map(e=>`<li>${e.from} → ${e.to}: ${esc(e.condition)}</li>`).join('')}</ul></article>`).join('')}</div></section>`;
}
