import {transformationFor} from './content.mjs';
import {transformationBinding} from './transformations/diagram-bindings.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function transformationHtml({scene,locale='en-AU',comparison='target',compare=false,context={},selectedChange=null,openChanges=[],traceOpen=[],diagramFocus=null,print=false}={}){
 const pilot=transformationFor(typeof scene==='string'?scene:scene?.id,locale);if(!pilot)return '';
 const zh=locale==='zh-CN',t=(en,cn)=>zh?cn:en,both=compare||print;
 const sources=items=>items.map(s=>`<p>${esc(s.verbatim_text)} · ${esc(s.visible_actor)}<br><span class="trace-meta">${esc(s.deck_filename)} · ${t('slide','页')} ${esc(s.slide_no)} · ${t('shape','形状')} ${esc(s.shape_id)} · ${esc(s.source_id)}</span></p>`).join('');
 const work=(change,view)=>`<section data-view="${view}"><h4>${view==='current'?'Current':'Target'}</h4><p>${esc(change[view])}</p></section>`;
 const changes=pilot.changes.map((change,i)=>{
  const open=print||openChanges.includes(change.id),binding=transformationBinding(change.id);
  const refs=change.references.map(ref=>`<article><p><strong>${esc(ref.title)}</strong></p><p>${esc(ref.observation)}</p><p>${t('Limits','边界')}: ${esc(ref.limits)}</p><p class="trace-meta">${esc(ref.sourceStatus)} · ${t('Inherited verification; no new verification claimed','沿用核验记录；本视图未新增核验')}</p>${!print&&ref.canonicalRef?`<button data-action="transformation-reference" data-value="${esc(ref.canonicalRef)}" data-change="${esc(change.id)}">${t('Read source record','阅读来源记录')}</button>`:''}${ref.url?`<a href="${esc(ref.url)}" target="_blank" rel="noopener noreferrer" referrerpolicy="no-referrer">${t('Public source','公开来源')} ↗</a>`:''}</article>`).join('');
  return `<details class="transformation-change${selectedChange===change.id?' is-selected':''}" data-change-id="${esc(change.id)}"${open?' open':''}><summary><span class="transformation-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><strong>${esc(change.title)}</strong><small class="trace-meta">${esc(zh?({'Enhanced':'强化','Proposed addition':'拟议新增','Retained':'保留','Reassigned':'职责调整'})[change.type]||change.type:change.type)}</small></summary><div class="transformation-change-body"><div class="transformation-work${both?' is-compare':''}">${both?work(change,'current')+work(change,'target'):work(change,comparison==='current'?'current':'target')}</div><p class="transformation-boundary"><strong>${t('Control boundary','控制边界')}</strong> ${esc(change.boundary)}</p>${!print&&binding?`<button data-action="transformation-focus" data-value="${esc(change.id)}">${t('Locate in product diagram','定位到产品图')}</button>`:''}<details class="trace-details" data-trace-id="${esc(change.id)}"${print||traceOpen.includes(change.id)?' open':''}><summary>${t('Why this change · sources and fields','改变依据 · 来源与字段')} <span class="trace-meta">${esc(change.id)}</span></summary><div class="transformation-provenance"><section data-provenance="current"><h4>${t('1. Current source','1. Current 来源')}</h4>${sources(change.currentSources)}</section><section data-provenance="target"><h4>${t('2. Target source','2. Target 来源')}</h4>${sources(change.targetSources)}</section><section data-provenance="reference"><h4>${t('3. Reference observations','3. 参考观察')}</h4>${refs}</section><section data-provenance="interpretation"><h4>${t('4. Our design interpretation','4. 本项目设计推导')}</h4>${change.references.map(ref=>`<p>${esc(ref.adaptation)}</p>`).join('')}<p>${t('A design proposal for validation; not approved bank policy or proof of deployment.','供验证的设计提案；不是银行已批准政策或投产证明。')}</p></section></div><h4>${t('Proposed field changes','拟议字段变化')}</h4><ul class="trace-meta transformation-fields">${change.fields.map(field=>`<li><code>${esc(field)}</code></li>`).join('')}</ul></details></div></details>`;
 }).join('');
 const binding=transformationBinding(diagramFocus),focused=pilot.changes.find(c=>c.id===diagramFocus);
 const diagram=binding&&focused?`<section class="transformation-diagram" id="transformation-diagram" tabindex="-1" data-diagram-change="${esc(focused.id)}"><h4>${t('Product diagram','产品图')} · ${esc(focused.title)}</h4><p>${t('Existing proposed product view. Highlighted work references below locate the design; no case action is executed.','既有拟议产品视图。下列工作引用用于定位设计，不执行案件操作。')}</p><p class="trace-meta">${esc(binding.diagram)} · ${esc(binding.archifyNodes.join(' / '))} · ${esc(binding.semanticNodes.join(' / '))}</p>${pilot.id==='SCN-GAP'?`<img src="${esc(binding.asset.replace('en-AU',locale))}" alt="${t('Proposed client collaboration product','拟议客户协作产品')}">`:`<p>${t('The screening decision view below is focused on the linked work.','下方筛查判断视图已聚焦关联工作。')}</p>`}</section>`:'';
 return `<section class="transformation-panel" aria-label="${t('Work transformation','工作变化')}" data-transformation-scene="${esc(pilot.id)}"><header class="transformation-head"><div><p class="eyebrow">${t('Work transformation · pilot','工作变化 · 试点')}</p><h3>${esc(pilot.title)}</h3></div>${print?'':`<button data-action="transformation-compare" aria-pressed="${compare}">${compare?t('Single view','单列视图'):t('Compare Current / Target','并排对比 Current / Target')}</button>`}</header><p>${t('Open a work item to inspect the activity, proposed change and human control.','展开一项工作，查看活动、拟议变化及人工控制。')}</p><details class="transformation-context trace-details" data-trace-id="${esc(pilot.id)}-context"${print||traceOpen.includes(pilot.id+'-context')?' open':''}><summary>${t('Same input · authored comparison checkpoint','同一输入 · 编制的对比检查点')}</summary><p>${esc(pilot.checkpoint)}</p><p>${esc(pilot.inputManifest)}</p><p class="trace-meta"><strong>Current</strong> ${esc(pilot.currentSummary)}</p><p class="trace-meta"><strong>Target</strong> ${esc(pilot.targetSummary)}</p><p>${t('This read-only comparison does not mean the live case has reached this checkpoint. Comparing never loads a fixture.','此只读设计对比不表示活动案件已达到该检查点；切换对比不会载入样例。')}</p><p class="trace-meta">${esc(context.caseId)} · ${t('Scope revision','范围版本')} ${esc(context.scopeRevision)} · ${t('Case revision','案件版本')} ${esc(context.caseRevision)}</p></details><div class="transformation-controls"><p><strong>${t('Wait and resume','等待与恢复')}</strong> ${esc(pilot.waitResume)}</p><p><strong>${t('Always preserved','必须保留')}</strong> ${esc(pilot.invariants)}</p></div><div class="transformation-changes">${changes}</div>${diagram}<p class="transformation-question"><strong>${t('Validate with users','与用户验证')}</strong> ${esc(pilot.validationQuestion)}</p></section>`;
}
