// Local workshop state is separate from product case state. Imported scoring dimensions are retained.
HERO.clear();SCENARIOS.forEach(s=>HERO.add(s.id));
state={...initialState(),...state,previewBundles:state.previewBundles||{},gates:state.gates||{},phaseOverrides:state.phaseOverrides||{}};
const baseRender=renderAll,basePortfolioCard=portfolioCard,baseBundlePanel=bundleScorePanel;
let mapping=null;
const moduleMessage=(type,value)=>parent.postMessage({channel:'ctt-module',type,...(type==='view'?{view:value}:{id:value})},location.origin);
const returnNav=document.createElement('nav');returnNav.className='module-return';returnNav.innerHTML='<button class="btn" id="returnProduct">← Product demo</button><button class="btn" id="returnJourney">Journey / scenarios</button><span class="tag">Workshop · final step</span>';
document.querySelector('.container').prepend(returnNav);document.getElementById('returnProduct').onclick=()=>moduleMessage('view','product');document.getElementById('returnJourney').onclick=()=>moduleMessage('view','journey');
if(new URLSearchParams(location.search).get('embedded')==='studio')returnNav.remove();
function validScore(v){return Number.isFinite(v)&&v>=1&&v<=5}
save=function(){try{localStorage.setItem(STORE,JSON.stringify(state));showToast('Saved locally')}catch{showToast('Storage unavailable — export your session before leaving')}};
scheduleSave=function(){clearTimeout(st);renderMetrics();save()};
setScenarioScore=function(sid,key,party,v){if(!validScore(v))return;const s=state.scenarioScores[sid]?.[key];if(!s||!['ntt','client'].includes(party))return;s[party]=party==='client'&&s[party]===v?null:v;renderAll();save()};
setBundleScore=function(sid,bid,key,party,v){if(!validScore(v))return;const s=state.bundleScores[sid]?.[bid]?.[key];if(!s||!['ntt','client'].includes(party))return;s[party]=party==='client'&&s[party]===v?null:v;renderAll();save()};
setFinal=function(id,v){if(v!==''&&!validScore(Number(v)))return;state.finalConsensus[id]=v===''?null:Number(v);renderAll();save()};
consensusReached=function(id){return reviewed(id)&&(alignmentGap(id)<2||state.finalConsensus[id]!=null&&!!state.notes[id]?.trim())};
selectBundlePreview=function(sid,bid){state.previewBundles[sid]=bid;renderAll();save()};
const originalBundleRender=renderBundleStep;
renderBundleStep=function(){const sid=state.selectedScenario,committed=state.selectedBundles[sid];state.selectedBundles[sid]=state.previewBundles[sid]||committed;originalBundleRender();state.selectedBundles[sid]=committed};
selectedCombo=function(sid){const bid=state.selectedBundles[sid];if(!bid||!state.portfolio[sid])return null;return {scenario:sdata(sid),bundle:BUNDLES[sid].find(b=>b.id===bid),score:bundleScore(sid,bid),scenarioScore:scenarioScore(sid)}};
phaseSuggestion=function(sid,bid){const b=BUNDLES[sid].find(x=>x.id===bid),bs=bundleScore(sid,bid),ss=scenarioScore(sid);if(b.control==='Blocked'||b.dependency==='Blocked')return 'P3';if(b.control==='Pass'&&b.dependency==='Pass'&&bs>=4&&ss>=4)return 'P1';if(b.control==='Pass'&&b.dependency==='Pass'&&bs>=3.5)return 'P2';return 'P3'};
function setGate(sid,bid,key,value){if(!['Pass','Conditional','Blocked'].includes(value)||!['control','dependency'].includes(key))return;state.gates[sid+'|'+bid]??={};state.gates[sid+'|'+bid][key]=value;BUNDLES[sid].find(b=>b.id===bid)[key]=value;if(state.selectedBundles[sid]===bid&&!state.phaseOverrides[sid])state.phase[sid]=phaseSuggestion(sid,bid);renderAll();save()}
bundleScorePanel=function(s,b){return baseBundlePanel(s,b)+`<div class="gate-editor">${[['control','Control Fit'],['dependency','Dependency Fit']].map(([k,t])=>`<label>${t} · workshop assessment<select aria-label="${t}" onchange="setGate('${s.id}','${b.id}','${k}',this.value)">${['Pass','Conditional','Blocked'].map(v=>`<option ${b[k]===v?'selected':''}>${v}</option>`).join('')}</select></label>`).join('')}</div><p class="footer-note">Gates do not enter the numeric average. A Pass is a workshop assessment, not a bank approval. Selecting a preview does not add it to the portfolio.</p>`};
portfolioCard=function(c){return basePortfolioCard(c).replace('<div class="pc-controls">',`<div class="gate-row"><span class="gate ${c.bundle.control.toLowerCase()}">Control Fit: ${c.bundle.control}</span><span class="gate ${c.bundle.dependency.toLowerCase()}">Dependency Fit: ${c.bundle.dependency}</span></div><div class="pc-meta">NTT DATA: ${partyMean(c.scenario.id,'ntt').toFixed(1)} · Client: ${partyMean(c.scenario.id,'client')?.toFixed(1)||'Not scored'} · ${state.finalConsensus[c.scenario.id]!=null?'Final consensus':'Draft, not agreed'}</div><div class="pc-controls">`)};
function partyMean(id,party){const v=DIMS.map(d=>state.scenarioScores[id][d[0]][party]);return v.some(x=>x==null)?null:v.reduce((a,b)=>a+b,0)/v.length}
setPhase=function(sid,value){if(!['P1','P2','P3'].includes(value))return;const c=selectedCombo(sid);if(!c)return;if(value!==phaseSuggestion(sid,c.bundle.id)&&!state.portfolio[sid]?.note?.trim()){showToast('Add a decision note before overriding the suggested phase.');renderAll();return}state.phase[sid]=value;state.phaseOverrides[sid]=value!==phaseSuggestion(sid,c.bundle.id);renderAll();save()};
const oldAdd=addPortfolio;addPortfolio=function(sid,bid){const previous=state.selectedBundles[sid];if(previous!==bid){delete state.phase[sid];delete state.phaseOverrides[sid]}oldAdd(sid,bid)};
const oldRemove=removeCombo;removeCombo=function(sid){delete state.previewBundles[sid];delete state.phaseOverrides[sid];oldRemove(sid)};
function enhanceAccessibility(){document.querySelectorAll('.step,.scenario-card,.bundle-card,.rank-item').forEach(e=>{e.tabIndex=0;e.setAttribute('role','button');e.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();e.click()}}});document.querySelectorAll('.score-btn').forEach(e=>{const call=e.getAttribute('onclick'),parts=call.match(/'([^']+)'/g)||[];e.setAttribute('aria-label',parts.map(x=>x.slice(1,-1)).join(' ')+' score '+e.textContent);e.setAttribute('aria-pressed',String(e.classList.contains('on')))});document.querySelectorAll('.rank-item,.scenario-card').forEach(e=>{e.style.minHeight='44px'});document.querySelectorAll('.party-label').forEach(e=>{if(e.textContent==='Client')e.title='Blank until a client participant scores. Click an active score again to clear it.'})}
renderAll=function(){for(const [id,values] of Object.entries(state.gates)){const [sid,bid]=id.split('|'),b=BUNDLES[sid]?.find(b=>b.id===bid);if(b)Object.assign(b,values)}baseRender();enhanceAccessibility();document.querySelectorAll('.phase-card').forEach(card=>{const sid=card.querySelector('.phase-code').textContent,c=selectedCombo(sid);if(c){const gates=document.createElement('div');gates.className='gate-row';gates.innerHTML=`<span class="gate ${c.bundle.control.toLowerCase()}">Control: ${c.bundle.control}</span><span class="gate ${c.bundle.dependency.toLowerCase()}">Dependency: ${c.bundle.dependency}</span>`;card.append(gates);if(state.phaseOverrides[sid]){const note=document.createElement('p');note.textContent='Workshop override: '+state.portfolio[sid].note;card.append(note)}}});if(mapping){const s=mapping.scenes.find(s=>s.id===state.selectedScenario);for(const target of document.querySelectorAll('#step1 .detail,#step2 .bundle-scorebox')){const el=document.createElement('details');el.className='source-links';el.innerHTML=`<summary>Scenario evidence and principle mapping</summary><p>${s.id} · ${esc(s.title)}</p><p>${s.parents.length} work items · ${s.actions.length} detailed actions · ${s.principles.length} principle mappings</p><p>${esc([...new Set(s.process)].join(' · '))}</p><button class="btn">Open source analysis →</button>`;el.querySelector('button').onclick=()=>moduleMessage('scenario',s.id);target.append(el)}}};
resetSession=function(){if(confirm('Reset all workshop scores and selections? Product demo cases will be kept.')){clearTimeout(st);state={...initialState(),previewBundles:{},gates:{},phaseOverrides:{}};for(const s of SCENARIOS){const original=bundleDefs(s);BUNDLES[s.id].forEach((b,i)=>{b.control=original[i].control;b.dependency=original[i].dependency})}localStorage.removeItem(STORE);renderAll();showToast('Workshop reset')}};
exportJSON=function(){const blob=new Blob([JSON.stringify({schema:'ctt-workshop-r10',synthetic:true,exportedAt:new Date().toISOString(),seedQualification:'Illustrative NTT DATA draft; Client scores are participant inputs',dimensions:DIMS,bundleDimensions:BDIMS,scenarios:SCENARIOS,bundles:BUNDLES,sourceMappings:mapping?.scenes.map(s=>({id:s.id,parents:s.parents,actions:s.actions,principles:s.principles})),state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Clear_to_Trade_Workshop_Session.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
addEventListener('beforeprint',()=>{document.querySelectorAll('.dim-row').forEach((row,i)=>{const key=DIMS[i]?.[0],v=state.scenarioScores[state.selectedScenario]?.[key];if(v){const span=document.createElement('p');span.className='print-score';span.textContent=`NTT DATA: ${v.ntt} · Client: ${v.client??'Not scored'} · Draft: ${consensusDimension(state.selectedScenario,key).toFixed(1)}`;row.append(span)}});document.querySelectorAll('.bdim').forEach((row,i)=>{const sid=state.selectedScenario,bid=state.previewBundles[sid]||state.selectedBundles[sid]||BUNDLES[sid][1].id,v=state.bundleScores[sid][bid][BDIMS[i][0]];const el=document.createElement('p');el.className='print-score';el.textContent=`NTT DATA: ${v.ntt} · Client: ${v.client??'Not scored'}`;row.append(el)})});addEventListener('afterprint',()=>document.querySelectorAll('.print-score').forEach(e=>e.remove()));
fetch('../product-demo/catalogue.json').then(r=>r.json()).then(data=>{mapping=data;SCENARIOS.forEach(s=>{const m=data.scenes.find(x=>x.id===s.id);if(m){s.name=m.title;s.direction=m.direction==='Add-on'?'Add':m.direction==='Optimize'?'Enhance':m.direction}});renderAll()}).catch(()=>showToast('Source mapping unavailable; scoring remains available.'));
renderAll();
