import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {act,readiness,id,find} from '../case-engine.mjs';
const seed=()=>JSON.parse(readFileSync(new URL('../../04_operating_model/round-a/synthetic-case-fixture.json',import.meta.url)));
const run=(s,type,role='ROLE-KYCOPS',extra={})=>act(s,{type,role,rationale:'Reviewed the synthetic subject identifier and the purpose-linked evidence.',expectedRevision:s.case.revision,key:`${type}-${s.case.revision}`,at:'2026-09-07T04:00:00Z',...extra});
function prepared(){let s=seed();for(const t of ['confirm_requirements','reuse_identity','send_residual_request','receive_supplement','assess_supplement'])s=run(s,t);return s;}
test('False Green: unresolved Legal, Credit, QA and unknown EDD prevent readiness',()=>{assert.equal(readiness(seed()).result,'not_ready');});
test('Empty conditions and missing scope fail closed',()=>{let s=seed();s.clearanceConditions=[];assert.equal(readiness(s).result,'not_ready');s.scopes=[];assert.equal(readiness(s).result,'not_ready');});
test('Evidence receipt does not satisfy a requirement or decide a finding',()=>{let s=seed();for(const t of ['confirm_requirements','reuse_identity','send_residual_request','receive_supplement'])s=run(s,t);assert.equal(find(s,'evidence',id('evidence','supplement')).receipt_status,'received');assert.notEqual(find(s,'requirements',id('requirement','screening-purpose')).status,'satisfied');assert.equal(s.decisions.length,0);});
test('Registry reuse supports identity only, not every evidence purpose',()=>{let s=run(run(seed(),'confirm_requirements'),'reuse_identity');assert.equal(find(s,'requirements',id('requirement','identity')).status,'satisfied');assert.equal(find(s,'evidenceUseAssessments',id('assessment','registry-screening')).sufficiency,'insufficient');assert.notEqual(find(s,'requirements',id('requirement','screening-purpose')).status,'satisfied');});
test('An unauthorised role cannot record disposition',()=>{assert.throws(()=>run(prepared(),'record_disposition','ROLE-CASEMGR'),/authority/i);});
test('Disposition requires sufficient evidence and nonempty rationale',()=>{assert.throws(()=>run(seed(),'record_disposition','ROLE-FINCRIME'),/evidence/i);assert.throws(()=>run(prepared(),'record_disposition','ROLE-FINCRIME',{rationale:''}),/rationale/i);});
test('One complete slice records a local decision, preserves other branches and does not publish',()=>{
 let s=run(prepared(),'record_disposition','ROLE-FINCRIME');assert.equal(s.decisions.length,1);assert.equal(s.decisions[0].currency,'current');assert.equal(s.decisions[0].bank_authority_ref,null);
 assert.equal(find(s,'workItems',id('work','screening-review')).status,'completed');assert.equal(find(s,'clearanceConditions',id('condition','screening')).status,'satisfied');assert.equal(find(s,'clearanceConditions',id('condition','legal')).status,'awaiting_execution');assert.equal(find(s,'clearanceConditions',id('condition','conflicts')).status,'satisfied');assert.equal(s.case.publication_status,'not_requested');assert.equal(readiness(s).result,'not_ready');assert.equal(readiness(s).blocking_condition_ids.length,3);assert.equal(s.auditEvents.length,7);
});
test('Stale revisions and duplicate submissions cannot create contradictory decisions',()=>{let s=prepared();const a={type:'record_disposition',role:'ROLE-FINCRIME',rationale:'Reviewed sufficient synthetic evidence.',expectedRevision:s.case.revision,key:'same-submit',at:'2026-09-07T04:00:00Z'};const changed=act(s,a);assert.equal(act(changed,a).decisions.length,1);assert.throws(()=>act(changed,{...a,key:'new-key'}),/revision/i);});
test('Missing authority configuration fails closed even for reviewer',()=>{let s=prepared();s.authorities=s.authorities.filter(x=>x.authority_kind!=='demo_action_permission');assert.throws(()=>run(s,'record_disposition','ROLE-FINCRIME'),/authority/i);});
test('Missing input blocks reuse and no real publication action exists',()=>{assert.throws(()=>run(seed(),'reuse_identity'),/requirements/i);assert.throws(()=>run(seed(),'publish','ROLE-FINCRIME'),/authority|unsupported/i);});
test('Draft, request and referral are not disposition decisions',()=>{let s=run(seed(),'refer','ROLE-KYCOPS');assert.equal(find(s,'workItems',id('work','screening-review')).status,'referred');assert.equal(s.decisions.length,0);assert.equal(readiness(s).result,'not_ready');});
test('Dependency status follows fulfilled inputs rather than retaining the seed pending state',()=>{let s=run(seed(),'confirm_requirements');assert.equal(s.dependencies[0].status,'satisfied');assert.equal(s.dependencies[1].status,'pending');s=run(prepared(),'record_disposition','ROLE-FINCRIME');assert.ok(s.dependencies.every(d=>d.status==='satisfied'));assert.equal(readiness(s).result,'not_ready');});
test('Resolved finding cannot be silently reopened by a pause or information request',()=>{const s=run(prepared(),'record_disposition','ROLE-FINCRIME');assert.throws(()=>run(s,'request_evidence','ROLE-FINCRIME'),/resolved|outside/i);assert.throws(()=>run(s,'pause','ROLE-FINCRIME'),/resolved|outside/i);});
